### ISSUE TITLE
QoS : Volume with QoS enabled mount operation slowness OR takes long time to mount with both FC & iSCSI backends.

### ISSUE THREAD

**Issue by dgavand** [hpe-storage/python-hpedockerplugin#100]
OS platform: Ubuntu 16.04 with FC Backend
Plugin tag: dockerciuser/hpedockerplugin:test (Date : 12/13/2017)
Docker Version : 17.06.1-ee-2 / API version: 1.30

All the performed steps are mentioned below on how the issue was observed:

1. Created a docker volume with QoS option:
   docker volume create -d hpe --name volume1 -o qos-name=vvk_vvset

2. Verified docker volume as member of respective VVset in 3PAR.

3. Mount a volume:
   docker run -it --mount src=volume1,dst=/test1,volume-driver=hpe --rm busybox /bin/sh

Observations : (1) Mount operation failed with below error:

<div class= "error" >
    <span>hpedockerplugin.exception.HPEPluginMountException</span>: <span>HPE Docker Volume Plugin Mount Failed: (u'OS Brick connect volume failed, error is: %s', u'Unable to find a Fibre Channel volume device.')</span>
  </div>
</div>

(2) Observed vluns in 3PAR

(3) Did not observed any new container as created but observed stale entries ( ls -lrt /dev/disk/by-path )

root@cld6b3:~  docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
e3fae3c623d5        quay.io/coreos/etcd:v2.2.0   "/etcd -name etcd0..."   4 weeks ago         Up 2 weeks          0.0.0.0:2379-2380->2379-2380/tcp, 0.0.0.0:4001->4001/tcp, 7001/tcp   etcd
root@cld6b3:~ 
root@cld6b3:~ 
root@cld6b3:~  ls -lrt /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root 10 Dec 12 23:44 pci-0000:03:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Dec 12 23:44 pci-0000:03:00.0-scsi-0:1:0:0-part5 -> ../../sda5
lrwxrwxrwx 1 root root  9 Dec 12 23:44 pci-0000:03:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Dec 12 23:44 pci-0000:03:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Dec 13 00:05 pci-0000:21:00.3-fc-0x20010002ac019d52-lun-0 -> ../../sdd
lrwxrwxrwx 1 root root  9 Dec 13 00:05 pci-0000:21:00.2-fc-0x20020002ac019d52-lun-0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Dec 13 00:05 pci-0000:21:00.3-fc-0x20020002ac019d52-lun-0 -> ../../sde
lrwxrwxrwx 1 root root  9 Dec 13 00:05 pci-0000:21:00.2-fc-0x20010002ac019d52-lun-0 -> ../../sdb
root@cld6b3:~#
root@cld6b3:~# lsscsi
[0:0:0:0]    storage HP       P220i            7.02  -
[0:0:0:4194240]storage HP       P220i            7.02  -
[0:1:0:0]    disk    HP       LOGICAL VOLUME   7.02  /dev/sda
[1:0:0:254]  enclosu 3PARdata SES              3310  -
[1:0:1:254]  enclosu 3PARdata SES              3310  -
[1:0:2:0]    disk    3PARdata VV               3310  /dev/sdb
[1:0:2:254]  enclosu 3PARdata SES              3310  -
[1:0:3:0]    disk    3PARdata VV               3310  /dev/sdc
[1:0:3:254]  enclosu 3PARdata SES              3310  -
[2:0:0:254]  enclosu 3PARdata SES              3310  -
[2:0:1:254]  enclosu 3PARdata SES              3310  -
[2:0:2:0]    disk    3PARdata VV               3310  /dev/sdd
[2:0:2:254]  enclosu 3PARdata SES              3310  -
[2:0:3:0]    disk    3PARdata VV               3310  /dev/sde
[2:0:3:254]  enclosu 3PARdata SES              3310  -
[4:0:0:254]  enclosu 3PARdata SES              3310  -
[5:0:0:254]  enclosu 3PARdata SES              3310  -
root@cld6b3:~#

Note : Same operation performed with iSCSI backend and it is passed but took long time (30-45 seconds) to complete mount operation. Also verified with flash-cache enabled and it is working normally.

<see attached complete error logs>
[DCV_Mount_FC.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1554271/DCV_Mount_FC.txt)

**Comment by dgavand** [comment]
The VVset was not configured with suitable QoS values. 
Created a new VVset with new QoS suitable values and able to mount QoS enabled VV with FC backend as well. 
But It is taking more time than usual to complete mount operation for QoS enabled VV with both the backends.
Hence needs to be investigated and if possible fixed.

**Comment by sonivi** [comment]
Time taken in step “create file system” using function ‘mkfs()’ of ‘sh’ python module and same is used while mounting volume without QOS.
QOS value, which was used while testing was found to be inappropriate and this caused delay in creating file system.
I have re-created vvset and given appropriate qos value and it was mounted successfully without any delay.

**Comment by wdurairaj** [comment]
Documented in "Known limitations" of quick start guide.
