### ISSUE TITLE
iSCSI: Few mount operations fails after continuous hours of operation.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#101]
**Plugin**: hpestorage/hpedockervolumeplugin:2.0.2
**Docker version:** 17.06.2-ee-6
**OS**: Ubuntu 16.04 / CentOS 7.4

Run this python script for period between 12 hours and 96 hours: https://github.com/sumitshatwara/docker-3par-cho/blob/master/hpe_3par_cho_test.py

This script randomly performs: volume creation, deletion, mount and unmount operations for a given duration.

Observe the summary results once test is completed.

We observed couple of mount failures during two different test runs.

Error observed was as below:
_<span>hpedockerplugin.exception.HPEPluginMountException</span>: <span>HPE Docker Volume Plugin Mount Failed: (u'exception is : %s', u'\n\n  RAN: /bin/mount -t ext4 /dev/sdg /opt/hpe/data/hpedocker-scsi-360002ac00000000000015be400019d52\n\n  STDOUT:\n\n\n  STDERR:\nmount: /opt/hpe/data/hpedocker-scsi-360002ac00000000000015be400019d52: wrong fs type, bad option, bad superblock on /dev/sdg, missing codepage or helper program, or other error.\n')</span>_

**Comment by imran-ansari** [comment]
This issue was raised last year. Request to try this out again on the latest plugin.

**Comment by prablr79** [comment]
CHO ran successfully with 72 hrs. hence closing this defect
