### ISSUE TITLE
Bug: Cloned volume created using -cloneOf=<src_vol> does'nt have Comment field populated on 3PAR Volume

### ISSUE THREAD

**Issue by wdurairaj** [hpe-storage/python-hpedockerplugin#117]
```
$ docker volume create -d hpe --name test_vol1 -o size=2
$ docker volume create -d hpe --name clone_of_test_vol1 -o cloneOf=test_vol1
```
Observe the output in the array for the actual volume created.

you will see the Name,Comment fields which are metadata of the volume is not populated for the cloned volume.

```
Jan 22 08:45:58 cld6b8-rhel dockerd: time="2018-01-22T08:45:58-07:00" level=info msg="2018-01-22 15:45:58.722 16 INFO hpedockerplugin.hpe.hpe_3par_common [-] Creating a clone of volume, using online copy." plugin=287a0131ff932d5c2bf5e68a46134f2b4db2d472c5807fced8d7b4d831a3b8eb
Jan 22 08:45:58 cld6b8-rhel dockerd: time="2018-01-22T08:45:58-07:00" level=info msg="2018-01-22 15:45:58.722 16 INFO hpedockerplugin.hpe.hpe_3par_common [-] Creating clone of a volume dcv-AtFynLihReaM6M0ofChmUA to dcv-Wt5G0CaXROCb6KY-WotpQQ." plugin=287a0131ff932d5c2bf5e68a46134f2b4db2d472c5807fced8d7b4d831a3b8eb
Jan 22 08:45:58 cld6b8-rhel dockerd: time="2018-01-22T08:45:58-07:00" level=info plugin=287a0131ff932d5c2bf5e68a46134f2b4db2d472c5807fced8d7b4d831a3b8eb


CSIM-8K02_MXN6072AC7 cli% showvv dcv-Wt5G0CaXROCb6KY-WotpQQ
                                                                                          -Rsvd(MiB)- -(MiB)-
    Id Name                       Prov Compr Dedup Type CopyOf   BsId Rd -Detailed_State-   Snp   Usr   VSize
129398 dcv-Wt5G0CaXROCb6KY-WotpQQ tpvv Yes   No    base ---    129398 RW normal            1024  2048   17408
-------------------------------------------------------------------------------------------------------------
     1 total                                                                               1024  2048   17408
CSIM-8K02_MXN6072AC7 cli% showvv -showcols Name,Comment dcv-Wt5G0CaXROCb6KY-WotpQQ
Name                       Comment
dcv-Wt5G0CaXROCb6KY-WotpQQ --
----------------------------------
total
CSIM-8K02_MXN6072AC7 cli%


CSIM-8K02_MXN6072AC7 cli% showvv -cpg SSD_r1 -showcols Name,Comment dcv*
Name                       Comment                                                                                                                                       
dcv-AtFynLihReaM6M0ofChmUA {"display_name": "test_compr_vol3", "type": "Docker", "name": "02d1729c-b8a1-45e6-8ce8-cd287c286650", "volume_id": "02d1729c-b8a1-45e6-8ce8-cd287c286650"}
dcv-Gp8tGiG6RQClDz0.qr0Qyw {"display_name": "qos_vol1", "type": "Docker", "name": "1a9f2d1a-21ba-4500-a50f-3d3eaabd10cb", "volume_id": "1a9f2d1a-21ba-4500-a50f-3d3eaabd10cb"}
dcv-m7tx63g2SjiKFKeIhwOEHA --                                                                                                                                            
dcv-pcl3CSPyRqGn--2oY5nXKw {"display_name": "test_compr_vol2", "type": "Docker", "name": "a5c97709-23f2-46a1-a7ff-fda86399d72b", "volume_id": "a5c97709-23f2-46a1-a7ff-fda86399d72b"}
dcv-Wt5G0CaXROCb6KY-WotpQQ --                                                                                                                                            
dcv-Y6iaMpklQxugTiB2Ezrj1A {"display_name": "qos_demo_vol1", "type": "Docker", "name": "63a89a32-9925-431b-a04e-2076133ae3d4", "volume_id": "63a89a32-9925-431b-a04e-2076133ae3d4"}
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
total            
```

**Comment by sonawane-shashikant** [comment]
If a clone for the volume is created without specifying a size, issue exists.
If clone is created by specifying size greater than parent volume, we see comments.

Below is the output for the same.

$ docker volume create -d hpe --name test123_vol1 -o size=10
$ docker volume create -d hpe --name clone_of_test123_vol1 -o cloneOf=test123_vol1

=========================================================================================

docker@cld13b10 : ~ $  docker volume create -d hpe --name clone_of_test123_vol2 -o size=15 -o cloneOf=test123_vol1
clone_of_test123_vol2
docker@cld13b10 : ~ $  docker volume ls
DRIVER              VOLUME NAME
hpe:latest          clone_of_test123_vol1
hpe:latest          clone_of_test123_vol2
hpe:latest          test123_vol1

=======================================================================================
CSIM-8K02_MXN6072AC7 cli% showvv -cpg SHASHI-SSD -showcols Name,Comment dcv*
Name                       Comment                                                                                                                                               
dcv-3DnX7nvjTXyqjCAUBQ1RwA --                                                                                                                                                    
dcv-H-GfZUBjQcWsvvGURAPpSw {"display_name": "clone_of_test123_vol2", "type": "Docker", "name": "1ff19f65-4063-41c5-acbe-f1944403e94b", "volume_id": "1ff19f65-4063-41c5-acbe-f1944403e94b"}
dcv-YGUeXPjUS5iBGL9Sl-HmZA {"display_name": "test123_vol1", "type": "Docker", "name": "60651e5c-f8d4-4b98-8118-bf5297f1e664", "volume_id": "60651e5c-f8d4-4b98-8118-bf5297f1e664"}
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
total                                                                                                                                                                            
CSIM-8K02_MXN6072AC7 cli%  showvv -cpg SHASHI-SSD
                                                                                        -Rsvd(MiB)- -(MiB)-
   Id Name                       Prov Compr Dedup Type CopyOf  BsId Rd -Detailed_State-   Snp   Usr   VSize
76909 dcv-3DnX7nvjTXyqjCAUBQ1RwA tpvv No    No    base ---    76909 RW normal            1024  1024   10240
76911 dcv-H-GfZUBjQcWsvvGURAPpSw tpvv No    No    base ---    76911 RW normal            1024  1024   15360
76906 dcv-YGUeXPjUS5iBGL9Sl-HmZA tpvv No    No    base ---    76906 RW normal            1024  1024   10240
-----------------------------------------------------------------------------------------------------------
    3 total                                                                              3072  3072   35840
CSIM-8K02_MXN6072AC7 cli%

=========================================================================================================================================


docker@cld13b10 : ~ $  docker plugin ls
ID                  NAME                                         DESCRIPTION                    ENABLED
0c40527725b0        hpe:latest                                   HPE Docker Volume Plugin       true
6ba9876b1511        docker/telemetry:1.0.0.linux-x86_64-stable   Docker Inc. metrics exporter   false
docker@cld13b10 : ~ $ 
===================================================================================================================================


docker@cld13b10 : ~ $  docker version
Client: Docker Enterprise Edition (EE) 2.0
Version:       17.06.2-ee-10
API version:   1.30
Go version:    go1.8.7
Git commit:    66261a0
Built: Fri Apr 27 00:38:10 2018
OS/Arch:       linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
Engine:
  Version:      17.06.2-ee-10
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   66261a0
  Built:        Fri Apr 27 00:36:53 2018
  OS/Arch:      linux/amd64
  Experimental: false
docker@cld13b10 : ~ $ 
==============================================================================================================

**Comment by hpe-storage** [comment]
It's partially fixed. Only on offline copy path, the volume's "Comment" field will be updated. On online copy path we have a limitation on the 3PAR copy process, where the metadata information of volume (which has copy in progress) can't be done.
