### ISSUE TITLE
Bug: Latency of volume inspect command is high for volumes with snapshots

### ISSUE THREAD

**Issue by wdurairaj** [hpe-storage/python-hpedockerplugin#118]
```
[root@cld6b8-rhel ~]# time docker volume inspect test_compr_vol3
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/287a0131ff932d5c2bf5e68a46134f2b4db2d472c5807fced8d7b4d831a3b8eb/rootfs",
        "Name": "test_compr_vol3",
        "Options": {
            "compression": "true",
            "size": "17"
        },
        "Scope": "local",
        "Status": {
            "Snapshots": [
                {
                    "Name": "snapshot1_vol3",
                    "ParentName": "test_compr_vol3"
                },
                {
                    "Name": "snapshot2_vol3",
                    "ParentName": "test_compr_vol3"
                }
            ]
        }
    }
]

real    0m20.892s
user    0m0.011s
sys     0m0.006s
[root@cld6b8-rhel ~]#
```

You can see 20 secs are spent for volume inspect command using the unix `time` command.

**Comment by wdurairaj** [comment]
[debug_perf_issue.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1655000/debug_perf_issue.txt)

**Comment by wdurairaj** [comment]
```

Out of 20 secs 

1st 10 secs is here
===================
Jan 23 00:47:37 cld6b8-rhel dockerd: time="2018-01-23T00:47:37-07:00" level=info msg="2018-01-23 07:47:37.327 16 DEBUG paramiko.transport [-] Local version/idstring: SSH-2.0-paramiko_2.2.1 _log /usr/lib/python2.7/site-packages/paramiko/transport.py:1636" plugin=287a0131ff932d5c2bf5e68a46134f2b4db2d472c5807fced8d7b4d831a3b8eb
Jan 23 00:47:47 cld6b8-rhel dockerd: time="2018-01-23T00:47:47-07:00" level=info msg="2018-01-23 07:47:47.330 16 DEBUG paramiko.transport [-] Remote version/idstring: SSH-2.0-OpenSSH_6.6.1p1 Debian-4~bpo70+1 _log /usr/lib/python2.7/site-packages/paramiko/transport.py:1636" plugin=287a0131ff932d5c2bf5e68a46134f2b4db2d472c5807fced8d7b4d831a3b8eb


2nd 10 secs is here.
===================
Jan 23 00:47:47 cld6b8-rhel dockerd: time="2018-01-23T00:47:47-07:00" level=info msg="2018-01-23 07:47:47.452 16 DEBUG paramiko.transport [-] userauth is OK _log /usr/lib/python2.7/site-packages/paramiko/transport.py:1636" plugin=287a0131ff932d5c2bf5e68a46134f2b4db2d472c5807fced8d7b4d831a3b8eb
Jan 23 00:47:57 cld6b8-rhel dockerd: time="2018-01-23T00:47:57-07:00" level=info msg="2018-01-23 07:47:57.474 16 INFO paramiko.transport [-] Authentication (password) successful!" plugin=287a0131ff932d5c2bf5e68a46134f2b4db2d472c5807fced8d7b4d831a3b8eb

Interestingly both are SSH authentication is done
```

**Comment by wdurairaj** [comment]
I checked why we have references of ssh invocations in the get snapshot of a volume call, and it looks like this line of 
https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/hpedockerplugin/hpe_storage_api.py#L1026 calls python-3parclient’s 
https://github.com/hpe-storage/python-3parclient/blob/master/hpe3parclient/client.py#L3998 which inturn calls 

`showvv –p –copyof <vv_name>`

I did further check on the WSAPI 1.6 and 1.5 and found there is no equivalent command in REST for this in 1.5, but in 1.6 the following REST API can be used.

Querying volume copies
You can query for volume copies using the following filter:
copyOf (vv_name) – Name of vv to copy
To query for information about 1st level snapshots for a volume, use the HTTP GET method with the following
URI and no message body:
https://<storage_system>:8080/api/v1/volumes?query=”copyOf EQ <vvname>”


But still to improve performance of the docker volume inspect command, we have to use the above API if the connected array has 1.6 version of WSAPI , and CLI calls on 1.5 (3.2.2.x)

**Comment by sumitshatwara** [comment]
Observed the snapshot is not displayed in volume inspect when snap cpg is different than user cpg. Need to fix it.

**Comment by wdurairaj** [comment]
Fixed and tested.
