### ISSUE TITLE
Readme only reflects Ubuntu support

### ISSUE THREAD

**Issue by ddefolo** [hpe-storage/python-hpedockerplugin#12]
The https://github.com/hpe-storage/python-hpedockerplugin/blob/containerize/README.md file still indicates only Ubuntu is supported when I believe the containerized version of the plugin has been validated on RHEL 7.2 at least.  Given there are instructions in the quick-start for how to use the container plugin for RHEL the top level readme support matrix should be revisited.

**Comment by garthmbooth** [comment]
Resolved in the v1.1.0 release.
