### ISSUE TITLE
Bug: Inspect volume returns error when VVset doesn't have QoS rules enabled  

### ISSUE THREAD

**Issue by imran-ansari** [hpe-storage/python-hpedockerplugin#134]
Problem:
======
When volume is created with 'qos-name' parameter as some vv-set which is not associated with QoS at the backend, and inspect is performed on such a volume, it errors out "No such volume..."

Steps to reproduce:
=============
1. Create some vv-set 'myvvset' at the backend without attaching QoS to it
2. From Docker CLI, create some volume 'vol01' specifying 'qos-name' with 'myvvset'
3. Volume is shown to be created successfully
4. Inspect volume 'vol01' results in error

$ sudo docker volume create -d test --name tstvol01 -o qos-name=imvvset
tstvol01

$ sudo docker volume inspect tstvol01
[]
Error: No such volume: tstvol01

Expected:
=======
Create volume should fail when it detects that QoS is not attached to the vv-set

**Comment by sonivi** [comment]
@imran-ansari : I suggest the expected should be, it should allow creation of volume under vvset, but inspecting the volume should give details of volume without qos details.

since, its 3par administrator responsibility to create a vvset and associate it with QOS

**Comment by imran-ansari** [comment]
I think allowing volume creation without QoS in this case would be somewhat confusing to the user as the original intent was to create a volume with QoS and respecting such request would set user’s expectation that the volume with desired characteristics got created. It’s only after he/she fires inspect, that he/she would discover that to be untrue.

Since an option was used with invalid QoS, I would still suggest that we throw an error upfront so that user can get the situation rectified by the storage admin or get a now QoS name.

I definitely agree that it's administrator's responsibility to provide a good VV-Set name. However, mistakes do happen and it is here that we are trying to help out both the user and the administrator :).

Let me know if this makes sense.

**Comment by wdurairaj** [comment]
Fixed in the latest plugin release 2.1 -- hpestorage/hpedockervolumeplugin:2.1
Please verify and close this.

**Comment by imran-ansari** [comment]
Verified by Shashi. Closing now.
