### ISSUE TITLE
Bug: Remove volume on QOS enabled volume leaves backend volume intact when VVset name has prefix "vvs-"

### ISSUE THREAD

**Issue by imran-ansari** [hpe-storage/python-hpedockerplugin#135]
Description:
========
When a pre-created VVSET has a name that begins with 'vvs-' and QOS is attached to it, a volume created using such a QOS doesn't get deleted from the backend. However, Docker CLI shows it as deleted.

Steps:
====
1. On 3PAR CLI, create VVSET with name that begins with 'vvs-' say 'vvs-test'
2. Set QOS on 'vvs-test'
3. On Docker CLI, create volume using 'qos-name' as 'vvs-test'
4. On 3PAR CLI, using 'showvvset vvs-test', verify that one volume is a member of VVSET
5. On Docker CLI, remove the volume
6. On 3PAR CLI, using 'showvvset vvs-test', check that the volume is still a member of VVSET

**Comment by wdurairaj** [comment]
Please verify in the latest tag -- hpestorage/hpedockervolumeplugin:2.1 , and close this.

**Comment by sonawane-shashikant** [comment]
This issue is verified as FIXED on K8s with OpenShift environment.
