### ISSUE TITLE
RHEL: Error while reading data after plugin upgrade

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#143]
Steps followed along with the outPut - 

------------------------------------------------------------

Steps Followed - 

1.	"Create few volumes with different properties:

$ docker volume create -d hpe --name upgrade11 -o size=16 -o provisioning=thin
$ docker volume create -d hpe --name upgrade12 -o size=26 -o provisioning=full
$ docker volume create -d hpe --name upgrade13 -o size=36 -o provisioning=dedup
$ docker volume create -d hpe --name upgrade14 -o size=46 -o flash-cache=True"

[root@cld13b11 ~]# docker volume create -d hpe --name upgrade11 -o size=16 -o provisioning=thin
upgrade11
[root@cld13b11 ~]# docker volume create -d hpe --name upgrade12 -o size=26 -o provisioning=full
upgrade12
[root@cld13b11 ~]# docker volume create -d hpe --name upgrade13 -o size=36 -o provisioning=dedup
upgrade13
[root@cld13b11 ~]# docker volume create -d hpe --name upgrade14 -o size=46 -o flash-cache=True
upgrade14

[root@cld13b11 ~]# docker volume ls
DRIVER              VOLUME NAME
hpe:latest          upgrade11
hpe:latest          upgrade12
hpe:latest          upgrade13
hpe:latest          upgrade14

2.	"Mount all the volumes sequentially using for loop (below command):

$ for i in `seq 11 14`; do  echo $i; docker run -it -d --mount src=upgrade$i,dst=/data1,volume-driver=hpe --name container$i --rm busybox /bin/sh ; done"

[root@cld13b11 ~]# for i in `seq 11 14`; do  echo $i; docker run -it -d --mount src=upgrade$i,dst=/data1,volume-driver=hpe --name container$i --rm busybox /bin/sh ; done
11
cbd5ba3e88a7ec49178414c9b129cca4e510ac1091b84d4d5457fd28d60406d7
12
bdc9611c40473f34fa65d7e22576e44607c455797035340e7d8e5a57eaa52771
13
a74e7df318dcb70edcad665ef41ca908f608917202399447239a8b90c5d6e646
14
b75d5c0844cd5d3b58334acca1a29c012fe54f5f6b91c72b48460bf40d111d20

3.	"Write data on all volumes using below command:

for i in `seq 11 14`; do  echo $i; docker exec -it container$i /bin/sh -c ""echo 'data' > /data1/hi$i.txt"" ; done"

4.	"Upgrade the plugin to Y tag using following commands:

$ docker plugin disable --force hpe
$ docker plugin upgrade hpe hpestorage/hpedockervolumeplugin:Y
$ docker plugin set hpe certs.source=/tmp (for Ubuntu)
$ docker plugin set hpe glibc_libs.source=/lib64 certs.source=/tmp (for RHEL / CentOS)
$ docker plugin enable hpe"

[root@cld13b11 ~]# docker plugin disable --force hpe
hpe
[root@cld13b11 ~]# docker plugin upgrade hpe dockerciuser/hpedockerplugin:test
Upgrading plugin hpe:latest from dockerciuser/hpedockerplugin:old to dockerciuser/hpedockerplugin:test
Plugin images do not match, are you sure? [y/N] y
Plugin "dockerciuser/hpedockerplugin:test" is requesting the following privileges:
 - network: [host]
 - mount: [/dev]
 - mount: [/run/lock]
 - mount: [/var/lib]
 - mount: [/etc]
 - mount: [/var/run/docker.sock]
 - mount: [/root/.ssh]
 - mount: [/sys]
 - mount: [/root/plugin/certs]
 - mount: [/sbin/iscsiadm]
 - mount: [/lib/modules]
 - mount: [/lib/x86_64-linux-gnu]
 - allow-all-devices: [true]
 - capabilities: [CAP_SYS_ADMIN CAP_SYS_RESOURCE CAP_MKNOD CAP_SYS_MODULE]
Do you grant the above permissions? [y/N] y
test: Pulling from dockerciuser/hpedockerplugin
b0e74bcd78f6: Download complete
Digest: sha256:25dc17eafa08efada31b7ba0b16f7bb03b37814108fca8d4d82e77778bd85445
Status: Downloaded newer image for dockerciuser/hpedockerplugin:test
Upgraded plugin hpe:latest to dockerciuser/hpedockerplugin:test
[root@cld13b11 ~]# docker plugin set hpe glibc_libs.source=/lib64 certs.source=/tmp
[root@cld13b11 ~]# docker plugin enable hpe
hpe

5.	"Read the data from all old volumes using below command:

$ for i in `seq 11 14`; do  echo $i; docker exec -it container$i /bin/sh -c ""cat /data1/hi$i.txt"" ; done"

6.	"Unmount all volumes using below command:

$ docker attach <container name>
# / exit"

[root@cld13b11 ~]# docker attach container11
/ # exit
[root@cld13b11 ~]# docker attach container12
/ # exit
[root@cld13b11 ~]# docker attach container13
/ # exit
[root@cld13b11 ~]# docker attach container14
/ # exit

7.	"Create two new volumes:

$ docker volume create -d hpe --name upgrade15 -o size=56 -o provisioning=thin
$ docker volume create -d hpe --name upgrade16 -o size=22 -o provisioning=full"

[root@cld13b11 ~]# docker volume create -d hpe --name upgrade15 -o size=20 -o provisioning=thin
upgrade15
[root@cld13b11 ~]# docker volume create -d hpe --name upgrade16 -o size=22 -o provisioning=full
upgrade16

8.	"List volumes using below command:

$ docker volume ls"

[root@cld13b11 ~]# docker volume ls
DRIVER              VOLUME NAME
hpe:latest          upgrade11
hpe:latest          upgrade12
hpe:latest          upgrade13
hpe:latest          upgrade14
hpe:latest          upgrade15
hpe:latest          upgrade16

9.	"Navigate to 3par array CLI and verify volumes using below command:

% showvv"

CSIM-8K02_MXN6072AC7 cli% showvv -cpg SS_CPG5
                                                                                         -Rsvd(MiB)- -(MiB)--
   Id Name                        Prov Compr Dedup Type CopyOf  BsId Rd -Detailed_State-  Snp    Usr    VSize
41570 .shared.SS_CPG5_0           dds  NA    No    base ---    41570 RW normal              0   1024 67108864
41571  dcv-C8WXcEZ0SiO1mwLxG0Lz1A tdvv No    Yes   base ---    41571 RW normal              0   5120    36864
41572 dcv-874b44faRJ68nHcWrB1djg  tpvv No    No    base ---    41572 RW normal              0   6144    47104
41569 dcv-E4q3Ag0bTcK6d4KFh2NaCw  full NA    NA    base ---    41569 RW normal              0  26624    26624
41573 dcv-rYSCmNDYTo6t.5AR7RxGhw  tpvv No    No    base ---    41573 RW normal           1024   1024    20480
41574 dcv-yzJxd4ZbTBeMqM5k4V2Srg  cpvv NA    NA    base ---    41574 RW normal           1024  22528    22528
41568 dcv-zthuNc18TVW-Y0luJHzGLg  tpvv No    No    base ---    41568 RW normal              0   2048    16384
-------------------------------------------------------------------------------------------------------------
    7 total                                                                              2048  64512 67278848

10.	"Mount all the volumes sequentially using for loop (below command):

$ for i in `seq 11 16`; do  echo $i; docker run -it -d -v upgrade$i:/data1 --volume-driver hpe --name container$i --rm busybox /bin/sh ; done

[root@cld13b11 ~]# $ for i in `seq 11 16`; do  echo $i; docker run -it -d --mount src=upgrade$i,dst=/data1,volume-driver=hpe --name container$i --rm busybox /bin/sh ; done"
11
15d2491909200d38a2c1e005333b161e9c04ddebd0e997159ee7d7c1c9b9615d
12
93151543c34fa776710cd92cc275d52e88c16d3a94a28c4a1b6f8e18c9254876
13
2d51d42a988d81537ec857c69a71e727d18dc227e83f32280893624224817429
14
0be40ecfa804d365a99b049b86ec420a299c7ac87507410db4bc2d1fe05fa023
15
e2738e65d231903caf9a95963ea9ec789da3d87659fc19537ceca1a8ee3a4b22
16
d7354184b4ef3f58480ba1478e7e6c10799e8bffc4e43d168c617ae04680322a

11.	"Inspect containers:

$ docker inspect container11
$ docker inspect container12
.
.
$ docker inspect container16"

[root@cld13b11 ~]# docker inspect container11 > /tmp/container11/txt
-bash: /tmp/container11/txt: No such file or directory
[root@cld13b11 ~]# docker inspect container11 > /tmp/container11.txt
[root@cld13b11 ~]# docker inspect container12 > /tmp/container12.txt
[root@cld13b11 ~]# docker inspect container13 > /tmp/container13.txt
[root@cld13b11 ~]# docker inspect container14 > /tmp/container14.txt
[root@cld13b11 ~]# docker inspect container15 > /tmp/container15.txt
[root@cld13b11 ~]# docker inspect container16 > /tmp/container16.txt

12.	"Verify LUN entries with device details are present in host using below command:

$ ls -lrt /dev/disk/by-path"

[root@cld13b11 ~]# ls -lrt /dev/disk/by-path
total 0
lrwxrwxrwx. 1 root root 10 Feb 27 07:23 pci-0000:07:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 10 Feb 27 07:23 pci-0000:07:00.0-scsi-0:1:0:0-part3 -> ../../sda3
lrwxrwxrwx. 1 root root 10 Feb 27 07:23 pci-0000:07:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx. 1 root root 10 Feb 27 07:23 pci-0000:07:00.0-scsi-0:1:0:2-part1 -> ../../sdc1
lrwxrwxrwx. 1 root root 10 Feb 27 07:23 pci-0000:07:00.0-scsi-0:1:0:1-part1 -> ../../sdb1
lrwxrwxrwx. 1 root root  9 Feb 27 07:23 pci-0000:07:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx. 1 root root  9 Feb 27 07:23 pci-0000:07:00.0-scsi-0:1:0:2 -> ../../sdc
lrwxrwxrwx. 1 root root  9 Feb 27 07:23 pci-0000:07:00.0-scsi-0:1:0:1 -> ../../sdb
lrwxrwxrwx. 1 root root  9 Mar  5 01:11 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-0 -> ../../sdd
lrwxrwxrwx. 1 root root  9 Mar  5 01:11 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-1 -> ../../sde
lrwxrwxrwx. 1 root root  9 Mar  5 01:12 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-2 -> ../../sdf
lrwxrwxrwx. 1 root root  9 Mar  5 01:12 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-3 -> ../../sdg
lrwxrwxrwx. 1 root root  9 Mar  5 01:44 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-4 -> ../../sdh
lrwxrwxrwx. 1 root root  9 Mar  5 01:45 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-5 -> ../../sdi

13.	"Navigate to 3par array CLI and verify VLUNs are created:

% showvlun -host <hostname>"

CSIM-8K02_MXN6072AC7 cli%  showvlun -host cld13b11
Active VLUNs
Lun VVName                     HostName --------Host_WWN/iSCSI_Name--------  Port        Type Status ID
  0 dcv-zthuNc18TVW-Y0luJHzGLg cld13b11 iqn.1994-05.com.redhat:c01ffacf2b68 2:2:1 matched set active  1
  1 dcv-E4q3Ag0bTcK6d4KFh2NaCw cld13b11 iqn.1994-05.com.redhat:c01ffacf2b68 2:2:1 matched set active  1
  2 dcv-C8WXcEZ0SiO1mwLxG0Lz1A cld13b11 iqn.1994-05.com.redhat:c01ffacf2b68 2:2:1 matched set active  1
  3 dcv-874b44faRJ68nHcWrB1djg cld13b11 iqn.1994-05.com.redhat:c01ffacf2b68 2:2:1 matched set active  1
  4 dcv-rYSCmNDYTo6t.5AR7RxGhw cld13b11 iqn.1994-05.com.redhat:c01ffacf2b68 2:2:1 matched set active  1
  5 dcv-yzJxd4ZbTBeMqM5k4V2Srg cld13b11 iqn.1994-05.com.redhat:c01ffacf2b68 2:2:1 matched set active  1
-------------------------------------------------------------------------------------------------------
  6 total

VLUN Templates
Lun VVName                     HostName -Host_WWN/iSCSI_Name-  Port        Type
  0 dcv-zthuNc18TVW-Y0luJHzGLg cld13b11 ----------------      2:2:1 matched set
  1 dcv-E4q3Ag0bTcK6d4KFh2NaCw cld13b11 ----------------      2:2:1 matched set
  2 dcv-C8WXcEZ0SiO1mwLxG0Lz1A cld13b11 ----------------      2:2:1 matched set
  3 dcv-874b44faRJ68nHcWrB1djg cld13b11 ----------------      2:2:1 matched set
  4 dcv-rYSCmNDYTo6t.5AR7RxGhw cld13b11 ----------------      2:2:1 matched set
  5 dcv-yzJxd4ZbTBeMqM5k4V2Srg cld13b11 ----------------      2:2:1 matched set
-------------------------------------------------------------------------------
  6 total
CSIM-8K02_MXN6072AC7 cli% Session timed out after being idle for 3600 seconds

14.	"Write data on all volumes using below command:

for i in `seq 11 16`; do  echo $i; docker exec -it container$i /bin/sh -c ""echo 'data' > /data1/foo$i.txt"" ; done"

[root@cld13b11 ~]# for i in `seq 11 16`; do  echo $i; docker exec -it container$i /bin/sh -c "echo 'data' > /data1/foo$i.txt" ; done
11
12
13
14
15
16

15.	"Unmount all volumes using below command:

$ docker attach <container name>
# / exit"

[root@cld13b11 ~]# docker attach container11
/ # exit
[root@cld13b11 ~]# docker attach container12
/ # exit
[root@cld13b11 ~]# docker attach container13
/ # exit
[root@cld13b11 ~]# docker attach container14
/ # exit
[root@cld13b11 ~]# docker attach container15
/ # exit
[root@cld13b11 ~]# docker attach container16
/ # exit

16.	"Read the data from all the volumes using below command:

17.	$ for i in `seq 11 16`; do  echo $i; docker run -it --mount src=upgrade$i,dst=/data1,volume-driver=hpe --rm busybox cat /data1/foo$i.txt ; done"

[root@cld13b11 ~]# for i in `seq 11 16`; do  echo $i; docker run -it --mount src=upgrade$i,dst=/data1,volume-driver=hpe --rm busybox cat /data1/foo$i.txt ; done
11
data
12
data
13
data
14
data
15
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/88c7746263c3976a67b931c90ff8d4f336f1a7d748f1b47c3fa0dcc34afaa701/rootfs': VolumeDriver.Mount: <html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b>

<div>
  <style type="text/css">
    div.error {
      color: red;
      font-family: Verdana, Arial, helvetica, sans-serif;
      font-weight: bold;
    }

    div {
      font-family: Verdana, Arial, helvetica, sans-serif;
    }

    div.stackTrace {
    }

    div.frame {
      padding: 1em;
      background: white;
      border-bottom: thin black dashed;
    }

    div.frame:first-child {
      padding: 1em;
      background: white;
      border-top: thin black dashed;
      border-bottom: thin black dashed;
    }

    div.location {
    }

    span.function {
      font-weight: bold;
      font-family: "Courier New", courier, monospace;
    }

    div.snippet {
      margin-bottom: 0.5em;
      margin-left: 1em;
      background: #FFFFDD;
    }

    div.snippetHighlightLine {
      color: red;
    }

    span.code {
      font-family: "Courier New", courier, monospace;
    }
  </style>

  <div class="error">
    <span>hpedockerplugin.exception.HPEPluginMountException</span>: <span>HPE Docker Volume Plugin Mount Failed: (u'exception is : %s', u'\n\n  RAN: /bin/mount -t ext4 /dev/sdd /opt/hpe/data/hpedocker-scsi-360002ac0000000000100a26500019d52\n\n  STDOUT:\n\n\n  STDERR:\nmount: /opt/hpe/data/hpedocker-scsi-360002ac0000000000100a26500019d52: wrong fs type, bad option, bad superblock on /dev/sdd, missing codepage or helper program, or other error.\n')</span>
  </div>
  <div class="stackTrace">
    <div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/site-packages/twisted/internet/defer.py</span>:<span>150</span> in
        <span class="function">maybeDeferred</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">149</span>
          <code class="code"> &#160; &#160;try:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">150</span>
          <code class="code"> &#160; &#160; &#160; &#160;result = f(*args, **kw)</code>
        </div><div class="snippetLine">
          <span class="lineno">151</span>
          <code class="code"> &#160; &#160;except:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/site-packages/klein/app.py</span>:<span>126</span> in
        <span class="function">execute_endpoint</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">125</span>
          <code class="code"> &#160; &#160; &#160; &#160;endpoint_f = self._endpoints[endpoint]</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">126</span>
          <code class="code"> &#160; &#160; &#160; &#160;return endpoint_f(self._instance, *args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">127</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/site-packages/klein/app.py</span>:<span>211</span> in
        <span class="function">_f</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">210</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;def _f(instance, request, *a, **kw):</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">211</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;return _call(instance, f, request, *a, **kw)</code>
        </div><div class="snippetLine">
          <span class="lineno">212</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python2.7/site-packages/klein/app.py</span>:<span>48</span> in
        <span class="function">_call</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">47</span>
          <code class="code"> &#160; &#160;else:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">48</span>
          <code class="code"> &#160; &#160; &#160; &#160;result = f(instance, *args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">49</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py</span>:<span>516</span> in
        <span class="function">volumedriver_mount</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">515</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;# mount the directory</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">516</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;fileutil.mount_dir(path.path, mount_dir)</code>
        </div><div class="snippetLine">
          <span class="lineno">517</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;LOG.debug('Device: %(path) successfully mounted on %(mount)s',</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/python-hpedockerplugin/hpedockerplugin/fileutil.py</span>:<span>97</span> in
        <span class="function">mount_dir</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">96</span>
          <code class="code"> &#160; &#160; &#160; &#160;LOG.error(msg)</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">97</span>
          <code class="code"> &#160; &#160; &#160; &#160;raise exception.HPEPluginMountException(reason=msg)</code>
        </div><div class="snippetLine">
          <span class="lineno">98</span>
          <code class="code"> &#160; &#160;return True</code>
        </div>
      </div>
    </div>
  </div>
  <div class="error">
    <span>hpedockerplugin.exception.HPEPluginMountException</span>: <span>HPE Docker Volume Plugin Mount Failed: (u'exception is : %s', u'\n\n  RAN: /bin/mount -t ext4 /dev/sdd /opt/hpe/data/hpedocker-scsi-360002ac0000000000100a26500019d52\n\n  STDOUT:\n\n\n  STDERR:\nmount: /opt/hpe/data/hpedocker-scsi-360002ac0000000000100a26500019d52: wrong fs type, bad option, bad superblock on /dev/sdd, missing codepage or helper program, or other error.\n')</span>
  </div>
</div>

</body></html>.
16
data
[root@cld13b11 [~]#
[RHEL-SINGLE-PATH-TC23.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1780287/RHEL-SINGLE-PATH-TC23.txt)

**Comment by wdurairaj** [comment]
please check whether it's a duplicate of https://github.com/hpe-storage/python-hpedockerplugin/issues/46

**Comment by sonivi** [comment]
**After plugin upgrade from _dockerciuser/hpedockerplugin:old_ to _dockerciuser/hpedockerplugin:test_, unmounting was successful but failed to remove vluns entries from 3par and host** 

root@cld6b9:/home/stack/docker/python-hpedockerplugin# docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                         PORTS                                                                NAMES
27919589448d        busybox                      "/bin/sh"                17 minutes ago      Up 17 minutes                                                                                       container14
ec495585850e        busybox                      "/bin/sh"                17 minutes ago      Up 17 minutes                                                                                       container13
ce72efd37e49        busybox                      "/bin/sh"                17 minutes ago      Up 17 minutes                                                                                       container12
86241a52ad6b        busybox                      "/bin/sh"                18 minutes ago      Up 17 minutes                                                                                       container11
98324cb91ef1        quay.io/coreos/etcd:v2.2.0   "/etcd -name etcd0..."   About an hour ago   Up About an hour               0.0.0.0:2379-2380->2379-2380/tcp, 0.0.0.0:4001->4001/tcp, 7001/tcp   etcd
c4a123650c0c        hello-world                  "/hello"                 About an hour ago   Exited (0) About an hour ago                                                                        reverent_goldstine
root@cld6b9:/home/stack/docker/python-hpedockerplugin# docker attach container11
/data1 # exit
root@cld6b9:/home/stack/docker/python-hpedockerplugin# docker attach container12
/ # exit
^[[Aroot@cld6b9:/home/stack/docker/python-hpedockerplugin# docker attach container13
/ # exit
root@cld6b9:/home/stack/docker/python-hpedockerplugin# docker attach container14
/ # exit
root@cld6b9:/home/stack/docker/python-hpedockerplugin# docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                         PORTS                                                                NAMES
98324cb91ef1        quay.io/coreos/etcd:v2.2.0   "/etcd -name etcd0..."   About an hour ago   Up About an hour               0.0.0.0:2379-2380->2379-2380/tcp, 0.0.0.0:4001->4001/tcp, 7001/tcp   etcd
c4a123650c0c        hello-world                  "/hello"                 About an hour ago   Exited (0) About an hour ago                                                                        reverent_goldstine
root@cld6b9:/home/stack/docker/python-hpedockerplugin# ls -lrt /dev/disk/by-path
total 0
lrwxrwxrwx 1 root root  9 Apr 13 00:44 pci-0000:03:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Apr 13 00:44 pci-0000:03:00.0-scsi-0:1:0:0-part5 -> ../../sda5
lrwxrwxrwx 1 root root 10 Apr 13 00:44 pci-0000:03:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root 10 Apr 13 00:44 pci-0000:03:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root  9 Apr 13 01:38 ip-10.50.3.60:3260-iscsi-iqn.2000-05.com.3pardata:23210002ac019d52-lun-1 -> ../../sdd
lrwxrwxrwx 1 root root  9 Apr 13 01:38 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-1 -> ../../sde
lrwxrwxrwx 1 root root  9 Apr 13 01:38 ip-10.50.3.60:3260-iscsi-iqn.2000-05.com.3pardata:23210002ac019d52-lun-2 -> ../../sdf
lrwxrwxrwx 1 root root  9 Apr 13 01:38 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-2 -> ../../sdg
lrwxrwxrwx 1 root root  9 Apr 13 01:39 ip-10.50.3.60:3260-iscsi-iqn.2000-05.com.3pardata:23210002ac019d52-lun-0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Apr 13 01:39 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Apr 13 01:39 ip-10.50.3.60:3260-iscsi-iqn.2000-05.com.3pardata:23210002ac019d52-lun-3 -> ../../sdh
lrwxrwxrwx 1 root root  9 Apr 13 01:39 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-3 -> ../../sdi


**Error Snippet:
[command.log](https://github.com/hpe-storage/python-hpedockerplugin/files/1906786/command.log)

**

/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py:105 in\n volumedriver_unmount
104        mount_id = contents['ID']
105        return self._manager.unmount_volume(volname, vol_mount, mount_id)
106
/python-hpedockerplugin/hpedockerplugin/synchronization.py:24 in _wrapped
23                         % (f.__name__, lck_name))
24 Apr 13 01:57:23 cld6b9 dockerd[20188]:                return f(*a, **k)
25            except exception.HPEPluginLockFailed:
/python-hpedockerplugin/hpedockerplugin/volume_manager.py:857 in unmount_volume
856        volid = vol['id']
857        is_snap = vol['is_snap']
858
 exceptions.KeyError: 'is_snap'

**Comment by imran-ansari** [comment]
In the command
[root@cld13b11 ~]# $ for i in seq 11 16; do echo $i; docker run -it -d --mount src=upgrade$i,dst=/data1,volume-driver=hpe --name container$i --rm busybox /bin/sh ; done"

shouldn't the mount point be different for all the volumes? Please try dst=/data$i and report the results.

**Comment by sonawane-shashikant** [comment]
Closing this issue as the same is not reproduced on the latest docker plugin.
Attaching detailed output of the test executed.

[Issue_143_verification_latest.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1978552/Issue_143_verification_latest.txt)
