### ISSUE TITLE
Docker: Automation: VolumeBindTest.test_revert_volume_from_snapshots fails with AssertionError

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#146]
Environment - 
root@csimbe06-b10:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
root@csimbe06-b10:~#

Array - 
hpe3par_api_url = https://10.50.3.9:8080/api/v1
hpe3par_username = 3paradm
hpe3par_password = 3pardata
san_ip = 10.50.3.9
san_login = 3paradm
san_password = 3pardata
hpe3par_cpg = SHASHI-CPG
hpe3par_iscsi_ips = 10.50.3.59

CSIM-8K02_MXN6072AC7 cli% showversion -b
Release version 3.3.1.269 (MU1)
Patches:  P09,P11,P18

Component Name                   Version
CLI Server                       3.3.1.269 (MU1)
CLI Client                       3.3.1.269
System Manager                   3.3.1.315 (P18)
Kernel                           3.3.1.269 (MU1)
TPD Kernel Code                  3.3.1.315 (P18)
TPD Kernel Patch                 3.3.1.315 (P18)
CSIM-8K02_MXN6072AC7 cli%

Ran Automation script on the above setup to see one failure as below.
Attaching journalctl docker.service log for this particular case only.

root@csimbe06-b10:/home/docker/python-hpedockerplugin/tests/integration# py.test -v
=============================================================== test session starts ================================================================
platform linux2 -- Python 2.7.12, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python
cachedir: ../../.cache
rootdir: /home/docker/python-hpedockerplugin, inifile:
collected 53 items

hpe_3par_api_container_test.py::VolumeBindTest::test_checksum_persistance_of_binary_file PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_clone_mount_unmount_delete PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_delete_compressed_volume PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_mount_unmount_compressed_volume PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_mount_unmount_volume_with_qos PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_mount_volume_create_snapshots PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_read_clone_data PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_remove_unused_volumes PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_revert_volume_from_snapshots FAILED
hpe_3par_api_container_test.py::VolumeBindTest::test_shared_volume PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_volume_mount PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_volume_mount_readonly_fs PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_volume_persists_container_is_removed

PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_volume_unmount PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_write_and_read_data PASSED
hpe_3par_api_container_test.py::VolumeBindTest::test_write_data_get_file_archive_from_container PASSED
hpe_3par_api_plugin_test.py::PluginTest::test_disable_plugin PASSED
hpe_3par_api_plugin_test.py::PluginTest::test_enable_plugin PASSED
hpe_3par_api_plugin_test.py::PluginTest::test_force_remove_plugin PASSED
hpe_3par_api_plugin_test.py::PluginTest::test_inspect_plugin PASSED
hpe_3par_api_plugin_test.py::PluginTest::test_install_plugin PASSED
hpe_3par_api_plugin_test.py::PluginTest::test_list_plugins PASSED
hpe_3par_api_plugin_test.py::PluginTest::test_remove_plugin PASSED
hpe_3par_api_plugin_test.py::PluginTest::test_upgrade_plugin_with_volume_operations PASSED
hpe_3par_api_plugin_test.py::PluginTest::test_upgrade_plugin_without_volume_operations PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_clone_qos_name PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_clone_without_options PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_dedup_compressed_clone PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_dedup_compressed_volume PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_dedup_compressed_volume_15GB PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_dedup_prov_clone PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_dedup_prov_compressed_flashcache_volume PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_dedup_prov_volume PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_flash_cache_clone PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_flash_cache_volume PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_force_remove_volumes_clones PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_full_prov_clone PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_full_prov_compressed_volume PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_full_prov_volume PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_list_volumes_clones PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_remove_snapshot_within_retention PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_snapshot_expiration_retention PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_snapshot_retention_greater_than_expiration PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_snapshots_list PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_thin_compressed_clone PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_thin_compressed_volume PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_thin_compressed_volume_15GB PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_thin_prov_compressed_flashcache_volume PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_thin_prov_volume PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_volume_existent_qos PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_volume_non_existent_qos PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_volume_qos_with_flash_cache PASSED
hpe_3par_api_volume_test.py::VolumesTest::test_volume_snapshot PASSED

===================================================================== FAILURES =====================================================================
_________________________________________________ VolumeBindTest.test_revert_volume_from_snapshots _________________________________________________

self = <tests.integration.hpe_3par_api_container_test.VolumeBindTest testMethod=test_revert_volume_from_snapshots>

    def test_revert_volume_from_snapshots(self):
        '''
                This is a reverting a volume from its snapshots test.

                Steps:
                1. Create a volume.
                2. Create a container and mount volume to it.
                3. Write data.
                4. Create a snapshot without expiration period.
                5. Write data again on volume.
                6. Create a snapshot with expiration period.
                7. Write data again on volume.
                8. Promote volume to its 1st snapshot and verify the data.
                9. Promote volume to its 2nd snapshot and verify the data.
                10. Unmount the volume.
                11. Verify the unmount in 3par array.
                12. Delete all the snapshots, container and volume.
                13. Verify the removal of snapshots and volume in 3par array.
            '''
        client = docker.from_env(version=TEST_API_VERSION)
        volume_name = helpers.random_name()
        self.tmp_volumes.append(volume_name)
        snapshot_names = []
        i = 0; j = 0
        for i in range(2):
            snapshot_names.append(helpers.random_name())
            self.tmp_volumes.append(volume_name + '/' + snapshot_names[i])
        volume = self.hpe_create_volume(volume_name, driver=HPE3PAR,
                               size=THIN_SIZE, provisioning='thin')
        container = client.containers.run(BUSYBOX, "sh", detach=True,
                                          name=helpers.random_name(), tty=True, stdin_open=True,
                                          volumes=[volume_name + ':/data1']
        )
        self.tmp_containers.append(container.id)
        # assert container.wait()['StatusCode'] == 0
        container.exec_run("sh -c 'echo \"snapshot_data1\" > /data1/test1'")
        container.stop()

        self.hpe_create_snapshot(snapshot_names[0], driver=HPE3PAR,
                                 snapshotOf=volume_name)

        container.start()
        container.exec_run("sh -c 'echo \"snapshot_data2\" > /data1/test2'")
        container.stop()

        self.hpe_create_snapshot(snapshot_names[1], driver=HPE3PAR,
                                 snapshotOf=volume_name, expirationHours='2')

        container.start()
        container.exec_run("sh -c 'echo \"snapshot_data3\" > /data1/test3'")
        container.stop()
        self.client.create_volume(name=snapshot_names[0], driver=HPE3PAR,
                             driver_opts={'promote' : volume_name})

        container.start()
        # assert container.wait()['StatusCode'] == 0
        ExecResult1 = container.exec_run("sh -c 'ls data1/'")
        self.assertEqual(ExecResult1.exit_code, 0)
>       self.assertEqual(ExecResult1.output, b"test1\n")
E       AssertionError: 'Example1.txt\nchecksum\nfile.txt\nrandom\ntest\ntest1\ntest2\ntest3\n' != 'test1\n'

hpe_3par_api_container_test.py:731: AssertionError
====================================================== 1 failed, 52 passed in 4278.05 seconds ======================================================
[test_revert_volume_from_snapshots.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1792343/test_revert_volume_from_snapshots.txt)

**Comment by sumitshatwara** [comment]
Revert volume from snapshot feature has been deprecated in 3par volume plugin 2.1. This will be removed in the latest build of automation test suite. Therefore, please close it.
