### ISSUE TITLE
Automation Scripts: CPU Stuck error

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#151]
[root@cld13b11 log]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.4 (Maipo)
[root@cld13b11 log]# uname -a
Linux cld13b11 3.10.0-693.17.1.el7.x86_64 #1 SMP Sun Jan 14 10:36:03 EST 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@cld13b11 log]#

[root@cld13b11 log]# docker version
Client:
 Version:      17.06.2-ee-6
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:43:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ee-6
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   e75fdb8
 Built:        Mon Nov 27 22:45:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
[root@cld13b11 log]#

Array Details - 

Release version 3.3.1.269 (MU1)
Patches:  P09,P11,P18

Component Name                   Version
CLI Server                       3.3.1.269 (MU1)
CLI Client                       3.3.1.269
System Manager                   3.3.1.315 (P18)
Kernel                           3.3.1.269 (MU1)
TPD Kernel Code                  3.3.1.315 (P18)
TPD Kernel Patch                 3.3.1.315 (P18)

Steps To Reproduce - 
Install docker engine followed by etcd.
Configure docker plugin with 3PAR.
Run Automation script twice or thrice.

CPU stuck error is seen.

Attaching Message log for the reference.
[messages.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1813990/messages.txt)
[messages.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1813992/messages.txt)

**Comment by wdurairaj** [comment]
I have filed the above docker bug  -- NMI watchdog: BUG: soft lockup - CPU stuck error #36675

**Comment by sonawane-shashikant** [comment]
Since this will be documented, closing this issue.
