### ISSUE TITLE
mountConflictDelay:  Volume Mount operation takes longer time than expected on different node after cleaning-up of VLUN forcefully.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#154]
Steps to reproduce:

1. On fresh setup, create a volume and mount it to a container1 in node1.
2. Mount the same volume to container2 in node2.
3. Wait for 40 seconds (default mountConflictDelay period is 30 seconds and 10 seconds to cleanup vlun and mount to node2).

Observation: Volume did not get mounted.

4. Wait for 20-25 more seconds.

Observation: Volume got mounted. It took total 60-65 seconds for mount operation.

Expected result: Mount operation should get completed within 40-45 seconds.

**Comment by imran-ansari** [comment]
@shashi / @sandesh - could you please test this once and let us know if you see the same behavior?

**Comment by imran-ansari** [comment]
Would suggest a retest for this one and then we can decide whether we need to document it.

**Comment by prablr79** [comment]
@sandesh @Shashi did you guys verify this ?  do we need documentation ?
@nilangekarss can you close with test team ?

**Comment by nilangekarss** [comment]
@wdurairaj @imran-ansari @@sonawane-shashikant I feel any mount operation shall take 20-30 sec atleast to mount a device.(This involves discovery, finding paths etc). Hence this needs to be re-thought whether its a bug or documentation activity.

**Comment by sonawane-shashikant** [comment]
With appropriate documentation, this issues can be closed.

**Comment by nilangekarss** [comment]
@sonawane-shashikant I see on this usage documentation https://github.com/hpe-storage/python-hpedockerplugin/blob/master/docs/usage.md#hpe-3par-docker-volume-parameters
purpose of mountConflictDelay is mentioned. Hence it is okay to close this issue. If not agreeing to this statement please reopen it. Closing this bug now.
