### ISSUE TITLE
Volume properties does not display MountConflictDelay from different node

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#156]
1. Create Multinode docker setup having a node running etcd only and 2 nodes with docker volume plugin installed, both nodes pointing towards the node runing etcd.
2. Create a volume on one of the nodes having docker volume plugin with parameters as below:
	size=21
	mountConflictDelay=120
	flash-cache=true
	provisioning=full
docker@cld6b4:~$ docker volume create -d hpe --name SHASHI-VOL -o size=21 -o mountConflictDelay=120 -o flash-cache=true -o provisioning=full
SHASHI-VOL

3. Verify the volume properties on the node from where create command was hit.
docker@cld6b4:  $ docker inspect SHASHI-VOL
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/8ad9ebb7022ba7249fc061f0d079b13ab7492dc44a72e2a6dc832bb5e1fbe34d/rootfs",
        "Name": "SHASHI-VOL",
        "Options": {
            "flash-cache": "true",
            "mountConflictDelay": "120",
            "provisioning": "full",
            "size": "21"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "compression": null,
                "flash_cache": "true",
                "provisioning": "full",
                "size": 21
            }
        }
    }
]

4. Verify the properties of the same volume on the other node.
docker@cld6b5 :  $ docker inspect SHASHI-VOL
[
    {
        "Driver": "hpe:latest",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/plugins/e5136c1b00a0aed4effe0f11f347342633117b5c14309f678038442cc2fb1eed/rootfs",
        "Name": "SHASHI-VOL",
        "Options": {},
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "compression": null,
                "flash_cache": "true",
                "provisioning": "full",
                "size": 21
            }
        }
    }
]
docker@cld6b5:~$

Nowhere on the second node, we could see the mountConflictDelay property.

**Comment by imran-ansari** [comment]
This has been fixed. Code under review.

**Comment by sonawane-shashikant** [comment]
Issue#156 is fixed.
mountConlictDelay is seen on both the nodes

docker@cld6b4:~$ docker inspect SNAP
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/ad2719a928323c48e1fabdbaecb6a9832b83a1f9f93bf996813bb55045987583/rootfs",
        "Name": "SNAP",
        "Options": {
            "expirationHours": "2",
            "mountConflictDelay": "35",
            "qos-name": "SHASHI-VVS",
            "retentionHours": "1"
        },
        "Scope": "global",
        "Status": {
            "qos_detail": {
                "Latency": "500 sec",
                "enabled": true,
                "maxBWS": "40 MB/sec",
                "maxIOPS": "2000000 IOs/sec",
                "minBWS": "30 MB/sec",
                "minIOPS": "10000 IOs/sec",
                "priority": "Low",
                "vvset_name": "SHASHI-VVS"
            },
            "volume_detail": {
                "compression": null,
                "flash_cache": null,
                "mountConflictDelay": 35,
                "provisioning": "thin",
                "size": 100
            }
        }
    }
]
docker@cld6b4:~$


docker@cld6b5:~$ docker inspect SNAP
[
    {
        "Driver": "hpe:latest",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/plugins/c4c6f75f0ad8bf390aa38b6215fd695da45a30e7267932b5f113aafc6a83afdc/rootfs",
        "Name": "SNAP",
        "Options": {},
        "Scope": "global",
        "Status": {
            "qos_detail": {
                "Latency": "500 sec",
                "enabled": true,
                "maxBWS": "40 MB/sec",
                "maxIOPS": "2000000 IOs/sec",
                "minBWS": "30 MB/sec",
                "minIOPS": "10000 IOs/sec",
                "priority": "Low",
                "vvset_name": "SHASHI-VVS"
            },
            "volume_detail": {
                "compression": null,
                "flash_cache": null,
                "mountConflictDelay": 35,
                "provisioning": "thin",
                "size": 100
            }
        }
    }
]
