### ISSUE TITLE
MountConflictDelay : TimeOut with 120 issue

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#157]
1. Create Multinode docker setup having a node running etcd only and 2 nodes with docker volume plugin installed, both nodes pointing towards the node running etcd.
2. Create a volume on one of the nodes having docker volume plugin with parameters as below:
size=21
mountConflictDelay=120
flash-cache=true
provisioning=full
docker@cld6b4: ~ $  docker volume create -d hpe --name SHASHI-VOL -o size=21 -o mountConflictDelay=120 -o flash-cache=true -o provisioning=full
SHASHI-VOL
3. Mount volume
docker@cld6b4: ~ $  docker run -it -d --mount src=SHASHI-VOL,dst=/data1,volume-driver=hpe --name MOUNT --rm busybox /bin/sh
886256f3263de474acdc7201b388f2102a29ff3a51afba26fd4c2d3d6571584a
4. Verify by-path entries
docker@cld6b4: ~ $  ls -lrt /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Mar 21 01:55 pci-0000:03:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx 1 root root  9 Mar 21 01:55 pci-0000:03:00.0-scsi-0:1:0:2 -> ../../sdc
lrwxrwxrwx 1 root root 10 Mar 21 01:55 pci-0000:03:00.0-scsi-0:1:0:0-part5 -> ../../sda5
lrwxrwxrwx 1 root root 10 Mar 21 01:55 pci-0000:03:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Mar 21 01:55 pci-0000:03:00.0-scsi-0:1:0:1 -> ../../sdb
lrwxrwxrwx 1 root root 10 Mar 21 01:55 pci-0000:03:00.0-scsi-0:1:0:2-part1 -> ../../sdc1
lrwxrwxrwx 1 root root 10 Mar 21 01:55 pci-0000:03:00.0-scsi-0:1:0:1-part1 -> ../../sdb1
lrwxrwxrwx 1 root root 10 Mar 21 01:55 pci-0000:03:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root  9 Mar 22 21:37 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-0 -> ../../sdd
lrwxrwxrwx 1 root root  9 Mar 22 21:37 ip-10.50.3.60:3260-iscsi-iqn.2000-05.com.3pardata:23210002ac019d52-lun-0 -> ../../sde
5. Verify the host on the array.
CSIM-8K02_MXN6072AC7 cli% showvlun
Active VLUNs
Lun VVName                     HostName               ---------Host_WWN/iSCSI_Name----------  Port        Type Status ID
  0 dcv-Kf9pr9gnQleVXDSIiGmZ3Q cld6b4                 iqn.1993-08.org.debian:01:15e3441420c7 2:2:1 matched set active  1
  0 dcv-Kf9pr9gnQleVXDSIiGmZ3Q cld6b4                 iqn.1993-08.org.debian:01:15e3441420c7 3:2:1 matched set active  1
  0 dcv-yQtffohtQo69ZS7oIbtmow csimbe06-b12           iqn.1994-05.com.redhat:23f53bc77bcc    2:2:1 matched set active  1
  0 dcv-yQtffohtQo69ZS7oIbtmow csimbe06-b12           iqn.1994-05.com.redhat:23f53bc77bcc    3:2:1 matched set active  1
  0 dcv-yb3cNLKiSPuuL2VOUBvTwQ openshift-worker-node2 iqn.1994-05.com.redhat:74f8a7b5d7be    2:2:1 matched set active  1
  0 dcv-yb3cNLKiSPuuL2VOUBvTwQ openshift-worker-node2 iqn.1994-05.com.redhat:74f8a7b5d7be    3:2:1 matched set active  1
------------------------------------------------------------------------------------------------------------------------
  6 total

VLUN Templates
Lun VVName                     HostName               -Host_WWN/iSCSI_Name-  Port        Type
  0 dcv-Kf9pr9gnQleVXDSIiGmZ3Q cld6b4                 ----------------      2:2:1 matched set
  0 dcv-Kf9pr9gnQleVXDSIiGmZ3Q cld6b4                 ----------------      3:2:1 matched set
  0 dcv-yQtffohtQo69ZS7oIbtmow csimbe06-b12           ----------------      2:2:1 matched set
  0 dcv-yQtffohtQo69ZS7oIbtmow csimbe06-b12           ----------------      3:2:1 matched set
  0 dcv-yb3cNLKiSPuuL2VOUBvTwQ openshift-worker-node2 ----------------      2:2:1 matched set
  0 dcv-yb3cNLKiSPuuL2VOUBvTwQ openshift-worker-node2 ----------------      3:2:1 matched set
---------------------------------------------------------------------------------------------
  6 total

6. Now Mount the same volume from another node and wait till MountConflictDelay period gets over.
docker@cld6b5: ~ $  docker run -it -d --mount src=SHASHI-VOL,dst=/data1,volume-driver=hpe --name MOUNT --rm busybox /bin/sh
d65b431a249b1866f4ff033c5b8afc52430803cf607f5d42e33875ca0fd43558
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/e5136c1b00a0aed4effe0f11f347342633117b5c14309f678038442cc2fb1eed/rootfs': Post http://%2Frun%2Fdocker%2Fplugins%2Fe5136c1b00a0aed4effe0f11f347342633117b5c14309f678038442cc2fb1eed%2Fhpe.sock/VolumeDriver.Mount: context deadline exceeded.

Expected results - Mount on the second node and unmount on the first node should be successful.

Actual Results - Error displays as, "context deadline exceeded."

Note: 
1. Despite above error. Migration of the volume from first node to the seconds succeeds.
2. We can see entries on the /dev/disk/by-path/ on the second node.
3. Host entry on the array changes as seen below.

CSIM-8K02_MXN6072AC7 cli% showvlun
Active VLUNs
Lun VVName                     HostName               ---------Host_WWN/iSCSI_Name----------  Port        Type Status ID
  0 dcv-Kf9pr9gnQleVXDSIiGmZ3Q cld6b5                 iqn.1993-08.org.debian:01:79fbac79f151 2:2:1 matched set active  1
  0 dcv-Kf9pr9gnQleVXDSIiGmZ3Q cld6b5                 iqn.1993-08.org.debian:01:79fbac79f151 3:2:1 matched set active  1
  0 dcv-yQtffohtQo69ZS7oIbtmow csimbe06-b12           iqn.1994-05.com.redhat:23f53bc77bcc    2:2:1 matched set active  1
  0 dcv-yQtffohtQo69ZS7oIbtmow csimbe06-b12           iqn.1994-05.com.redhat:23f53bc77bcc    3:2:1 matched set active  1
  0 dcv-yb3cNLKiSPuuL2VOUBvTwQ openshift-worker-node2 iqn.1994-05.com.redhat:74f8a7b5d7be    2:2:1 matched set active  1
  0 dcv-yb3cNLKiSPuuL2VOUBvTwQ openshift-worker-node2 iqn.1994-05.com.redhat:74f8a7b5d7be    3:2:1 matched set active  1
------------------------------------------------------------------------------------------------------------------------
  6 total

VLUN Templates
Lun VVName                     HostName               -Host_WWN/iSCSI_Name-  Port        Type
  0 dcv-Kf9pr9gnQleVXDSIiGmZ3Q cld6b5                 ----------------      2:2:1 matched set
  0 dcv-Kf9pr9gnQleVXDSIiGmZ3Q cld6b5                 ----------------      3:2:1 matched set
  0 dcv-yQtffohtQo69ZS7oIbtmow csimbe06-b12           ----------------      2:2:1 matched set
  0 dcv-yQtffohtQo69ZS7oIbtmow csimbe06-b12           ----------------      3:2:1 matched set
  0 dcv-yb3cNLKiSPuuL2VOUBvTwQ openshift-worker-node2 ----------------      2:2:1 matched set
  0 dcv-yb3cNLKiSPuuL2VOUBvTwQ openshift-worker-node2 ----------------      3:2:1 matched set
---------------------------------------------------------------------------------------------
  6 total

**Comment by wdurairaj** [comment]
Any delay more than 30 secs.. probably the docker CLI is timing out rather than the plugin I believe here. Let's confirm this.

**Comment by sonawane-shashikant** [comment]
Since this will be documented, closing this issue.
