### ISSUE TITLE
Enable CI workflow for all push requests to master

### ISSUE THREAD

**Issue by garthmbooth** [hpe-storage/python-hpedockerplugin#16]

**Comment by farhan7500** [comment]
Added Travis CI unit test and pep8 check to the current development plugin_v2 branch.

https://travis-ci.com/hpe-storage/python-hpedockerplugin/

**Comment by wdurairaj** [comment]
plugin_v2 branch of this repository is used for the current plugin implementation, and the CI workflow is integrated on this branch using Travis, as updated in the previous comment. Hence closing this.
