### ISSUE TITLE
Incorrect provisioning seen for docker volume-snapshot inspect

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#160]
Summary - When snapshot is created for dedup provisioned volume, its provisioning is seen as dedup in docker and NA in 3PAR

Prerequisite - 
Docker engine 17.06 install
Plugin docketciuser install
3PAR backend conifgured with docker

Steps to reproduce - 
1. Create volume with dedipt provisioning
2. Create snapshot of the volume created in step1
3. Inspect volume snapshot

Expected results - 
Values printed in docker inspect of the volume snapshot should match with the snapshot details seen in 3PAR backend.

Actual Results - 
Docker inspect volume snapshot shows provisioning as Dedup whereas in 3PAR dedup parameter is seen as NA('--' in IMC)

Below is the command output for docker volume-snap inspect command
docker@cld6b1:~$ docker volume inspect VOLUME1
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/5854e2e503d392b6e86ed5479e98ba47252ee2976c518d849ddcd80aff458019/rootfs",
        "Name": "VOLUME1",
        "Options": {
            "expirationHours": "2",
            "retentionHours": "2",
            "virtualCopyOf": "VOLUME"
        },
        "Scope": "global",
        "Status": {
            "snap_detail": {
                "compression": null,
                "expiration_hours": 2,
                "flash_cache": null,
                "is_snap": true,
                "parent_id": "8d4beab2-1cf7-472b-ba91-6eceedd19f8c",
                "parent_volume": "VOLUME",
                "provisioning": "dedup",
                "retention_hours": 2,
                "size": 13
            }
        }
    }
]

Snapshot provisioning parameter on 3PAR backend - 
CSIM-8K02_MXN6072AC7 cli %  showvv -cpg SS_CPG6
                                                                                                              -Rsvd(MiB)- -(MiB)-
   Id Name                        Prov Compr Dedup Type  CopyOf                      BsId Rd -Detailed_State-   Snp   Usr   VSize
49980 dcv-jUvqshz3Ryu6kW7O7dGfjA  tdvv No    Yes   base  ---                        49980 RW normal            1024  1024   13312
49982  dcs-3zp0rvNnSrWisCef00ZGdA snp  NA    NA    vcopy dcv-jUvqshz3Ryu6kW7O7dGfjA 49980 RW normal              --    --   13312
---------------------------------------------------------------------------------------------------------------------------------
    2 total                                                                                                    1024  1024   26624

**Comment by wdurairaj** [comment]
Documented in "Known limitations" of quick start guide.
