### ISSUE TITLE
OpenShift: Stale VLUN entries are still present in host and 3par array after deleting ReplicaSets/Deployments.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#163]
Steps to reproduce:

**1. Create a Deployment or Replica Sets.**

[docker@openshift-master-node1 ~]$ sudo oc get pod,pvc,pv -o wide
NAME                                              CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS     CLAIM               STORAGECLASS   REASON    AGE
pv/pv-snap3                                       10Gi       RWO           Retain          Released   default/pvc-snap3                            49m
pv/sc-full-f3f81a94-37ed-11e8-9d58-ecb1d7a4b070   10Gi       RWO           Delete          Released   default/pvc-full    sc-full                  1d
pv/sc-mcd-d2bbdd7f-38b7-11e8-9d58-ecb1d7a4b070    10Gi       RWO           Delete          Bound      default/pvc-mcd     sc-mcd                   1m

NAME          STATUS    VOLUME                                        CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pvc/pvc-mcd   Bound     sc-mcd-d2bbdd7f-38b7-11e8-9d58-ecb1d7a4b070   10Gi       RWO           sc-mcd         1m

NAME                                   READY     STATUS    RESTARTS   AGE       IP            NODE
po/docker-registry-1-tdjl8             1/1       Running   1          34d       10.129.0.5    openshift-master-node1
po/nginx-deployment-3740778278-d298q   1/1       Running   0          15s       10.128.0.37   openshift-worker-node3
po/router-1-z5jhl                      1/1       Running   1          34d       10.50.9.17    openshift-master-node1

**2. Scale up it with replicas as "3"**

[docker@openshift-master-node1 ~]$ sudo oc scale --replicas=3 deploy/nginx-deployment
deployment "nginx-deployment" scaled

[docker@openshift-master-node1 ~]$ sudo oc get all
NAME                                REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfigs/docker-registry   1          1         1         config
deploymentconfigs/router            1          1         1         config

NAME                                   READY     STATUS    RESTARTS   AGE       IP            NODE
po/docker-registry-1-tdjl8             1/1       Running   1          34d       10.129.0.5    openshift-master-node1
po/nginx-deployment-3740778278-4t8sh   1/1       Running   0          3m        10.130.0.47   openshift-worker-node2
po/nginx-deployment-3740778278-d298q   1/1       Running   0          6m        10.128.0.37   openshift-worker-node3
po/nginx-deployment-3740778278-w2b9v   1/1       Running   0          3m        10.128.0.38   openshift-worker-node3
po/router-1-z5jhl                      1/1       Running   1          34d       10.50.9.17    openshift-master-node1

NAME                   DESIRED   CURRENT   READY     AGE       CONTAINER(S)   IMAGE(S)                                  SELECTOR
rc/docker-registry-1   1         1         1         34d       registry       openshift/origin-docker-registry:v3.7.0   deployment=docker-registry-1,deploymentconfig=docker-registry,docker-registry=default
rc/router-1            1         1         1         34d       router         openshift/origin-haproxy-router:v3.7.0    deployment=router-1,deploymentconfig=router,router=router

NAME                  CLUSTER-IP       EXTERNAL-IP   PORT(S)                   AGE       SELECTOR
svc/docker-registry   172.30.148.189   <none>        5000/TCP                  34d       docker-registry=default
svc/kubernetes        172.30.0.1       <none>        443/TCP,53/UDP,53/TCP     34d       <none>
svc/router            172.30.143.255   <none>        80/TCP,443/TCP,1936/TCP   34d       router=router

NAME                      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE       CONTAINER(S)   IMAGE(S)   SELECTOR
deploy/nginx-deployment   3         3         3            3           6m        nginx          nginx      app=nginx

**3. VLUNs were present for a single node only as expected.**

CSIM-8K02_MXN6072AC7 cli% showhost openshift*
Id Name                   Persona      ----------WWN/iSCSI_Name----------- Port
33 openshift-worker-node2 Generic-ALUA iqn.1994-05.com.redhat:74f8a7b5d7be 2:2:1
                                       iqn.1994-05.com.redhat:74f8a7b5d7be 3:2:1
--------------------------------------------------------------------------------
 2 total
CSIM-8K02_MXN6072AC7 cli% showvlun -host openshift*
Active VLUNs
Lun VVName                     HostName               --------Host_WWN/iSCSI_Name--------  Port        Type Status ID
  0 dcv-q1bTdzWiQHS9fPLWc4N0IA openshift-worker-node2 iqn.1994-05.com.redhat:74f8a7b5d7be 2:2:1 matched set active  1
  0 dcv-q1bTdzWiQHS9fPLWc4N0IA openshift-worker-node2 iqn.1994-05.com.redhat:74f8a7b5d7be 3:2:1 matched set active  1
---------------------------------------------------------------------------------------------------------------------
  2 total

VLUN Templates
Lun VVName                     HostName               -Host_WWN/iSCSI_Name-  Port        Type
  0 dcv-q1bTdzWiQHS9fPLWc4N0IA openshift-worker-node2 ----------------      2:2:1 matched set
  0 dcv-q1bTdzWiQHS9fPLWc4N0IA openshift-worker-node2 ----------------      3:2:1 matched set
---------------------------------------------------------------------------------------------
  2 total

**4. Delete the deployment.**
  
[docker@openshift-master-node1 ~]$ sudo oc delete deploy/nginx-deployment
deployment "nginx-deployment" deleted

[docker@openshift-master-node1 ~]$ sudo oc get pod,pvc,pv -o wide
NAME                                              CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS     CLAIM               STORAGECLASS   REASON    AGE
pv/pv-snap3                                       10Gi       RWO           Retain          Released   default/pvc-snap3                            1h
pv/sc-full-f3f81a94-37ed-11e8-9d58-ecb1d7a4b070   10Gi       RWO           Delete          Released   default/pvc-full    sc-full                  1d
pv/sc-mcd-d2bbdd7f-38b7-11e8-9d58-ecb1d7a4b070    10Gi       RWO           Delete          Bound      default/pvc-mcd     sc-mcd                   17m

NAME          STATUS    VOLUME                                        CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pvc/pvc-mcd   Bound     sc-mcd-d2bbdd7f-38b7-11e8-9d58-ecb1d7a4b070   10Gi       RWO           sc-mcd         17m

NAME                                   READY     STATUS        RESTARTS   AGE       IP           NODE
po/docker-registry-1-tdjl8             1/1       Running       1          34d       10.129.0.5   openshift-master-node1
po/nginx-deployment-3740778278-d298q   0/1       Terminating   0          16m       <none>       openshift-worker-node3
po/router-1-z5jhl                      1/1       Running       1          34d       10.50.9.17   openshift-master-node1

**5. VLUNs were still present in 3par array and host.**

[docker@openshift-worker-node2 ~]$ docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS               NAMES
36d9de57fe56        hpestorage/legacyvolumeplugin:2.1   "/bin/sh -c ./plugin-"   25 hours ago        Up 25 hours                             plugin_v21
[docker@openshift-worker-node2 ~]$ ls -lrt /dev/disk/by-path
total 0
lrwxrwxrwx. 1 root root 10 Apr  5 05:54 pci-0000:07:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx. 1 root root 10 Apr  5 05:54 pci-0000:07:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 10 Apr  5 05:54 pci-0000:07:00.0-scsi-0:1:0:0-part3 -> ../../sda3
lrwxrwxrwx. 1 root root  9 Apr  5 05:54 pci-0000:07:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx. 1 root root  9 Apr  5 06:00 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-0 -> ../../sde
lrwxrwxrwx. 1 root root  9 Apr  5 06:00 ip-10.50.3.60:3260-iscsi-iqn.2000-05.com.3pardata:23210002ac019d52-lun-0 -> ../../sdf

CSIM-8K02_MXN6072AC7 cli% showhost openshift*
Id Name                   Persona      ----------WWN/iSCSI_Name----------- Port
33 openshift-worker-node2 Generic-ALUA iqn.1994-05.com.redhat:74f8a7b5d7be 2:2:1
                                       iqn.1994-05.com.redhat:74f8a7b5d7be 3:2:1
--------------------------------------------------------------------------------
 2 total
CSIM-8K02_MXN6072AC7 cli% showvlun -host openshift*
Active VLUNs
Lun VVName                     HostName               --------Host_WWN/iSCSI_Name--------  Port        Type Status ID
  0 dcv-q1bTdzWiQHS9fPLWc4N0IA openshift-worker-node2 iqn.1994-05.com.redhat:74f8a7b5d7be 2:2:1 matched set active  1
  0 dcv-q1bTdzWiQHS9fPLWc4N0IA openshift-worker-node2 iqn.1994-05.com.redhat:74f8a7b5d7be 3:2:1 matched set active  1
---------------------------------------------------------------------------------------------------------------------
  2 total

VLUN Templates
Lun VVName                     HostName               -Host_WWN/iSCSI_Name-  Port        Type
  0 dcv-q1bTdzWiQHS9fPLWc4N0IA openshift-worker-node2 ----------------      2:2:1 matched set
  0 dcv-q1bTdzWiQHS9fPLWc4N0IA openshift-worker-node2 ----------------      3:2:1 matched set
---------------------------------------------------------------------------------------------
  2 total

**Comment by imran-ansari** [comment]
@sumitshatwara - Please provide the logs

**Comment by sonawane-shashikant** [comment]
This issue is verified as FIXED with documentation related to dangling LUNs on the worker node.
Attaching detailed output of the test executed.

[VerificationOfIssue163.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/1930618/VerificationOfIssue163.docx)

**Comment by sumitshatwara** [comment]
Closing this issue based on the verification.
