### ISSUE TITLE
OpenShift: Stale VLUN entries are still present in host and 3par array even after parent volume (with snapshot) is unmounted.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#164]
Steps to reproduce:

**1. Create a volume (StorageClass, PVC).**

**2. Mount this volume to a Pod.**

**3. Create a snapshot with base volume created in step1.**

**4. Mount this snapshot to a different Pod**

[docker@openshift-master-node1 ~]$ sudo oc get pod,pvc,pv -o wide
NAME                                               CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM               STORAGECLASS   REASON    AGE
pv/pv-snap3                                        10Gi       RWO           Retain          Bound     default/pvc-snap3                            8m
pv/sc-full-f3f81a94-37ed-11e8-9d58-ecb1d7a4b070    10Gi       RWO           Delete          Bound     default/pvc-full    sc-full                  23h
pv/sc-snap1-5a36a6da-3800-11e8-9d58-ecb1d7a4b070   10Gi       RWO           Delete          Bound     default/pvc-snap    sc-snap1                 21h

NAME            STATUS    VOLUME                                          CAPACITY   ACCESSMODES   STORAGECLASS   AGE
pvc/pvc-full    Bound     sc-full-f3f81a94-37ed-11e8-9d58-ecb1d7a4b070    10Gi       RWO           sc-full        23h
pvc/pvc-snap    Bound     sc-snap1-5a36a6da-3800-11e8-9d58-ecb1d7a4b070   10Gi       RWO           sc-snap1       21h
pvc/pvc-snap3   Bound     pv-snap3                                        10Gi       RWO                          8m

NAME                         READY     STATUS    RESTARTS   AGE       IP            NODE
po/docker-registry-1-tdjl8   1/1       Running   1          34d       10.129.0.5    openshift-master-node1
po/pod-nginx1                1/1       Running   0          22h       10.130.0.45   openshift-worker-node2
po/pod-snap                  1/1       Running   0          21h       10.128.0.36   openshift-worker-node3
po/pod-snap3                 1/1       Running   0          7m        10.130.0.46   openshift-worker-node2
po/router-1-z5jhl            1/1       Running   1          34d       10.50.9.17    openshift-master-node1

**5. Delete all Pods and PVCs.**
  
[docker@openshift-master-node1 ~]$ sudo oc delete po/pod-snap3 po/pod-snap po/pod-nginx1
pod "pod-snap3" deleted
pod "pod-snap" deleted
pod "pod-nginx1" deleted

[docker@openshift-master-node1 ~]$ sudo oc delete pvc/pvc-snap  pvc/pvc-full pvc/pvc-snap3
persistentvolumeclaim "pvc-snap" deleted
persistentvolumeclaim "pvc-full" deleted
persistentvolumeclaim "pvc-snap3" deleted

[docker@openshift-master-node1 ~]$ sudo oc get pod,pvc,pv -o wide
NAME                                              CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS     CLAIM               STORAGECLASS   REASON    AGE
pv/pv-snap3                                       10Gi       RWO           Retain          Released   default/pvc-snap3                            9m
pv/sc-full-f3f81a94-37ed-11e8-9d58-ecb1d7a4b070   10Gi       RWO           Delete          Released   default/pvc-full    sc-full                  23h

NAME                         READY     STATUS    RESTARTS   AGE       IP           NODE
po/docker-registry-1-tdjl8   1/1       Running   1          34d       10.129.0.5   openshift-master-node1
po/router-1-z5jhl            1/1       Running   1          34d       10.50.9.17   openshift-master-node1

**6. VLUNs were still present in 3par array and host.**

[docker@openshift-worker-node2 ~]$ docker ps -a
CONTAINER ID        IMAGE                               COMMAND                  CREATED             STATUS              PORTS               NAMES
36d9de57fe56        hpestorage/legacyvolumeplugin:2.1   "/bin/sh -c ./plugin-"   23 hours ago        Up 23 hours                             plugin_v21

[docker@openshift-worker-node2 ~]$ ls -lrt /dev/disk/by-path
total 0
lrwxrwxrwx. 1 root root 10 Apr  2 04:39 pci-0000:07:00.0-scsi-0:1:0:0-part3 -> ../../sda3
lrwxrwxrwx. 1 root root 10 Apr  2 04:39 pci-0000:07:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 10 Apr  2 04:39 pci-0000:07:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx. 1 root root  9 Apr  2 04:39 pci-0000:07:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx. 1 root root  9 Apr  4 06:34 ip-10.50.3.59:3260-iscsi-iqn.2000-05.com.3pardata:22210002ac019d52-lun-0 -> ../../sdd
lrwxrwxrwx. 1 root root  9 Apr  4 06:34 ip-10.50.3.60:3260-iscsi-iqn.2000-05.com.3pardata:23210002ac019d52-lun-0 -> ../../sde

CSIM-8K02_MXN6072AC7 cli% showvlun -host openshift*
Active VLUNs
Lun VVName                     HostName               --------Host_WWN/iSCSI_Name--------  Port        Type Status ID
  0 dcv-8mI0nd-sSRawxe1oyr09Xg openshift-worker-node2 iqn.1994-05.com.redhat:74f8a7b5d7be 2:2:1 matched set active  1
  0 dcv-8mI0nd-sSRawxe1oyr09Xg openshift-worker-node2 iqn.1994-05.com.redhat:74f8a7b5d7be 3:2:1 matched set active  1
---------------------------------------------------------------------------------------------------------------------
  2 total

VLUN Templates
Lun VVName                     HostName               -Host_WWN/iSCSI_Name-  Port        Type
  0 dcv-8mI0nd-sSRawxe1oyr09Xg openshift-worker-node2 ----------------      2:2:1 matched set
  0 dcv-8mI0nd-sSRawxe1oyr09Xg openshift-worker-node2 ----------------      3:2:1 matched set
---------------------------------------------------------------------------------------------
  2 total

  
CSIM-8K02_MXN6072AC7 cli% showhost openshift*
Id Name                   Persona      ----------WWN/iSCSI_Name----------- Port
28 openshift-worker-node2 Generic-ALUA iqn.1994-05.com.redhat:74f8a7b5d7be 3:2:1
                                       iqn.1994-05.com.redhat:74f8a7b5d7be 2:2:1
--------------------------------------------------------------------------------
 2 total

**Comment by imran-ansari** [comment]
@sumitshatwara - Could you please attach relevant logs?

**Comment by sumitshatwara** [comment]
This issue did not get reproduced with the latest plugin 2.1. Therefore, I am closing as of now.

I will re-open it as an intermittent issue if I observe this issue one more time.
