### ISSUE TITLE
Bug: Repeatedly force mounting a volume back and forth between nodes creates exception cases

### ISSUE THREAD

**Issue by wdurairaj** [hpe-storage/python-hpedockerplugin#166]
Steps:
1. Mount a volume V1 to C1 on Node1
2. Mount again C1 with V1 on Node2 (expected behaviour: node1's vluns will be cleaned forcefully) -- Failover case
3. Now mount the same container C1 with V1 on Node1 (expected behaviour: node2's vlun will be cleaned up forcefully, volume mount will happen on node1). This simulates a failback case.

In the above process , we have noticed the mount of V1 via C1 , throws either
1. Already mounted exception error
2. String processing exception error

**Comment by sumitshatwara** [comment]
I also observed this "Already mounted exception error" error couple of times in Openshift platform but the issue was intermittent.

**Comment by wdurairaj** [comment]
Fixed and confirmed as per the last update.
