### ISSUE TITLE
Fix Mount/Unmount Unit Test Cases

### ISSUE THREAD

**Issue by garthmbooth** [hpe-storage/python-hpedockerplugin#17]

**Comment by garthmbooth** [comment]
The Mount and Unmount unit tests currently assume a clean test system with no other hpedockerplugin volumes. This makes it difficult to verify new changes on an existing system w/o completely cleaning up the entire system. The tests should be smart enough to only test for volumes it has created as part of each test run. This will make it easier to validate new changes on an existing test system, prior to pushing to master.

**Comment by wdurairaj** [comment]
Now unit tests are added as part of https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/test/test_hpe_plugin_v2.py which uses mocking. Hence closing this.
