### ISSUE TITLE
OpenShift: pod goes in "Terminating" state after when deleted after FAILBACK

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#170]
PreRequisite - 
OpenShift Environment
Plugin Details -  hpestorage/legacyvolumeplugin:2.1

Steps followed - 
1. Create pv,pvc and pod - 
2. Volume created on node2 with pvs created in step1
3. Create new pod on node3 having same pvc
4. This migrates volume from node2 to 3
5.  Migration is successful
6. Try to delete pod created in step1

Expected Results - 
pod should be deleted

Actual results - 
pod goes into "Terminating Status"

Attaching detailed output.
[OpenShiftFailBackIssue.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/1898678/OpenShiftFailBackIssue.docx)

**Comment by wdurairaj** [comment]
I saw that the doryd binary was not either running as a process (or) a daemonset on that environment. We performed a similar set of steps, and the pods eventually got deleted up , when we delete them.

Can you re-confirm this behaviour again?

**Comment by prablr79** [comment]
reproduced again , new bug raised #186

**Comment by sumitshatwara** [comment]
Migrating a volume from one node to another leaves the former node in bad state that disallows deleting of POD on that node. In order workaround this situation, either use POD deletion with force flag OR restart of node services is required.

**Command for forced deletion of POD:**
``` oc delete <po/pod-name> --grace-period=0 --force ```

**Service to restart:**
1.	On Openshift Origin 3.7, restart ```origin-node``` service.
2.	On OpenShift enterprise 3.7, restart ```atomic-openshift-node``` service.
3.	On plain Kubernetes, restart ```kubelet``` service.

**Comment by sonawane-shashikant** [comment]
VERIFIED as FIXED. 
Please refer to bug#186 for verification details.
