### ISSUE TITLE
Kubernetes (1.8): Mount (creation of pod) is not working with managed plugin v2 on docker 17.06

### ISSUE THREAD

**Issue by atotala** [hpe-storage/python-hpedockerplugin#178]
Environment -
OS : RHEL 7.4
docker : 17.06
k8s : 1.8.9

When we tried mounting pvc to a pod, it got failed. Attached  is the dory log snippets for the failure.
[dory_log_snippet.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1954743/dory_log_snippet.txt)

**Comment by prablr79** [comment]
its Managed plugin issue, currently we are not supporting it. in Docker EE 2.0 Managed plugin will not work with Inbuilt kubernetes.

**Comment by wdurairaj** [comment]
1. Managed plugin mounts the volume under /var/lib/docker/plugins/<plugin_id>/rootfs/<mount_dir>
2. For the kubelet to see this directory it has to run as a process in the docker host
3. But, more recently with Docker EE 2.0 kubelet process is containerized and it does'nt have the volume mapping for /var/lib/docker/plugins folder, hence the managed plugin can't be used in conjuction with flexvolumedriver .

However, go forward recommended way is to use containerized plugin only for the flexvolume driver integration.

**Comment by prablr79** [comment]
this bug will be invalid for current plugin, hence closing this bug
