### ISSUE TITLE
Docker service fails to restart after system reboot

### ISSUE THREAD

**Issue by farhan7500** [hpe-storage/python-hpedockerplugin#189]
The docker service fails to restart after system reboot.

`root@ubuntu:~# systemctl start docker
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.`

`root@ubuntu:~# systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─http-proxy.conf, https-proxy.conf
   Active: failed (Result: exit-code) since Thu 2018-06-07 13:47:31 IST; 10s ago
     Docs: https://docs.docker.com
  Process: 3313 ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS (code=exited, status=2)
 Main PID: 3313 (code=exited, status=2)
    Tasks: 18
   Memory: 136.2M
      CPU: 3.691s
   CGroup: /system.slice/docker.service
           ├─3430 containerd-shim 21280c5489ffa1db1a4704cba0fc1f4a1993099f81ba00d7f5f91f656b1cb982 /var/run/docker/libcontainerd/21280c5489ffa1db1a4704cba0fc1f4a1993099f81ba00d7f5f91f656b1cb982 run
           └─21280c5489ffa1db1a4704cba0fc1f4a1993099f81ba00d7f5f91f656b1cb982
             ├─3446 /bin/sh ./plugin-start
             ├─3458 /sbin/udevd
             ├─3460 /sbin/multipathd
             └─3463 /usr/bin/python /usr/bin/twistd --nodaemon hpe_plugin_service
`

Logs snippet from "journalctl -xe"
`Jun 07 13:47:29 ubuntu dockerd[3313]: time="2018-06-07T13:47:29+05:30" level=info msg="2018-06-07 13:47:29.974 12 DEBUG hpe3parclient.http [-] " plugin=21280c5489ffa1db1a4704cba0fc1f4a1993099f81ba0
Jun 07 13:47:29 ubuntu dockerd[3313]: time="2018-06-07T13:47:29+05:30" level=info msg="REQ: curl -i https://15.212.192.252:8080/api/v1/cpgs/FC_r1 -X GET -H \"X-Hp3Par-Wsapi-Sessionkey: 0-59c284d91e
Jun 07 13:47:29 ubuntu dockerd[3313]: time="2018-06-07T13:47:29+05:30" level=info msg=" _http_log_req /usr/lib/python2.7/site-packages/hpe3parclient/http.py:169" plugin=21280c5489ffa1db1a4704cba0fc
Jun 07 13:47:31 ubuntu dockerd[3313]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 07 13:47:31 ubuntu dockerd[3313]: [signal 0xb code=0x1 addr=0x30 pc=0xa37db3]
Jun 07 13:47:31 ubuntu dockerd[3313]: goroutine 43 [running]:
Jun 07 13:47:31 ubuntu dockerd[3313]: panic(0x1d04bc0, 0xc82000e090)
Jun 07 13:47:31 ubuntu dockerd[3313]:         /usr/lib/go-1.6/src/runtime/panic.go:481 +0x3e6
Jun 07 13:47:31 ubuntu dockerd[3313]: github.com/docker/docker/volume/store.lookupVolume(0xc8203c3040, 0xa, 0xc8203c3028, 0x8, 0x0, 0x0, 0x0, 0x0)
Jun 07 13:47:31 ubuntu dockerd[3313]:         /build/docker.io-GDVFYM/docker.io-1.13.1/.gopath/src/github.com/docker/docker/volume/store/store.go:522 +0x353
Jun 07 13:47:31 ubuntu dockerd[3313]: github.com/docker/docker/volume/store.(*VolumeStore).restore.func2(0xc8203c3080, 0xc8203fa000, 0xc82047d0e0, 0xc8203c3028, 0x8, 0xc8203c3040, 0xa, 0xc8203f6f90
Jun 07 13:47:31 ubuntu dockerd[3313]:         /build/docker.io-GDVFYM/docker.io-1.13.1/.gopath/src/github.com/docker/docker/volume/store/restore.go:36 +0xfa
Jun 07 13:47:31 ubuntu dockerd[3313]: created by github.com/docker/docker/volume/store.(*VolumeStore).restore
Jun 07 13:47:31 ubuntu dockerd[3313]:         /build/docker.io-GDVFYM/docker.io-1.13.1/.gopath/src/github.com/docker/docker/volume/store/restore.go:70 +0x238
Jun 07 13:47:31 ubuntu systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 07 13:47:31 ubuntu systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
`

**Comment by wdurairaj** [comment]
Just to add more context to the issue

The sequence which creates the issue is like this:
1. docker volume plugin is in enabled state
2. containerized etcd is up and running
3. systemctl restart docker.service

Once the docker service comes up, the volume plugin which was enabled earlier is started, but the etcd (running as container is still not up - requires a manual start), is not up, and hence the plugin repeatedly hunts for the connection, and this causes some instability issue on the docker side itself, which was given in the previous update.

So, we need to find a way to stop the plugin , if the etcd connection can't be established after few attempts (or retry).

**Comment by sumitshatwara** [comment]
Referencing Issue #38 as I can see the steps are similar.

**Comment by prablr79** [comment]
@imran-ansari please review it..

**Comment by imran-ansari** [comment]
When etcd container is created, we can set the restart policy to "always" that would make the Docker engine bring it up whenever the host or Docker engine restarts.
Along with this, the plugin must keep retrying establishing connection with ETCD.

As an alternative, if we don't want to depend on restart policy, then might as well start ETCD container from within the plugin itself when plugin comes up. This will help the plugin to avoid from having to keep retrying for connection. This will also help the existing customer setups where restart policy has not been used.

**Comment by imran-ansari** [comment]
The first option that I mentioned above is possible using docker update:

**Restart Policy before update**
docker inspect etcd
            "RestartPolicy": {
                *"Name": "no",*
                "MaximumRetryCount": 0
            },

**Update restart policy**
docker update --restart always etcd


**Restart Policy after update**
docker inspect etcd
...
            "RestartPolicy": {
                *"Name": "always",*
                "MaximumRetryCount": 0
...

**Comment by imran-ansari** [comment]
Followed the steps mentioned by @wdurairaj and verified that "restart" policy set to "always" resolves the issue.

**Comment by farhan7500** [comment]
Verified!
