### ISSUE TITLE
Docker 3.0: 3PAR user with single domain access can mount the volume

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#197]
With user belonging to the single domain, I could create and mount the volume successfully.
This contradicts to the below host creation condition where user needs access to all domains.

 

CSIM_EOS14_1674003 cli% showuser
Username       Domain    Role    Default
3paradm        all       super   N
3parcim        all       browse  N
3parsvc        all       super   N
chefsuper      all       super   N
chefusr        Chef_Test edit    N
fsvcvm_user    all       service N
shashi-browse  SHASHI    browse  N
shashi-browse1 SHASHI1   edit    N
shashi-edit    SHASHI    edit    N
testuser       all       super   N
CSIM_EOS14_1674003 cli% showcpg
                                                          ------------------(MB)------------------
                                  ----Volumes---- -Usage- ----- Usr ----- ---- Snp ---- -- Adm ---
Id Name           Domain    Warn% VVs TPVVs TDVVs Usr Snp   Total    Used  Total   Used Total Used
6 ANAND_TEST_1   SHASHI        -   1     1     0   1   0    4096    4096  61440      0 16384  512
8 ANAND_TEST_2   SHASHI        -   1     1     0   0   1       0       0  65536   1024 16384    0
7 ANAND_TEST_3   SHASHI        -   0     0     0   0   0       0       0      0      0     0    0
4 Chef_FC        Chef_Test     -   0     0     0   0   0       0       0      0      0     0    0
5 Chef_FC_Change Chef_Test     -   0     0     0   0   0       0       0      0      0     0    0
0 FC_r1          CAPGEMINI     -   0     0     0   0   0       0       0      0      0     0    0
1 FC_r5          CAPGEMINI     -   1     1     0   1   1    1024    1024 220160   1024 32768  512
2 fs_cpg         -             -  15    12     0  15  12 2305664 2291328 155008 105344 16384 7424
3 SUMIT5         SUMIT         -   0     0     0   0   0       0       0      0      0     0    0
9 TEST_2         -             -   0     0     0   0   0       0       0      0      0     0    0
--------------------------------------------------------------------------------------------------
10 total                                           17  14 2310784 2296448 502144 107392 81920 8448
CSIM_EOS14_1674003 cli%

CSIM_EOS14_1674003 cli% showdomain
ID Domain
1 SUMIT
2 CAPGEMINI
3 SHASHI
4 Chef_Test
6 SHASHI1
CSIM_EOS14_1674003 cli%

docker@cld13b9 :  ~ $ sudo docker volume create -d hpe --name MOUNT-VOL -o size=17
MOUNT-VOL
docker@cld13b9 : ~ $ sudo docker volume create -d hpe --name M^CNT-VOL -o size=17
docker@cld13b9 : ~ $ docker run -it -d -v MOUNT-VOL:/data1 --volume-driver hpe --name MOUNT1 --rm busybox /bin/sh
1d6d6be8d9fc1425661316f1ccd1071244f774afefebf54f17ec134118427179
docker@cld13b9 : ~ $

hpe3par_api_url = https://10.50.3.24:8080/api/v1
hpe3par_username = shashi-edit
hpe3par_password = shashi-edit
san_ip = 10.50.3.24
san_login = 3paradm
san_password = 3pardata
hpe3par_cpg = ANAND_TEST_1
hpe3par_iscsi_chap_enabled = True
hpe3par_iscsi_ips = 10.50.3.2,10.50.2.150
hpe3par_snapcpg = ANAND_TEST_2
docker@cld13b9 : ~ $

CSIM_EOS14_1674003 cli% showvlun -host cld13b9
Active VLUNs
Domain Lun VVName                     HostName ---------Host_WWN/iSCSI_Name----------  Port        Type Status ID
SHASHI   0 dcv-pCZARb-sT2SfXI4VXzcF8A cld13b9  iqn.1993-08.org.debian:01:29f57dfa6792 2:2:1 matched set active  1
SHASHI   1 dcv-CawFFk9HRTOSImoELrWpdQ cld13b9  iqn.1993-08.org.debian:01:29f57dfa6792 2:2:1 matched set active  1
SHASHI   0 dcv-pCZARb-sT2SfXI4VXzcF8A cld13b9  iqn.1993-08.org.debian:01:29f57dfa6792 2:2:2 matched set active  1
SHASHI   1 dcv-CawFFk9HRTOSImoELrWpdQ cld13b9  iqn.1993-08.org.debian:01:29f57dfa6792 2:2:2 matched set active  1
-----------------------------------------------------------------------------------------------------------------
         4 total

VLUN Templates
Domain Lun VVName                     HostName -Host_WWN/iSCSI_Name-  Port        Type
SHASHI   0 dcv-pCZARb-sT2SfXI4VXzcF8A cld13b9  ----------------      2:2:1 matched set
SHASHI   1 dcv-CawFFk9HRTOSImoELrWpdQ cld13b9  ----------------      2:2:1 matched set
SHASHI   0 dcv-pCZARb-sT2SfXI4VXzcF8A cld13b9  ----------------      2:2:2 matched set
SHASHI   1 dcv-CawFFk9HRTOSImoELrWpdQ cld13b9  ----------------      2:2:2 matched set
--------------------------------------------------------------------------------------
         4 total
CSIM_EOS14_1674003 cli% showvv -cpg ANAND_TEST_1
                                                                                   ---Rsvd(MB)--- -(MB)-
   Id Name                       Domain Prov Type CopyOf  BsId Rd -Detailed_State-  Adm  Snp  Usr  VSize
32291 dcv-CawFFk9HRTOSImoELrWpdQ SHASHI tpvv base ---    32291 RW normal            512 1024 2048  17408
32288 dcv-pCZARb-sT2SfXI4VXzcF8A SHASHI tpvv base ---    32288 RW normal            512 1024 4096  23552
--------------------------------------------------------------------------------------------------------
    2 total                                                                        1024 2048 6144  40960
CSIM_EOS14_1674003 cli%

Attaching docker.service log.
[multi-tenancy.log](https://github.com/hpe-storage/python-hpedockerplugin/files/2154097/multi-tenancy.log)

**Comment by prablr79** [comment]
@team, Imran investigation required.

**Comment by sonawane-shashikant** [comment]
Closing as per above comment.
