### ISSUE TITLE
amqp version issue

### ISSUE THREAD

**Issue by Krassi10** [hpe-storage/python-hpedockerplugin#2]
Hi, 
while installing on ubuntu 14.04 LTS we get the follwing error on the amqp version:
error: amqp 1.4.9 is installed but amqp<3.0,>=2.0.2 is required by set(['kombu'])

pip freeze shows that 2.0.3 is installed:
pip freeze |grep amqp
amqp==2.0.3

Installation log:
Installed /usr/local/lib/python2.7/dist-packages/python_hpedockerplugin-1.0.0-py2.7.egg
Processing dependencies for python-hpedockerplugin==1.0.0
Searching for amqp<2.0,>=1.4.0
Reading https://pypi.python.org/simple/amqp/
Best match: amqp 1.4.9
Downloading https://pypi.python.org/packages/cc/a4/f265c6f9a7eb1dd45d36d9ab775520e07ff575b11ad21156f9866da047b2/amqp-1.4.9.tar.gz#md5=df57dde763ba2dea25b3fa92dfe43c19
Processing amqp-1.4.9.tar.gz
Writing /tmp/easy_install-6dVbHt/amqp-1.4.9/setup.cfg
Running amqp-1.4.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6dVbHt/amqp-1.4.9/egg-dist-tmp-q7oCUp
creating /usr/local/lib/python2.7/dist-packages/amqp-1.4.9-py2.7.egg
Extracting amqp-1.4.9-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding amqp 1.4.9 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/amqp-1.4.9-py2.7.egg
error: amqp 1.4.9 is installed but amqp<3.0,>=2.0.2 is required by set(['kombu'])

Thanks.

**Comment by leeantho** [comment]
This issue has been fixed in https://github.com/hpe-storage/python-hpedockerplugin/commit/cea0da83f620f5a31e852d7d30ba8d4b70c5cad2.
