### ISSUE TITLE
Docker plugin build failed with multiple issues

### ISSUE THREAD

**Issue by yashwant09** [hpe-storage/python-hpedockerplugin#201]
Executing udev-init-scripts-32-r2.post-install
(9/40) Installing eudev-libs (3.2.5-r2)
(10/40) Installing xz-libs (5.2.4-r0)
(11/40) Installing kmod (24-r1)
(12/40) Installing eudev (3.2.5-r2)
(13/40) Installing libcrypto1.0 (1.0.2o-r0)
(14/40) Installing libssl1.0 (1.0.2o-r0)
ERROR: libcrypto1.0-1.0.2o-r0: BAD signature
(15/40) Installing json-c (0.13.1-r0)
ERROR: libssl1.0-1.0.2o-r0: BAD signature
(16/40) Installing ncurses-terminfo-base (6.1-r0)
(17/40) Installing ncurses-terminfo (6.1-r0)
(18/40) Installing ncurses-libs (6.1-r0)
(19/40) Installing readline (7.0.003-r0)
(20/40) Installing userspace-rcu (0.10.1-r0)
(21/40) Installing multipath-tools (0.7.7-r0)
(22/40) Installing libbz2 (1.0.6-r6)
(23/40) Installing libressl2.7-libcrypto (2.7.4-r1)
(24/40) Installing expat (2.2.5-r0)
(25/40) Installing libffi (3.2.1-r4)
(26/40) Installing gdbm (1.13-r1)
(27/40) Installing sqlite-libs (3.24.0-r0)
(28/40) Installing libressl2.7-libssl (2.7.4-r1)
(29/40) Installing python2 (2.7.15-r0)
(30/40) Installing py-setuptools (39.1.0-r0)
(31/40) Installing py2-pip (10.0.1-r0)
(32/40) Installing sg3_utils (1.42-r1)
(33/40) Installing sudo (1.8.23-r2)
(34/40) Installing libgcc (6.4.0-r8)
(35/40) Installing sysfsutils (2.1.0-r8)
(36/40) Installing libmount (2.32-r0)
(37/40) Installing libsmartcols (2.32-r0)
(38/40) Installing findmnt (2.32-r0)
(39/40) Installing libfdisk (2.32-r0)
(40/40) Installing util-linux (2.32-r0)
Executing busybox-1.27.2-r7.trigger
2 errors; 79 MiB in 49 packages
The command '/bin/sh -c apk add --no-cache --update     py-pip     py-setuptools     python     sysfsutils     multipath-tools     device-mapper     util-linux     sg3_utils    eudev     libssl1.0 sudo  && apk update  && apk upgrade  && apk add e2fsprogs ca-certificates  && pip install --upgrade pip     setuptools  && rm -rf /var/cache/apk/*' returned a non-zero code: 2

**Comment by prablr79** [comment]
is this new bug or same as 198 ?

**Comment by prablr79** [comment]
is this same bug of SuSE environment ?

**Comment by wdurairaj** [comment]
Build script ./buildDockerPlugin.sh/ containerize.sh is not tested on SuSE, the common build done for all platform (on Ubuntu) will be used in SuSE CaaS platform. Closing this issue for now.
