### ISSUE TITLE
Manage: Snap of Managed Volume does not create

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#209]
Summary - If snap_cpg is not mentioned in hpe.conf, then snapshot of managed volume does not create. 

docker@ubuntu : ~ $  uname -a
Linux ubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
docker@ubuntu : ~ $ lab_release -a
-bash: lab_release: command not found
docker@ubuntu : ~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

Docker host o/p === 

docker@ubuntu : ~ $ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          Snap_Testvol1
hpe:latest          Testvol1
hpe:latest          Testvol2
hpe:latest          clone1
hpe:latest          snapshot2

CSSOS-SSA05 cli% createvv SUPER TEST-VOL 19g
CSSOS-SSA05 cli% showvv -cpg SUPER
                                                                                                            -Rsvd(MiB)- -(MiB)-
  Id Name                        Prov Compr Dedup Type  CopyOf                     BsId Rd -Detailed_State-  Snp    Usr   VSize
4326 dcv-5NtpHjASQjOGpK5IQhf99Q  tpvv No    No    base  ---                        4326 RW normal            512    512    1024
4316 dcv-IgweWOz5Rd6i7VpMxvDalw  tpvv No    No    base  ---                        4316 RW normal            512    512    1024
4323  dcs-vjVBYU1XQ76KGm0HcBo9bw snp  NA    NA    vcopy dcv-IgweWOz5Rd6i7VpMxvDalw 4316 RW normal             --     --    1024
4332 dcv-M-s3CINlR.y1.8fQonmKZw  full NA    NA    base  ---                        4332 RW normal              0  19456   19456
4314 dcv-UPG-LqM2QO2MOgVDzPAv-w  full NA    NA    base  ---                        4314 RW normal              0   1024    1024
4333 TEST-VOL1                   full NA    NA    base  ---                        4333 RW normal              0  17408   17408
-------------------------------------------------------------------------------------------------------------------------------
   6 total                                                                                                  1024  38912   40960

docker@ubuntu : ~ $ docker volume create -d hpe --name MANAGE-TST-VOL -o importVol=TEST-VOL
Error response from daemon: create MANAGE-TST-VOL: ('Volume:%(existing_ref)s does not exists Error: %(ex)s', {'existing_ref': 'TEST-VOL', 'ex': 'Not found (HTTP 404) 23 - volume does not exist'})
docker@ubuntu : ~ $ docker volume create -d hpe --name MANAGE-TST-VOL -o importVol=TEST-VOL1
MANAGE-TST-VOL
docker@ubuntu : ~ $ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          MANAGE-TST-VOL
hpe:latest          Snap_Testvol1
hpe:latest          Testvol1
hpe:latest          Testvol2
hpe:latest          clone1
hpe:latest          snapshot2
docker@ubuntu : ~ $

Note: Snapshot of normal docker volume is created in the user CPG if snapCPG is not mentioned.

CSSOS-SSA05 cli% showvv -cpg SUPER
                                                                                                            -Rsvd(MiB)- -(MiB)-
  Id Name                        Prov Compr Dedup Type  CopyOf                     BsId Rd -Detailed_State-  Snp    Usr   VSize
4333 dcv--Qut0byRRXWGjvFdNumrww  full NA    NA    base  ---                        4333 RW normal              0  17408   17408
4326 dcv-5NtpHjASQjOGpK5IQhf99Q  tpvv No    No    base  ---                        4326 RW normal            512    512    1024
4316 dcv-IgweWOz5Rd6i7VpMxvDalw  tpvv No    No    base  ---                        4316 RW normal            512    512    1024
4323  dcs-vjVBYU1XQ76KGm0HcBo9bw snp  NA    NA    vcopy dcv-IgweWOz5Rd6i7VpMxvDalw 4316 RW normal             --     --    1024
4332 dcv-M-s3CINlR.y1.8fQonmKZw  full NA    NA    base  ---                        4332 RW normal              0  19456   19456
4314 dcv-UPG-LqM2QO2MOgVDzPAv-w  full NA    NA    base  ---                        4314 RW normal              0   1024    1024
-------------------------------------------------------------------------------------------------------------------------------
   6 total                                                                                                  1024  38912   40960
CSSOS-SSA05 cli%

docker@ubuntu:~$ cat /etc/hpedockerplugin/hpe.conf
[DEFAULT]
ssh_hosts_key_file = /root/.ssh/known_hosts
logging = DEBUG
hpe3par_debug = True
suppress_requests_ssl_warnings = False
host_etcd_ip_address = 192.168.68.31
host_etcd_port_number = 2379
hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
hpe3par_api_url = https://192.168.67.5:8080/api/v1
hpe3par_username = 3paradm
hpe3par_password = 3pardata
san_ip = 192.168.67.5
san_password = 3pardata
hpe3par_cpg = SUPER
#hpe3par_snapcpg = SUPER
hpe3par_iscsi_ips = 192.168.68.202
hpe3par_iscsi_chap_enabled = True
use_multipath = True
enforce_multipath = True
mount_conflict_delay = 30

docker@ubuntu : ~ $
docker volume create -d hpe --name Snap_MANAGE-TST-VOL -o virtualCopyOf=MANAGE-TST-VOL
Error response from daemon: create Snap_MANAGE-TST-VOL: Conflict (HTTP 409) 33 - volume has no snapshot CPG
docker@ubuntu:~$

Attaching detailed output for reference.
[SNAPofMANAGE-issue.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/2222125/SNAPofMANAGE-issue.docx)

**Comment by sonivi** [comment]
'snapCPG' is not set in managed volume. thats why its not able to create a snapshot from it

**Comment by sonivi** [comment]
setting of 'snapCPG' was intentionally not handled, thinking it as a pre-requisite

@wdurairaj, @nilangekarss , @prablr79  & @imran-ansari - please suggest

**Comment by sonivi** [comment]
As snap of Managed Volume not able to create clone is also failed.

root@ubuntu:~# docker volume create -d hpe --name clone1 -o cloneOf=Testvol1
Error response from daemon: create clone1: Not authorized.

**Comment by sonawane-shashikant** [comment]
Now able to create a snapshot of managed volume successfully.
