### ISSUE TITLE
SnapShot Scheduling: scheduleFrequency validation is missing

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#219]
While creating snapshot schedule, scheduleFrequency parameter is not validated by the plugin. As per help contents, scheduleFrequecy accepts 5 integers sequentially as below - 
 Field         Allowed Values
                                -----         --------------
                                minute        0-59
                                hour          * or 0-23
                                day-of-month  * or 1-31
                                month         * or 1-12
                                day-of-week   * or 0-6 (0 is Sunday)

Each of the above field needs validation. Any incorrect field should not allow to create schedule.

docker@cld6b10:~$ docker volume create -d hpe --name TEST-SNAP1 -o virtualCopyOf=TEST-VOL -o scheduleFrequency="x x x x x" -o scheduleName=dailyOnceSchedule -o retentionHours=58 -o snapshotPrefix=pqr -o expHrs=5 -o retHrs=3
TEST-SNAP1
docker@cld6b10:~$ docker volum els
docker: 'volum' is not a docker command.
See 'docker --help'
docker@cld6b10:~$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          TEST-SNAP
hpe:latest          TEST-SNAP1
hpe:latest          TEST-VOL
docker@cld6b10 : ~ $  docker volume inspect TEST-SNAP1
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/2257c768fd582078fe18178f533cff7ca8c41737db5eecfa9f99ca6e0306ee76/rootfs",
        "Name": "TEST-SNAP1",
        "Options": {
            "expHrs": "5",
            "retHrs": "3",
            "retentionHours": "58",
            "scheduleFrequency": "x x x x x",
            "scheduleName": "dailyOnceSchedule",
            "snapshotPrefix": "pqr",
            "virtualCopyOf": "TEST-VOL"
        },
        "Scope": "global",
        "Status": {
            "snap_detail": {
                "compression": null,
                "expiration_hours": null,
                "is_snap": true,
                "mountConflictDelay": 30,
                "parent_id": "cd45f33f-a849-4ba5-b927-4af8d073c1e1",
                "parent_volume": "TEST-VOL",
                "provisioning": "thin",
                "retention_hours": 58,
                "size": 100,
                "snap_schedule": {
                    "sched_frequency": "x x x x x",
                    "sched_snap_exp_hrs": 5,
                    "sched_snap_ret_hrs": 3,
                    "schedule_name": "dailyOnceSchedule",
                    "snap_name_prefix": "pqr"
                }
            }
        }
    }
]
docker@cld6b10 : ~ $  docker volume ls
DRIVER              VOLUME NAME
hpe:latest          TEST-SNAP
hpe:latest          TEST-SNAP1
hpe:latest          TEST-VOL
docker@cld6b10 : ~ $ docker volume inspect TEST-SNAP1 | grep  "sched_frequency"
                    "sched_frequency": "x x x x x",
docker@cld6b10 : ~ $

**Comment by nilangekarss** [comment]
Thanks for this finding Shashi.
When we create a schedule on 3PAR with invalid character it doesn't return a string with  Error, It just returns a response saying Invalid character.
CSIM-8K02_MXN6072AC7 cli% createsched "createsv -exp 2h mno.@y@@m@@d@@H@@M@@S@ dcv-PVnvDqp4Tl286ikzpLPDJA" "X X X X X" ThisNewSchedule
Invalid character "X" in schedule 

I will update the code to check for Invalid response.

**Comment by sonawane-shashikant** [comment]
Verified that the scheduleFrequency parameter works as desired.

stack@cld6b9:~ $ sudo docker volume create -d hp_docker --name VOL_TEST -o size=2
VOL_TEST
stack@cld6b9:~ $ sudo docker volume create -d hp_docker --name SNAP_TEST -o virtualCopyOf=VOL_TEST -o scheduleFrequency="x x x x x" -o snapshotPrefix=pqr -o scheduleName=SCHED_TEST
Error response from daemon: create SNAP_TEST: Creation of snapshot schedule failed: Create snapschedule failed Error is 'Invalid character "x" in schedule'

For various scenarios, refer attachment.
In 3par, verified that schedule got created.

[snapshot_test_24aug_docker_window.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2327202/snapshot_test_24aug_docker_window.txt)
