### ISSUE TITLE
Not able to create a volume by using -o backend=3par1 command.

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#223]
Not able to create a volume by using -o backend=3par1 command.
#docker volume create -d hpe --name=db1_3par1 -o provisioning=thin -o backend=3par1 -o size=12
Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker version: Version:17.06.2-ee-15
3PAR array: 192.168.67.5 [DEFAULT] and 192.168.67.7 [3par1]

Steps as follows:
1) Run below command to create a volume on backend array.
   docker volume create -d hpe --name=db1_3par1 -o provisioning=thin -o backend=3par1 -o size=12
Error response from daemon: create db1_3par1: VolumeDriver.Create: <html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b>

    
  </div>
  <div class="error">
    <span>builtins.KeyError</span>: <span>'3par1'</span>
  </div>
</div>

</body></html>
root@ubuntu:~#

NOTE: Able to create a volume on DEFAULT array successfully.

Attached below file for reference.
[3par1_log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2261273/3par1_log.txt)
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2261274/hpe.conf.txt)
[Volume creation.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2261275/Volume.creation.txt)

**Comment by wdurairaj** [comment]
@sonawane-shashikant 

Can you please recreate it once more time on 192.168.68.31 ? I'm not able to recreate it now, after removing some blank spaces in hpe.conf?

i wanted to understand again what caused the original issue

Thanks.

**Comment by wdurairaj** [comment]
Any change in the backend's details in hpe.conf, requires a restart of the plugin (disable/enable)

**Comment by sonawane-shashikant** [comment]
Now able to create a volume by using -o backend=3par1 command.

**Comment by wdurairaj** [comment]
if there is nothing to be done on this. Can you close this issue ?

**Comment by sonawane-shashikant** [comment]
Able to create a volume by using -o backend=3par1 command.
Issue resolve now.
