### ISSUE TITLE
Docker: Repeated "volume id" in comments section

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#224]
1. Create Volume using latest docker volume plugin
2. Verify newly created volume on 3PAR using
    showvv -cpg <cpg-name> -showcols Name,Comment
3. Volume id appears twice as below
    dcv-cWAi04kgRPmt5hU6S3BmyQ  {"volume_id": "716022d3-8920-44f9-ade6-153a4b7066c9", "name": "716022d3-8920-44f9-ade6-153a4b7066c9", "type": "Docker", "display_name": "DOCKER-VOL"}

In Above example, "volume_id" and "name" has same value, so both need not to be displayed.

**Comment by sonawane-shashikant** [comment]
"display_name" is displays appropriately.
"volume_id" and "name" are repeated.

**Comment by nilangekarss** [comment]
@sonivi I agree with you Vivek. Can you please check whether we are using volume_id everywhere for all operations and not name for a particular operation.
If we change this now, we need to make sure another functionality is not broken especially related to snap and cloning.

**Comment by wdurairaj** [comment]
Removing the fixed label since this was not addressed as part of #336

**Comment by sonawane-shashikant** [comment]
Closing this issue as its no more a part of scope.
