### ISSUE TITLE
Snapshot Scheduling: Schedule without -o virtualCopyOf parameter creates on docker host

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#226]
Try to create schedule without passing -o virtualCopyOf parameter as below

docker@cld6b10:~$ docker volume create -d hpe --name SNAP -o scheduleFrequency="3 * * * *" -o snapshotPrefix=shashi -o scheduleName=SCH
SNAP
docker@cld6b10:~$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          SNAP
hpe:latest          TEST-VOL
docker@cld6b10:~$ docker volume inspect SNAP
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/54060d7025f695977533a2ee550f329735cf08dfc175d4ba0681d43c9322f8b2/rootfs",
        "Name": "SNAP",
        "Options": {
            "scheduleFrequency": "3 * * * *",
            "scheduleName": "SCH",
            "snapshotPrefix": "shashi"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "compression": null,
                "flash_cache": null,
                "mountConflictDelay": 30,
                "provisioning": "thin",
                "size": 100
            }
        }
    }
]
docker@cld6b10:~$

We could see on docker host it creates a volume. Same is not visible on 3PAR backend.

**Comment by nilangekarss** [comment]
Hi Shashi, I can see docker volume for the above command on 3PAR.
Can you please recheck.

**Comment by nilangekarss** [comment]
To create a snapshot schedule virtalCopyOf is a mandatory parameter.

**Comment by sonawane-shashikant** [comment]
Since it is a mandatory parameter, exception should be handled and appropriate error should be displayed if user tries to create schedule without passing -o virtualCopyOf parameter.

**Comment by sandesh-desai** [comment]
Verified and working fine as expected.
Attaching the output for reference.
[BUG 226.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2323318/BUG.226.txt)

**Comment by sonawane-shashikant** [comment]
Closing as per above comment
