### ISSUE TITLE
Snapshot Scheduling: snapshotPrefix greater than 3 chars is accepted

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#227]
When we create snapshot schedule with snapshotPrefix having more than 3 characters, schedule successfully created both on docker host as well 3PAR.

docker@cld6b10 : ~ $  docker volume create -d hpe --name SNAP-1 -o virtualCopyOf=TEST-VOL -o scheduleFrequency="13 * * * *" -o snapshotPrefix=shashi -o scheduleName=SCH-1
SNAP-1

CSIM-8K02_MXN6072AC7 cli% showvv -cpg SS_CPG6
                                                                                                              -Rsvd(MiB)- -(MiB)-
   Id Name                        Prov Compr Dedup Type  CopyOf                      BsId Rd -Detailed_State-   Snp   Usr   VSize
80465 dcv-FyPwuYjLT6GAlv3R6miIXw  tpvv No    No    base  ---                        80465 RW normal            1024  1024  102400
80464 dcv-Iu2vNaXQTMSpqLU.nfHhuA  cpvv NA    NA    base  ---                        80464 RW normal             256   256     256
80467  dcs-buAp5aOISAiDH3HkdcP2Bg snp  NA    NA    vcopy dcv-Iu2vNaXQTMSpqLU.nfHhuA 80464 RW normal              --    --     256
80469  dcs-K1YMtWQ4Q7Wu-xvMxJsJ.w snp  NA    NA    vcopy dcv-Iu2vNaXQTMSpqLU.nfHhuA 80464 RW normal              --    --     256
80471  shashi.180806101300        snp  NA    NA    vcopy dcv-Iu2vNaXQTMSpqLU.nfHhuA 80464 RW normal              --    --     256
---------------------------------------------------------------------------------------------------------------------------------
    5 total                                                                                                    1280  1280  103424
CSIM-8K02_MXN6072AC7 cli%

shashi was the prefix used in above case

**Comment by nilangekarss** [comment]
hi shashi,
can you try use case where you provide 15 or 24 digit prefix?

**Comment by sonawane-shashikant** [comment]
Verified that snapshotPrefix of upto 15 characters is accepted.

[bug_227.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2327282/bug_227.txt)
