### ISSUE TITLE
Multi-Array Support:Not able to import a volume from backend 3par1 array.

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#229]
Not able to import a volume from backend 3par1 array it gives an error.

root@ubuntu:~# docker volume create -d hpe --name=db5_3par5 -o backend=3par1 -o importVol=db5_3par5
Error response from daemon: create db5_3par5: ['backend', 'importVol'] cannot be specified at the same time

OR 

root@ubuntu:~# docker volume create -d hpe --name=db5_3par5 -o importVol=db5_3par5 -o backend=3par1
Error response from daemon: create db5_3par5: ['backend', 'importVol'] cannot be specified at the same time

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker version: Version:17.06.2-ee-15
3PAR array: 192.168.67.5 [DEFAULT] and 192.168.67.7 [3par1]

Steps as follows:
1) Create volume on 3PAR manually by using 3PAR command : 
   createvv Multicpg db5_3par5 400g 
2) Import volume db5_3par5 by using the command:
   root@ubuntu:~# docker volume create -d hpe --name=db5_3par5 -o importVol=db5_3par5 -o backend=3par1

it gives an error as : Error response from daemon: create db5_3par5: ['backend', 'importVol'] cannot be specified at the same time.

 Also run the below command:
root@ubuntu:~# docker volume create -d hpe --name=db5_3par5 -o backend=3par1 -o importVol=db5_3par5

It gives the same error below:
Error response from daemon: create db5_3par5: ['backend', 'importVol'] cannot be specified at the same time
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2264989/Syslog.txt)
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2264991/hpe.conf.txt)

**Comment by wdurairaj** [comment]
Use the recent dockerciuser/hpedockerplugin:test tag for the fix

**Comment by wdurairaj** [comment]
can you verify and close this issue ? It's already fixed

**Comment by sandesh-desai** [comment]
Now able to import the volume from backend 3par array.

**Comment by wdurairaj** [comment]
based on previous input closing this issue.
