### ISSUE TITLE
hpe.sock and hpe.sock.lock files not auto-removed on RHEL

### ISSUE THREAD

**Issue by garthmbooth** [hpe-storage/python-hpedockerplugin#23]
The hpe.sock and hpe.sock.lock files are not automatically removed when stopping the plugin on RHEL. This forces manual removal of those files before restarting.

**Comment by sumitshatwara** [comment]
This issue is fixed in the latest managed v2 plugin (v1.0 and later versions).

**Comment by imran-ansari** [comment]
@wdurairaj - I believe this has been fixed long back. Can someone from test team validate this?

**Comment by wdurairaj** [comment]
`docker stop <plugin_container_id> ` removes the hpe.sock, hpe.sock.lock files automatically
