### ISSUE TITLE
Snapshot Scheduling: Schedule Name greater than 31 chars

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#231]
When we create schedule and schedule name exceeds 31 chars, schedule is appropriately snapshot with schedule details appropriately created on docker host but on 3PAR schedule does not create.

docker@cld6b10 : ~ $ docker volume create -d hpe --name VALIDATE-SCHEDULE-LENGTH-1 -o virtualCopyOf=f52f2accdc078c6847950b8af9375a56530ed18b79cb73529c6bd1d5d89ed330 -o retentionHours=2 -o scheduleFrequency="45 * * * *" -o snapshotPrefix=shashi -o scheduleName=THIS-IS-THIRTY-ONE-CHAR-VALIDATION -o expHrs=1 -o retHrs=1
VALIDATE-SCHEDULE-LENGTH-1
docker@cld6b10 : ~ $ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          BASE-SNAP
hpe:latest          DOCKER-VOLUME
hpe:latest          VALIDATE-SCHEDULE-LENGTH
hpe:latest          VALIDATE-SCHEDULE-LENGTH-1
hpe:latest          f52f2accdc078c6847950b8af9375a56530ed18b79cb73529c6bd1d5d89ed330
docker@cld6b10 : ~ $ docker volume inspect VALIDATE-SCHEDULE-LENGTH-1
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/54060d7025f695977533a2ee550f329735cf08dfc175d4ba0681d43c9322f8b2/rootfs",
        "Name": "VALIDATE-SCHEDULE-LENGTH-1",
        "Options": {
            "expHrs": "1",
            "retHrs": "1",
            "retentionHours": "2",
            "scheduleFrequency": "45 * * * *",
            "scheduleName": "THIS-IS-THIRTY-ONE-CHAR-VALIDATION",
            "snapshotPrefix": "shashi",
            "virtualCopyOf": "f52f2accdc078c6847950b8af9375a56530ed18b79cb73529c6bd1d5d89ed330"
        },
        "Scope": "global",
        "Status": {
            "snap_detail": {
                "compression": null,
                "expiration_hours": null,
                "is_snap": true,
                "mountConflictDelay": 30,
                "parent_id": "ba53401d-83bd-4068-ab21-288e92ca478d",
                "parent_volume": "f52f2accdc078c6847950b8af9375a56530ed18b79cb73529c6bd1d5d89ed330",
                "provisioning": "dedup",
                "retention_hours": 2,
                "size": 18,
                "snap_schedule": {
                    "sched_frequency": "45 * * * *",
                    "sched_snap_exp_hrs": 1,
                    "sched_snap_ret_hrs": 1,
                    "schedule_name": "THIS-IS-THIRTY-ONE-CHAR-VALIDATION",
                    "snap_name_prefix": "shashi"
                }
            }
        }
    }
]
docker@cld6b10 : ~ $

**Comment by nilangekarss** [comment]
do u mean to say schedule is not created on 3PAR? can you paste 3par output as well?

**Comment by sonawane-shashikant** [comment]
CSIM-8K02_MXN6072AC7 cli% showsched
                                                                                                                 ------ Schedule ------
SchedName                       File/Command                                                                     Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime
THIS-IS-THIRTY-ONE-CHAR-VALIDAT createsv -exp 1h -retain 1h shashi.@y@@m@@d@@H@@M@@S@ dcv-ulNAHYO9QGirISiOkspHjQ  40    *   *     *   * 3paradm   active     Y 2018-08-07 01:40:00 MDT
SCH-NAME-NEW                    createsv -exp 1h shashi.@y@@m@@d@@H@@M@@S@ dcv-ulNAHYO9QGirISiOkspHjQ             11    *   *     *   * 3paradm   active     Y 2018-08-07 01:11:00 MDT
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2                               total
CSIM-8K02_MXN6072AC7 cli%

Please ignore schedule name "THIS-IS-THIRTY-ONE-CHAR-VALIDAT" as it was created earlier and had valid character length

**Comment by sonawane-shashikant** [comment]
Verified that scheduleName of upto 31 characters is accepted.

[bug_231.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2327291/bug_231.txt)
