### ISSUE TITLE
Snapshot Scheduling: Schedule with -o retHrs doesn’t create snapshot when schedule time is triggered

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#235]
Summary - Schedule with -o retHrs doesn’t create snapshot when schedule time is triggered. 

Testbed -
docker@cld6b10 : ~ $ docker version
Client: Docker Enterprise Edition (EE) 2.0
Version: 17.06.2-ee-16
API version: 1.30
Go version: go1.8.7
Git commit: 9ef4f0a
Built: Thu Jul 26 16:41:28 2018
OS/Arch: linux/amd64
Server: Docker Enterprise Edition (EE) 2.0
Engine:
Version: 17.06.2-ee-16
API version: 1.30 (minimum version 1.12)
Go version: go1.8.7
Git commit: 9ef4f0a
Built: Thu Jul 26 16:40:18 2018
OS/Arch: linux/amd64
Experimental: false
docker@cld6b10 : ~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 16.04.5 LTS
Release: 16.04
Codename: xenial
docker@cld6b10 : ~ $

Steps Followed – 

1.	Created and mounted volume
2.	Created a schedule with -o retHrs parameter as below.

docker@cld6b10 : ~ $  docker volume create -d hpe --name SNAPSHOT -o virtualCopyOf=29da825ab4668214cf8cb5bcb7f1ed1149f599686703980bbe2c969b768fad4f -o scheduleFrequency="33 * * * *" -o snapshotPrefix=PQR -o scheduleName=SCHEDULE -o retentionHours=1 -o retHrs=1 -o expHrs=1
SNAPSHOT
docker@cld6b10 : ~ $ 

3.	Schedule creates successfully. 
4.	Verified the same on 3PAR.
5.	Schedule on 3PAR creates successfully.

CSIM-8K02_MXN6072AC7 cli% showsched
                                                                                        ------ Schedule ------
SchedName File/Command                                                                  Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime
SCHEDULE  createsv -exp 1h -retain 1h PQR.@y@@m@@d@@H@@M@@S@ dcv-3CU9jUuoQI2VC6LDOEr-dQ  33    *   *     *   * 3paradm   active     Y 2018-08-08 02:33:00 MDT
-------------------------------------------------------------------------------------------------------------------------------------------------------------
1         total
CSIM-8K02_MXN6072AC7 cli% showvv -cpg SS_CPG5
                                                                                                               -Rsvd(MiB)- -(MiB)--
   Id Name                         Prov Compr Dedup Type  CopyOf                      BsId Rd -Detailed_State-   Snp   Usr    VSize
80912 .shared.SS_CPG5_0            dds  NA    No    base  ---                        80912 RW normal               0  1024 67108864
80913  dcv-3CU9jUuoQI2VC6LDOEr-dQ  tdvv No    Yes   base  ---                        80913 RW normal            1024  2048    16384
80922   dcs-dgaNf7whTSK6hHbukJQMHQ snp  NA    NA    vcopy dcv-3CU9jUuoQI2VC6LDOEr-dQ 80913 RW normal              --    --    16384
-----------------------------------------------------------------------------------------------------------------------------------
    3 total                                                                                                     1024  3072 67141632

6.	Wait till the first run triggers and after the first run we see no snaposhot is created.

SchedName File/Command                                                                  Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime
SCHEDULE  createsv -exp 1h -retain 1h PQR.@y@@m@@d@@H@@M@@S@ dcv-3CU9jUuoQI2VC6LDOEr-dQ  33    *   *     *   * 3paradm   active     Y 2018-08-08 03:33:00 MDT
-------------------------------------------------------------------------------------------------------------------------------------------------------------
1         total
CSIM-8K02_MXN6072AC7 cli% showvv -cpg SS_CPG5
                                                                                                               -Rsvd(MiB)- -(MiB)--
   Id Name                         Prov Compr Dedup Type  CopyOf                      BsId Rd -Detailed_State-   Snp   Usr    VSize
80912 .shared.SS_CPG5_0            dds  NA    No    base  ---                        80912 RW normal               0  1024 67108864
80913  dcv-3CU9jUuoQI2VC6LDOEr-dQ  tdvv No    Yes   base  ---                        80913 RW normal            1024  2048    16384
80922   dcs-dgaNf7whTSK6hHbukJQMHQ snp  NA    NA    vcopy dcv-3CU9jUuoQI2VC6LDOEr-dQ 80913 RW normal              --    --    16384
-----------------------------------------------------------------------------------------------------------------------------------
    3 total                                                                                                     1024  3072 67141632

7.	Task details of this run is seen as – 
CSIM-8K02_MXN6072AC7 cli% showtask
   Id Type           Name                       Status Phase Step -------StartTime------- ------FinishTime------- -Priority- -User--
11227 scheduled_task RET-HRS                    done     ---  --- 2018-08-07 03:25:00 MDT 2018-08-07 03:25:00 MDT n/a        3paradm
11246 scheduled_task REPEAT1                    done     ---  --- 2018-08-07 11:24:00 MDT 2018-08-07 11:24:01 MDT n/a        3paradm
~
~
~
~
11498 scheduled_task REPEAT4                    failed   ---  --- 2018-08-08 02:30:00 MDT 2018-08-08 02:30:01 MDT n/a        3paradm
11499 scheduled_task REPEAT5                    failed   ---  --- 2018-08-08 02:32:00 MDT 2018-08-08 02:32:01 MDT n/a        3paradm
11500 scheduled_task SCHEDULE                   failed   ---  --- 2018-08-08 02:33:00 MDT 2018-08-08 02:33:01 MDT n/a        3paradm

8.	Detailed task can be seen as below where there is a prompt for the user, due to absence of which task is failing.

CSIM-8K02_MXN6072AC7 cli% showtask -d 11500
   Id Type           Name     Status Phase Step -------StartTime------- ------FinishTime------- -Priority- -User--
11500 scheduled_task SCHEDULE failed   ---  --- 2018-08-08 02:33:00 MDT 2018-08-08 02:33:01 MDT n/a        3paradm

Detailed status:
2018-08-08 02:33:00 MDT Created     task.
2018-08-08 02:33:00 MDT Updated     Executing "SCHEDULE" as 2:700
2018-08-08 02:33:01 MDT Updated     Warning: The retention time cannot be removed or reduced once it is
2018-08-08 02:33:01 MDT Updated     set. This volume cannot be removed until its retention time expires.
2018-08-08 02:33:01 MDT Updated     Are you sure you want to set the retention time?
2018-08-08 02:33:01 MDT Updated     select q=quit y=yes n=no:
2018-08-08 02:33:01 MDT Error       Task exited with status 255
2018-08-08 02:33:01 MDT Failed      Could not complete task.

Expected Results – Snapshot should be created
Actual Results – Snapshot does not create

**Comment by sonawane-shashikant** [comment]
I tried to create schedule on 3PAR with -retain option and could see the same behavior.

CSIM-8K02_MXN6072AC7 cli% showtask
   Id Type           Name                       Status Phase Step -------StartTime------- ------FinishTime------- -Priority- -User--
11227 scheduled_task RET-HRS                    done     ---  --- 2018-08-07 03:25:00 MDT 2018-08-07 03:25:00 MDT n/a        3paradm
11246 scheduled_task REPEAT1                    done     ---  --- 2018-08-07 11:24:00 MDT 2018-08-07 11:24:01 MDT n/a        3paradm
~
~
~
~
11498 scheduled_task REPEAT4                    failed   ---  --- 2018-08-08 02:30:00 MDT 2018-08-08 02:30:01 MDT n/a        3paradm
11499 scheduled_task REPEAT5                    failed   ---  --- 2018-08-08 02:32:00 MDT 2018-08-08 02:32:01 MDT n/a        3paradm
11500 scheduled_task SCHEDULE                   failed   ---  --- 2018-08-08 02:33:00 MDT 2018-08-08 02:33:01 MDT n/a        3paradm
11501 scheduled_task 3PAR-SCHED                 failed   ---  --- 2018-08-08 03:08:00 MDT 2018-08-08 03:08:01 MDT n/a        3paradm


CSIM-8K02_MXN6072AC7 cli% showtask -d 11501
   Id Type           Name       Status Phase Step -------StartTime------- ------FinishTime------- -Priority- -User--
11501 scheduled_task 3PAR-SCHED failed   ---  --- 2018-08-08 03:08:00 MDT 2018-08-08 03:08:01 MDT n/a        3paradm

Detailed status:
2018-08-08 03:08:00 MDT Created     task.
2018-08-08 03:08:00 MDT Updated     Executing "3PAR-SCHED" as 2:1402
2018-08-08 03:08:01 MDT Updated     Warning: The retention time cannot be removed or reduced once it is
2018-08-08 03:08:01 MDT Updated     set. This volume cannot be removed until its retention time expires.
2018-08-08 03:08:01 MDT Updated     Are you sure you want to set the retention time?
2018-08-08 03:08:01 MDT Updated     select q=quit y=yes n=no:
2018-08-08 03:08:01 MDT Error       Task exited with status 255
2018-08-08 03:08:01 MDT Failed      Could not complete task.
CSIM-8K02_MXN6072AC7 cli%

**Comment by nilangekarss** [comment]
Can you check same with exp as 2h and retain as 1 h?

**Comment by sonawane-shashikant** [comment]
Closing this bug as FIXED
Please see attached doc for details..

[bug_235.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2331086/bug_235.txt)
