### ISSUE TITLE
Snapshot Scheduling: Deleting Base Snapshot within retention period (-o retentionHours), shows error but deletes the schedule from 3PAR

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#237]
Summary – Deleting base Snapshot within retention period (-o retentionPeriod) shows the retention related error but deletes the schedule from 3PAR and not from docker.

Testbed -
docker@cld6b10 : ~ $ docker version
Client: Docker Enterprise Edition (EE) 2.0
Version: 17.06.2-ee-16
API version: 1.30
Go version: go1.8.7
Git commit: 9ef4f0a
Built: Thu Jul 26 16:41:28 2018
OS/Arch: linux/amd64
Server: Docker Enterprise Edition (EE) 2.0
Engine:
Version: 17.06.2-ee-16
API version: 1.30 (minimum version 1.12)
Go version: go1.8.7
Git commit: 9ef4f0a
Built: Thu Jul 26 16:40:18 2018
OS/Arch: linux/amd64
Experimental: false
docker@cld6b10 : ~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 16.04.5 LTS
Release: 16.04
Codename: xenial
docker@cld6b10 : ~ $

Steps Followed – 

1.	Create and mount volume
2.	Created a schedule with -o retentionHours parameter (say 1 hr)

docker@cld6b10 : ~ $  docker volume create -d hpe --name SNAPSHOT-NEW -o virtualCopyOf=29da825ab4668214cf8cb5bcb7f1ed1149f599686703980bbe2c969b768fad4f -o scheduleFrequency="33 * * * *" -o snapshotPrefix=PQR -o scheduleName=SCHEDULE-NEW -o retentionHours=1 -o retHrs=1 -o expHrs=2
SNAPSHOT-NEW

3.	Schedule creates successfully. Verify the same on 3PAR. Schedule on 3PAR creates successfully as below.

CSIM-8K02_MXN6072AC7 cli% showsched
                                                                                           ------ Schedule ------
SchedName    File/Command                                                                  Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime
SCHEDULE-NEW createsv -exp 2h -retain 1h PQR.@y@@m@@d@@H@@M@@S@ dcv-3CU9jUuoQI2VC6LDOEr-dQ  33    *   *     *   * 3paradm   active     Y 2018-08-08 07:33:00 MDT
3PAR-SCHED1  createsv -ro -exp 5h -retain 2h SHASHI.@H@.@M@ dcv-3CU9jUuoQI2VC6LDOEr-dQ      15    *   *     *   * 3paradm   active     Y 2018-08-08 07:15:00 MDT
3PAR-SCHED   createsv -ro -exp 1h -retain 2h SHASHI.@H@.@M@ dcv-3CU9jUuoQI2VC6LDOEr-dQ       8    *   *     *   * 3paradm   active     Y 2018-08-08 07:08:00 MDT
SCHEDULE     createsv -exp 1h -retain 1h PQR.@y@@m@@d@@H@@M@@S@ dcv-3CU9jUuoQI2VC6LDOEr-dQ  33    *   *     *   * 3paradm   active     Y 2018-08-08 07:33:00 MDT
----------------------------------------------------------------------------------------------------------------------------------------------------------------
4            total

4.	Now try to delete the snapshot created in step#2 ie. SNAPSHOT-NEW within its retention Period i.e. 1 hour.
5.	Snapshot “SNAPSHOT-NEW” does not delete because of retention period as below,

docker@cld6b10 : ~ $  docker volume rm SNAPSHOT-NEW
Error response from daemon: unable to remove volume: remove SNAPSHOT-NEW: volume retention time has not expired

6.	Verify the schedule which was created on 3PAR. It gets deleted.

CSIM-8K02_MXN6072AC7 cli% showsched
                                                                                          ------ Schedule ------
SchedName   File/Command                                                                  Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime
3PAR-SCHED1 createsv -ro -exp 5h -retain 2h SHASHI.@H@.@M@ dcv-3CU9jUuoQI2VC6LDOEr-dQ      15    *   *     *   * 3paradm   active     Y 2018-08-08 07:15:00 MDT
3PAR-SCHED  createsv -ro -exp 1h -retain 2h SHASHI.@H@.@M@ dcv-3CU9jUuoQI2VC6LDOEr-dQ       8    *   *     *   * 3paradm   active     Y 2018-08-08 07:08:00 MDT
SCHEDULE    createsv -exp 1h -retain 1h PQR.@y@@m@@d@@H@@M@@S@ dcv-3CU9jUuoQI2VC6LDOEr-dQ  33    *   *     *   * 3paradm   active     Y 2018-08-08 07:33:00 MDT
---------------------------------------------------------------------------------------------------------------------------------------------------------------
3           total

7.	Now run docker volume inspect on the base snapshot to see the snapshot schedule details.

docker@cld6b10 : ~ $  docker volume inspect 29da825ab4668214cf8cb5bcb7f1ed1149f599686703980bbe2c969b768fad4f
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/opt/hpe/data/hpedocker-scsi-360002ac00000000001013c1100019d52",
        "Name": "29da825ab4668214cf8cb5bcb7f1ed1149f599686703980bbe2c969b768fad4f",
        "Options": {
            "provisioning": "dedup",
            "size": "16"
        },
        "Scope": "global",
        "Status": {
            "Snapshots": [
                {
                    "Name": "SNAPSHOT",
                    "ParentName": "29da825ab4668214cf8cb5bcb7f1ed1149f599686703980bbe2c969b768fad4f",
                    "snap_schedule": {
                        "sched_frequency": "33 * * * *",
                        "sched_snap_exp_hrs": 1,
                        "sched_snap_ret_hrs": 1,
                        "schedule_name": "SCHEDULE",
                        "snap_name_prefix": "PQR"
                    }
                },
                {
                    "Name": "SNAPSHOT-NEW",
                    "ParentName": "29da825ab4668214cf8cb5bcb7f1ed1149f599686703980bbe2c969b768fad4f",
                    "snap_schedule": {
                        "sched_frequency": "33 * * * *",
                        "sched_snap_exp_hrs": 2,
                        "sched_snap_ret_hrs": 1,
                        "schedule_name": "SCHEDULE-NEW",
                        "snap_name_prefix": "PQR"
                    }
                }
            ],
            "volume_detail": {
                "compression": null,
                "flash_cache": null,
                "mountConflictDelay": 30,
                "provisioning": "dedup",
                "size": 16
            }
        }
    }
]
docker@cld6b10 : ~ $ 

Expected Results – Snapshot schedule details should not be seen under docker volume inspect.
Actual Results – Snapshot schedule details are seen under docker volume inspect.

Attaching detailed output of the test in appropriate format to understand the bug in better manner.
[Deleting Base SnapShot.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/2271313/Deleting.Base.SnapShot.docx)

**Comment by nilangekarss** [comment]
@sonawane-shashikant @wdurairaj @prablr79 This needs some discussion to decide whether to allow retentionHours for a base snapshot while creating a snapshot schedule. If not allowed we need to throw an error if reterntionHours are passed.
If we allow retentionHours we need to add a roll back mechanism in our code. In 3PAR, snapshot schedules do not have any attribute for retaining a snapshot for n number of hours. keeping the retentionHorus associated with a snapshot schedule will restrict the user to retain the created snapshot for the stated number of hours.

**Comment by nilangekarss** [comment]
@sonawane-shashikant @prablr79 @wdurairaj Need your thoughts on this bug to decide do we need to restrict the use of retentionHours?
@sonawane-shashikant after importing the volume, do you see snapshots are getting created for the volume on scheduled time?

**Comment by sandesh-desai** [comment]
Verified and working as per expectation.
Attaching the log.

[Docker output result.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2449689/Docker.output.result.txt)

**Comment by sonawane-shashikant** [comment]
Closing as per above comment.
