### ISSUE TITLE
Multi-Array Support: -o backend option not available in "help"

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#239]
-o backend=[backend name]  option is not available in "help"

Created a pull request and added the above -o backend=[backend name]  option in help.

**Comment by wdurairaj** [comment]
Fix is part of last night build. Please verify.

**Comment by sandesh-desai** [comment]
Verified and Closed.

Attaching the help output.
[help output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2387539/help.output.txt)
