### ISSUE TITLE
Manage: Other option can be used along with importVol option.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#240]
Other option can be used along with importVol option.

Example:
root@ubuntu:~# docker volume create -d hpe --name=Testvol7 -o importVol=volume7 -o backend=3par1
Testvol7

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker version: Version:17.06.2-ee-15
3PAR array: 192.168.67.5 [DEFAULT] and 192.168.67.7 [3par1]

Steps as follows:

1) Create volume on 3PAR manually by using 3PAR command :
2) createvv Multicpg volume7 5g
3) Import  volume7  by using the command:
   root@ubuntu:~# docker volume create -d hpe --name=Testvol7 -o importVol=volume7 -o 
   backend=3par1
4) Volume7 manage successfully.
5) Check on 3PAR array 

After creating volume on 3PAR:
CSSOS-SSA04 cli% showvv -cpg Multicpg -hist
  Id Name    Prov Compr Dedup Type -----CreationTime------ -RetentionEndTime- -ExpirationTime- -SpaceCalcTime- -EfficiencyUpdateTime- -UnrefSpaceFreedTime- -Comment-
2654 volume7 full NA    NA    base 2018-08-09 15:49:01 IST --                 --               --              --                     --                    --
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
   1 total

After importing volume7 from docker:
CSSOS-SSA04 cli% showvv -cpg Multicpg -hist
  Id Name                       Prov Compr Dedup Type -----CreationTime------ -RetentionEndTime- -ExpirationTime- -SpaceCalcTime- -EfficiencyUpdateTime- -UnrefSpaceFreedTime- ----------------------------------------------------------------------Comment----------------------------------------------------------------------
2654 dcv-avouiH-HQtin2MP0EyKAWw cpvv NA    NA    base 2018-08-09 15:49:01 IST --                 --               --              --                     --                    {"volume_id": "6afa2e88-7fc7-42d8-a7d8-c3f41322805b", "name": "6afa2e88-7fc7-42d8-a7d8-c3f41322805b", "type": "Docker", "display_name": "Testvol7"}
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   1 total

**Comment by sonivi** [comment]
either alone 'importVol' option  or in combination with only and only 'backend' option is allowed.

**Comment by nilangekarss** [comment]
Hi,
It looks like it is already fixed and is expected behavior.
with import we can use backend option but other options are not allowed.

please check below link 
https://github.com/hpe-storage/python-hpedockerplugin/pull/236/files#diff-fb5ecd59686ef9e27c2a9e7113b77474R188

**Comment by wdurairaj** [comment]
-o importVol with -o backend is supported as per the recent change -- https://github.com/hpe-storage/python-hpedockerplugin/pull/236

Plus, there was bug to change this behaviour - https://github.com/hpe-storage/python-hpedockerplugin/issues/229

**Comment by sandesh-desai** [comment]
Expected behavior hence closing the bug.
