### ISSUE TITLE
Multi-Array Support:Snapshot schedule fail for import volume from backend array. 

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#246]
Multi-Array Support:Snapshot schedule fail for import volume from backend array. 

Error as follows:
docker@cld6b10:~$ docker volume create -d hpe --name SCHEDULE-VOL -o virtualCopyOf=IMPORTED-TEST-VOL-NEW -o scheduleFrequency="38 * * * *" -o snapshotPrefix=XYZ -o scheduleName=SCHEDULE -o expHrs=1
Error response from daemon: create SCHEDULE-VOL: VolumeDriver.Create: <html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b>

Steps as follows:

1) create a volume on backend 3par array
2) Manage the backend volume on docker.
3) schedule a snapshot Frequency for the manage volume 
it gives an below error
docker@cld6b10:~$ docker volume create -d hpe --name SCHEDULE-VOL -o virtualCopyOf=IMPORTED-TEST-VOL-NEW -o scheduleFrequency="38 * * * *" -o snapshotPrefix=XYZ -o scheduleName=SCHEDULE -o expHrs=1
Error response from daemon: create SCHEDULE-VOL: VolumeDriver.Create: <html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b>

Details log file attached.
[Snapshot scheduled fail.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2277883/Snapshot.scheduled.fail.txt)

**Comment by wdurairaj** [comment]
Please test this latest build for the fix -- dockerciuser/hpedockerplugin:test

**Comment by wdurairaj** [comment]
Looking at the log lines

```
Aug 14 05:45:32 ubuntu dockerd[5909]: time="2018-08-14T05:45:32-04:00" level=info msg="\t  File \"/python-hpedockerplugin/hpedockerplugin/backend_orchestrator.py\", line 119, in create_snapshot" plugin=e2533cdf5372073fc8d7d8ac56ed30ce87f6b82f0f531be58fe493ff48975ce5
Aug 14 05:45:32 ubuntu dockerd[5909]: time="2018-08-14T05:45:32-04:00" level=info msg="\t    schedFrequency, backend)" plugin=e2533cdf5372073fc8d7d8ac56ed30ce87f6b82f0f531be58fe493ff48975ce5
Aug 14 05:45:32 ubuntu dockerd[5909]: time="2018-08-14T05:45:32-04:00" level=info msg="\t  File \"/python-hpedockerplugin/hpedockerplugin/synchronization.py\", line 24, in _wrapped" plugin=e2533cdf5372073fc8d7d8ac56ed30ce87f6b82f0f531be58fe493ff48975ce5
Aug 14 05:45:32 ubuntu dockerd[5909]: time="2018-08-14T05:45:32-04:00" level=info msg="\t    return f(*a, **k)" plugin=e2533cdf5372073fc8d7d8ac56ed30ce87f6b82f0f531be58fe493ff48975ce5
Aug 14 05:45:32 ubuntu dockerd[5909]: time="2018-08-14T05:45:32-04:00" level=info msg="\t  File \"/python-hpedockerplugin/hpedockerplugin/volume_manager.py\", line 439, in create_snapshot" plugin=e2533cdf5372073fc8d7d8ac56ed30ce87f6b82f0f531be58fe493ff48975ce5
Aug 14 05:45:32 ubuntu dockerd[5909]: time="2018-08-14T05:45:32-04:00" level=info msg="\t    schedFrequency, current_backend)" plugin=e2533cdf5372073fc8d7d8ac56ed30ce87f6b82f0f531be58fe493ff48975ce5
Aug 14 05:45:32 ubuntu dockerd[5909]: time="2018-08-14T05:45:32-04:00" level=info msg="\t  File \"/python-hpedockerplugin/hpedockerplugin/synchronization.py\", line 24, in _wrapped" plugin=e2533cdf5372073fc8d7d8ac56ed30ce87f6b82f0f531be58fe493ff48975ce5
Aug 14 05:45:32 ubuntu dockerd[5909]: time="2018-08-14T05:45:32-04:00" level=info msg="\t    return f(*a, **k)" plugin=e2533cdf5372073fc8d7d8ac56ed30ce87f6b82f0f531be58fe493ff48975ce5
Aug 14 05:45:32 ubuntu dockerd[5909]: time="2018-08-14T05:45:32-04:00" level=info msg="\t  File \"/python-hpedockerplugin/hpedockerplugin/volume_manager.py\", line 547, in _create_snapshot" plugin=e2533cdf5372073fc8d7d8ac56ed30ce87f6b82f0f531be58fe493ff48975ce5
Aug 14 05:45:32 ubuntu dockerd[5909]: time="2018-08-14T05:45:32-04:00" level=info msg="\t    'fsMode': vol['fsMode']," plugin=e2533cdf5372073fc8d7d8ac56ed30ce87f6b82f0f531be58fe493ff48975ce5
```
volume_manager.py is failing at this step

```
 db_snapshot = {'name': snapshot_name,
                       'id': snapshot_id,
                       'parent_name': src_vol_name,
                       'parent_id': vol['id'],
                       'fsMode': vol['fsMode'],
```
this is regression caused by secret management change merge , I guess.

**Comment by sandesh-desai** [comment]
Verified and working fine as expected closing the bug.
[BUG 246 output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2317128/BUG.246.output.txt)

Please find the attached file for output.
