### ISSUE TITLE
Unable to mount snapshot of a managed volume

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#247]
Manged the volume from 3par array and created a snapshot of that volume.
Then tried to mount this snapshot ,  it failed.

  | CPG | USER
-- | -- | --
The cpg used   while creating volume on 3par | test_automation | 3paradm (access to   all domain)
CPG and user   deatils in hpe.conf | other_cpg | 3paruser (access to   only test_domain which have cpg "other_cpg")

CSSOS-SSA04 cli% showuser
Username    Domain      Role    Default
3paradm     all         super   N
3paredit    all         edit    N
3paruser    test_domain edit    N
---------------------------------------
3           total
CSSOS-SSA04 cli%

root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# cat /etc/hpedockerplugin/hpe.conf
[DEFAULT]
ssh_hosts_key_file = /root/.ssh/known_hosts
logging = DEBUG
hpe3par_debug = True
suppress_requests_ssl_warnings = False
host_etcd_ip_address = 192.168.68.34
host_etcd_port_number = 2379
hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
hpe3par_api_url = https://192.168.67.7:8080/api/v1
hpe3par_username = 3paradm
hpe3par_password = 3pardata
san_ip = 192.168.67.7
san_password = 3paruser
hpe3par_cpg = other_cpg
hpe3par_snapcpg = other_cpg
hpe3par_iscsi_ips = 192.168.68.203,192.168.68.201

Below are the steps and detailed output - 

1. Create volume from 3PAR cli
createvv test_automation manage_test1 4g
CSSOS-SSA04 cli% showvv -cpg test_automation
                                                                        -Rsvd(MiB)- -(MiB)-
  Id Name         Prov Compr Dedup Type CopyOf BsId Rd -Detailed_State-  Snp    Usr   VSize
3072 manage_test1 full NA    NA    base ---    3072 RW normal              0   4096    4096
-------------------------------------------------------------------------------------------
   1 total                                                                 0   4096    4096
 
2. Mange this volume in docker - 

root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume create  --name=docker_manage_1 -d dockerciuser/hpedockerplugin:test -o importVol=manage_test1
docker_manage_1
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume ls
DRIVER                              VOLUME NAME
local                               35b029a5db61e7491c734b49f173da72ed0874c7ee677225489f2efec32a0617
local                               59ee50cfc975d539a9a3551b0d02ca0218ae8209127c121bb794fb28dc2de836
dockerciuser/hpedockerplugin:test   docker_manage_1

3. Create snapshot of this volume -

root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume create  --name=snap_docker_volume1 -d dockerciuser/hpedockerplugin:test -o virtualCopyOf=docker_manage_1
snap_docker_volume1
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume ls
DRIVER                              VOLUME NAME
local                               35b029a5db61e7491c734b49f173da72ed0874c7ee677225489f2efec32a0617
local                               59ee50cfc975d539a9a3551b0d02ca0218ae8209127c121bb794fb28dc2de836
dockerciuser/hpedockerplugin:test   docker_manage_1
dockerciuser/hpedockerplugin:test   snap_docker_volume1

4. Mount the parent volume - successful

root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker run -it -d --mount src=docker_manage_1,dst=/data,volume-driver=dockerciuser/hpedockerplugin:test --name mounter_manage1 --rm busybox /bin/sh
a97311aa243abb4d80010de354c0ea627652d561164edd2e9faf578661989e66

5. Mount the snapshot of managed volume  - Failed

root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker run -it -d --mount src=snap_docker_volume1,dst=/data,volume-driver=dockerciuser/hpedockerplugin:test --name mounter_snap_manage1 --rm busybox /bin/sh
.
.
.
  </div>
  <div class="error">
    <span>hpedockerplugin.exception.HPEPluginMountException</span>: <span>HPE Docker Volume Plugin Mount Failed: ('connection info retrieval failed, error is: %s', 'Forbidden (HTTP 403) 118 - Volume not in same domain')</span>
  </div>
</div>

**Comment by sonivi** [comment]
tried reproducing it, but unable to reproduce.
might fixed with latest patches.
request to please check and close if not reproducible

**Comment by sandesh-desai** [comment]
Verified and working fine as expected closing the bug.
Please find the attached file for output.
[3PAR output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2464352/3PAR.output.txt)
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2464353/Docker.output.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2464354/Syslog.txt)

**Comment by dockerciuser** [comment]
Verified. Closing the bug.
