### ISSUE TITLE
Snapshot Scheduling:Snapshot Scheduling failed for docker volume

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#252]
Snapshot Scheduling failed for normal docker volume

Error as follows:
**root@ubuntu:~# docker volume create -d hpe --name=Testvolsnapshd -o virtualCopyOf=Testvol -o scheduleFrequency="50 * * * *" -o snapshotPrefix=XYZ -o scheduleName=SCHEDULE10 -o expHrs=1
Error response from daemon: create Testvolsnapshd: Error connecting via ssh: Authentication failed.**

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker version: Version:17.06.2-ee-15
3PAR array: 192.168.67.5 [DEFAULT] and 192.168.67.7 [3par1]

Steps as follows:
1) Create a volume on docker environment:
   docker volume create -d hpe --name=Testvol -o size=100
2) Snapshot creation for docker volume:
   docker volume create -d hpe --name=Testvolsnap -o virtualCopyOf=Testvol
3) snapshot scheduled for the docker volume:
  docker volume create -d hpe --name=Testvolsnapshd -o virtualCopyOf=Testvol -o scheduleFrequency="50 * * * *" -o snapshotPrefix=XYZ -o scheduleName=SCHEDULE10 -o expHrs=1

**Error response from daemon: create Testvolsnapshd: Error connecting via ssh: Authentication failed.**

Attaching the syslog.
[Syslog snapshot_scheduled fail.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2292962/Syslog.snapshot_scheduled.fail.txt)

**Comment by nilangekarss** [comment]
Hi Sandesh,
I was able to create a schedule from the same host on another array.
Can you please try changing the default backend to point it to 3par1 backend array.

These are the outputs for your reference:
docker@ubuntu:~$ docker volume create -d hpe --name 3par1vol -o size=23 -o backend=3par1
3par1vol
docker@ubuntu:~$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          3par1vol
hpe:latest          Testvol
hpe:latest          clone1
hpe:latest          snapshot1
hpe:latest          volume
docker@ubuntu:~$ docker volume inspect 3par1vol
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/0b9aa4fabea800cef4bd3c65feebb580734fcf4a61c4fe1650ec0da3d81e029b/rootfs",
        "Name": "3par1vol",
        "Options": {
            "backend": "3par1",
            "size": "23"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "compression": null,
                "cpg": "Multicpg",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "thin",
                "size": 23,
                "snap_cpg": "Multicpg"
            }
        }
    }
]
docker@ubuntu:~$ docker volume create -d hpe --name snapsched -o virtualCopyOf="3par1" -o scheduleName=scheduleswapnil -o scheduleFrequency="15 * * * *" -o snapshotPre                              fix=swapnil
Error response from daemon: create snapsched: source volume: 3par1 does not exist
docker@ubuntu:~$ docker volume create -d hpe --name snapsched -o virtualCopyOf="3par1vol" -o scheduleName=scheduleswapnil -o scheduleFrequency="15 * * * *" -o snapshot                              Prefix=swapnil
snapsched
docker@ubuntu:~$ vi /etc/hpedockerplugin/hpe.conf
docker@ubuntu:~$ docker volume create -d hpe --name snapsched1 -o virtualCopyOf="3par1vol"
snapsched1
docker@ubuntu:~$
docker@ubuntu:~$
docker@ubuntu:~$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          3par1vol
hpe:latest          Testvol
hpe:latest          clone1
hpe:latest          snapsched
hpe:latest          snapsched1
hpe:latest          snapshot1
hpe:latest          volume
docker@ubuntu:~$ ssh 3paradm@192.168.67.7
The authenticity of host '192.168.67.7 (192.168.67.7)' can't be established.
RSA key fingerprint is SHA256:uU2aco922hyEUXNi85CMlfdFyHf7tmeLcsZvly0KLuU.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '192.168.67.7' (RSA) to the list of known hosts.
3paradm@192.168.67.7's password:
CSSOS-SSA04 cli% showsched
                                                                                      ------ Schedule ------
SchedName       File/Command                                                          Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime
scheduleswapnil createsv -f swapnil.@y@@m@@d@@H@@M@@S@ dcv-AwBa51J5SWmUas5I8eKjMw      15    *   *     *   * 3paradm   active     Y 2018-08-16 15:15:00 IST
SCHEDULE11      createsv -f -exp 1h XYZ.@y@@m@@d@@H@@M@@S@ dcv-5VYpJzB5THmCaR2ssWKo2w  50    *   *     *   * 3paradm   active     Y 2018-08-16 15:50:00 IST
SCHEDULE10      createsv -f -exp 1h XYZ.@y@@m@@d@@H@@M@@S@ dcv-UPD2Fh1iRV.kXNn3rTjYdA  45    *   *     *   * 3paradm   active     Y 2018-08-16 15:45:00 IST
SCHEDULE9       createsv -f -exp 1h XYZ.@y@@m@@d@@H@@M@@S@ dcv-UPD2Fh1iRV.kXNn3rTjYdA  45    *   *     *   * 3paradm   active     Y 2018-08-16 15:45:00 IST
SCHEDULE8       createsv -f -exp 1h XYZ.@y@@m@@d@@H@@M@@S@ dcv-UPD2Fh1iRV.kXNn3rTjYdA  45    *   *     *   * 3paradm   active     Y 2018-08-16 15:45:00 IST
SCHEDULE7       createsv -f -exp 1h XYZ.@y@@m@@d@@H@@M@@S@ dcv-UPD2Fh1iRV.kXNn3rTjYdA  45    *   *     *   * 3paradm   active     Y 2018-08-16 15:45:00 IST
SCHEDULE6       createsv -f -exp 1h XYZ.@y@@m@@d@@H@@M@@S@ dcv-UPD2Fh1iRV.kXNn3rTjYdA  45    *   *     *   * 3paradm   active     Y 2018-08-16 15:45:00 IST
SCHEDULE5       createsv -f -exp 1h XYZ.@y@@m@@d@@H@@M@@S@ dcv-1-uNsicpSL6LvuC.0RtvRg  45    *   *     *   * 3paradm   active     Y 2018-08-16 15:45:00 IST
SCHEDULE2       createsv -f -exp 1h XYZ.@y@@m@@d@@H@@M@@S@ dcv-lNlwNHO-R.epwh6w7cWlPQ  40    *   *     *   * 3paradm   active     Y 2018-08-16 15:40:00 IST
SCHEDULE1       createsv -f -exp 1h XYZ.@y@@m@@d@@H@@M@@S@ dcv-Y.dbUmH5TOq3zLBdE4Wn2Q  38    *   *     *   * 3paradm   active     Y 2018-08-16 15:38:00 IST
SCHEDULE        createsv -f -exp 1h XYZ.@y@@m@@d@@H@@M@@S@ dcv-axAVWylrS9KiVpBG6hXkfA  38    *   *     *   * 3paradm   active     Y 2018-08-16 15:38:00 IST
-----------------------------------------------------------------------------------------------------------------------------------------------------------
11              total
CSSOS-SSA04 cli%

**Comment by sandesh-desai** [comment]
After changing the default backend array to point it to 3par1 backend array ,able to schedule snapshot successfully.


root@ubuntu:~# docker volume create -d hpe --name=Testvol -o size=100
Testvol
root@ubuntu:~# docker volume create -d hpe --name=Testvolsnap -o virtualCopyOf=Testvol
Testvolsnap
root@ubuntu:~# docker volume ls
DRIVER              VOLUME NAME
hpe:latest          Testvol
hpe:latest          Testvolsnap
root@ubuntu:~# docker volume create -d hpe --name=Testvolsnapshd -o virtualCopyOf=Testvol -o scheduleFrequency="50 * * * *" -o snapshotPrefix=XYZ -o scheduleName=SCHEDULE10 -o expHrs=1
Testvolsnapshd
root@ubuntu:~#

Hence closing the ticket.
