### ISSUE TITLE
File Permission:Not able to manage a volume by using fsMode option.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#253]
File Permission:Not able to manage a volume by using fsMode option for both the array [DEFAULT] and [3par1]

Error for [DEFAULT] array.
**root@ubuntu:~# docker volume create -d hpe --name=volume_import -o fsMode=0755 -o importVol=impvol
Error response from daemon: create volume_import: ['fsMode', 'importVol'] cannot be  specified at the same time**

Error for [3par1] array.
root@ubuntu:~# docker volume create -d hpe --name=volume_import_3par1 -o fsMode=0755 -o importVol=impvol_3par1 -o backend=3par1
Error response from daemon: create volume_import_3par1: ['backend', 'fsMode', 'importVol'] cannot be  specified at the same time
===================================================================

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker version: Version:17.06.2-ee-15
3PAR array: 192.168.67.7 [DEFAULT] and 192.168.67.5 [3par1]
================================================================
Steps as follows for [DEFAULT]
1) Create volume on 3PAR manually by using 3PAR command :
    createvv Multicpg impvol 100g
2) Manage a volume impvol on docker with file permission oprtion.
    docker volume create -d hpe --name=volume_import -o fsMode=0755 -o importVol=impvol
================================================================
Steps as follows for [3par1]
1) Create volume on 3PAR manually by using 3PAR command :
    createvv SD_1 impvol_3par1 200g
2) Manage a volume impvol_3par1  on docker with file permission oprtion.
   docker volume create -d hpe --name=volume_import_3par1 -o fsMode=0755 -o importVol=impvol_3par1 -o backend=3par1

===================================================================

Syslog file upload:
[Manage volume syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2296036/Manage.volume.syslog.txt)

[Manage volume syslog_3par1.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2296071/Manage.volume.syslog_3par1.txt)

**Comment by atotala** [comment]
fsMode and fsOwner is not supported with importVol.

**Comment by sandesh-desai** [comment]
As fsMode and fsOwner is not supported with importVol 
closing the BUG.
