### ISSUE TITLE
Multi-array: Additional validations for the -o backend

### ISSUE THREAD

**Issue by wdurairaj** [hpe-storage/python-hpedockerplugin#255]
1. Currently backend name passed as part of -o backend is not validated, and result in a key error
2. Also, if there is a invalid array details in a backend section, the code does'nt ignore that backend and proceed with other backend details parsing.

**Comment by wdurairaj** [comment]
Requirements for Validation:

1) `docker volume create -d hpe --name <vol_name> -o size=X -o backend=Y`
Here the value passed as 'Y' should be validated whether such backend exists in hpe.conf

2) If one of the backend has invalid details like not proper WSAPI URL, CPG information is incorrect etc., then the backend processing should be ignored, and the code should recover (possibly by displaying a warning on the LOG) and move with processing the other backends.

**Comment by wdurairaj** [comment]
Request test team member to cross verify this. Fix is part of last night build. Please verify.

**Comment by sonawane-shashikant** [comment]
Verified this bug; it can be closed.

Performed following scenarios:
1] Created a volume with valid backend & deleted it
2] Tried to create volume with non-existing backend; error is shown [as desired]
3] Tried to use -o backend and -o cloneOf at same time; appropriate error is shown [as desired]
4] Tried to use -o backend and -o virtualCopyOf at same time; appropriate error is shown [as desired]

without specifying -o backend performed following:
5] Created clone
6] Created snapshot
7] Created snapshot schedule

Kindly refer attached files for output from docker window and 3par window.
[docker_window.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2383010/docker_window.txt)
[3par_window.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2383011/3par_window.txt)

**Comment by wdurairaj** [comment]
Based on Shashi's comment previously, closing this issue as fixed.
