### ISSUE TITLE
File Permission:Unable to mount a  backend 3par1 volume 

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#256]
File Permission:Unable to mount a backend 3par1 fsOwner volume.

Steps as follows for [3par1]
1) Create a volume on backend 3par1
    docker volume create -d hpe --name=volume1_3par1 -o size=100 -o fsOwner=1001:1001 -o 
     backend=3par1
2) Create a snapshot
   docker volume create -d hpe --name= snapshot_3par1 -o virtualCopyOf=volume1_3par1
3) create a clone.
   docker volume create -d hpe --name clone1_3par1 -o cloneOf=volume1_3par1
4) Mount a volume
   docker run -it -d --mount src=volume1_3par1,dst=/data1,volume-driver=hpe --name mounter1 --rm --user 1001:1001 busybox /bin/sh
 While mounting a volume it gives an error

Attaching a log file.
[Mounting a backend 3par1 volume .txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2297069/Mounting.a.backend.3par1.volume.txt)

**Comment by sandesh-desai** [comment]
Volume created by using backend=3par1
root@ubuntu:~# docker volume create  --name=volume4 -d hpe -o fsOwner=1001:1001 -o fsMode=0755 -o backend=3par1
volume4

Use below command for mounting the volume:
root@ubuntu:~# docker run -it -v volume4:/data1 --rm --user 1001:1001 --volume-driver hpe busybox /bin/sh

Failed with below error message:
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/87733d013e3c737f080d91e12ca22a98514882d2c91d2c4403121195d8999b75/rootfs': VolumeDriver.Mount: <html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b>

[Mounting a backend 3par1 volume updated .txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2302247/Mounting.a.backend.3par1.volume.updated.txt)

**Comment by sandesh-desai** [comment]
Mounting of snapshot and clone for backend 3par also failed.
[Mounting a backend 3par1 clone.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2302271/Mounting.a.backend.3par1.clone.txt)
[Mounting a backend 3par1 snapshot.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2302272/Mounting.a.backend.3par1.snapshot.txt)

**Comment by atotala** [comment]
Working properly on my setup .

PF Console logs for the same.
```
root@cld13b9:config# docker volume create -d hpe --name=volume1_3par1 -o size=100 -o fsOwner=1001:1001 -o backend=3PAR-1
volume1_3par1
root@cld13b9:config# docker run -it -d --mount src=volume1_3par1,dst=/data1,volume-driver=hpe --name mounter1 --rm --user 1001:1001 busybox /bin/sh
52a960ef3841190d9c123e61ec01892f1f718dd5eddf4a54a5b8690b83b65e48
root@cld13b9:/config#
```

**Comment by sandesh-desai** [comment]
Verified and closed as this issue occurs without file permission option also.
Hence closing this bug and opening new bug.
