### ISSUE TITLE
Inspect volume of snapshot of managed volume failed and entry of snapshot got removed.

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#257]
1. Created a volume using 3parcli - 
    CB2111_67_2 cli% createvv Docker_CI_NEW UNMANAGE_VOL 11
2. Created the volume in docker with -o importVol option
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume create  --name=UNMANAGE_VOL_dcv -d dockerciuser/hpedockerplugin:test -o importVol=UNMANAGE_VOL
UNMANAGE_VOL_dcv
3. Created the snapshot of the managed volume.
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume create  --name=snapshot_UNMANAGE -d dockerciuser/hpedockerplugin:test -o virtualCopyOf=UNMANAGE_VOL_dcv
snapshot_UNMANAGE
4. docker volume ls
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume ls
DRIVER                              VOLUME NAME
dockerciuser/hpedockerplugin:test   UNMANAGE_VOL_dcv
dockerciuser/hpedockerplugin:test   snapshot_UNMANAGE

5. Tried to inspect the snapshot
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume inspect snapshot_UNMANAGE
[]
Error: No such volume: snapshot_UNMANAGE

6. The snapshot entry is deleted from docker side.
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume ls
DRIVER                              VOLUME NAME
dockerciuser/hpedockerplugin:test   UNMANAGE_VOL_dcv

The snapshot exists in 3par

CB2111_67_2 cli% showvv -cpg Docker_CI_NEW -hist
   Id Name                        Prov Compr Dedup Type  -----CreationTime------ ---RetentionEndTime---- -ExpirationTime- -SpaceCalcTime- -EfficiencyUpdateTime- -UnrefSpaceFreedTime- --------------------------------------------------------------------------------------Comment--------------------------------------------------------------------------------------
71870 dcv--Rs5DWtlSjutJ6kC24QXTw  cpvv NA    NA    base  2018-08-17 20:50:57 IST --                      --               --              --                     --                    {"volume_id": "fd1b390d-6b65-4a3b-ad27-a902db84174f", "name": "fd1b390d-6b65-4a3b-ad27-a902db84174f", "type": "Docker", "display_name": "UNMANAGE_VOL_dcv"}
71872  dcs-05L4rfJpTdiiSe9kXcmF-Q snp  NA    NA    vcopy 2018-08-17 20:52:13 IST --                      --               --              --                     --                    {"volume_name": "UNMANAGE_VOL_dcv", "volume_id": "fd1b390d-6b65-4a3b-ad27-a902db84174f", "display_name": "snapshot_UNMANAGE", "description": "snapshot of volume UNMANAGE_VOL_dcv"}

[syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2297805/syslog.txt)

**Comment by sandesh-desai** [comment]
Verified and working fine as expected.
Please find the attached file for output.
[BUG 257 output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2316991/BUG.257.output.txt)

**Comment by dockerciuser** [comment]
Working fine.
