### ISSUE TITLE
Snapshot Sceduling: Unable to create Snapshot Schedule

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#263]
With latest docker volume plugin snapshot scheduling functionality does not work.

[docker@CSSOSBE02-B10 ~]$ docker volume ls
DRIVER              VOLUME NAME
[docker@CSSOSBE02-B10 ~]$ docker version
Client: Docker Enterprise Edition (EE) 2.0
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:40:49 2018
 OS/Arch:      linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:42:11 2018
  OS/Arch:      linux/amd64
  Experimental: false
[docker@CSSOSBE02-B10 ~]$ docker plugin inspect hpe | grep PluginRef
        "PluginReference": "docker.io/dockerciuser/hpedockerplugin:test",

CREATE DOCKER VOLUME

[docker@CSSOSBE02-B10 ~]$ docker volume create -d hpe --name TEST-VOL -o size=21
TEST-VOL

MOUNT DOCKER VOLUME - (THIS IS AN OTIONAL STEP)

[docker@CSSOSBE02-B10 ~]$ docker run -it -d -v TEST-VOL:/data1 --rm busybox /bin/sh
74ed6bb63ee4862503f0cb84cf69c43a2bb660593845c709558bc0a863eef337

CREATE SNAPSHOT SCHEDULE TO SEE THE FAILURE

[docker@CSSOSBE02-B10 ~]$ docker volume create -d hpe --name=TEST-SNAP -o virtualCopyOf=TEST-VOL -o scheduleFrequency="15 * * * *" -o scheduleName=SCHEDULE -o snapshotPrefix=xyz -o expHrs=1 Error response from daemon: create TEST-SNAP: Error connecting via ssh: Authentication failed.

CREATE SNAPSHOT WITHOUT PASSING SCHEDULING PARAMETERS

[docker@CSSOSBE02-B10 ~]$ docker volume create -d hpe --name=TEST-SNAP -o virtualCopyOf=TEST-VOL
TEST-SNAP

[docker@CSSOSBE02-B10 ~]$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          TEST-SNAP
hpe:latest          TEST-VOL

Attaching hpe.conf and logs captured while creating the snapshot schedule.
[auth-issue.log](https://github.com/hpe-storage/python-hpedockerplugin/files/2314218/auth-issue.log)

**Comment by sonawane-shashikant** [comment]
[hpe.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2314222/hpe.txt)

**Comment by sonawane-shashikant** [comment]
Closing this bug as INVALID


[RE_ Snapshot Scheduling Bug Verification Blocker.zip](https://github.com/hpe-storage/python-hpedockerplugin/files/2317214/RE_.Snapshot.Scheduling.Bug.Verification.Blocker.zip)

**Comment by nilangekarss** [comment]
This was a configuration issue.
