### ISSUE TITLE
MultiCPG : Error while creating volume with option importVol and cpg together

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#264]
Creation of  the volume in docker with importVol and cpg options failed with below error - 

root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests# sudo docker volume create -d dockerciuser/hpedockerplugin:test --name managed_3parvol -o importVol=3parvol -o cpg=multi_cpg
Error response from daemon: create managed_3parvol: ['cpg', 'importVol'] cannot be  specified at the same time

**Comment by wdurairaj** [comment]
-o importVol and -o backend is the only option permitted right now.

Source Ref: https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/hpedockerplugin/hpe_storage_api.py#L197

**Comment by dockerciuser** [comment]
As importVol and cpg options not permitted now... Closing the bug.
