### ISSUE TITLE
Replication: Volume inspect shows CPG of Primary Array even after failover

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#266]
Summary - Volume inspect shows Primary Array CPG after failover
Pre-requisites - Docker configured with replicated 3PAR having quorum witness.

Below steps were followed - 
1. Create, Mount volume
2. Create data files into the container.
3. Verify the volume on both Primary and Secondary arrays - desired RCG with volume should be seen on both Primary and Secondary arrays.
4. INSPECT DOCKER VOLUME TO SEE THE CPG OF PRIMARY ARRAY.
5. Now failover the RCG
6. INSPECT DOCKER VOLUME TO SEE THE CPG DETAILS OF PRIMARY ARRAY. IT SHOULD SHOW CPG OF SECONDARY ARRAY.

Attaching detailed output of the test executed.

[replication-inspect-issue.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/2318016/replication-inspect-issue.docx)

**Comment by imran-ansari** [comment]
@sonawane-shashikant - This has been fixed. Please validate and close if fine.

**Comment by sandesh-desai** [comment]
Verified and closed.
Attaching output
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2410705/Docker.output.txt)
[Primary Array output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2410706/Primary.Array.output.txt)
[Secondary Array output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2410707/Secondary.Array.output.txt)


.

**Comment by sonawane-shashikant** [comment]
Closing as per above comment
