### ISSUE TITLE
docker volume inspect is showing "flash_cache": null, when volume is created using vvset with flashcache enabled.

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#268]
Followed below steps - 
1. Created vvset 
createvvset multicpg_2
2. Set QOS rules as  - 
setqos -io 300 vvset:multicpg_2
3. Enabled flashcache for the vvset 
setflashcache enable vvset:multicpg_2
4. Created a docker volume -
docker volume create --name=volmulti_cpg -d dockerciuser/hpedockerplugin:test -o size=13 -o cpg=Docker_CI -o qos-name=multicpg_2

The volume is created without any error but the flashcache showing "null" in docker volume inspect output as

root@cssosbe03-b04:/home/stack# docker volume inspect volmulti_cpg
[
    {
        "Driver": "dockerciuser/hpedockerplugin:test",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/f31580821d6225c32dcf9bde9f38aacf07169e5dbcc236d6266f531f91017a4a/rootfs",
        "Name": "volmulti_cpg",
        "Options": {
            "cpg": "Docker_CI",
            "qos-name": "multicpg_2",
            "size": "13"
        },
        "Scope": "global",
        "Status": {
            "qos_detail": {
                "enabled": true,
                "maxIOPS": "300 IOs/sec",
                "minIOPS": "300 IOs/sec",
                "priority": "Normal",
                "vvset_name": "multicpg_2"
            },
            "volume_detail": {
                "compression": null,
                "cpg": "Docker_CI",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "thin",
                "size": 13,
                "snap_cpg": "Docker_CI_NEW"
            }
        }
    }
]

Whereas I can see this volume listed under showflashcache -vv output on 3PAR -

CB2111_67_2 cli% showvv -cpg Docker_CI_NEW -hist
   Id Name                       Prov Compr Dedup Type -----CreationTime------ -RetentionEndTime- -ExpirationTime- -SpaceCalcTime- -EfficiencyUpdateTime- -UnrefSpaceFreedTime- ------------------------------------------------------------------------Comment------------------------------------------------------------------------
92216 dcv-SnZKQsN4SrSV1wXwPc5H1A tpvv No    No    base 2018-08-24 17:16:44 IST --                 --               --              --                     --                    {"volume_id": "4a764a42-c378-4ab4-95d7-05f03dce47d4", "name": "4a764a42-c378-4ab4-95d7-05f03dce47d4", "type": "Docker", "display_name": "volmulti_cpg"}
92205 flashcache_2               full NA    NA    base 2018-08-24 16:41:11 IST --                 --               --              --                     --                    --        
----------------------------------------------------------------------------------------------------------------------------------------------------

CB2111_67_2 cli% showflashcache -vv dcv-SnZKQsN4SrSV1wXwPc5H1A
 VVid VVName                     AFCPolicy
92216 dcv-SnZKQsN4SrSV1wXwPc5H1A enabled
------------------------------------------
    1 total
CB2111_67_2 cli%

**Comment by sonivi** [comment]
volume object is not populating 'flash-cache'

**Comment by dockerciuser** [comment]
Verified ..... working fine.
