### ISSUE TITLE
quick-start: containerize.sh exists with error code (image not created)

### ISSUE THREAD

**Issue by chris7444** [hpe-storage/python-hpedockerplugin#27]
436  git clone  https://github.com/hpe-storage/python-hpedockerplugin.git
 437  cd python-hpedockerplugin/
 440  ./containerize.sh 2>&1 | tee ~/containerize.log
  
last lines
Processing requests-2.12.5.tar.gz
Writing /tmp/easy_install-pbAoxz/requests-2.12.5/setup.cfg
Running requests-2.12.5/setup.py -q bdist_egg --dist-dir /tmp/easy_install-pbAoxz/requests-2.12.5/egg-dist-tmp-g_FTII
warning: no files found matching 'test_requests.py'
creating /usr/lib/python2.7/site-packages/requests-2.12.5-py2.7.egg
Extracting requests-2.12.5-py2.7.egg to /usr/lib/python2.7/site-packages
Adding requests 2.12.5 to easy-install.pth file

Installed /usr/lib/python2.7/site-packages/requests-2.12.5-py2.7.egg
error: amqp 1.4.9 is installed but amqp!=2.1.4,>=2.1.0 is required by set(['oslo.messaging'])
The command '/bin/sh -c apk add --virtual /tmp/.temp --no-cache --update     build-base     g++     gcc     libffi-dev     linux-headers     make     openssl         openssh-client  openssl-dev     python-dev  && wget https://pypi.python.org/packages/69/17/eec927b7604d2663fef82204578a0056e11e0fc08d485fdb3b6199d9b590/pyasn1-0.2.3.tar.gz#md5=79f98135071c8dd5c37b6c923c51be45  && tar xvzf pyasn1-0.2.3.tar.gz  && cd pyasn1-0.2.3  && python setup.py install  && rm -rf pyasn1-0.2.3  && cd /python-hpedockerplugin  && pip install --upgrade .  && python setup.py install  && apk del /tmp/.temp  && rm -rf /var/cache/apk/*' returned a non-zero code: 1

this is RHEL-7.3 (Red Hat Enterprise Linux Server release 7.3 (Maipo))

[containerize.zip](https://github.com/hpe-storage/python-hpedockerplugin/files/933578/containerize.zip)

**Comment by wdurairaj** [comment]
https://github.com/hpe-storage/python-hpedockerplugin/pull/28/files has a changed requirement.txt which will address this issue. Once this pull request is merged, the fix will be available in master branch of the repo.

**Comment by hpe-storage** [comment]
Current master has the fix for this issue -- change in requirement.txt
