### ISSUE TITLE
Snapshot Schedule: Docker does not support frequency shortcuts like "@monthly"

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#270]
Frequency shortcuts are present in 3PAR createsched command, however they are absent in docker command.
Eg. In createsched command, we can use "@monthly" as taskschedule.
Then snapshot would be created every month
CB2111_67_2 cli% createsched "createsv -f abcd.@y@@m@@d@@H@@M@@S@ dcv-qju26LsnTtyIhszkBH6a6w" "@monthly" sched_monthly
CB2111_67_2 cli%
CB2111_67_2 cli% showsched
                                                                             ---------- Schedule -----------
SchedName     File/Command                                                   Min Hour     DOM    Month   DOW CreatedBy Status Alert NextRunTime
sched_monthly createsv -f abcd.@y@@m@@d@@H@@M@@S@ dcv-qju26LsnTtyIhszkBH6a6w   0    0       1        *     * 3paradm   active     Y 2018-09-01 00:00:00 IST

Apart from @monthly, following shortcuts are available: @hourly, @daily, @weekly, @yearly

These shortcuts are not supported in docker command:
[docker@CSSOSBE02-B10 ~]$ docker volume create -d hpe --name snap_monthly -o virtualCopyOf=vol_aug -o scheduleFrequency="@monthly" -o snapshotPrefix=ppp -o scheduleName=sched_monthly
Error response from daemon: create snap_monthly: Invalid schedule string is passed: HPE Docker Volume plugin Create volume failed: create schedule failed, error is: Improper string passed.
[docker@CSSOSBE02-B10 ~]$

Documents needs to be updated in case we are not supporting such shortcuts which 3PAR does.

**Comment by nilangekarss** [comment]
@sonawane-shashikant @wdurairaj @wdurairaj 
This is done as per the design documentation doc discussed initially if this needs to be supported it has to be marked as an enhancement/ good to have an option.
Along with this design doc, create_help doc needs to be changed.

**Comment by wdurairaj** [comment]
As per the design only crontab format is supported.. Hence removed the "bug" tag and marked it as an "enhancement"

**Comment by nilangekarss** [comment]
@hpe-storage do we need to take this enhancement in this sprint?
@wdurairaj @sonawane-shashikant is "@" special character allowed in storage class?

**Comment by wdurairaj** [comment]
@ is a not a valid character in StorageClass, request Shashi to close this issue.

**Comment by sonawane-shashikant** [comment]
Looking at the kubernetes limitation regarding "@", this issue can be closed.
