### ISSUE TITLE
Snapshot Schedule: No error if "-o scheduleName" is omitted while creating a schedule

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#271]
While creating snapshot schedule, if scheduleName is omitted, error is NOT observed.
Please find attached screenshot of terminal.

In the below example virtual copy creates but schedule does not - 

[docker@CSSOSBE02-B10 ~]$ docker volume create -d hpe --name TEST-SNAP -o virtualCopyOf=TEST-VOL -o scheduleFrequency="25 * * * *" -o snapshotPrefix=ABCDEFGH
TEST-SNAP
[docker@CSSOSBE02-B10 ~]$
[docker@CSSOSBE02-B10 ~]$ docker volume inspect TEST-SNAP
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/3ab360d82193d43929cff81314ca12033766e516c7d4653edbf61d9869627c27/rootfs",
        "Name": "TEST-SNAP",
        "Options": {
            "scheduleFrequency": "25 * * * *",
            "snapshotPrefix": "ABCDEFGH",
            "virtualCopyOf": "TEST-VOL"
        },
        "Scope": "global",
        "Status": {
            "snap_detail": {
                "compression": null,
                "expiration_hours": null,
                "fsMode": null,
                "fsOwner": null,
                "is_snap": true,
                "mountConflictDelay": 30,
                "parent_id": "9001d762-56ea-4ad2-876b-5aa804a4b312",
                "parent_volume": "TEST-VOL",
                "provisioning": "thin",
                "retention_hours": null,
                "size": 29,
                "snap_cpg": "SHASHI"
            }
        }
    }
]
[docker@CSSOSBE02-B10 ~]$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          TEST-SNAP
hpe:latest          TEST-VOL

CB2111_67_2 cli% showvv -cpg SHASHI -showcols Name,Comment
Name                        Comment                                                                                                                                              
dcv-kAHXYlbqStKHa1qoBKSzEg  {"volume_id": "9001d762-56ea-4ad2-876b-5aa804a4b312", "name": "9001d762-56ea-4ad2-876b-5aa804a4b312", "type": "Docker", "display_name": "TEST-VOL"}  
 dcs-jjKQXsHrTrqR1jCBEdTj1w {"volume_name": "TEST-VOL", "volume_id": "9001d762-56ea-4ad2-876b-5aa804a4b312", "display_name": "TEST-SNAP", "description": "snapshot of volume TEST-VOL"}  

CB2111_67_2 cli% showsched
                                                                            ---------- Schedule -----------
SchedName    File/Command                                                   Min Hour     DOM    Month   DOW CreatedBy Status Alert NextRunTime
# Entry is not added here

**Comment by nilangekarss** [comment]
Hi Shashi,
Do u see snapshot is getting created if user does not specify scheduleName?

Or do u see any problem when u try to remove this snapshot?

**Comment by nilangekarss** [comment]
scheduleName is a mandatory parameter to create a snapshotschedule.
If this is not passed normal snapshot will be created and other parameters are ignored.
If you try to see the status field these parameters will not be seen.

**Comment by nilangekarss** [comment]
@sonawane-shashikant 
If scheduleName is not given in options and other schedule related parameters are passed, it simply creates a snapshot and other parameters are ignored.
But, if few parameters related to schedule creation are passed and virtualCopyOf is not passed in options, we should not allow user to create volume. This will throw an error.
This is as per implementation.

**Comment by nilangekarss** [comment]
@hpe-storage will work on this bug today

**Comment by sandesh-desai** [comment]
Verified and working as per expectation.
Attaching the log.
[Docker output result.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2449711/Docker.output.result.txt)

**Comment by sonawane-shashikant** [comment]
Closing as per above comment.
