### ISSUE TITLE
Functional testcases failing with mount status & snapshot creation error

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#273]
Docker plugin's Functional testcases on CentOS environment failing while unmounting & Snapshot creation.

Please find below common log for the same.

=======
Error logs
=======
hpe_3par_manager.py:310: in hpe_inspect_container_volume_mount
self.assertEqual(mount_status, True)
AssertionError: False != True

hpe_3par_manager.py:137: in hpe_create_snapshot
self.assertIn(snapshot_creation, volumes['Volumes'])
AssertionError: {'CreatedAt': '0001-01-01T00:00:00Z', 'Driver': 'dockerciuser/hpedockerplugin:test', 'Labels': None, 'Mountpoint': '', 'Name': 'docker_dc2389f1', 'Options': {'virtualCopyOf': 'docker_b92d06c2'}, 'Scope': 'global'} not found in [{'CreatedAt': '2018-08-20T22:01:54+05:30', 'Driver': 'local', 'Labels': None, 'Mountpoint': '/var/lib/docker/volumes/beeebe123272270ae7cc5917f2243c3744354e6aaac73e7aa75a037f9cdf347f/_data', 'Name': 'beeebe123272270ae7cc5917f2243c3744354e6aaac73e7aa75a037f9cdf347f', 'Options': None, 'Scope': 'local'}

CI job URL :- http://16.184.15.6:8080/job/docker-3par-iscsi-plugin-centos/156/consoleFull

**Comment by sonivi** [comment]
Mount entry of container are seen :
**Centos**:
/var/lib/docker/plugins/346cbbab060e7f38d3713165d8fa3f9f7459a73aaa336bb88949fe8081d813b8/propagated-mount/**hpedocker-dm-uuid-mpath**-360002ac00000000000019e470001c00a

**Ubuntu**:
/var/lib/docker/plugins/b86f4c97493fe47d7ffad5e98630f4ed15446a1dcdcc51dd3ce7826fa22575bb/rootfs/opt/hpe/data/**hpedocker-scsi**-360002ac0000000000001d2750001c00a

so for now let keep it generic for matching "hpedocker-"

**Comment by wdurairaj** [comment]
@soniv
is this the cause of the 7 failures on the CI job ? If yes, please propose a new change on the test automation to handle the pattern generically.

**Comment by sonivi** [comment]
yes, this cause 7 failures.

for now i am raising PR which will match generic pattern. In future, we can list down the iscsi & fc on all combination of platform and create a strict regex pattern

**Comment by prablr79** [comment]
@virendra-sharma its already fixed can you check this ?

**Comment by virendra-sharma** [comment]
I have run CI on ubuntu & CentOS slave with merged code. mount status error is passing now, hence closing this issue.
