### ISSUE TITLE
Multi-Array support negative testing:Docker plugin enable fail after changing array settings in hpe.conf 

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#274]
Docker plugin enable fail after changing backend 3par array settings in hpe.conf 

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker Version:  17.06.2-ee-16
3PAR array: 192.168.67.7 [DEFAULT]  192.168.67.5 [3par1] and 192.168.67.2 [3par2]

Steps as follows:
1) In Hpe.conf settings add 2 arrays 192.168.67.5 as [3par1.1] with 192.168.67.7 as [DEFAULT]
2) Docker plugin disable and then enable successfully.
3) Create a volume successfully.
3) Change Hpe.conf settings 192.168.67.5 as [1.1],192.168.67.2[1.2] with 192.168.67.7 [DEFAULT]
4) Docker plugin disable successfully.
5) Docker plugin enable failed with the error as below:

root@ubuntu:~# docker plugin enable hpe
Error response from daemon: dial unix /run/docker/plugins/e6415794402caa4deb2833474fe449deed33d2a3e8dee83a74d1af12b36f1dc7/hpe.sock: connect: no such file or directory

[hpe.conf settings.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2326878/hpe.conf.settings.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2326879/Syslog.txt)

**Comment by hpe-storage** [comment]
Can you attach the log as well ?

**Comment by sandesh-desai** [comment]
Attaching log.

[hpe.conf settings.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2327113/hpe.conf.settings.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2327114/Syslog.txt)

**Comment by imran-ansari** [comment]
I'm able to enable plugin after making changes to the configuration file.

The logs attached show an error that has to do with incorrect CPG:
```sh
Aug 28 01:40:53 ubuntu dockerd[3341]: time="2018-08-28T01:40:53-04:00" level=info msg="2018-08-28 01:40:53.703 19 ERROR hpe_storage_api hpe3parclient.exceptions.HTTPNotFound: Not found (HTTP 404) 15 - CPG does not exist" 
```
Please try this out again.

**Comment by sandesh-desai** [comment]
Verified and working fine as expected closing the bug.
Please find the attached file for output.
[hpe.conf.settings.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2463792/hpe.conf.settings.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2463793/Syslog.txt)
