### ISSUE TITLE
MultiCPG/Multiarray: The clone of the volume created using cpg and backend  option is not deleted from 3PAR

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#278]
Below are the steps followed - 
1. Created the volume in docker  - 
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume create --name=new_vol04 -d hpe -o backend=3par1 -o cpg=multi_cpg
new_vol04
2.  Created the clone of the volume - 
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume create --name=new_vol04_snap -d hpe -o backend=3par1 -o cloneOf=new_vol04
new_vol04_snap
3. Both the volume and its clone is present in 3par 
CSSOS-SSA05 cli% showvv -cpg multi_cpg -hist
  Id Name                       Prov Compr Dedup Type -----CreationTime------ -RetentionEndTime- -ExpirationTime- -SpaceCalcTime- -EfficiencyUpdateTime- -UnrefSpaceFreedTime- ----------------------------------------------------------------------Comment-----------------------------------------------------------------------
6085 dcv-KhPn65yKRmKVEci-7XIQGg tpvv No    No    base 2018-08-28 20:17:05 IST --                 --               --              --                     --                    --         
6082 dcv-lZFZKNGLRRmIMpRwTqdKmA tpvv No    No    base 2018-08-28 20:16:18 IST --                 --               --              --                     --                    {"volume_id": "95915928-d18b-4519-8832-94704ea74a98", "name": "95915928-d18b-4519-8832-94704ea74a98", "type": "Docker", "display_name": "new_vol04"}
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   2 total                                                                                                                                                                                
CSSOS-SSA05 cli%

4. Tried to remove both from docker as (Deleted successfully)- 
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume rm new_vol04_snap new_vol04
new_vol04_snap
docker volume lsnew_vol04
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration# docker volume ls
DRIVER              VOLUME NAME
root@cssosbe03-b04:/home/stack/python-hpedockerplugin/tests/integration#
 
5. Checked the volumes in 3par -
CSSOS-SSA05 cli% showvv -cpg multi_cpg -hist
  Id Name                       Prov Compr Dedup Type -----CreationTime------ -RetentionEndTime- -ExpirationTime- -SpaceCalcTime- -EfficiencyUpdateTime- -UnrefSpaceFreedTime- -Comment-
6085 dcv-KhPn65yKRmKVEci-7XIQGg tpvv No    No    base 2018-08-28 20:17:05 IST --                 --               --              --                     --                    --
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
   1 total
CSSOS-SSA05 cli%

Still I can see the clone is not deleted from 3par.

**Comment by sandesh-desai** [comment]
Verified and working fine as expected closing the bug.
Please find the attached file for output.
[BUG 278.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2369257/BUG.278.txt)

**Comment by dockerciuser** [comment]
Verified & Closing the bug...
