### ISSUE TITLE
Docker 3.0 : -o replicationGroup parameter accepted twice

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#282]
User can create RCG by passing -o replicationGroup twice

Expected Results - 
-o replicationGroup should be restricted with below error - 
Error response from daemon: create clone-volume: ['virtualCopyOf', 'cloneOf', 'qos-name', 'replicationGroup'] cannot be specified at the same time

root@cssosbe03-b14 : ~ # docker volume create -d hpe --name=clone-volume -o size=200 -o replicationGroup=sandesh -o virtualCopyOf=volume
Error response from daemon: create clone-volume: ['virtualCopyOf', 'cloneOf', 'qos-name', 'replicationGroup'] cannot be specified at the same time

root@cssosbe03-b14 : ~ # docker volume create -d hpe --name=clone-volume -o size=200 -o replicationGroup=sandesh -o replicationGroup=shashi
clone-volume
root@cssosbe03-b14 : ~ # docker volume ls
DRIVER              VOLUME NAME
hpe:latest          clone-volume
hpe:latest          volume
root@cssosbe03-b14 : ~ # docker volume inspect clone-volume
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/832165925c676d56f9a87120663d80a614d066050bc4cc5ffa6c0375fe23b604/rootfs",
        "Name": "clone-volume",
        "Options": {
            "replicationGroup": "shashi",
            "size": "200"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "compression": null,
                "cpg": "SHASHI-PRIM",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "thin",
                "size": 200,
                "snap_cpg": "SHASHI-PRIM-SNAP"
            }
        }
    }
]
root@cssosbe03-b14 : ~ #

PRIMARY
CSSOS-SSA04 cli % showvv -cpg SHASHI-PRIM -showcols Name,Comment
Name                       Comment
dcv-hrgxcItKTpSbY7bvrolnAw {"volume_id": "86b83170-8b4a-4e94-9b63-b6efae896703", "name": "86b83170-8b4a-4e94-9b63-b6efae896703", "type": "Docker", "display_name": "volume"}
dcv-p4d5s917TWarrZWYu.8cEw {"volume_id": "a78779b3-dd7b-4d66-abad-9598bbef1c13", "name": "a78779b3-dd7b-4d66-abad-9598bbef1c13", "type": "Docker", "display_name": "clone-volume"}

CSSOS-SSA04 cli % showrcopy groups shashi*

Remote Copy System Information
Status: Started, Normal

Group Information

Name         Target      Status   Role       Mode     Options
shashi       CSSOS-SSA05 Started  Primary    Sync     auto_recover,auto_failover,path_management
  LocalVV                    ID   RemoteVV                   ID   SyncStatus    LastSyncTime
  dcv-p4d5s917TWarrZWYu.8cEw 4410 dcv-p4d5s917TWarrZWYu.8cEw 6057 Synced        NA

Name         Target      Status   Role       Mode     Options
shashi-rcg   CSSOS-SSA05 Started  Primary    Sync     auto_recover,auto_failover,path_management
  LocalVV                    ID   RemoteVV                   ID   SyncStatus    LastSyncTime
  dcv-hrgxcItKTpSbY7bvrolnAw 4321 dcv-hrgxcItKTpSbY7bvrolnAw 6028 Synced        NA

CSSOS-SSA04 cli % showvv -cpg SHASHI-PRIM
                                                                                      -Rsvd(MiB)- -(MiB)-
  Id Name                       Prov Compr Dedup Type CopyOf BsId Rd -Detailed_State-   Snp   Usr   VSize
4321 dcv-hrgxcItKTpSbY7bvrolnAw tpvv No    No    base ---    4321 RW normal             512  8192  102400
4410 dcv-p4d5s917TWarrZWYu.8cEw tpvv No    No    base ---    4410 RW normal             512   512  204800
---------------------------------------------------------------------------------------------------------
   2 total                                                                             1024  8704  307200
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
total

SECONDARY

CSSOS-SSA05 cli % showvv -cpg SHASHI-SEC -showcols Name,Comment
Name                       Comment
dcv-hrgxcItKTpSbY7bvrolnAw --
dcv-p4d5s917TWarrZWYu.8cEw --
----------------------------------
total
CSSOS-SSA05 cli %

**Comment by sonawane-shashikant** [comment]
Same is the case with -o retentionHours parameter

root@cssosbe03-b14  : ~# docker volume create -d hpe --name=retVol -o size=200 -o replicationGroup=sandesh -o retentionHours=xxx
retVol

root@cssosbe03-b14 : ~# docker volume inspect retVol
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/832165925c676d56f9a87120663d80a614d066050bc4cc5ffa6c0375fe23b604/rootfs",
        "Name": "retVol",
        "Options": {
            "replicationGroup": "sandesh",
            "retentionHours": "xxx",
            "size": "200"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "compression": null,
                "cpg": "SHASHI-PRIM",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "thin",
                "size": 200,
                "snap_cpg": "SHASHI-PRIM-SNAP"
            }
        }
    }
]
root@cssosbe03-b14 : ~ #

**Comment by imran-ansari** [comment]
@sonawane-shashikant - As discussed, this is a general defect and not specific to replication. 
E.g. the below commands will work:
docker volume create -d hpe -o help -o help
docker volume create -d hpe --name SNP1 -o virtualCopyOf=VOL1 -o virtualCopyOf=VOL2

Please update the title to sound more general :)

**Comment by sandesh-desai** [comment]
While performing Multi-array testing with the below command it also create a volume instead of restricting to create a volume :
docker volume create -d hpe --name=Testvol3 -o backend=3par2 -o backend=1.1
Volume Testvol3 created in backend 1.1

**Comment by imran-ansari** [comment]
This is an issue with Docker itself as plugin receives only the last value of the option that was specified multiple times (1.1 in the case above). Either Docker CLI must handle this or it should pass the duplicate options to the plugin.

**Comment by wdurairaj** [comment]
Already captured as a docker bug.. hence we will not fix it.

**Comment by sonawane-shashikant** [comment]
Closing as per above comment.
