### ISSUE TITLE
Multi-Array support negative testing:Docker volume inspect missing backend option for manage volume.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#283]
Docker volume inspect missing backend option for manage volume.

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker Version: 17.06.2-ee-16
3PAR array: 192.168.67.5 [DEFAULT] 192.168.67.5 [3par2]

Steps as follows:

1) In Hpe.conf  add 2 arrays settings as 192.168.67.5 as [DEFAULT] -- and 192.168.67.5 as [3par2]
2) Keep both array settings same except CPG
3) Docker plugin disable and then enable successfully.
4) Create a volume on DEFAULT as well as 3par2 array successfully.
5) Create a volume on backend 3par2 array.
    CSSOS-SSA05 cli% createvv SD_1 Testvol 200g
6) Manage the backend volume from docker
    docker volume create -d hpe --name=importvol  -o importVol=Testvol
7) Volume manage successfully.
8) Inspect the volume importvol
volume inspect missing backend option for manage volume.
root@ubuntu:~# docker volume inspect importvol
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/9b336a46d71959887c3a85af8b4f0eb1a555b5ff28d2edc5e278df990914ce48/rootfs",
        "Name": "importvol",
        "Options": {
            "importVol": "Testvol"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "compression": null,
                "cpg": "SD_1",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "full",
                "size": 200,
                "snap_cpg": "SD_1"
            }
        }
    }
]

Attaching the syslog and Hpe.conf logs.
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2330880/hpe.conf.txt)
[Syslog .txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2330881/Syslog.txt)

**Comment by imran-ansari** [comment]
@Tester - Please clarify if the ask here is to show backend as part of "Status" or as part of "Options".
@Dev - while importing a volume using the user supplied backend or default backend, please ensure that the domain of the imported volume is same as that of any other volume created by this backend.

**Comment by wdurairaj** [comment]
if you are importing a volume from '3par2' use this command and verify if the 'backend' field is populated

`docker volume create -d hpe --name=importvol -o importVol=Testvol  -o backend=3par2`

now do a `docker volume inspect importvol`

**Comment by wdurairaj** [comment]
remember -o importVol= with -o backend= means the backend is DEFAULT, absense of the backend in the inspect the code assumes, the backend is DEFAULT.

**Comment by wdurairaj** [comment]
Request test team to verify , it is part of the nightly build now.

**Comment by sandesh-desai** [comment]
Verified and Closed.
Attaching docker output.
[docker output.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/2440662/docker.output.docx)
