### ISSUE TITLE
Multi-Array support negative testing:Docker volume inspect missing backend [3par2]option for snapshot and snapshot scheduled volume.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#284]
Docker volume inspect missing backend [3par2]option for snapshot and snapshot scheduled volume.

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker Version: 17.06.2-ee-16
3PAR array: 192.168.67.7 [DEFAULT] 192.168.67.5 [3par2]

Steps as follows:

1) In Hpe.conf add 2 arrays settings as 192.168.67.7 as [DEFAULT] -- and 192.168.67.5 as [3par2]
2) Docker plugin disable and then enable successfully.
3) Create a volume on 3par2 array.
    docker volume create --name=volume -d hpe -o backend=3par2
4) Create a snapshot on 3par2 array.
     docker volume create -d hpe --name=snapshot -o virtualCopyOf=volume
5)  Run a Snapshot scheduling for volume.
    docker volume create -d hpe --name=snap_aug -o virtualCopyOf=volume -o scheduleFrequency="10 * * * *" -o snapshotPrefix=abc -o scheduleName=sched_aug
6)  Inspect a volume snap_aug
     docker volume inspect snap_aug

volume inspect snap_aug missing backend option.

docker volume inspect snap_aug
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/9b336a46d71959887c3a85af8b4f0eb1a555b5ff28d2edc5e278df990914ce48/rootfs",
        "Name": "snap_aug",
        "Options": {
            "scheduleFrequency": "10 * * * *",
            "scheduleName": "sched_aug",
            "snapshotPrefix": "abc",
            "virtualCopyOf": "volume"
        },
        "Scope": "global",
        "Status": {
            "snap_detail": {
                "compression": null,
                "expiration_hours": null,
                "fsMode": null,
                "fsOwner": null,
                "is_snap": true,
                "mountConflictDelay": 30,
                "parent_id": "8f26e5ec-e220-4e38-b691-a58c7e5562ac",
                "parent_volume": "volume",
                "provisioning": "thin",
                "retention_hours": null,
                "size": 100,
                "snap_cpg": "SD_1",
                "snap_schedule": {
                    "sched_frequency": "10 * * * *",
                    "sched_snap_exp_hrs": null,
                    "sched_snap_ret_hrs": null,
                    "schedule_name": "sched_aug",
                    "snap_name_prefix": "abc"

Attaching the log files.
[3par2 array output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2331654/3par2.array.output.txt)
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2331657/Docker.output.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2331658/Syslog.txt)

**Comment by imran-ansari** [comment]
Hi @sandesh-desai , In step 4, since "-o backend=xxx" has not been specified, it won't be displayed in the inspect command.
Step 4 in fact should fail as part of validation as the source volume was created using "3par2" backend whereas its snapshot in step 4 is being created using "DEFAULT" backend. Anyone else has any different opinion?

**Comment by wdurairaj** [comment]
Request test team to verify , it is part of the nightly build now.

**Comment by sandesh-desai** [comment]
Verified and Closed.
Attaching docker output.
[3PAR data.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2441474/3PAR.data.txt)
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2441475/Docker.output.txt)
