### ISSUE TITLE
[File Permission] : fsMode, fsOwner is not displayed on help text

### ISSUE THREAD

**Issue by wdurairaj** [hpe-storage/python-hpedockerplugin#288]
`docker volume create -d hpe -o help`  will not display help text for -o fsMode, -o fsOwner since this file does'nt contain reference of it

https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/config/create_help.txt

However, these options are present in https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/hpedockerplugin/hpe_storage_api.py#L163

**Comment by atotala** [comment]
Please close the bug
