### ISSUE TITLE
Can't create volume using size attribute with Mesos/Marthon UI

### ISSUE THREAD

**Issue by garthmbooth** [hpe-storage/python-hpedockerplugin#29]
When I add the size parameter to dvdi options I get a marathon error:
There was a problem with your configuration
general: must be undefined for Docker containers

I am able to create a volume of specific size with dvdcli:
dvdcli create --volumedriver=hpe --volumename=testvol10 --volumeopts=size=5

This appears to be a potential issue with the Mesosphere/Marthon UI, but I'm opening here so that we can track and resolve appropriately.

**Comment by hpe-storage** [comment]
This is not a bug on the hpe docker volume plugin, but on Mesosphere.
