### ISSUE TITLE
Enhancement: Move quorum_witness_ip under replication_device configuration

### ISSUE THREAD

**Issue by imran-ansari** [hpe-storage/python-hpedockerplugin#290]
As of now, quorum_witness_ip is present at the same level as replication_device. However, it makes sense only if replication_device is defined. Hence, it should be moved under replication_device.

**Comment by imran-ansari** [comment]
Done! Pushed as part of pull request https://github.com/hpe-storage/python-hpedockerplugin/pull/286

**Comment by sonawane-shashikant** [comment]
Verified as FIXED.


[quorum-witness-verification-terminal.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2352233/quorum-witness-verification-terminal.txt)

[hpe (3).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2352237/hpe.3.txt)
