### ISSUE TITLE
Replication: Incorrect error message with -o cpg and -o backend option is used

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#292]
While creating remote copy group, if we use -o cpg or -o backend option, we see incorrect message.

root@cssosbe03-b14 : ~ # docker volume create -d hpe --name=third-volume -o size=100 -o cpg=SHASHI-PRIM
Error response from daemon: create third-volume: Invalid input received: %(reason)s
root@cssosbe03-b14 : ~ # sudo vi /etc/hpedockerplugin/hpe.conf
root@cssosbe03-b14 : ~ # docker volume create -d hpe --name=third-volume -o size=100 -o backend=3PAR
Error response from daemon: create third-volume: Invalid input received: %(reason)s

Expected results - Instead of "%(reason)s", appropriate message should be displayed.

**Comment by imran-ansari** [comment]
The create volume commands mentioned in the issue description above do not have "replicationGroup" parameter specified - a parameter that is MUST to make a command a replication command. 
Please clarify the reason why this issue should be treated as a replication issue along with relevant logs.

**Comment by imran-ansari** [comment]
In case you have configured replication in the hpe.conf and this is just a negative test case of not specifying "replicationGroup" parameter on the command line, then I would suggest validating this against the latest plugin and update the results.

**Comment by sandesh-desai** [comment]
Verified and working fine as expected closing the bug.
Please find the attached file for output.
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2414821/Docker.output.txt)

**Comment by sonawane-shashikant** [comment]
Closing as per above comment
