### ISSUE TITLE
Multi-Array support: Not able to create a volume by using multi-cpg option.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#293]
Not able to create a volume by using multi-cpg option.

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker Version: 17.06.2-ee-16
3PAR array: 192.168.67.7 [DEFAULT] 192.168.67.5 [3par2] 

1) Create a CPG SD_1 in 3par2
2) Move the CPG in domain as SUPER
3) Create another CPG SUPER in 3par2
4) Create a volume by using below commad:
    docker volume create -d hpe --name=VOL1 -o size=200 -o cpg=SUPER  -o backend=3par2
It Gives an error below:
"root@ubuntu:~# docker volume create -d hpe --name=VOL1 -o size=200 -o cpg=SUPER  -o backend=3par2
Error response from daemon: create VOL1: Invalid input received: Error: User CPG is in domain -,but snp CPG is in domain SUPER"

Attaching syslog and hpe.conf files.
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2334736/Syslog.txt)
[Hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2334745/Hpe.conf.txt)

**Comment by nilangekarss** [comment]
Hi Sandesh,
For creating a volume user and snapcpg should be in same domain.

You can try creating a volume on 3PAR directly having user cpg in domain1 and snapcpg in domain2.

I feel you will get an error.

Multi cpg support for a volume is for the different CPG which belong to same domain.

Thanks and Regards,
Swapnil

**Comment by sandesh-desai** [comment]
Verified and working fine as expected closing the bug.
Please find the attached file for output.

[docker and 3par output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2351945/docker.and.3par.output.txt)

[hpe.conf settings.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2351952/hpe.conf.settings.txt)
