### ISSUE TITLE
Replication: Error on volume creation on switched over RCG but volume creates on 3PAR

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#295]
Summary: Error on volume creation on switched over RCG but volume creates on 3PAR
Pre-requisite: Replicated arrays with quorum witness.
Testbed -
 docker@cld6b10 : ~ $ docker version
 Client: Docker Enterprise Edition (EE) 2.0
 Version: 17.06.2-ee-16
 API version: 1.30
 Go version: go1.8.7
 Git commit: 9ef4f0a
 Built: Thu Jul 26 16:41:28 2018
 OS/Arch: linux/amd64
 Server: Docker Enterprise Edition (EE) 2.0
 Engine:
 Version: 17.06.2-ee-16
 API version: 1.30 (minimum version 1.12)
 Go version: go1.8.7
 Git commit: 9ef4f0a
 Built: Thu Jul 26 16:40:18 2018
 OS/Arch: linux/amd64
 Experimental: false
 docker@cld6b10 : ~ $ lsb_release -a
 No LSB modules are available.
 Distributor ID: Ubuntu
 Description: Ubuntu 16.04.5 LTS
 Release: 16.04
 Codename: xenial

root@cssosbe03-b14 : ~ # docker plugin inspect hpe | grep PluginRef
        "PluginReference" :   "docker.io/dockerciuser/hpedockerplugin:test",
root@cssosbe03-b14:~# date
Thu Aug 30 16:14:54 IST 2018
root@cssosbe03-b14:~#

Steps Followed - 
1. create volume with -o replicationGroup parameter
2. RCG is created on 3PAR
3. SwitchOver RCG
4. Try to create new volume using docker command again and verify the error.
5. Below error displays and docker volume does not create.
6. Verify the volume on 3PAR. Volume is creates on 3PAR

Expected Results - In case of error, volume shouldn't be created on 3PAR as well

Please see the below output - 

root@cssosbe03-b14:/home/stack# docker volume create -d hpe --name=fourth-volume -o size=250 -o replicationGroup=shashi
Error response from daemon: create fourth-volume: Bad or unexpected response from the storage volume backend API: Error occurred while adding volume 'dcv-.Hf1V6fLRX.3B1XlPx5Rcw' to the remote copy group 'shashi': Forbidden (HTTP 403) 215 - remote copy group has already been started

CSSOS-SSA04 cli% showvv -cpg SHASHI-PRIM -showcols Name,Comment
Name                       Comment
dcv-.Hf1V6fLRX.3B1XlPx5Rcw {"volume_id": "f877f557-a7cb-457f-b707-55e53f1e5173", "name": "f877f557-a7cb-457f-b707-55e53f1e5173", "type": "Docker", "display_name": "fourth-volume"}

**Comment by imran-ansari** [comment]
@sonawane-shashikant - In this scenario, rollback mechanism should have cleaned up the created volume when a failure occurred while adding it to RCG. Could you please attach the logs?

**Comment by sonawane-shashikant** [comment]
Attaching required logs

[CreateVolumeObSwitchedOverRCG.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2365196/CreateVolumeObSwitchedOverRCG.txt)

**Comment by imran-ansari** [comment]
Fixed in pull request https://github.com/hpe-storage/python-hpedockerplugin/pull/325

**Comment by sonawane-shashikant** [comment]
This bug is VERIFIED as FIXED..

setrcopygroup for failover shashi-rcg01.r121649
failover started with tasks: 2572
CSSOS-SSA05 cli% showtask -d 2572
  Id Type                 Name                 Status Phase Step -------StartTime------- ------FinishTime------- -Priority- -User--
2572 remote_copy_failover shashi-rcg01.r121649 done     ---  --- 2018-09-14 12:16:38 IST 2018-09-14 12:16:38 IST n/a        3paradm

Detailed status:
2018-09-14 12:16:38 IST Created     task.
2018-09-14 12:16:38 IST Begin       Failover operation on group shashi-rcg01.r121649 started.
2018-09-14 12:16:38 IST Switched    Group shashi-rcg01.r121649 was switched from secondary to primary.
2018-09-14 12:16:38 IST Completed   Group shashi-rcg01.r121649 failover completed.
CSSOS-SSA05 cli% showrcopy groups

Remote Copy System Information
Status: Started, Normal

Group Information

Name                 Target      Status   Role        Mode     Options
shashi-rcg01.r121649 CSSOS-SSA04 Stopped  Primary-Rev Sync
  LocalVV                     ID   RemoteVV                   ID   SyncStatus    LastSyncTime
  dcv-hA0sW.RITxO52sfHr2Qkmg 32200 dcv-hA0sW.RITxO52sfHr2Qkmg 7330 Stopped       2018-09-14 12:16:24 IST
  dcv-qwhC8HifTDClAhvrOxMY0Q 32201 dcv-qwhC8HifTDClAhvrOxMY0Q 7331 Stopped       2018-09-14 12:16:24 IST


root@cssosbe03-b14 : ~ # docker volume create -d hpe --name shashivolume-03 -o replicationGroup=shashi-rcg01
Error response from daemon: create shashivolume-03: Bad or unexpected response from the storage volume backend API: Error occurred while adding volume 'dcv-y2L0DBYjRlKOUdOsKH4xLA' to the remote copy group 'shashi-rcg01': Forbidden (HTTP 403) 255 -  Remote copy group in failover state, both systems are in primary state
root@cssosbe03-b14:~#


CSSOS-SSA04 cli% showvv -cpg SHASHI-PRIM -showcols Name,Comment
Name                       Comment
dcv-0ThgzceZRUChD.jX54uS2A {"volume_id": "d13860cd-c799-4540-a10f-e8d7e78b92d8", "name": "d13860cd-c799-4540-a10f-e8d7e78b92d8", "type": "Docker", "display_name": "earth_vol"}
dcv-hA0sW.RITxO52sfHr2Qkmg {"volume_id": "840d2c5b-e448-4f13-b9da-c7c7af64249a", "name": "840d2c5b-e448-4f13-b9da-c7c7af64249a", "type": "Docker", "display_name": "shashivolume-01"}
dcv-qwhC8HifTDClAhvrOxMY0Q {"volume_id": "ab0842f0-789f-4c30-a502-1beb3b1318d1", "name": "ab0842f0-789f-4c30-a502-1beb3b1318d1", "type": "Docker", "display_name": "shashivolume-02"}
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
total
CSSOS-SSA04 cli%



CSSOS-SSA04 cli% showvv -cpg SHASHI-PRIM-SNAP -showcols Name,Comment
Name                       Comment
dcv-0ThgzceZRUChD.jX54uS2A {"volume_id": "d13860cd-c799-4540-a10f-e8d7e78b92d8", "name": "d13860cd-c799-4540-a10f-e8d7e78b92d8", "type": "Docker", "display_name": "earth_vol"}
dcv-hA0sW.RITxO52sfHr2Qkmg {"volume_id": "840d2c5b-e448-4f13-b9da-c7c7af64249a", "name": "840d2c5b-e448-4f13-b9da-c7c7af64249a", "type": "Docker", "display_name": "shashivolume-01"}
 rcpy.204.7330.2           Remote Copy snapshot created for target 'CSSOS-SSA05' of group 'shashi-rcg01'.
dcv-qwhC8HifTDClAhvrOxMY0Q {"volume_id": "ab0842f0-789f-4c30-a502-1beb3b1318d1", "name": "ab0842f0-789f-4c30-a502-1beb3b1318d1", "type": "Docker", "display_name": "shashivolume-02"}
 rcpy.204.7331.2           Remote Copy snapshot created for target 'CSSOS-SSA05' of group 'shashi-rcg01'.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
total
CSSOS-SSA04 cli%

CSSOS-SSA05 cli% showvv -cpg SHASHI-SEC
                                                                                        -Rsvd(MiB)- -(MiB)-
   Id Name                       Prov Compr Dedup Type CopyOf  BsId Rd -Detailed_State-  Snp    Usr   VSize
31047 dcv-0ThgzceZRUChD.jX54uS2A tpvv No    No    base ---    31047 RW normal           1024   1024   10240
32200 dcv-hA0sW.RITxO52sfHr2Qkmg tpvv No    No    base ---    32200 RW normal            512   8704  102400
32201 dcv-qwhC8HifTDClAhvrOxMY0Q tpvv No    No    base ---    32201 RW normal            512    512  102400
-----------------------------------------------------------------------------------------------------------
    3 total                                                                             2048  10240  215040
CSSOS-SSA05 cli% showvv -cpg SHASHI-SEC-SNAP
                                                                                                             -Rsvd(MiB)- -(MiB)-
   Id Name                       Prov Compr Dedup Type  CopyOf                      BsId Rd -Detailed_State-  Snp    Usr   VSize
31047 dcv-0ThgzceZRUChD.jX54uS2A tpvv No    No    base  ---                        31047 RW normal           1024   1024   10240
32200 dcv-hA0sW.RITxO52sfHr2Qkmg tpvv No    No    base  ---                        32200 RW normal            512   8704  102400
32203  rcpy.204.32200.2          snp  NA    NA    vcopy dcv-hA0sW.RITxO52sfHr2Qkmg 32200 RO normal             --     --  102400
32201 dcv-qwhC8HifTDClAhvrOxMY0Q tpvv No    No    base  ---                        32201 RW normal            512    512  102400
32204  rcpy.204.32201.2          snp  NA    NA    vcopy dcv-qwhC8HifTDClAhvrOxMY0Q 32201 RO normal             --     --  102400
--------------------------------------------------------------------------------------------------------------------------------
    5 total                                                                                                  2048  10240  419840
CSSOS-SSA05 cli%
