### ISSUE TITLE
Multi-Array Support:Not able to import a volume from backend 3par2 array with -o cpg option.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#298]
Not able to import a volume from backend 3par2 array with -o cpg option.

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker version: Version:17.06.2-ee-16
3PAR array: 15.212.192.252 [DEFAULT] and 192.168.67.5 [3par2]

Steps as follows:

Create volume on [3par2] manually by using 3PAR command :
createvv SD_1 Test 10g
Import volume Test by using the below command:

docker volume create -d hpe --name=Test_import -o cpg=SD_1 -o backend=3par2 -o importVol=Test

It gives the same error below:
Error response from daemon: create Test_import: ['backend', 'cpg', 'importVol'] cannot be  specified at the same time

Attaching a Syslog and h
[Hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2339263/Hpe.conf.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2339264/Syslog.txt)

pe.conf settings.
Syslog.txt
hpe.conf.txt

**Comment by sonivi** [comment]
This is not supported yet. only '-o backend' is valid option with '-o importVol'

same as #264. so please close this
Thanks

**Comment by sandesh-desai** [comment]
As per above comment only '-o backend' is valid option with '-o importVol' hence closing this bug.
