### ISSUE TITLE
Multi-Array Support: Not able to mount a volume from backend 3par array.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#299]
Not able to mount a volume from backend 3par array.

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker Version: 17.06.2-ee-16
3PAR array: 15.212.192.252 [DEFAULT] 192.168.67.5 [3par2]

Steps as follows:

1) Create a volume on backend 3par1
docker volume create -d hpe --name=volume -o backend=3par2
2) mount a volume by using below command:
    docker run -it -d --mount src=volume,dst=/data1,volume-driver=hpe --name mounter2 --rm busybox /bin/sh

While mounting a volume it gives an error
Attaching a log file.
[Mount Error.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2339756/Mount.Error.txt)

**Comment by sandesh-desai** [comment]
Earlier it was pass while mounting the volume from backend 3par array.
Today when verifying the file permissions bug#256 found that its not mounting with normal 3par backend.

**Comment by sandesh-desai** [comment]
Same issue observed in 3.3.1 MU3 array.

**Comment by wdurairaj** [comment]
On the given IP 

i have tried this commands 

```
docker@ubuntu:~$ vi /etc/hpedockerplugin/hpe.conf
docker@ubuntu:~$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          snap_27aug
hpe:latest          snap_freq
hpe:latest          snap_sn_31
hpe:latest          snap_sn_all_my
hpe:latest          snap_sn_my_upgrade
hpe:latest          snap_ssp1
hpe:latest          snap_ssp5
hpe:latest          snap_ssp_15
hpe:latest          snap_ssp_ssp
hpe:latest          vol_27aug
docker@ubuntu:~$ vi /etc/hpedockerplugin/hpe.conf
docker@ubuntu:~$ docker volume create -d hpe --name 3par_vol1 -o size=12 -o backend=3par1
3par_vol1
docker@ubuntu:~$ docker run -it -v 3par_vol1:/data1 --rm busybox /bin/sh
/ #

```

**Comment by wdurairaj** [comment]
IP of the machine where it has been tried is `192.168.68.31`

**Comment by sandesh-desai** [comment]
Verified the same scenario but still facing the issue.
attaching the logs.
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2351232/hpe.conf.txt)
[Mount error.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2351233/Mount.error.txt)

**Comment by sandesh-desai** [comment]
Verified and working fine as expected closing the bug.
Please find the attached file for output.

[Bug 299 output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2366566/Bug.299.output.txt)
