### ISSUE TITLE
Replication: Volume creation fails with Active Passive configuration

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#301]
Summary: Volume creation fails with Active Passive configuration

 Pre-requisite: Replicated arrays with quorum witness.
Testbed -
root@cssosbe03-b14:~# docker version
Client: Docker Enterprise Edition (EE) 2.0
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:41:28 2018
 OS/Arch:      linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:40:18 2018
  OS/Arch:      linux/amd64
  Experimental: false
root@cssosbe03-b14:~#

root@cssosbe03-b14 : ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
root@cssosbe03-b14 : ~ #

root@cssosbe03-b14 : ~ # docker plugin inspect hpe | grep PluginRef
        "PluginReference": "docker.io/dockerciuser/hpedockerplugin:test",
root@cssosbe03-b14 : ~ # date
Mon Sep  3 17:23:10 IST 2018
root@cssosbe03-b14 : ~ #

Steps Followed - 
1. Configure hpe.conf for Active Passive (Disable Quorum Witness)
2. Install docker volume plugin and create volume to see the below error.

root@cssosbe03-b14:~# docker volume create -d hpe --name shashi-volume-new -o replicationGroup=shashi-new
Error response from daemon: create shashi-volume-new: VolumeDriver.Create: <html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b>

<div>
  <style type="text/css">
    div.error {
      color: red;
      font-family: Verdana, Arial, helvetica, sans-serif;
      font-weight: bold;
    }

    div {
      font-family: Verdana, Arial, helvetica, sans-serif;
    }

    div.stackTrace {
    }

    div.frame {
      padding: 1em;
      background: white;
      border-bottom: thin black dashed;
    }

    div.frame:first-child {
      padding: 1em;
      background: white;
      border-top: thin black dashed;
      border-bottom: thin black dashed;
    }

    div.location {
    }

    span.function {
      font-weight: bold;
      font-family: "Courier New", courier, monospace;
    }

    div.snippet {
      margin-bottom: 0.5em;
      margin-left: 1em;
      background: #FFFFDD;
    }

    div.snippetHighlightLine {
      color: red;
    }

    span.code {
      font-family: "Courier New", courier, monospace;
    }
  </style>

  <div class="error">
    <span>builtins.AttributeError</span>: <span>'dict' object has no attribute 'sync_period'</span>
  </div>
  <div class="stackTrace">
    <div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/internet/defer.py</span>:<span>151</span> in
        <span class="function">maybeDeferred</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">150</span>
          <code class="code"> &#160; &#160;try:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">151</span>
          <code class="code"> &#160; &#160; &#160; &#160;result = f(*args, **kw)</code>
        </div><div class="snippetLine">
          <span class="lineno">152</span>
          <code class="code"> &#160; &#160;except:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/klein-17.10.0-py3.6.egg/klein/app.py</span>:<span>128</span> in
        <span class="function">execute_endpoint</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">127</span>
          <code class="code"> &#160; &#160; &#160; &#160;endpoint_f = self._endpoints[endpoint]</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">128</span>
          <code class="code"> &#160; &#160; &#160; &#160;return endpoint_f(self._instance, *args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">129</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/klein-17.10.0-py3.6.egg/klein/app.py</span>:<span>227</span> in
        <span class="function">_f</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">226</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;def _f(instance, request, *a, **kw):</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">227</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;return _call(instance, f, request, *a, **kw)</code>
        </div><div class="snippetLine">
          <span class="lineno">228</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/klein-17.10.0-py3.6.egg/klein/app.py</span>:<span>50</span> in
        <span class="function">_call</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">49</span>
          <code class="code"> &#160; &#160; &#160; &#160;args = (instance,) + args</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">50</span>
          <code class="code"> &#160; &#160;result = f(*args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">51</span>
          <code class="code"> &#160; &#160;if iscoroutine(result):</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py</span>:<span>347</span> in
        <span class="function">volumedriver_create</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">346</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;try:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">347</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;self._validate_rcg_params(rcg_name)</code>
        </div><div class="snippetLine">
          <span class="lineno">348</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;except exception.InvalidInput as ex:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py</span>:<span>391</span> in
        <span class="function">_validate_rcg_params</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">390</span>
          <code class="code"></code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">391</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;if replication_device.sync_period and rep_mode == 'synchronous':</code>
        </div><div class="snippetLine">
          <span class="lineno">392</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;msg = "'sync_period' can be defined only for 'asynchronous'" \</code>
        </div>
      </div>
    </div>
  </div>
  <div class="error">
    <span>builtins.AttributeError</span>: <span>'dict' object has no attribute 'sync_period'</span>
  </div>
</div>

</body></html>
root@cssosbe03-b14 : ~

Attaching required logs
[VolumeCreateActivePassive.log](https://github.com/hpe-storage/python-hpedockerplugin/files/2345387/VolumeCreateActivePassive.log)

Attaching hpe.conf

[hpe.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2345407/hpe.txt)

**Comment by imran-ansari** [comment]
This has been fixed with the latest build. Please verify it and let me know if you still see the issue.

**Comment by sonawane-shashikant** [comment]
This issues is verified as FIXED

root@cssosbe03-b14 : ~ # docker volume create -d hpe --name shashivol -o replicationGroup=shashiGroup
shashivol
root@cssosbe03-b14 : ~ # docker volume ls
DRIVER              VOLUME NAME
hpe:latest          PP_Test_Vol02
hpe:latest          shashivol
root@cssosbe03-b14 : ~ # docker volume inspect shashivol
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/589b6fd641b2c80790a7ae22dee9c4c856ba90ef4e218b14d5e729d2bcd79349/rootfs",
        "Name": "shashivol",
        "Options": {
            "replicationGroup": "shashiGroup"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "compression": null,
                "cpg": "SHASHI-PRIM",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "thin",
                "size": 100,
                "snap_cpg": "SHASHI-PRIM-SNAP"
            }
        }
    }
]
root@cssosbe03-b14 : ~ #
