### ISSUE TITLE
Volume created in StoreVirtual array has a name without prefix when it is created from Docker host.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#31]
Volume name is displayed with prefix “dcv-” followed by UUID in 3Par array when a volume is created from Docker host. But this is not the case for Lefthand driver. 
There should be some consistency in volume name when a volume is created from HPE Docker host.

CLI snippet from Storevirtual array for a volume which is created from Docker host:

CLIQ>getVolumeInfo

HPE StoreVirtual LeftHand OS Command Line Interface, v12.6.00.0155
(C) Copyright 2016 Hewlett Packard Enterprise Development LP

RESPONSE
 result         0
 processingTime 93
 name           CliqSuccess
 description    Operation succeeded.

  VOLUME
   transport                          iSCSI
   thinProvision                      true
   stridePages                        32
   size                               10737418240
   serialNumber                       a28eafb99674dd972a7e830132afc42c0000000000000162
   scratchQuota                       4194304
   reserveQuota                       536870912
   replication                        1
   provisionedSpace                   553648128
   parity                             0
   name                               **_d7167f6e-f180-4979-8d6e-30247bac93b7_**
   minReplication                     1
   md5                                a28eafb99674dd972a7e830132afc42c
   maxSize                            145661100032
   iscsiIqn                           iqn.2003-10.com.lefthandnetworks:ci-mg-12.5:354:d7167f6e-f180-4979-8d6e-30247bac93b7
   isPrimary                          true
   initialQuota                       536870912
   id                                 354
   groupName                          ci-mg-12.5
   description
   deleting                           false
   created                            2017-05-09T10:40:21Z
   consumedSpace                      553648128
   clusterName                        CI-125
   clusterAdaptiveOptimizationCapable false
   checkSum                           false
   bytesWritten                       0
   blockSize                          1024
   availability                       online
   autogrowPages                      1
   adaptiveOptimizationPermitted      true

    STATUS
     value       2
     description OK

**Comment by hpe-storage** [comment]
- Adding a dcv- prefix like 3PAR volume names for StoreVirtual volumes might break backward-compatibility during plugin upgrades.
- StoreVirtual Driver will not be supported going forward, and hence I'm closing this bug.
