### ISSUE TITLE
Exception module  does not have NotFound() class 

### ISSUE THREAD

**Issue by yashwant09** [hpe-storage/python-hpedockerplugin#311]
we are raising the "NotFound" exception whenever we get http not found from 3parclient but we have not implemented 

Example 
       --------some code here
        except hpeexceptions.HTTPForbidden:
            raise exception.NotAuthorized()
        except hpeexceptions.HTTPNotFound:
            raise exception.NotFound()  #### **Not implemented NotFound()**

**Comment by wdurairaj** [comment]
Pull request https://github.com/hpe-storage/python-hpedockerplugin/pull/318 addressed this. Hence closing.
