### ISSUE TITLE
Replication:iSCSI:PP:Volume delete fails when volume is part of remote copy group

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#312]
Summary - Volume delete fails when volume is part of remote copy group

Pre-requisite: Replicated arrays with quorum witness.
Testbed -
root@cld6b2:~# docker version
Client: Docker Enterprise Edition (EE) 2.0
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:41:28 2018
 OS/Arch:      linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:40:18 2018
  OS/Arch:      linux/amd64
  Experimental: false
root@cld6b2 : ~# docker plugin inspect hpe | grep PluginR
        "PluginReference": "docker.io/dockerciuser/hpedockerplugin:test",
root@cld6b2 : ~#

root@cld6b2 : ~ # docker volume create -d hpe --name shashi_vol1 -o size=200 -o replicationGroup=shashi_rcg
shashi_vol1
root@cld6b2 : ~ # docker volume create -d hpe --name shashi_vol2 -o size=200 -o replicationGroup=shashi_rcg
shashi_vol2
root@cld6b2 : ~ # docker volume ls
DRIVER              VOLUME NAME
hpe:latest          shashi-volume
hpe:latest          shashi_vol1
hpe:latest          shashi_vol2
root@cld6b2 : ~ # docker volume rm shashi_vol1 shashi_vol2
Error response from daemon: unable to remove volume: remove shashi_vol1: Post http://%2Frun%2Fdocker%2Fplugins%2F0ebfb77fb878cdfccf05f873fef3e34a654b56b297ee6073bcc19d998b826de1%2Fhpe.sock/VolumeDriver.Remove: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Error response from daemon: get shashi_vol2: error while checking if volume "shashi_vol2" exists in driver "hpe:latest": Post http://%2Frun%2Fdocker%2Fplugins%2F0ebfb77fb878cdfccf05f873fef3e34a654b56b297ee6073bcc19d998b826de1%2Fhpe.sock/VolumeDriver.Get: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

When we create volume which is not a part of remote copy group and try to delete then it gets deleted.

root@cld6b2 : ~ # docker volume create -d hpe --name shashi_vol3
shashi_vol3
root@cld6b2 :~ # docker volume rm shashi_vol3
shashi_vol3
root@cld6b2 :~ # docker volume ls
DRIVER              VOLUME NAME
hpe:latest          shashi-volume
hpe:latest          shashi_vol1
hpe:latest          shashi_vol2
root@cld6b2 :~ #

[volumeDeleteError.log](https://github.com/hpe-storage/python-hpedockerplugin/files/2352345/volumeDeleteError.log)

**Comment by imran-ansari** [comment]
Strangely, this is happening in 3PAR Client function removeVolumeFromRemoteCopyGroup() where it never succeeds in removing the volume from the RCG and the Docker operation eventually times out.

**Comment by sonawane-shashikant** [comment]
The bug has been verified and it is fixed.

Performed following steps to verify:
1] Created two volumes in a replication group
2] Attached one volume
3] Tried to delete attached volume; it didn't get deleted.
    Later detached volume; then we were able to delete volume
4] Tried to delete other volume; it got deleted
5] Finally group was also deleted from 3par

Refer attachments for details
[docker_window.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2382186/docker_window.txt)

[3par_primary_window.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2382187/3par_primary_window.txt)

[3par_secondary_window.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2382190/3par_secondary_window.txt)
