### ISSUE TITLE
Replication: Volume creation fails with Asyc mode

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#322]
Summary - Volume with Async mode fails to create

root@cssosbe03-b14:~# docker version
Client: Docker Enterprise Edition (EE) 2.0
 Version:      17.06.2-ee-16
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   9ef4f0a
 Built:        Thu Jul 26 16:41:28 2018
 OS/Arch:      linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-16
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   9ef4f0a
  Built:        Thu Jul 26 16:40:18 2018
  OS/Arch:      linux/amd64
  Experimental: false
root@cssosbe03-b14:~# cat /etc/hpedockerplugin/hpe.conf
[DEFAULT]
ssh_hosts_key_file = /root/.ssh/known_hosts

host_etcd_ip_address = 192.168.68.44
host_etcd_port_number = 2379
logging = DEBUG
hpe3par_debug = True
suppress_requests_ssl_warnings = True
hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver

hpe3par_api_url = https://192.168.67.7:8080/api/v1
hpe3par_username = 3paradm
hpe3par_password = 3pardata
san_ip = 192.168.67.7
san_login = 3paradm
san_password = 3pardata
hpe3par_cpg = SHASHI-PRIM
hpe3par_snapcpg = SHASHI-PRIM-SNAP
hpe3par_iscsi_chap_enabled = True
hpe3par_iscsi_ips = 192.168.68.201,192.168.68.203
use_multipath = True
enforce_multipath = True
backend_id = CSSOS-SSA04
replication_device = backend_id:CSSOS-SSA05,
                     replication_mode:asynchronous,
                     sync_period:400,
                     cpg_map:SHASHI-PRIM:SHASHI-SEC,
                     snap_cpg_map:SHASHI-PRIM-SNAP:SHASHI-SEC-SNAP,
                     hpe3par_api_url:https://192.168.67.5:8080/api/v1,
                     hpe3par_username:3paradm,
                     hpe3par_password:3pardata,
                     san_ip:192.168.67.5,
                     san_login:3paradm,
                     hpe3par_iscsi_ips:192.168.68.202,
                     san_password:3pardata
#                     quorum_witness_ip:dummy_ip

[3PAR]
hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_fc.HPE3PARFCDriver
hpe3par_api_url = https://192.168.67.2:8080/api/v1
hpe3par_username = 3paradm
hpe3par_password = 3pardata
san_ip = 192.168.67.2
san_login = 3paradm
san_password = 3pardata
hpe3par_cpg = Docker_CI_NEW
hpe3par_snapcpg = Docker_CI_NEW
use_multipath = True
enforce_multipath = True
mount_conflict_delay = 30
root@cssosbe03-b14:~#

root@cssosbe03-b14:~# docker volume create -d hpe --name shashivolume -o replicationGroup=shashi-group
Error response from daemon: create shashivolume: VolumeDriver.Create: <html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b>

<div>
  <style type="text/css">
    div.error {
      color: red;
      font-family: Verdana, Arial, helvetica, sans-serif;
      font-weight: bold;
    }

    div {
      font-family: Verdana, Arial, helvetica, sans-serif;
    }

    div.stackTrace {
    }

    div.frame {
      padding: 1em;
      background: white;
      border-bottom: thin black dashed;
    }

    div.frame:first-child {
      padding: 1em;
      background: white;
      border-top: thin black dashed;
      border-bottom: thin black dashed;
    }

    div.location {
    }

    span.function {
      font-weight: bold;
      font-family: "Courier New", courier, monospace;
    }

    div.snippet {
      margin-bottom: 0.5em;
      margin-left: 1em;
      background: #FFFFDD;
    }

    div.snippetHighlightLine {
      color: red;
    }

    span.code {
      font-family: "Courier New", courier, monospace;
    }
  </style>

  <div class="error">
    <span>builtins.AttributeError</span>: <span>'dict' object has no attribute 'sync_period'</span>
  </div>
  <div class="stackTrace">
    <div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/internet/defer.py</span>:<span>151</span> in
        <span class="function">maybeDeferred</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">150</span>
          <code class="code"> &#160; &#160;try:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">151</span>
          <code class="code"> &#160; &#160; &#160; &#160;result = f(*args, **kw)</code>
        </div><div class="snippetLine">
          <span class="lineno">152</span>
          <code class="code"> &#160; &#160;except:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/klein-17.10.0-py3.6.egg/klein/app.py</span>:<span>128</span> in
        <span class="function">execute_endpoint</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">127</span>
          <code class="code"> &#160; &#160; &#160; &#160;endpoint_f = self._endpoints[endpoint]</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">128</span>
          <code class="code"> &#160; &#160; &#160; &#160;return endpoint_f(self._instance, *args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">129</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/klein-17.10.0-py3.6.egg/klein/app.py</span>:<span>227</span> in
        <span class="function">_f</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">226</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;def _f(instance, request, *a, **kw):</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">227</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;return _call(instance, f, request, *a, **kw)</code>
        </div><div class="snippetLine">
          <span class="lineno">228</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/klein-17.10.0-py3.6.egg/klein/app.py</span>:<span>50</span> in
        <span class="function">_call</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">49</span>
          <code class="code"> &#160; &#160; &#160; &#160;args = (instance,) + args</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">50</span>
          <code class="code"> &#160; &#160;result = f(*args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">51</span>
          <code class="code"> &#160; &#160;if iscoroutine(result):</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py</span>:<span>352</span> in
        <span class="function">volumedriver_create</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">351</span>
          <code class="code"> &#160; &#160; &#160; &#160;try:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">352</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;self._validate_rcg_params(rcg_name, current_backend)</code>
        </div><div class="snippetLine">
          <span class="lineno">353</span>
          <code class="code"> &#160; &#160; &#160; &#160;except exception.InvalidInput as ex:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py</span>:<span>415</span> in
        <span class="function">_validate_rcg_params</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">414</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;try:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">415</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;sync_period = int(replication_device.sync_period)</code>
        </div><div class="snippetLine">
          <span class="lineno">416</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;except ValueError as ex:</code>
        </div>
      </div>
    </div>
  </div>
  <div class="error">
    <span>builtins.AttributeError</span>: <span>'dict' object has no attribute 'sync_period'</span>
  </div>
</div>

</body></html>
root@cssosbe03-b14:~#

**Comment by imran-ansari** [comment]
This has been fixed with the pull request https://github.com/hpe-storage/python-hpedockerplugin/pull/323 waiting for review.

**Comment by imran-ansari** [comment]
Hi @sonawane-shashikant , please validate this as this is part of the build now.

**Comment by imran-ansari** [comment]
Please validate and close this

**Comment by sonawane-shashikant** [comment]
Able to create volumes but mount fails.
Kindly refer attachments:

[docker_window.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2397098/docker_window.txt)
[mount_red_vol.log](https://github.com/hpe-storage/python-hpedockerplugin/files/2397100/mount_red_vol.log)
[hpe_conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2397102/hpe_conf.txt)

**Comment by wdurairaj** [comment]
I'm seeing this error as per the attached logs

```
nfo msg=" _http_log_resp /usr/lib/python3.6/site-packages/python_3parclient-4.2.7-py3.6.egg/hpe3parclient/http.py:181\x1b[00m" plugin=9ef2adf1761aba228624e19b46f703acc5b326429dfcbfad3341673bd02b3298
Sep 19 06:13:45 cld6b9 dockerd[35162]: time="2018-09-19T06:13:45-04:00" level=info msg="2018-09-19 10:13:45.030 18 ERROR hpedockerplugin.volume_manager [-] ('Initialize Connection Failed: connection info retrieval failed, error is: ', 'Forbidden (HTTP 403) 118 - Volume not in same domain'): hpe3parclient.exceptions.HTTPForbidden: Forbidden (HTTP 403) 118 - Volume not in same domain\x1b[00m" plugin=9ef2adf1761aba228624e19b46f703acc5b326429dfcbfad3341673bd02b3298
```

`volume not in same domain`  @sonawane-shashikant , can you do a cleanup of 
- host, VLUN (including templates), and re-run the testcase ?

**Comment by sonawane-shashikant** [comment]
Cleaning up all hosts entries and rescan on docker server resolved the mount issue.

[docker_window_2.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2405028/docker_window_2.txt)
[mount_vol_a_2.log](https://github.com/hpe-storage/python-hpedockerplugin/files/2405029/mount_vol_a_2.log)
