### ISSUE TITLE
Multi-Array Support:Creating virtualcopy accepting invalid backend option.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#324]
Multi-Array Support:Creating virtualcopy accepting invalid backend option.

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker version: Version:17.06.2-ee-16 
3PAR array: 192.168.67.7 [DEFAULT],15.212.192.252[3par1] 192.168.67.2 [3par11]

Steps as follows:
1)Create a volume on backend 3par11 
   #docker volume create -d hpe --name=volume -o size=150 -o backend=3par11
2) Create a snapshot on backend 3par1
   #docker volume create -d hpe --name=volume-snap -o virtualCopyOf=volume -o retentionHours=1 -o 
   expirationHours=1 -o backend=3par1

 Snapshot created successfully on backend 3par11 but volume inspect shows invalid backend name as 3par1

Attaching log files and hpe.conf files.
[3paroutput.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2370998/3paroutput.txt)
[docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2370989/docker.output.txt)
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2370990/hpe.conf.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2370991/Syslog.txt)

**Comment by sonivi** [comment]
@wdurairaj, will restrict user to use both options 'virtualCopyOf' & 'backend' at a same time

**Comment by sandesh-desai** [comment]
Verified and Closed.
Attaching docker output.
[docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2387738/docker.output.txt)
