### ISSUE TITLE
Clone volume gets deleted before completing retentionHours=1 -o expirationHours=1

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#331]
Clone volume gets deleted before completing -o
[3par side.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2388061/3par.side.txt)
[Docker command output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2388062/Docker.command.output.txt)

 retentionHours=1 -o expirationHours=1

Testbed Details:
Host:192.168.68.31
Host OS: Ubuntu Release: 16.04
Docker version: Version:17.06.2-ee-16
3PAR array: 192.168.67.7 [DEFAULT],15.212.192.252[3par1] 192.168.67.2 [3par11]

Steps as follows:
1) Create a volume 
    #docker volume create -d hpe --name=TEST-VOL -o size=10
2) Create a clone with retention and expiration hrs.
   #docker volume create -d hpe --name=TEST-snap -o cloneOf=TEST-VOL -o retentionHours=1 -o expirationHours=1
3) Delete a clone before retentionHours and expirationHours
    #docker volume rm TEST-snap
4) Clone gets deleted successfully.

Attaching docker output and 3par ouput files.
[3par side.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2388055/3par.side.txt)
[Docker command output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2388056/Docker.command.output.txt)

**Comment by sandesh-desai** [comment]
Attaching 3par CLI output.
[3par Retention through CLI.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2388425/3par.Retention.through.CLI.txt)

**Comment by wdurairaj** [comment]
Fixed label should be put only for issues with PR raised and also merged, but pending QA verification.

**Comment by imran-ansari** [comment]
retentionHours and expirationHours are not meant to be used with clone operation. Options validation fix which is part of PR https://github.com/hpe-storage/python-hpedockerplugin/pull/344 addresses this.

**Comment by sandesh-desai** [comment]
Verified and closed.
Attaching the logs.
[docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2468072/docker.output.txt)
[Hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2468073/Hpe.conf.txt)
