### ISSUE TITLE
hpe3parencryptor does not support multi etcd configuration

### ISSUE THREAD

**Issue by farhan7500** [hpe-storage/python-hpedockerplugin#339]
hpe3parencryptor utility takes a key and a password as arguments  and creates an encrypted password that can then be consumed by docker plugin via hpe.conf

For a single etcd configuration, this utility works and returns an encrypted password.

However, for multi etcd configurations, it throws an error while parsing multiple etcd IPs that also have ports attached to them.

```
root@localhost hpedockerplugin]# hpe3parencryptor -a 12345 3pardata
Traceback (most recent call last):
  File "/usr/bin/hpe3parencryptor", line 7, in <module>
    from hpe3parencryptor import encryption_utility
  File "/usr/lib/python2.7/site-packages/hpe3parencryptor/encryption_utility.py", line 180, in <module>
    ,host_etcd_client_key)
  File "/usr/lib/python2.7/site-packages/hpe3parencryptor/encryption_utility.py", line 143, in __init__
    self.client.read(BACKENDROOT)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 597, in read
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 893, in wrapper
    cause=e
etcd.EtcdConnectionFailed: Connection to etcd failed due to LocationParseError(u'Failed to parse: 15.213.67.74:23790,15.213.67.75:23790,15.213.67.76:23790:23790',)
```

The following hpe.conf file was used for this:

```
[DEFAULT]
ssh_hosts_key_file=/root/.ssh/known_hosts
host_etcd_port_number=23790
logging=DEBUG
hpe3par_debug=True
suppress_requests_ssl_warning=True
hpe3par_username=3paradm
hpe3par_password=3pardata
hpe3par_cpg=FC_r1
hpe3par_snapcpg=FC_r1
hpe3par_iscsi_chap_enabled=True
use_multipath=False
enforce_multipath=False
hpedockerplugin_driver=hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
san_ip=15.212.192.251
san_login=3paradm
san_password=3pardata
host_etcd_ip_address=15.213.67.74:23790,15.213.67.75:23790,15.213.67.76:23790
#host_etcd_ip_address=15.213.67.74
hpe3par_api_url=https://15.212.192.251:8080/api/v1
hpe3par_iscsi_ips=15.212.202.107,15.212.202.109
[3PAR1]
ssh_hosts_key_file=/root/.ssh/known_hosts
host_etcd_port_number=second_key
```

**Comment by sandesh-desai** [comment]
Installed py-3parencryptor-1.0.7 successfully.
Verified and working as per the expectation.
Please find the attached output.
[Hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2445900/Hpe.conf.txt)
[pip py-3parencryptor Output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2445901/pip.py-3parencryptor.Output.txt

**Comment by sandesh-desai** [comment]
Installed py-3parencryptor-successfully.
Verified and working as per the expectation.
Please find the attached output.
[Pip py 3parencryptor output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2514277/Pip.py.3parencryptor.output.txt)

**Comment by farhan7500** [comment]
Closing issue as per the discussion with @sandesh-desai
