### ISSUE TITLE
Volume plugin "resource in use" error

### ISSUE THREAD

**Issue by farhan7500** [hpe-storage/python-hpedockerplugin#346]
This is an intermittent issue I have seen on multiple configurations:
1. Multiple etcd configuration
2. Standalone docker volume plugin installation

Once the plugin has started, the logs indicate a 409 conflict: Resource in use. Failed to initialize 3PAR driver for array: https://15.212.192.251:8080/api/v1!Exception: HPE Docker Volume plugin not ready

Steps to reproduce:
Though this is intermittent, I was able to get 30% hit rate on this today
1. Follow instructions at https://github.com/hpe-storage/python-hpedockerplugin/blob/master/quick-start/README.md
2. Start docker volume plugin
3. docker logs `<plugin-container-id>`

[Download error logs here](https://github.com/hpe-storage/python-hpedockerplugin/files/2442693/resource_in_use.txt)

hpe.conf:
```
[DEFAULT]
host_etcd_port_number=23790
hpe3par_username=3paradm
hpe3par_password=wy4a8PYh4IY=
hpe3par_cpg=FC_r1
hpedockerplugin_driver=hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
logging=DEBUG
san_ip=15.212.192.251
san_login=3paradm
san_password=wy4a8PYh4IY=
host_etcd_ip_address=15.213.67.74:23790,15.213.67.75:23790,15.213.67.76:23790
hpe3par_api_url=https://15.212.192.251:8080/api/v1
hpe3par_iscsi_ips=15.212.202.107,15.212.202.109
[3PAR1]
host_etcd_port_number=23790
hpe3par_username=3paradm
hpe3par_password=6uHczrIw4RY=
hpe3par_cpg=FC_r1
hpedockerplugin_driver=hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
logging=DEBUG
san_ip=15.212.192.252
san_login=3paradm
san_password=6uHczrIw4RY=
host_etcd_ip_address=15.213.67.74:23790,15.213.67.75:23790,15.213.67.76:23790
hpe3par_api_url=https://15.212.192.252:8080/api/v1
hpe3par_iscsi_ips=15.212.192.112
```

**Comment by wdurairaj** [comment]
From your logs , this is what i see

```
2018-10-03 15:21:36.672 12 DEBUG hpedockerplugin.hpe.hpe_3par_common [-] Connecting to 3PAR client_login /python-hpedockerplugin/hpedockerplugin/hpe/hpe_3par_common.py:159[00m
2018-10-03 15:21:41.756 12 DEBUG hpedockerplugin.hpe.hpe_3par_common [-] Disconnect from 3PAR REST and SSH c1599ede-031c-473b-849e-07fb3986f717 client_logout /python-hpedockerplugin/hpedockerplugin/hpe/hpe_3par_common.py:184[00m
2018-10-03 15:21:42.204 12 ERROR hpedockerplugin.volume_manager [-] ('hpeplugin_driver do_setup failed, error is: %s', 'Conflict (HTTP 409) 34 - resource in use'): hpe3parclient.exceptions.HTTPConflict: Conflict (HTTP 409) 34 - resource in use[00m
```
time gap between 15:21:36 - 15:21:41 is approximately more than 5 secs (considering milliseconds)

So, this line  https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/hpedockerplugin/volume_manager.py#L174 has a timeout of max 5 secs.. And the REST client creation fails due to the timeout, which is wrapped and returned as error message as shown in 15:21:42.204

Easier thing to try is change this timeout value and see if that solves the problem. 
This should be mostly a shared array setup on BLR, hence the problem is more noticed, which confirms the theory of hit ratio of 30% 

But I believe this timeout was introduced for another problem, where the incorrect WSAPI URL is causing long time to throw an exception. 

Please confirm this theory and let me know Farhan.

**Comment by farhan7500** [comment]
Yes, you are correct!

It took 13 seconds to connect after increasing my timeout to 50 seconds

```
        try:
            hpeplugin_driver.do_setup(timeout=50)
            hpeplugin_driver.check_for_setup_error()


```
```
plugin_container   | 2018-10-04 12:00:26.971 18 DEBUG hpedockerplugin.hpe.hpe_3par_common [-] Connecting to 3PAR client_login /python-hpedockerplugin/hpedockerplugin/hpe/hpe_3par_common.py:159
plugin_container   | 2018-10-04 12:00:39.721 18 DEBUG hpedockerplugin.hpe.hpe_3par_common [-] Disconnect from 3PAR REST and SSH 8eae401a-b587-47fe-8dba-6db49cbd3d08 client_logout /python-hpedockerplugin/hpedockerplugin/hpe/hpe_3par_common.py:184
plugin_container   | 2018-10-04 12:00:39.762 18 DEBUG hpedockerplugin.hpe.hpe_3par_common [-] Connecting to 3PAR client_login /python-
```

Now that we know what has caused this, should we:

- [ ] **Increase the timeout? If yes, how much?**
- [ ] **Ignore this as this is not a customer use case?**
- [ ] **Any other suggestion?**

**Comment by farhan7500** [comment]
Fix committed at https://github.com/hpe-storage/python-hpedockerplugin/pull/353 

Needs verification

**Comment by farhan7500** [comment]
Fixed with https://github.com/hpe-storage/python-hpedockerplugin/pull/353

**Comment by farhan7500** [comment]
Reopening as the errors was seen again on shared arrays when using multiple etcd cluster

```
2018-10-22 05:52:02.015 18 INFO hpedockerplugin.hpe.hpe_3par_common [-] HPE3PARCommon 0.0.6,hpe3parclient 4.2.7
2018-10-22 05:52:02.015 18 DEBUG hpedockerplugin.hpe.hpe_3par_common [-] Connecting to 3PAR client_login /python-hpedockerplugin/hpedockerplugin/hpe/hpe_3par_common.py:159
2018-10-22 05:52:32.142 18 DEBUG hpedockerplugin.hpe.hpe_3par_common [-] Disconnect from 3PAR REST and SSH 36fb50a5-ba16-44ad-8fb8-43e15841ef67 client_logout /python-hpedockerplugin/hpedockerplugin/hpe/hpe_3par_common.py:184
2018-10-22 05:52:32.183 18 ERROR hpedockerplugin.volume_manager [-] ('hpeplugin_driver do_setup failed, error is: %s', 'Conflict (HTTP 409) 34 - resource in use'): hpe3parclient.exceptions.HTTPConflict: Conflict (HTTP 409) 34 - resource in use
```

**Comment by farhan7500** [comment]
Closing this: The array is not responding to the rest GET CPG call, thus timing out. The call is taking 50 seconds to complete which is beyond the 30 seconds timeout
