### ISSUE TITLE
Display proper error message in case of failure in "docker volume inspect" command

### ISSUE THREAD

**Issue by sonivi** [hpe-storage/python-hpedockerplugin#347]
Issue: when `docker volume inspect <vol_name>` command failed, instead of displaying appropriate message it throws below common error
```
root@COSSOSBE03-B07:# docker volume inspect vvk_vol
[]
Error: No such volume: vvk_vol
```
so far we need to handle this, in **THREE** scenarios for inspect code:
1. Failure while inspecting a volume having qos-enabled.
code:

```
except Exception as ex:
    msg = 'unable to get/filter qos from 3par, error is: %s' % six.text_type(ex)
    LOG.error(msg)
    **return json.dumps({u"Err": six.text_type(ex)})**
```
Note : high-lighted json should be returned and displayed to end-user

step: to reproduce this scenario
- create a volume with qos enabled
- From 3PAR clear QOS from vvset
- Try inspecting that volume

2. Failure while inspecting a replicated volume (i.e. at the time of rcg detail fetching)

code:
```
except Exception as ex:
    msg = 'unable to get/filter rcg from 3par, error is: %s' % six.text_type(ex)
    LOG.error(msg)
    **return json.dumps({u"Err": six.text_type(ex)})**
```
Note : high-lighted json should be returned and displayed to end-user

step: to reproduce this scenario
- create a replicated volume
- From 3PAR delete the rcopy group
- Try inspecting that volume

3. docker volume inspect volumename/snap1/snap3
code : In _hpe_storage_api.py_
```
if token_cnt > 2:
    msg = (_LE("invalid volume or snapshot name %s" % qualified_name))
    LOG.error(msg)
    response = json.dumps({u"Err": msg})
    return response
```
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2445660/hpe.conf.txt)

**Comment by imran-ansari** [comment]
As per the documentation for Docker REST API "/VolumeDriver.Get", the response can contain error as below:
```sh
{
  "Volume": {
    "Name": "volume_name",
    "Mountpoint": "/path/under/PropagatedMount",
    "Status": {}
  },
  "Err": ""
}
```
However, when plugin populates "Err" field with some error, Docker ignores it and CLI always displays:
```sh
[]
Error: No such volume: xxx
```

Looks like we have hit another Docker issue.

**Comment by imran-ansari** [comment]
Moby issue raised https://github.com/moby/moby/issues/38058

**Comment by sandesh-desai** [comment]
Verified and Closed.
Attaching the logs.
[For QOS related volume.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2525126/For.QOS.related.volume.txt)
[For replicated volume.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2525127/For.replicated.volume.txt)
[Hpe.conf for QOS volume.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2525128/Hpe.conf.for.QOS.volume.txt)
[Hpe.conf for replicated volume.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2525129/Hpe.conf.for.replicated.volume.txt)

**Comment by wdurairaj** [comment]
Closing based on previous comment by Sandesh
