### ISSUE TITLE
Docker EE 2.0 (with UCP) : POD creation is failing with an error

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#358]
Pod creation is failed with below error - 

Events:
  Type     Reason                 Age                From                  Message
  ----     ------                 ----               ----                  -------
  Normal   SuccessfulMountVolume  1h                 kubelet, csosbe03b10  MountVolume.SetUp succeeded for volume "default-token-87hbp"
  Normal   Scheduled              1h                 default-scheduler     Successfully assigned podhpe to csosbe03b10
  Warning  FailedSync             24m (x20 over 1h)  kubelet, csosbe03b10  Error syncing pod
  Warning  FailedMount            12m (x25 over 1h)  kubelet, csosbe03b10  Unable to mount volumes for pod "podhpe_kube-system(ef8246c4-c7dc-11e8-86aa-0242ac110006)": timeout expired waiting for volumes to attach/mount for pod "kube-system"/"podhpe". list of unattached/unmounted volumes=[export]
  Warning  FailedMount            8m (x36 over 1h)   kubelet, csosbe03b10  MountVolume.SetUp failed for volume "schpe-d10d2b1d-c7dc-11e8-86aa-0242ac110006" : mount command failed, status: Failure, reason: Post http://unix/VolumeDriver.Mount: http: ContentLength=98 with Body length 0

**Comment by nilangekarss** [comment]
@dockerciuser is it a default pod creation? Can we also describe is it standalone setup or multinode setup?

**Comment by nilangekarss** [comment]
@wdurairaj could you please describe the cause of this issue?

**Comment by wdurairaj** [comment]
@nilangekarss , read the pull request description please.

**Comment by wdurairaj** [comment]
> @dockerciuser is it a default pod creation? Can we also describe is it standalone setup or multinode setup?

This is a specific problem in Docker EE 2.0 only, not on Openshift/Plain k8s. It's applicable both for single/multi-node setup.

**Comment by dockerciuser** [comment]
Verified the pod creation, working as expected.
Closing the bug.
