### ISSUE TITLE
Multipath doesn't work in HPE Docker plugin V2

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#36]
**_Installed multipathd, open-iscsi and xfsprogs_** 

**_Disabled plugin, turned on multipath and enabled plugin_**

stack@csimbe13-b13:~$ sudo docker volume create -d hpestorage/hpedockervolumeplugin:1.0 --name svol2 -o size=30 -o flash-cache=true
svol2

stack@csimbe13-b13:~$ docker volume ls
DRIVER                                 VOLUME NAME
hpestorage/hpedockervolumeplugin:1.0   svol2

stack@csimbe13-b13:~$ sudo docker run -it -v svol2:/data1/ --rm busybox sh
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/3880d433b4abc371a04467ef0b749328a0159cb19e2aaccbb5e9201896e3b0ed/rootfs': VolumeDriver.Mount
<span>oslo_concurrency.processutils.ProcessExecutionError</span>: <span>[Errno 2] No such file or directory
Command: multipathd show status
Exit code: -
Stdout: None
Stderr: None

------------------------------------------------------------------------------------------------------------------------------------------------------------

**_Uninstalled both multipathd and open-iscsi both_**

Found below error while enabling plugin:

stack@csimbe13-b13:~$ docker plugin enable hpestorage/hpedockervolumeplugin:1.0
Error response from daemon: rpc error: code = 2 desc = oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/sbin/iscsiadm\\\" to rootfs \\\"/var/lib/docker/plugins/3880d433b4abc371a04467ef0b749328a0159cb19e2aaccbb5e9201896e3b0ed/rootfs\\\" at \\\"/sbin/ia\\\" caused \\\"stat /sbin/iscsiadm: no such file or directory\\\"\""

----------------------------------------------------------------------------------------------------------------------------------------------------------------

**_Installed open-iscsi again_**

**_Enabled plugin_**

stack@csimbe13-b13:~$ sudo docker volume create -d hpestorage/hpedockervolumeplugin:1.0 --name svol3 -o size=30
svol3

stack@csimbe13-b13:~$ docker volume ls
DRIVER                                 VOLUME NAME
hpestorage/hpedockervolumeplugin:1.0   svol3

stack@csimbe13-b13:~$ sudo docker run -it -v svol3:/data1/ --rm busybox sh
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/3880d433b4abc371a04467ef0b749328a0159cb19e2aaccbb5e9201896e3b0ed/rootfs': VolumeDriver.Mount:
  <span>oslo_concurrency.processutils.ProcessExecutionError</span>: <span>[Errno 2] No such file or directory
Command: multipathd show status
Exit code: -
Stdout: None
Stderr: None

**Comment by wdurairaj** [comment]
Addressed as part of 1.1 plugin.
