### ISSUE TITLE
Kubernetes : The docker host throwing  "no space left on device" error

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#360]
The docker host is getting unstable after the unknown event.
The error which we observed is - 

[root@CSSOSBE03-B11 ~]# docker start ucp-kubelet
Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/dev/shm\\\" to rootfs \\\"/var/lib/docker/overlay2/f220fe8b699006e4213a807b18cf0283f9377cac9a857c7f1fe7d0e55aac6090/merged\\\" at \\\"/var/lib/docker/overlay2/f220fe8b699006e4213a807b18cf0283f9377cac9a857c7f1fe7d0e55aac6090/merged/dev/shm\\\" caused \\\"no space left on device\\\"\""
Error: failed to start containers: ucp-kubelet

We can see following mount entries in thousands - 
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,seclabel)

[root@CSSOSBE03-B11 ~]# mount | wc -l
32862

**Comment by wdurairaj** [comment]
This problem was directly corelated with the volume plugin operations, but seen on the Docker EE 2.0 environment with UCP. Hence reducing the priority.

**Comment by prablr79** [comment]
@Team, is this observed in latest UCP testing ?

**Comment by virendra-sharma** [comment]
@prablr79 I didn't find this issue on my docker UCP setup so far, my setup is still intact and able to perform operations. This issue looks like to be setup issue so can not re-produce it.

**Comment by prablr79** [comment]
@prablr79 I didn't find this issue on my docker UCP setup so far, my setup is still intact and able to perform operations. This issue looks like to be setup issue so can not re-produce it.
message from Test engineer, hence closing this defect.
