### ISSUE TITLE
Upgrade Scenario Testing :After Upgrading plugin not able to create a snapshot,also inspect volume missing snap_cpg.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#369]
After Upgrading not able to create a snapshot also inspect volume missing snap_cpg.

Testbed Details:
Host:192.168.68.45
Host OS: Ubuntu Release: 16.04
Docker Version: 17.06.2-ee-16
3PAR array: 192.168.67.7 [DEFAULT] 15.212.192.112 [3par1]

Steps perform:
1) Install old plugin successfully.
    docker plugin install dockerciuser/hpedockerplugin:old
2) Create a volume test
   docker volume create -d dockerciuser/hpedockerplugin:old --name=test1 -o flash-cache=true
3) Inspect the volume test1
    docker volume inspect test1
4) Upgrade the plugin
5) Inspect the volume test1
    docker volume inspect test1
    It shows "snap_cpg": null
Also while creating a snapshot it gives an error as below:
root@cssosbe03-b15:~# docker volume create -d dockerciuser/hpedockerplugin:old --name=snaptest -o virtualCopyOf=test1
Error response from daemon: create snaptest: Conflict (HTTP 409) 33 - volume has no snapshot CPG

Attaching the logs
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2482614/hpe.conf.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2482615/Syslog.txt)

**Comment by nilangekarss** [comment]
@sandesh-desai I do not know if dockerciuser/hpedockerplugin:old is a proper build?
I can see, it was uploaded 1 year back, 2.1 was not released.
old78 MB
Last updated a year ago

Could you please create a build from 2.1 source code and upload to dockerciuser with 2.1 tag and try the upgrade test.

**Comment by wdurairaj** [comment]
@sandesh-desai , i agree with @nilangekarss , you should use the released tag for 2.1 from the Docker store (if it's a managed plugin) or hpestorage/legacyvolumeplugin:2.1 (containerized build for 2.1)

**Comment by nilangekarss** [comment]
@sandesh-desai could you please also attach logs when you create volume from old plugin along with logs when you create snapshot from new plugin. It will help to rectify it earlier.

**Comment by sandesh-desai** [comment]
After upgrading from 2.1 to latest build snapshot creation failed.
attaching the logs.
[After snapshot creation fail 3PAR status.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2490905/After.snapshot.creation.fail.3PAR.status.txt)
[After upgrade snapshot creation successfull.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2490906/After.upgrade.snapshot.creation.successfull.txt)
[After Upgrade snapshot error.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2490907/After.Upgrade.snapshot.error.txt)
[Before upgrade.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2490908/Before.upgrade.txt)
[Snapshot creation successfull syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2490910/Snapshot.creation.successfull.syslog.txt)
[2.1 syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2490924/2.1.syslog.txt)
[Upgrade syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2490925/Upgrade.syslog.txt)

**Comment by nilangekarss** [comment]
@sandesh-desai thanks I will look into it

**Comment by sandesh-desai** [comment]
@nilangekarss : As per request uploaded latest log file.
[Latest Logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2491297/Latest.Logs.txt)

**Comment by nilangekarss** [comment]
@sandesh-desai The title of this bug is no more relevant. We can see the snap_cpg and cpg filed during inspect of a volume. But snapshot creation fails with an upgraded plugin and older volume. Fix for this issue should also fix bug #378.

**Comment by sandesh-desai** [comment]
@nilangekarss : snap_cpg and cpg filed during inspect of a volume but snap_cpg shows "null" instead of CPG name.
Attaching the logs:
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2506007/Docker.output.txt)

**Comment by nilangekarss** [comment]
[snapAfterUpgradeFrom2_1 to 3_0.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2514336/snapAfterUpgradeFrom2_1.to.3_0.txt)

**Comment by sandesh-desai** [comment]
Verified and closed.
Attaching the logs.


[bug-369-syslog.1.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2519023/bug-369-syslog.1.txt)
[bug-369-syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2519024/bug-369-syslog.txt)
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2519016/Docker.output.txt)
