### ISSUE TITLE
Docker EE 2.0 (UCP) : Error in creating snapshot and clone, getting error because of mountConflictDelay parameter

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#372]
1. Created the SC and PVC - both created successfully and volume is listed in docker volume ls as

root@cssosbe03-b04:/home/stack# docker volume ls
DRIVER              VOLUME NAME
hpe                 sc-test-6-ae9d3cd9-d2b7-11e8-a0ae-0242ac110010

2. Created SC for clone operation with following details

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name:  sc-test-6c
provisioner: hpe.com/hpe
parameters:
  cloneOf: sc-test-6-ae9d3cd9-d2b7-11e8-a0ae-0242ac110010

Got following error in Doryd logs -

07:06:01 provisioner.go:147: send: skipping 7472c708-d2b1-11e8-a0ae-0242ac110010, not in map
07:06:03 provisioner.go:237: statusLogger: provision chains=1, delete chains=0, parked chains=0, ids tracked=1, connection=valid
07:06:08 provisioner.go:237: statusLogger: provision chains=1, delete chains=0, parked chains=0, ids tracked=1, connection=valid
07:06:11 client.go:126: request: action=POST path=http://unix/VolumeDriver.Create payload={"Name":"sc-test-6c-4354f637-d2c5-11e8-a0ae-0242ac110010","Opts":{"cloneOf":"sc-test-6-ae9d3cd9-d2b7-11e8-a0ae-0242ac110010","mountConflictDelay":30,"size":16}}
07:06:11 client.go:168: response: 200 OK, length=-1
07:06:11 dockervol.go:267: unable to create docker volume using sc-test-6c-4354f637-d2c5-11e8-a0ae-0242ac110010 & map[mountConflictDelay:30 cloneOf:sc-test-6-ae9d3cd9-d2b7-11e8-a0ae-0242ac110010 size:16] - Invalid input received: Invalid option(s) ['mountConflictDelay'] specified for operation clone volume. Please check help for usage.
07:06:11 provisioner.go:520: failed to create docker volume, error = Invalid input received: Invalid option(s) ['mountConflictDelay'] specified for operation clone volume. Please check help for usage.
07:06:13 provisioner.go:237: statusLogger: provision chains=1, delete chains=0, parked chains=0, ids tracked=1, connection=valid
07:06:18 provisioner.go:237: statusLogger: provision chains=1, delete chains=0, parked chains=0, ids tracked=1, connection=valid

Similar behavior seen while creating snapshot.

**Comment by dockerciuser** [comment]
@wdurairaj @imran-ansari , still not able to import the volume.

04:11:06 client.go:126: request: action=POST path=http://unix/VolumeDriver.Create payload={"Name":"sc-import-vol-a055bd6f-db51-11e8-a0ae-0242ac110010","Opts":{"importVol":"tushar-2","mountConflictDelay":30}}
04:11:06 client.go:168: response: 200 OK, length=-1
04:11:06 dockervol.go:267: unable to create docker volume using sc-import-vol-a055bd6f-db51-11e8-a0ae-0242ac110010 & map[importVol:tushar-2 mountConflictDelay:30] - ['importVol', 'mountConflictDelay'] cannot be  specified at the same time
04:11:06 provisioner.go:520: failed to create docker volume, error = ['importVol', 'mountConflictDelay'] cannot be  specified at the same time

Create snapshot and Clone is working fine.

**Comment by imran-ansari** [comment]
Though it was allowed to have mountConflictDelay with importVol in request_validator, however, after crossing this validation layer, there is another level of check - redundant now - only for importVol which doesn't allow any option except for backend.
This has been fixed in the PR https://github.com/hpe-storage/python-hpedockerplugin/pull/388 for which the review and approval process is complete. 
@wdurairaj - request you to merge this PR.

**Comment by dockerciuser** [comment]
Verified the clone, snapshot and import vol and snapshot scheduling. All are working fine in kubernetes setup. Closing the bug.
