### ISSUE TITLE
Upgrade Scenario Testing:After plugin upgrade not able to create a volume if cpg and snapcpg is different in hpe.conf

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#373]
Upgrade Scenario Testing:After plugin upgrade not able to create a volume if  if cpg and snapcpg is different in hpe.conf

Testbed Details:
Host:192.168.68.45
Host OS: Ubuntu Release: 16.04
Docker Version: 17.06.2-ee-16
3PAR array: 192.168.67.5 [DEFAULT]

Steps perform:

1) Install old plugin 2.1 successfully.
sudo docker plugin install hpestorage/hpedockervolumeplugin:2.1 --grant-all-permissions --disable --alias hpe
2) Create a volume successfully.
3) Make changes in hpe.conf as below
   hpe3par_cpg = SD_1
   hpe3par_snapcpg = SD_2 ( is in Domain)
4) Upgrade the latest plugin successfully.
    enable the plugin 
5) Create a volume it gives and error as below:
root@cssosbe03-b15:~# docker volume create -d hpe --name=AA -o size=10
Error response from daemon: create AA: Invalid input received: Error: User CPG is in domain -,but snp CPG is in domain SUPER

[docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2494783/docker.output.txt)
[Volume create error.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2494785/Volume.create.error.txt)

**Comment by imran-ansari** [comment]
This I think is expected behavior and not a bug as the CPGs specified belong to different domains.

Attempt to create VV via 3PAR CLI using SD1 and SD2 as CPGs confirms it: 

```sh
CSSOS-SSA05 cli% createvv -snp_cpg SD_2 SD_1 test_vv 1
Everything must be in the same domain to perform this operation.
Objects belonging to no domain and to SUPER were specified.
```

**Comment by sandesh-desai** [comment]
As per the above input this is expected behavior closing the bug.
