### ISSUE TITLE
Upgrade Scenario Testing:After plugin upgrade from 2.1 to latest able to import a volume from a CPG which is in a different domain

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#375]
Upgrade Scenario Testing:After plugin upgrade able to import a volume from a CPG which is in DOMAIN

Testbed Details:
Host:192.168.68.45
Host OS: Ubuntu Release: 16.04
Docker Version: 17.06.2-ee-16
3PAR array: 192.168.67.5 [DEFAULT]

Steps perform:

1) Install old plugin 2.1 successfully.
   sudo docker plugin install hpestorage/hpedockervolumeplugin:2.1 --grant-all-permissions --disable -- 
    alias hpe
2) Make changes in hpe.conf as below
hpe3par_cpg = SD_1 -- (Not in Domain)
hpe3par_snapcpg = SD_2 ( In Domain = SUPER)
3) Create a volume in (hpe3par_snapcpg = SD_2)  in 3PAR (192.168.67.5) successfully.
    createvv SD_2 GALAXY2 10g
4) Upgrade the latest plugin successfully.
5) Import the volume GALAXY2
    docker volume create -d hpe --name=import-GALAXY2 -o importVol=GALAXY2
6) Inspect  volume import-GALAXY2 shows:
   root@cssosbe03-b15:~# docker volume inspect import-GALAXY2
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/8a75b82ea1c6bcc9e342b4b7680599fe543cd5b6b693547f0604cb17ef46fe00/rootfs",
        "Name": "import-GALAXY2",
        "Options": {
            "importVol": "GALAXY2"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-OocZMuN.TyenhOI21i.S4g",
                "backend": "DEFAULT",
                "compression": null,
                **"cpg": "SD_2"**,
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "full",
                "size": 10,
                **"snap_cpg": "SD_2"**
            }
        }
    }
]

ERROR : Volume should not import as snapcpg is in DOMAIN.
              Also inspect volume shows cpg": "SD_2 and snap_cpg": "SD_2

Attaching the logs:
[3PAR Output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2495691/3PAR.Output.txt)
[docker ouput.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2495692/docker.ouput.txt)
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2495693/hpe.conf.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2495694/Syslog.txt)

**Comment by imran-ansari** [comment]
After discussion with @nilangekarss, it seems that this behavior must be allowed as long as 3PAR allows it for a particular user who has access to the domains involved. However, this calls for adding domain information in response to Docker inspect command for the benefit of the user. From that perspective, we can continue to have this issue as a valid issue probably with appropriate change in the title.

**Comment by sandesh-desai** [comment]
Verified and closed.
Attaching the logs.
[3PAR Output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2533056/3PAR.Output.txt)
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2533057/Docker.output.txt)
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2533058/hpe.conf.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2533059/Syslog.txt)
[with cpg option.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2533060/with.cpg.option.txt)
