### ISSUE TITLE
Docker 3.0: Secured ETCD: Volume Mount operation fails

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#379]
Note: Though all LUN entries cleaned up using 
**for i in `lsscsi | grep 3PARdata | awk '{print $6}'| grep -v "-"| cut -d"/" -f3`; do  echo $i;  echo 1 > /sys/block/$i/device/delete; done**
and 
**rescan-scsi-bus.sh -r -f -m**
mount operation failed.

**Testbed Details:**
Host:192.168.80.1 - Secured ETCD
Host OS: CentOS Linux release 7.5.1804 (Core)
Docker Version: 17.06.2-ee-16
3PAR array: 192.168.67.7 & 192.168.67.5 Replication [DEFAULT]
192.168.67.2 [3PAR]

**Before creating and mounting volume.
No hosts entries on docker host.**

[root@CSSOSBE02-B10 ~]# docker volume ls
DRIVER              VOLUME NAME
[root@CSSOSBE02-B10 ~]# date:ls -lrt /dev/disk/by-path
-bash: date:ls: command not found
[root@CSSOSBE02-B10 ~]# date;ls -lrt /dev/disk/by-path
Mon Oct 22 06:12:16 EDT 2018
total 0
lrwxrwxrwx. 1 root root 10 Oct 22 04:36 pci-0000:07:00.0-scsi-0:1:0:0-part3 -> ../../sda3
lrwxrwxrwx. 1 root root 10 Oct 22 04:36 pci-0000:07:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx. 1 root root 10 Oct 22 04:36 pci-0000:07:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx. 1 root root  9 Oct 22 04:36 pci-0000:07:00.0-scsi-0:1:0:0 -> ../../sda
[root@CSSOSBE02-B10 ~]# docker container ls -a^C
[root@CSSOSBE02-B10 ~]# docker volume ls
DRIVER              VOLUME NAME

**No volumes and hosts on Primary as well as secondary arrays.**

CSSOS-SSA04 cli% showhost CSSOSBE02-B10
no hosts listed
CSSOS-SSA04 cli%
CSSOS-SSA04 cli%
CSSOS-SSA04 cli% showvv -cpg SHASHI-PRIM
no vv listed
CSSOS-SSA04 cli% showvv -cpg SHASHI-PRIM-SNAP
no vv listed

CSSOS-SSA05 cli% showhost CSSOSBE02-B10
no hosts listed
CSSOS-SSA05 cli%
CSSOS-SSA05 cli%
CSSOS-SSA05 cli% showvlun -host CSSOSBE02-B10
Active VLUNs
Invalid host name: CSSOSBE02-B10
CSSOS-SSA05 cli% showvv -cpg SHASHI-SEC
no vv listed
CSSOS-SSA05 cli% showvv -cpg SHASHI-SEC-SNAP
no vv listed
CSSOS-SSA05 cli%

**Perform Create and mount operation.
Error on docker server.**

[root@CSSOSBE02-B10 ~]# docker volume create -d hpe --name test-volume -o size=200 -o provisioning=full -o replicationGroup=shashi-group
test-volume
[root@CSSOSBE02-B10 ~]# docker run -it -v test-volume:/Data --volume-driver hpe --name mount --rm busybox /bin/sh
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8/rootfs': Post http://%2Frun%2Fdocker%2Fplugins%2Fa1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8%2Fhpe.sock/VolumeDriver.Mount: net/http: request canceled (Client.Timeout exceeded while awaiting headers).
[root@CSSOSBE02-B10 ~]#

**Despite above error, volume and host created successfully on Primary 3par.**

CSSOS-SSA04 cli% showvv -cpg SHASHI-PRIM
                                                                                        -Rsvd(MiB)- -(MiB)-
   Id Name                       Prov Compr Dedup Type CopyOf  BsId Rd -Detailed_State- Snp     Usr   VSize
14465 dcv-CIHAbyEzTMq1mqV1fJ-fcw cpvv NA    NA    base ---    14465 RW normal           512  204800  204800
-----------------------------------------------------------------------------------------------------------
    1 total                                                                             512  204800  204800
CSSOS-SSA04 cli% showvlun -v dcv-CIHAbyEzTMq1mqV1fJ-fcw
Active VLUNs
no vluns listed

VLUN Templates
Lun VVName                     HostName      -Host_WWN/iSCSI_Name-  Port        Type
  0 dcv-CIHAbyEzTMq1mqV1fJ-fcw CSSOSBE02-B10 ----------------      0:2:1 matched set
  0 dcv-CIHAbyEzTMq1mqV1fJ-fcw CSSOSBE02-B10 ----------------      1:2:1 matched set
------------------------------------------------------------------------------------
  2 total
CSSOS-SSA04 cli%

Remote copy group on primary

CSSOS-SSA04 cli% showrcopy groups shashi-group

Remote Copy System Information
Status: Started, Normal

Group Information

Name         Target      Status   Role       Mode     Options
shashi-group CSSOS-SSA05 Started  Primary    Sync
  LocalVV                     ID   RemoteVV                    ID   SyncStatus    LastSyncTime
  dcv-CIHAbyEzTMq1mqV1fJ-fcw 14465 dcv-CIHAbyEzTMq1mqV1fJ-fcw 36717 Synced        NA

CSSOS-SSA04 cli%

Remote copy group on secondary

CSSOS-SSA05 cli% showrcopy groups shashi*

Remote Copy System Information
Status: Started, Normal

Group Information

Name                 Target      Status   Role       Mode     Options
shashi-group.r121649 CSSOS-SSA04 Started  Secondary  Sync
  LocalVV                     ID   RemoteVV                    ID   SyncStatus    LastSyncTime
  dcv-CIHAbyEzTMq1mqV1fJ-fcw 36717 dcv-CIHAbyEzTMq1mqV1fJ-fcw 14465 Synced        NA

CSSOS-SSA05 cli%
[REPLIVOL-MOUNT.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2501119/REPLIVOL-MOUNT.txt)

**Comment by prablr79** [comment]
verified in the Troubleshooting section. and updated Limitation as well.
