### ISSUE TITLE
Docker engine is repeatedly attempting to initialize HPE plugin in case if the etcd is down.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#38]
Install plugin, stop etcd and observe logs.

Or else install hpe volume plugin v2 without starting etcd container.

Docker engine is repeatedly attempting to connect HPE plugin and it says "Connection refused" everytime. This keeps CPU busy. 

Please find the logs in the attachments.
[restart_logs.zip](https://github.com/hpe-storage/python-hpedockerplugin/files/1058194/restart_logs.zip)

.

**Comment by atotala** [comment]
In case of managed plugin, docker engine makes plugin keep on retrying till the time plugin doesn't start running successfully. 
After starting of etcd, plugin initialization will be successful and docker engine stops retrying.

**Comment by imran-ansari** [comment]
Once we have "restart" policy set to "always" this issue should get resolved.
A similar issue https://github.com/hpe-storage/python-hpedockerplugin/issues/189 was raised that has some comments as to how to set "restart" policy for existing deployments.
This can be closed once fix for the issue #189 is validated.

**Comment by imran-ansari** [comment]
#189 has been verified and closed. Hence closing this one too.
