### ISSUE TITLE
Upgrade Scenario Testing:After upgrade from 2.1 to latest plugin,Not able to enable the plugin.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#380]
Upgrade Scenario Testing:After upgrade from 2.1 to latest plugin,Not able to enable the plugin.After changing DEFAULT hpe3par_snapcpg, plugin enable successfully.

Testbed Details:
Host:192.168.68.45
Host OS: Ubuntu Release: 16.04
Docker Version: 17.06.2-ee-16
3PAR array: 192.168.67.5 [DEFAULT] 15.212.192.252[3par1] and 192.168.67.2[3par11]

Steps perform:
1) In hpe.conf, 3PAR array mention as 192.168.67.5 [DEFAULT] 15.212.192.252[3par1] and 
    192.168.67.2[3par11]
    hpe3par_cpg = SD_1
    hpe3par_snapcpg = SUPER
2) Install old plugin 2.1 successfully.
3) Enable the plugin successfully.
3) Create a volume.
4) Upgrade the latest plugin successfully.
5) While enabling the plugin it gives an below error:
     root@cssosbe03-b15:~# docker plugin enable hpe
Error response from daemon: dial unix /run/docker/plugins/7464ef41f37cb5cd55fdb51a68518807998a824fb5c92852a73ff928b822b9ac/hpe.sock: connect: no such file or directory

6) Make changes in hpe3par_snapcpg as SD_1 earlier it was hpe3par_snapcpg = SUPER
7) Now enable the plugin successfully.

Attaching the logs.
[After upgrade hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2501284/After.upgrade.hpe.conf.txt)
[Before upgrade hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2501285/Before.upgrade.hpe.conf.txt)

**Comment by sandesh-desai** [comment]
Attaching Syslog

[upgrade.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2517647/upgrade.txt)

**Comment by nilangekarss** [comment]
@wdurairaj @sandesh-desai Having multiple back ends in 2.1 plugin is not a valid use case.
Can you try adding multiple back ends in hpe.conf after upgrading to 3.0 ? If you still face the same issue i will have a look at it. Else, this can be closed as not valid scenario. I would like William to give his say on this.

**Comment by sandesh-desai** [comment]
@nilangekarss  Yes,Able to add multiple back ends in hpe.conf after upgrading to 3.0.

**Comment by wdurairaj** [comment]
@sandesh-desai , if you are upgrading the plugin from 2.1 to 3.x the assumption should be use only DEFAULT backend. After the upgrade process is complete, you can add further backends to the hpe.conf.

**Comment by sandesh-desai** [comment]
As per the above comment by @wdurairaj  only DEFAULT backend should be use while upgrading from 2.1 to 3.X.
Hence closing the bug.
