### ISSUE TITLE
Snapshot Schedule: Despite error on docker, schedule created on backend.

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#381]
While creating snapshot schedule, docker shows an error but schedule is created on 3PAR backend

Testbed Details:
Host:192.168.80.1 - Secured ETCD
Host OS: CentOS Linux release 7.5.1804 (Core)
Docker Version: 17.06.2-ee-16
3PAR array: 192.168.67.7 & 192.168.67.5 Replication [DEFAULT]
192.168.67.2 [3PAR]

Step wise execution  

**1. TRY TO CREATE VOLUME WITHOUT REPLICATIONGROUP, TO SEE EXPECTED ERROR MESSAGE**

[root@CSSOSBE02-B10 ~]# docker volume create -d hpe --name volume -o size=30 -o provisioning=full
Error response from daemon: create volume: Invalid input received: Request to create replicated volume cannot be fulfilled without specifying 'replicationGroup' option in the request. Please specify 'replicationGroup' and execute the request again.

**2. NOW CREATE VOLUME ON AN ADDIITIONAL BACKEND SET IN HPE.CONF**

[root@CSSOSBE02-B10 ~]# docker volume create -d hpe --name volume -o size=30 -o provisioning=full -o backend=3PAR
volume

**3. CREATE SNAPSHOT SCHEDULE WITH BACKEND OPTION TO SEE THE EXPECTED ERROR.**

[root@CSSOSBE02-B10 ~]# docker volume create -d hpe --name snap-volume -o size=30 -o provisioning=full -o backend=3PAR -o virtualCopyOf=volume -o scheduleName=snap-sched -o scheduleFrequency="30 * * * *" -o snapshotPrefix=GFD
Error response from daemon: create snap-volume: Invalid input received: Invalid option(s) ['backend', 'provisioning', 'size'] specified for operation create snapshot schedule. Please check help for usage.

**4. CREATE SNAPSHOT SCHEDULE WITHOUT BACKEND OPTION TO SEE TIMEOUT ERROR BELOW.**

[root@CSSOSBE02-B10 ~]# docker volume create -d hpe --name snap-volume -o virtualCopyOf=volume -o scheduleName=snap-sched -o scheduleFrequency="30 * * * *" -o snapshotPrefix=GFD
Error response from daemon: create snap-volume: Post http://%2Frun%2Fdocker%2Fplugins%2Fa1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8%2Fhpe.sock/VolumeDriver.Create: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
[root@CSSOSBE02-B10 ~]#

**5. DESPITE ERROR WE CAN SEE SCHEDULE CREATED ON 3PAR BACKEND**

CB2111_67_2 cli% showsched
                                                                         ------ Schedule ------
SchedName  File/Command                                                  Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime
snap-sched createsv -f GFD.@y@@m@@d@@H@@M@@S@ dcv-oasRuUkySUeEaAYO-7UBNQ  30    *   *     *   * 3paradm   active     Y 2018-10-22 17:30:00 IST
----------------------------------------------------------------------------------------------------------------------------------------------
1          total

**ATTACHING DOCKER LOG WHICH WAS CAPTURED WHILE EXECUTING ABOVE STEPS**

[sched.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2504475/sched.txt)

**Comment by sonawane-shashikant** [comment]
Additional Comments below from @wdurairaj 

Create snapshot workflow, where 2 createsched is done with identical set of parameters in 3PAR.

@nilangekarss  i do see the `createsched` is called twice on the create snapshot with schedule workflow
```
Oct 22 08:22:05 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:05-04:00" level=info msg="2018-10-22 12:22:05.908 15 DEBUG hpedockerplugin.etcdutil [-] Name is locked : snapshot_of_3par1_vol1 try_lock_name /python-hpedockerplugin/hpedockerplugin/etcdutil.py:189\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:05 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:05-04:00" level=info msg="2018-10-22 12:22:05.908 15 INFO hpedockerplugin.synchronization [-] Lock acquired: [caller=create_snapshot, lock-name=snapshot_of_3par1_vol1]\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:05 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:05-04:00" level=info msg="2018-10-22 12:22:05.909 15 DEBUG etcd.client [-] Issuing read for key /volumes/ with args {'recursive': True} read /usr/lib/python3.6/site-packages/python_etcd-0.4.5-py3.6.egg/etcd/client.py:582\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:05 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:05-04:00" level=info msg="2018-10-22 12:22:05.910 15 INFO hpedockerplugin.etcdutil [-] Get volbyname: volname is snapshot_of_3par1_vol1\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:05 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:05-04:00" level=info msg="2018-10-22 12:22:05.911 15 DEBUG hpedockerplugin.etcdutil [-] Try locking name 3par1_vol1 try_lock_name /python-hpedockerplugin/hpedockerplugin/etcdutil.py:186\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
----------------------------------------------------------------------
Oct 22 08:22:16 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:16-04:00" level=info msg="2018-10-22 12:22:16.240 15 DEBUG paramiko.transport [-] userauth is OK _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/transport.py:1687\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.262 15 INFO paramiko.transport [-] Authentication (password) successful!\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.263 15 DEBUG paramiko.transport [-] [chan 0] Max packet in: 32768 bytes _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.269 15 DEBUG paramiko.transport [-] [chan 0] Max packet out: 32768 bytes _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.269 15 DEBUG paramiko.transport [-] Secsh channel 0 opened. _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/transport.py:1687\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.273 15 DEBUG paramiko.transport [-] [chan 0] Sesch channel 0 request ok _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.275 15 DEBUG paramiko.transport [-] [chan 0] Sesch channel 0 request ok _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.692 15 DEBUG paramiko.transport [-] [chan 0] EOF received (0) _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.693 15 DEBUG paramiko.transport [-] [chan 0] EOF sent (0) _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.694 15 DEBUG hpedockerplugin.hpe.hpe_3par_common [-] Disconnect from 3PAR REST and SSH e517b167-c460-42f1-b166-40d42dbd5603 client_logout /python-hpedockerplugin/hpedockerplugin/hpe/hpe_3par_common.py:184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="REQ: curl -i https://192.168.67.2:8080/api/v1/credentials/0-4e78f63d5973b3e51439148223d05fec-78c2cd5b DELETE -H \"X-Hp3Par-Wsapi-Sessionkey: 0-4e78f63d5973b3e51439148223d05fec-78c2cd5b\" -H \"User-Agent: python-3parclient\" -H \"Accept: application/json\"" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.694 15 DEBUG hpe3parclient.http [-] " plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
----------------------------------------------------------------------
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.901 15 INFO hpedockerplugin.hpe.hpe_3par_common [-] Creating a snapshot schedule, command is ['createsched', '\"createsv -f xyz.@y@@m@@d@@H@@M@@S@ dcv-ZoEo-xUoSiyZejHmKojeyw\"', '\"0 0,12 * * *\"', 'dummy_schedule', '\\r']...\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:37 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:37-04:00" level=info msg="2018-10-22 12:22:37.072 15 DEBUG paramiko.transport [-] userauth is OK _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/transport.py:1687\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.093 15 INFO paramiko.transport [-] Authentication (password) successful!\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.094 15 DEBUG paramiko.transport [-] [chan 0] Max packet in: 32768 bytes _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.100 15 DEBUG paramiko.transport [-] [chan 0] Max packet out: 32768 bytes _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.100 15 DEBUG paramiko.transport [-] Secsh channel 0 opened. _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/transport.py:1687\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.104 15 DEBUG paramiko.transport [-] [chan 0] Sesch channel 0 request ok _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.106 15 DEBUG paramiko.transport [-] [chan 0] Sesch channel 0 request ok _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.680 15 DEBUG paramiko.transport [-] [chan 0] EOF received (0) _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.681 15 DEBUG paramiko.transport [-] [chan 0] EOF sent (0) _log /usr/lib/python3.6/site-packages/paramiko-2.4.1-py3.6.egg/paramiko/channel.py:1184\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.683 15 INFO hpedockerplugin.hpe.hpe_3par_common [-] Created a snapshot schedule - command is: ['createsched', '\"createsv -f xyz.@y@@m@@d@@H@@M@@S@ dcv-ZoEo-xUoSiyZejHmKojeyw\"', '\"0 0,12 * * *\"', 'dummy_schedule', '\\r']...\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
```
first create schedule is at 
```
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.901 15 INFO hpedockerplugin.hpe.hpe_3par_common [-] Creating a snapshot schedule, command is ['createsched', '\"createsv -f xyz.@y@@m@@d@@H@@M@@S@ dcv-ZoEo-xUoSiyZejHmKojeyw\"', '\"0 0,12 * * *\"', 'dummy_schedule', '\\r']...\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
```
second create schedule is at 
```
Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.683 15 INFO hpedockerplugin.hpe.hpe_3par_common [-] Created a snapshot schedule - command is: ['createsched', '\"createsv -f xyz.@y@@m@@d@@H@@M@@S@ dcv-ZoEo-xUoSiyZejHmKojeyw\"', '\"0 0,12 * * *\"', 'dummy_schedule', '\\r']...\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8
```
Can you try to see what is the issue ?

**Comment by nilangekarss** [comment]
@sonawane-shashikant @wdurairaj This looks like a timeout issue from docker.
A user is able to create the snapshot schedule at the backend but logging into the array takes longer time. 
Docker engine expects a response in a defined time frame if an engine doesn't get a response from plugin it does timeout. This is what happens here. I suggest performing this test with some another array which has lower ssh login time.
This array is taking almost 20 seconds to log in to the array from a host node normally.

**Comment by wdurairaj** [comment]
```
Oct 22 08:22:26 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:26-04:00" level=info msg="2018-10-22 12:22:26.901 15 INFO hpedockerplugin.hpe.hpe_3par_common [-] Creating a snapshot schedule, command is ['createsched', '\"createsv -f xyz.@y@@m@@d@@H@@M@@S@ dcv-ZoEo-xUoSiyZejHmKojeyw\"', '\"0 0,12 * * *\"', 'dummy_schedule', '\\r']...\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8

Oct 22 08:22:47 CSSOSBE02-B10 dockerd: time="2018-10-22T08:22:47-04:00" level=info msg="2018-10-22 12:22:47.683 15 INFO hpedockerplugin.hpe.hpe_3par_common [-] Created a snapshot schedule - command is: ['createsched', '\"createsv -f xyz.@y@@m@@d@@H@@M@@S@ dcv-ZoEo-xUoSiyZejHmKojeyw\"', '\"0 0,12 * * *\"', 'dummy_schedule', '\\r']...\x1b[00m" plugin=a1e316853eba71c304cd5faa4fefb69a1c41f3aa252fe6abe6d4f065a5d6c9f8

```
Start of the schedule creation is on timestamp: `08:22:26`
End of schedule creation is       on timestamp: `08:22:47`

Total time taken for the schedule is `21 secs`. Docker timeout is 30secs, paramiko initialization would have taken roughly `10 secs`.
So, no wonder timeout has happened.

This we will not do a code fix, but would document it as a limitation.

**Comment by imran-ansari** [comment]
@sandesh - are you able to inspect the created snapshot in this case? Does it display proper snapshot schedule details?

**Comment by sandesh-desai** [comment]
@imran-ansari -- Yes,able to inspect snapshot and it display proper schedule details.

root@cssosbe03-b15:~# docker volume inspect snap-volume
[
    {
        "Driver": "hpe:latest",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/plugins/c894307abe033ca38459f3e0c3c110ea4b7a76dc238d7d417256edf2868530f2/rootfs",
        "Name": "snap-volume",
        "Options": {},
        "Scope": "global",
        "Status": {
            "snap_detail": {
                "3par_vol_name": "dcs-v4hhOeQsQiWlWM7hb29w4Q",
                "backend": "3PAR",
                "compression": null,
                "expiration_hours": null,
                "fsMode": null,
                "fsOwner": null,
                "is_snap": true,
                "mountConflictDelay": 30,
                "parent_id": "8ec4f3ea-0402-44ba-8da6-6dcf398a8cf5",
                "parent_volume": "volume",
                "provisioning": "full",
                "retention_hours": null,
                "size": 30,
                "snap_cpg": "Test",
                "snap_schedule": {
                    "sched_frequency": "10 * * * *",
                    "sched_snap_exp_hrs": null,
                    "sched_snap_ret_hrs": null,
                    "schedule_name": "snap-sched",
                    "snap_name_prefix": "GFD"
                }
            }
        }

**Comment by imran-ansari** [comment]
Snapshot schedule creation can take more time resulting into Docker CLI timeout. However, snapshot schedule may still get created in the background.
E.g. if user executes the following command:
```sh
$ docker volume create -d hpe --name snap-volume -o virtualCopyOf=volume -o scheduleName=snap-sched -o scheduleFrequency="30 * * * *" -o snapshotPrefix=GFD
```
User can follow the below steps to verify if snapshot schedule got created:
1. Inspect the snapshot to verify if the snapshot schedule got created
docker volume inspect snap-volume. This should display *snap-volume* details with snapshot schedule information.

2. Verify if schedule got created on the array using 3PAR CLI command:
```sh
$ showsched snap-sched
```

**Comment by nilangekarss** [comment]
@imran-ansari Hi Imran, Could you please add your this observation under create snapshot schedule section as a note.

"Snapshot schedule creation can take more time resulting into Docker CLI timeout. However, snapshot schedule may still get created in the background. user can follow these two steps in case of time out issue from docker daemon while creating snapshot schedule."
1. Inspect the snapshot to verify if the snapshot schedule got created
docker volume inspect <snapshot-name>. This should display snapshot details with snapshot schedule information.

2. Verify if schedule got created on the array using 3PAR CLI command:
$ showsched <sched-name>

**Comment by prablr79** [comment]
verified in Limitation notes, hence closing this defect
