### ISSUE TITLE
LUN ID is different for every VLUN in 3par if mounting is performed on volume with multipath. 

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#39]
Enabled multipath in hpe.conf

1. Create a volume.
_stack@csimbe13-b13:~$ sudo docker volume create -d hpe --name svol1
svol1_

2. Mount this volume.
_stack@csimbe13-b13:~$ sudo docker run -it -v svol1:/data1/ --rm busybox sh_
svol1 is mounted successfully.

3. Observe vlun created in 3par.

CSIM-EOS07_1611168 cli% showvlun
Active VLUNs
Lun VVName                     HostName     --------Host_WWN/iSCSI_Name--------  Port        Type Status ID
  0 dcv-a..tqo32SYynMhU84A-4zw csimbe13-b05 iqn.1994-05.com.redhat:be258d546d5d 0:2:1 matched set active  1
  1 dcv-a..tqo32SYynMhU84A-4zw csimbe13-b05 iqn.1994-05.com.redhat:be258d546d5d 0:2:2 matched set active  1
-----------------------------------------------------------------------------------------------------------
  2 total

**Comment by hpe-storage** [comment]
Addressed as part of 1.1 plugin
