### ISSUE TITLE
Incorrect 3par volume name in docker inspect after managing existing snapshot

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#393]
I have created volume & snapshot in secondary 3par and tried to manage it through -o importVol & -o backend, volume and snapshot managed well but during docker inspect for snapshot, incorrect name of 3par volume gets populated.

3par volume name in docker inspect : "**dcv**-Wgebe8hsSuie8wkx9Bv4tA"
Actual name of managed snapshot in 3par : "**dcs**-Wgebe8hsSuie8wkx9Bv4tA"

**Below steps to re-produce :**

**3par CLI for secondary array to create volume :**
===> createvv -snp_cpg docker_cpg docker_cpg py.vol1 1
===> createsv py.vol1_snap py.vol1

**Docker CLI to manage existing volume:**
===> docker volume create -d hpe --name docker1 -o importVol=py.vol1 -o backend=backend2
===> docker volume inspect docker1
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/969535c47640a6b1bf897482592676e3e40b55491d1e215cb3d536aa515adcaa/rootfs",
        "Name": "docker1",
        "Options": {
            "backend": "backend2",
            "importVol": "py.vol1"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-kugmXta8RauScXdclSK3Ow",
                "backend": "backend2",
                "compression": null,
                "cpg": "docker_cpg",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "full",
                "size": 1,
                "snap_cpg": "docker_cpg"
            }
        }
    }
]

===> docker volume create -d hpe --name docker1_snap -o importVol=py.vol1_snap -o backend=backend2
===> docker volume inspect docker1_snap
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/969535c47640a6b1bf897482592676e3e40b55491d1e215cb3d536aa515adcaa/rootfs",
        "Name": "docker1_snap",
        "Options": {
            "backend": "backend2",
            "importVol": "py.vol1_snap"
        },
        "Scope": "global",
        "Status": {
            "snap_detail": {
                "3par_vol_name": "dcv-Wgebe8hsSuie8wkx9Bv4tA",
                "backend": "backend2",
                "compression": null,
                "expiration_hours": null,
                "fsMode": null,
                "fsOwner": null,
                "is_snap": true,
                "mountConflictDelay": 30,
                "parent_id": "92e8265e-d6bc-45ab-9271-775c9522b73b",
                "parent_volume": "docker1",
                "provisioning": "thin",
                "retention_hours": null,
                "size": 1,
                "snap_cpg": "docker_cpg"
            }
        }
    }
]

**3par CLI for secondary array to verify managed volume :**
===> CSSOS-SSA04 cli% showvv dcv-Wgebe8hsSuie8wkx9Bv4tA
no vv listed

Checked with dcs-Wgebe8hsSuie8wkx9Bv4tA
===> CSSOS-SSA04 cli% showvv dcs-Wgebe8hsSuie8wkx9Bv4tA
                                                                                                             -Rsvd(MiB)- -(MiB)-
   Id Name                       Prov Compr Dedup Type  CopyOf                      BsId Rd -Detailed_State-   Snp   Usr   VSize
24529 dcs-Wgebe8hsSuie8wkx9Bv4tA snp  NA    NA    vcopy dcv-kugmXta8RauScXdclSK3Ow 24516 RW normal              --    --     256
--------------------------------------------------------------------------------------------------------------------------------
    1 total

**Comment by nilangekarss** [comment]
@virendra-sharma Hi Virendra, have u created py.vol1 py.vol1_snap volume and snapshots respectively?
I do see you have imported the volume correctly.
docker volume create -d hpe --name docker1 -o importVol=py.vol1 -o backend=backend2
Now, while importing the snapshot you have used the same command only different name(you should have imported a snapshot).
docker volume create -d hpe --name docker1_snap -o importVol=py.vol1 -o backend=backend2

If a volume is imported the name of a volume on 3PAR change and starts with dcv-*

I was expecting an error when you import non-existing volume py.vol1 to docker environment but I do not see it here. Can you please check this again?

**Comment by virendra-sharma** [comment]
@nilangekarss Hi Swapnil, Sorry, it was typo and steps are corrected now.

I was expecting an error when you import non-existing volume py.vol1 to docker environment but I do not see it here. Can you please check this again?

Yes, but I wrongly missed "_snap" while copy, paste in github from import snapshot command.

**Comment by nilangekarss** [comment]
It's a valid bug, thanks for the detailed log I have looked into it.

**Comment by wdurairaj** [comment]
Nice bug Virendra :+1:

**Comment by wdurairaj** [comment]
i believe we don't distinguish between snapshot/volume during the import process.

Problem lies https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/hpedockerplugin/volume_manager.py#L356 

This line `vol = volume.createvol(volname)` , assumes `is_snap` to False, and hence the `dcv` prefix is done for volume name computation in `volume.py`

Fix should be done by detecting if the imported object is a snapshot/volume and pass the `is_snap` in the `volume.createvol()` call appropriately.

**Comment by nilangekarss** [comment]
Please review the pull request https://github.com/hpe-storage/python-hpedockerplugin/pull/395
I have verified the following scenario by creating a build with changed code.

```
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker plugin install nilangekarswapnil/python-hpedockerplugin:fix393 --alias hpe --disable
Plugin "nilangekarswapnil/python-hpedockerplugin:fix393" is requesting the following privileges:
 - network: [host]
 - mount: [/dev]
 - mount: [/run/lock]
 - mount: [/var/lib]
 - mount: [/etc]
 - mount: [/var/run/docker.sock]
 - mount: [/root/.ssh]
 - mount: [/sys]
 - mount: [/root/plugin/certs]
 - mount: [/sbin/iscsiadm]
 - mount: [/lib/modules]
 - mount: [/lib/x86_64-linux-gnu]
 - allow-all-devices: [true]
 - capabilities: [CAP_SYS_ADMIN CAP_SYS_RESOURCE CAP_MKNOD CAP_SYS_MODULE]
Do you grant the above permissions? [y/N] y
fix393: Pulling from nilangekarswapnil/python-hpedockerplugin
bd833c2098a3: Download complete
Digest: sha256:91b07107fe556e87122a7335389985e5cf58776d544469f0093998c49a467bb0
Status: Downloaded newer image for nilangekarswapnil/python-hpedockerplugin:fix393
Installed plugin nilangekarswapnil/python-hpedockerplugin:fix393
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker plugin ls
ID                  NAME                                         DESCRIPTION                    ENABLED
5fc67936db72        hpe:latest                                   HPE Docker Volume Plugin       false
fa0cde7bec8c        docker/telemetry:1.0.0.linux-x86_64-stable   Docker Inc. metrics exporter   true
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker plugin set hpe certs.source=/tmp
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker plugin enable 5fc67936db72
5fc67936db72
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker plugin ls
ID                  NAME                                         DESCRIPTION                    ENABLED
5fc67936db72        hpe:latest                                   HPE Docker Volume Plugin       true
fa0cde7bec8c        docker/telemetry:1.0.0.linux-x86_64-stable   Docker Inc. metrics exporter   true


CSSOS-SSA04 cli% createvv -snp_cpg docker_cpg docker_cpg swap363vol 5
CSSOS-SSA04 cli% showvv swap363vol
                                                                        -Rsvd(MiB)- -(MiB)-
   Id Name       Prov Compr Dedup Type CopyOf  BsId Rd -Detailed_State-   Snp   Usr   VSize
40554 swap363vol cpvv NA    NA    base ---    40554 RW normal             256   256     256
-------------------------------------------------------------------------------------------
    1 total                                                               256   256     256
CSSOS-SSA04 cli% createsv swap363vol_snap swap363vol
CSSOS-SSA04 cli% showvv swap363vol_snap
                                                                                  -Rsvd(MiB)- -(MiB)-
   Id Name            Prov Compr Dedup Type  CopyOf      BsId Rd -Detailed_State-   Snp   Usr   VSize
40557 swap363vol_snap snp  NA    NA    vcopy swap363vol 40554 RW normal              --    --     256
-----------------------------------------------------------------------------------------------------
    1 total                                                                           0     0     256
CSSOS-SSA04 cli% exit
Connection to 192.168.67.7 closed.
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker volume create -d hpe --name -o importVol=swap363vol
Conflicting options: either specify --name or provide positional arg, not both

root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker volume create -d hpe --name impswapvol -o importVol=swap363vol
impswapvol
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker volume ls
DRIVER              VOLUME NAME
hpe:latest          impswapvol
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker volume inspect impswapvol
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/5fc67936db729b97d033fe884c478887a84e532f564384dbb61f99067ceb9cbd/rootfs",
        "Name": "impswapvol",
        "Options": {
            "importVol": "swap363vol"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-74ilDLsgSB6rNxdeV8mW4Q",
                "backend": "DEFAULT",
                "compression": null,
                "cpg": "docker_cpg",
                "domain": "test_domain",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "full",
                "size": 1,
                "snap_cpg": "docker_cpg"
            }
        }
    }
]
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker volume ls
DRIVER              VOLUME NAME
hpe:latest          impswapvol
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker volume create -d hpe --name impswapvol_snap -o importVol=swap363vol_snap
impswapvol_snap
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker volume ls
DRIVER              VOLUME NAME
hpe:latest          impswapvol
hpe:latest          impswapvol_snap
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# docker volume inspect impswapvol_snap
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/5fc67936db729b97d033fe884c478887a84e532f564384dbb61f99067ceb9cbd/rootfs",
        "Name": "impswapvol_snap",
        "Options": {
            "importVol": "swap363vol_snap"
        },
        "Scope": "global",
        "Status": {
            "snap_detail": {
                "3par_vol_name": "dcs-TsxOwSGeQU62XMzjYaTdSQ",
                "backend": "DEFAULT",
                "compression": null,
                "expiration_hours": null,
                "fsMode": null,
                "fsOwner": null,
                "is_snap": true,
                "mountConflictDelay": 30,
                "parent_id": "ef88a50c-bb20-481e-ab37-175e57c996e1",
                "parent_volume": "impswapvol",
                "provisioning": "thin",
                "retention_hours": null,
                "size": 1,
                "snap_cpg": "docker_cpg"
            }
        }
    }
]
root@administrator-ProLiant-BL460c-Gen9:~/plugin_code/forkedrepo/python-hpedockerplugin# ssh 3paradm@192.168.67.7
3paradm@192.168.67.7's password:
CSSOS-SSA04 cli% showvv "dcs-TsxOwSGeQU62XMzjYaTdSQ"
                                                                                                             -Rsvd(MiB)- -(MiB)-
   Id Name                       Prov Compr Dedup Type  CopyOf                      BsId Rd -Detailed_State-   Snp   Usr   VSize
40557 dcs-TsxOwSGeQU62XMzjYaTdSQ snp  NA    NA    vcopy dcv-74ilDLsgSB6rNxdeV8mW4Q 40554 RW normal              --    --     256
--------------------------------------------------------------------------------------------------------------------------------
    1 total                                                                                                      0     0     256
CSSOS-SSA04 cli% showvv swap*
no vv listed
CSSOS-SSA04 cli% ~
```

**Comment by sandesh-desai** [comment]
Verified and working as per expectation.
Attaching the logs.
[3PAR output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2547160/3PAR.output.txt)
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2547161/Docker.output.txt)
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2547162/hpe.conf.txt)
[Syslog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2547163/Syslog.txt)

**Comment by virendra-sharma** [comment]
As per above comment & verification from automation script, closing this issue. issue has been fixed and verified.
