### ISSUE TITLE
Kubernetes : The optional parameters are not displayed in "Options" section docker volume inspect 

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#394]
If the volume is created in kubernetes environment the "Options" field of docker volume inspect is blank.
Whereas in case of plane docker volume plugin it is displayed.

Example : 
1. volume created with docker volume plugin - 

root@cssosbe02-b12:/home/stack/tushar/python-hpedockerplugin/tests/integration# docker volume inspect docker_699c0215
[
    {
        "Driver": "dockerciuser/hpedockerplugin:test",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/plugins/469af071de941e9e9b21e6436c40b393a436ef69cbe59d0699f33ca84143d0b5/rootfs",
        "Name": "docker_699c0215",
        "Options": {
           **"importVol": "python_vol_8"**
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-H5vgExn0Si2CPp1T2cVzaQ",
                "backend": "DEFAULT",
                "compression": null,
                "cpg": "Docker_CI",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "full",
                "size": 1,
                "snap_cpg": "Docker_CI"
            }
        }
    }
]

2. Volume created on kubernetes environment - 

[root@CSSOSBE03-B11 new_yaml]# docker volume inspect sc-import-vol-bbeaa0eb-dc09-11e8-a0ae-0242ac110010
\[
    {
        "Driver": "hpe",
        "Labels": null,
        "Mountpoint": "/",
        "Name": "sc-import-vol-bbeaa0eb-dc09-11e8-a0ae-0242ac110010",
        **"Options": {},**
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-wWkxEZ8aTmK3Biy3EYfIEA",
                "backend": "DEFAULT",
                "compression": null,
                "cpg": "FC_r6",
                "domain": null,
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "full",
                "size": 2,
                "snap_cpg": "FC_r6"
            }
        }
    }
]

**Comment by nilangekarss** [comment]
@dockerciuser @prablr79 @wdurairaj This is a correct behavior as long as Status field is showing same data we will not be worried. An options field will populate these values only when inspect is used on the same node where docker volume is created on the same node and depends on docker cli commands. In the case of K8S dory/doryd invokes docker API internally hence this behavior.

**Comment by nilangekarss** [comment]
@prablr79 Its not a bug from my point of view.

**Comment by prablr79** [comment]
Lets verify CloneOf and snapshotOf, import vol details.

**Comment by dockerciuser** [comment]
Executed the ymls in kubernetes environment with -o parameters as - 

1. with cloneOf option - 

[root@CSSOSBE03-B11 new_yaml]# cat sc_clone.yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-clone-test
provisioner: hpe.com/hpe
parameters:
  cloneOf: test-sc-55a55c53-e340-11e8-a0ae-0242ac110010


[root@CSSOSBE03-B11 new_yaml]# docker volume  inspect sc-clone-test-89ac2751-e340-11e8-a0ae-0242ac110010
[
    {
        "Driver": "hpe",
        "Labels": null,
        "Mountpoint": "/",
        "Name": "sc-clone-test-89ac2751-e340-11e8-a0ae-0242ac110010",
        "Options": {},
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-PNzt-4OQTrOAKToEGNNSGQ",
                "backend": "DEFAULT",
                "compression": null,
                "cpg": "FC_r6",
                "domain": null,
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "thin",
                "size": 20,
                "snap_cpg": "FC_r6"
            }
        }
    }
]

**With above inspect output , it is not clear whether this is a clone or base base volume**

2. With virtualCopyOf option

[root@CSSOSBE03-B11 new_yaml]# cat sc_snp.yml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: test-sc-snp
provisioner: hpe.com/hpe
parameters:
  virtualCopyOf: test-sc-55a55c53-e340-11e8-a0ae-0242ac110010


[root@CSSOSBE03-B11 new_yaml]# docker volume inspect test-sc-snp-0ad48cc9-e341-11e8-a0ae-0242ac110010
[
    {
        "Driver": "hpe",
        "Labels": null,
        "Mountpoint": "/",
        "Name": "test-sc-snp-0ad48cc9-e341-11e8-a0ae-0242ac110010",
        "Options": {},
        "Scope": "global",
        "Status": {
            "snap_detail": {
                "3par_vol_name": "dcs-IUx1WEHjQOiNFRBIJVT-LA",
                "backend": "DEFAULT",
                "compression": null,
                "expiration_hours": null,
                "fsMode": null,
                "fsOwner": null,
                "is_snap": true,
                "mountConflictDelay": 30,
                "parent_id": "6022b48b-2391-4e16-b226-4793ab80fa7b",
                "parent_volume": "test-sc-55a55c53-e340-11e8-a0ae-0242ac110010",
                "provisioning": "thin",
                "retention_hours": null,
                "size": 20,
                "snap_cpg": "FC_r6"
            }
        }
    }
]
**This is giving information of snapshot, this looks good**

3. For importVol option -

**Same as my previous comment , this parameter is not part of docker volume inspect output. So user cant differentiate in between imported volume and normal docker volume**

**Comment by wdurairaj** [comment]
Please see the pull request -- https://github.com/hpe-storage/python-hpedockerplugin/pull/410 for sample responses after this fix.

**Comment by dockerciuser** [comment]
thanks @wdurairaj for sample output. Verified , closing the bug.
