### ISSUE TITLE
FC plugin: unable to mount volume for pod

### ISSUE THREAD

**Issue by maxaquino** [hpe-storage/python-hpedockerplugin#399]
Hi,

We are experiencing an error while testing the FC plugin for 3PAR on a SuSE CaaS 3.0 installation.

The volume is successfully created on the storage system but the pod associated to the volume does not start and I don't see any LUN presented to the OS.

Below the error raised:
  ----     ------                 ----  ----                   -------
  Normal   Scheduled              2m    default-scheduler      Successfully assigned pod1 to caas-worker3
  Normal   SuccessfulMountVolume  2m    kubelet, caas-worker3  MountVolume.SetUp succeeded for volume "default-token-x7jvg"
  Warning  FailedMount            3s    kubelet, caas-worker3  Unable to mount volumes for pod "pod1_default(06491b8d-e0eb-11e8-a134-005056a3122b)": timeout expired waiting for volumes to attach/mount for pod "default"/"pod1". list of unattached/unmounted volumes=[export]

Any hints?

Thank you
BR
Massimiliano

**Comment by prablr79** [comment]
@maxaquino can you also explain the complete setup if you have any handy diagram that will also help here.

**Comment by maxaquino** [comment]
Hi,
we are working in a lab env.
I don't have a diagram but it is a simple CaaS 3.0 installation with 1 master and 2 worker nodes deployed as VMs in a vCenter plus 1 more physical worker deployed on a SY480 Gen10.
That last node (SY480) is the one used to test the FC plugin.

I just modified the example pod yaml file to pin the volume to the physical node using labels.
Below the file used:
>>> sample_pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    arraytype: 3par
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: export
      mountPath: /export
  restartPolicy: Always
  volumes:
  - name: export
    persistentVolumeClaim:
      claimName: pvc1

Other files used:
- configuration file for 3par plugin
>>> /etc/hpedockerplugin/hpe.conf
[DEFAULT]
ssh_hosts_key_file = /root/.ssh/known_hosts
host_etcd_ip_address = 192.168.15.171
host_etcd_port_number = 2378
logging = DEBUG
hpe3par_debug = True
suppress_requests_ssl_warnings = True
hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_fc.HPE3PARFCDriver
hpe3par_api_url = https://192.168.0.32:8080/api/v1
hpe3par_username = k8sadmin
hpe3par_password = K8spwd2018
san_ip = 192.168.0.32
san_login = k8sadmin
san_password = K8spwd2018
hpe3par_cpg = FC_R6_K8sDemo
use_multipath = True
enforce_multipath = True

- docker-compose.yml used to deploy the plugin on every node
>>> docker-compose.yml
hpedockerplugin:
  image: hpe-storage/python-hpedockerplugin:plugin_v2
  container_name: volplugin
  net: host
  restart: always
  privileged: true
  volumes:
     - /dev:/dev
     - /run/lock:/run/lock
     - /var/lib:/var/lib
     - /var/run/docker/plugins:/var/run/docker/plugins:rw
     - /etc:/etc
     - /root/.ssh:/root/.ssh
     - /sys:/sys
     - /root/plugin/certs:/root/plugin/certs
     - /sbin/iscsiadm:/sbin/ia
     - /lib/modules:/lib/modules
     - /lib64:/lib64
     - /var/run/docker.sock:/var/run/docker.sock
     - /opt/hpe/data:/opt/hpe/data:shared
     - /usr/lib64:/usr/lib64

Please let me know if you need more information.

Thank you

**Comment by maxaquino** [comment]
Hi,

doing some troubleshooting I did find that the reason why the container does not mount the volume is that the underlying OS does not have the correct symlink for the volume created.
The hpestorage plugin waits for a device in the /dev/disk/by-path path (hardcoded into the python code /usr/lib/python2.7/site-packages/os_brick/initiator/connectors/fibre_channel.py) that is not there.
The workaround I found to solve the issue is to write a custom udev rule on SuSE microOS to automatically create the missing symlink.

waiting for a better solution.

BR
Max

**Comment by wdurairaj** [comment]
I’m going through this issue in detail, but not finding any relevant log attachments on that bug.
I believe you have found some kind of workaround using udev to make the path of the presented volume in /dev/disk/by-path/ and proceeded with that.

I have few asks from  you..

1)	Can you share me the problematic logs (container logs – using $ docker logs –f <container_id> , where <container_id> is the container id of the volume plugin)
2)	What exactly you have corrected in the udev to make the volume presented under /dev/disk/by-path ?
3)	Can we have a look at your setup , provided it’s reachable from our corporate HPE network.
4)	Is this driver setup configured for FC / iSCSI Protocol ?

This help us to dig more on this problem.

**Comment by maxaquino** [comment]
Hi,

1) See the attached file. You will find logs from hpestorage and doryd containers.
2) See the attached file. You will find two scripts
3) I will send a private message soon with all the information you need to log into our environment.
4) FC is used. We know that iSCSI protocol is not working on a SuSE CaaS environment. Please confirm as it is a relevant information for us.

Thanks
BR
Max

[hpeplugin.tar.gz](https://github.com/hpe-storage/python-hpedockerplugin/files/2615148/hpeplugin.tar.gz)

**Comment by wdurairaj** [comment]
I was able to logon to your system, and I definitely see there are differences between the blade which we have our FC driver running and yours.

Working setup:
```
docker@csosbe03b10:~$ ls -lrt /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Oct 29 19:19 pci-0000:07:00.0-scsi-0:1:0:0 -> ../../sda

docker@csosbe03b10:/var/log$ systool -c fc_host -v
Class = "fc_host"

  Class Device = "host1"
  Class Device path = "/sys/devices/pci0000:00/0000:00:03.0/0000:09:00.0/host1/fc_host/host1"
    dev_loss_tmo        = "16"

```
Problematic setup:

```
caas-worker3:~ # ls -l /dev/disk/by-path
total 0
lrwxrwxrwx 1 root root  9 Nov 20 20:43 pci-0000:00:14.0-usb-0:4:1.0-scsi-0:0:0:0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Nov 20 20:43 pci-0000:13:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Nov 20 20:43 pci-0000:13:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Nov 20 20:43 pci-0000:13:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root 10 Nov 20 20:43 pci-0000:13:00.0-scsi-0:1:0:0-part3 -> ../../sda3
lrwxrwxrwx 1 root root 10 Nov 20 20:43 pci-0000:13:00.0-scsi-0:1:0:0-part4 -> ../../sda4
lrwxrwxrwx 1 root root  9 Nov 20 20:43 pci-virtual-fc--lun-0 -> ../../sda
lrwxrwxrwx 1 root root 10 Nov 20 20:43 pci-virtual-fc--lun-0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Nov 20 20:43 pci-virtual-fc--lun-0-part2 -> ../../sda2
lrwxrwxrwx 1 root root 10 Nov 20 20:43 pci-virtual-fc--lun-0-part3 -> ../../sda3
lrwxrwxrwx 1 root root 10 Nov 20 20:43 pci-virtual-fc--lun-0-part4 -> ../../sda4
lrwxrwxrwx 1 root root  9 Nov 20 21:04 pci-virtual-fc-0x20010002ac0211f4-lun-0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Nov 20 21:08 pci-virtual-fc-0x20010002ac0211f4-lun-1 -> ../../sdd

See only the paths for sdc, sdd

caas-worker3:~ # systool -c fc_host -v
Class = "fc_host"

  Class Device = "host2"
  Class Device path = "/sys/devices/virtual/net/eth2.4064-fcoe/ctlr_0/host2/fc_host/host2"

```
couple of questions:

1) Is it a NPIV setup ?
2) Is it a FC driver running on a VM (Virtual Machine ) ?

**Comment by maxaquino** [comment]
You see only the paths for sdc and sdd because I only activated 1 fc port instead of 2 as it's a simple lab setup.

1. yes it's a sy480 blade behind Virtual Connect modules so NPIV is used
2. It's a bare metal installation so the FC driver is an inbox driver (bnx2fc to be more accurate).

**Comment by prablr79** [comment]
Engineering decided not to support SuSE CAAS  environment. hence closing this case..
