### ISSUE TITLE
Documentation: Add sample configuration for replication in quick-start guide

### ISSUE THREAD

**Issue by imran-ansari** [hpe-storage/python-hpedockerplugin#402]
Sample files referred to in quick start guide need to have replication configuration

**Comment by imran-ansari** [comment]
This has been taken care of. Please check out the following:
https://github.com/imran-ansari/python-hpedockerplugin/blob/plugin_v2/docs/active-passive-based-replication.md
https://github.com/imran-ansari/python-hpedockerplugin/blob/plugin_v2/docs/peer-persistence-based-replication.md

**Comment by prablr79** [comment]
is this added in Master branch ? i can close this defect as well..
