### ISSUE TITLE
Documentation: Link to sample configuration files in quick start guide is broken

### ISSUE THREAD

**Issue by imran-ansari** [hpe-storage/python-hpedockerplugin#403]
Link refers to master branch which doesn't have the sample files. Instead it needs to refer to plugin_v2 branch.

**Comment by imran-ansari** [comment]
On master branch, the links are good. Based on the fact that the documentation will be maintained on master going forward, we can close this issue.

**Comment by prablr79** [comment]
closing this issue since its invalid..
