### ISSUE TITLE
Unable to import volume from backend 3par1

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#407]
Unable to import volume from secondary array ("backend2" in my setup), Getting error as volume does not exist on secondary array, whereas i can see my volume present over there.

Steps to reproduce :-
============
Created volume on secondary array :-  
createvv docker_cpg python_vol_1 1

Importing from docker using -o importVol & -o backend option :-
docker volume create -d hpe --name docker1 -o importVol=python_vol_1 -o backend=backend2

Error :-
====
Error response from daemon: create docker1: Volume:python_vol_1 does not exists Error: Not found (HTTP 404) 23 - volume does not exist

[syslog_importVol_multiarray.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2571314/syslog_importVol_multiarray.txt)

**Comment by wdurairaj** [comment]
I do see an issue here , the usage is wrong
Created volume on secondary array :-
`createvv docker_cpg python_vol_1 1`

Importing from docker using -o importVol & -o backend option :-
`docker volume create -d hpe --name docker1 -o importVol=python_vol_1 -o backend=backend2`

the volume name issued in -o importVol does'nt have the original name which got created in 3par array.

See the difference python_vol_1 1 and python_vol_1, 

You should try ``docker volume create -d hpe --name docker1 -o importVol=python_vol_1_1 -o backend=backend2``

**Comment by virendra-sharma** [comment]
@wdurairaj  I can see volume "python_vol_1" in secondary array, whereas "python_vol_1_1" is not present, since i didn't create it. 

In below command.
createvv docker_cpg python_vol_1 1 --> volume name is "python_vol_1" only and remaining "1" is for size.

**Comment by wdurairaj** [comment]
> @wdurairaj I can see volume "python_vol_1" in secondary array, whereas "python_vol_1_1" is not present, since i didn't create it.
> 
> In below command.
> createvv docker_cpg python_vol_1 1 --> volume name is "python_vol_1" only and remaining "1" is for size.

definitely i misread the createvv command got your point @virendra-sharma 
Thanks for clarifying.

**Comment by virendra-sharma** [comment]
Able to import volume but unable to inspect & delete volume, where as volume is visible through "docker volume ls" command.

Steps performed :-

Steps on secondary array:-
---> createvv docker_cpg volume_docker 1

Steps on docker host:-
---> docker volume create -d hpe --name import_volume -o importVol=volume_docker -o backend=backend2
---> docker volume ls | grep import_volume
---> docker volume inspect import_volume
---> docker volume rm import_volume

Error:-

During volume inspect:-
[]
Error: No such volume: import_volume

During volume delete:-
Error response from daemon: get import_volume: no such volume

**Comment by virendra-sharma** [comment]
Please find syslog for above steps...
[syslog_importVol_multiarray_inspect.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2579584/syslog_importVol_multiarray_inspect.txt)

**Comment by wdurairaj** [comment]
@virendra-sharma , can re-test by installing this newly generated tag -- dockerciuser/hpedockerplugin:test

**Comment by virendra-sharma** [comment]
Tested and verified, volume import and inspect working properly. Please find commands and output as below.

Steps performed:-

Steps on secondary backend:
--> createvv docker_cpg test_import 1

Steps on docker host:
--> docker volume create -d hpe --name test_imported_vol -o importVol=test_import -o backend=backend2
test_imported_vol
--> docker volume inspect test_imported_vol
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/9542694b745c6173bd281a5612f999d924b49d03dbcb3a731aa73eb9b6ec9f36/rootfs",
        "Name": "test_imported_vol",
        "Options": {
            "backend": "backend2",
            "importVol": "test_import"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-HN5ei4RwRbe1XGFRwnNX3A",
                "Options": {
                    "backend": "backend2",
                    "importVol": "test_import"
                },
                "backend": "backend2",
                "compression": null,
                "cpg": "docker_cpg",
                "domain": "test_domain",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "full",
                "size": 1,
                "snap_cpg": "docker_cpg"
            }
        }
    }
]

Verified on 3par after import:
---> showvv -hist dcv-HN5ei4RwRbe1XGFRwnNX3A
   Id Name                       Prov Compr Dedup Type -----CreationTime------ -RetentionEndTime- -ExpirationTime- -SpaceCalcTime- -EfficiencyUpdateTime- -UnrefSpaceFreedTime- --------------------------------------------------------------------------Comment---------------------------------------------------------------------------
48147 dcv-HN5ei4RwRbe1XGFRwnNX3A cpvv NA    NA    base 2018-11-14 19:25:45 IST --                 --               --              --                     --                    {"volume_id": "1cde5e8b-8470-45b7-b55c-6151c27357dc", "name": "1cde5e8b-8470-45b7-b55c-6151c27357dc", "type": "Docker", "display_name": "test_imported_vol"}
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    1 total

**Comment by virendra-sharma** [comment]
attaching syslog log for above steps.
[Verified_bug_407.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2581159/Verified_bug_407.txt)
