### ISSUE TITLE
Idle VLUN templates are present in 3par array intermittently if unmount is performed with multipath.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#41]
Steps to Reproduce:
1)	Create 4 volumes. 
2)	Mount all 4 volumes parallely via 4 different sessions .
3)	Write data on all 4 volumes.
4)	Unmount all 4 volumes.

**Observation 1 : One of the volumes (volume-1) was unmounted successfully on docker client but VLUN templates were still present in 3par for that volume-1 but VLUNs were removed.**

5)	Delete volume-1. It failed

**Observation 2:  <span>HPE Docker Volume plugin Remove volume failed: (u'Err: Failed to remove volume %s, error is %s', u'clh-test07', u'resource in use')</span>
This error is similar to what was observed by Chris.**

6)	Mount volume-1 again. It failed.

**Observation 3: <span>hpedockerplugin.exception.HPEPluginMountException</span>: <span>HPE Docker Volume Plugin Mount Failed: (u'OS Brick connect volume failed, error is: %s', u'Could not login to any iSCSI portal.')</span>**

7)	Unexport volume-1 manually from 3par array. Also, remove host entry for volume-1. This removed VLUN templates present in 3par.  
8)	Mount all 4 volume again. It was successful.
9)	Read data from all 4 volumes.
10)	Unmount all 4 volumes.

**Observation 4: Observation 1 was seen for different volume i.e. volume-2. One of the volumes (volume-2) was unmounted successfully on docker client but VLUN templates were still present in 3par for that volume-2 but VLUNs were removed.** 

11)	Unexport volume-2 manually from 3par array. Also, remove host entry for volume-2. This removed VLUN templates present in 3par.  
12)	Delete all 4 volumes.
13)	All the volumes were deleted successfully.

**Comment by hpe-storage** [comment]
Addressed as part of 1.1 plugin
