### ISSUE TITLE
More than one plugin enabled and volume from single plugin reflected in other plugin together with same volume name

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#416]
I have installed and enabled two docker plugin with different alias and when I manage volume from 3par, imported volume is reflecting under both installed plugin driver with same volume name.

Steps to reproduce:- 

steps in secondary array:
---> createvv docker_cpg import_volume 1

steps in docker host:
---> docker plugin install dockerciuser/hpedockerplugin:test --grant-all-permissions --disable --alias hpe
---> docker plugin install dockerciuser/hpedockerplugin:test --grant-all-permissions --disable
---> docker plugin set hpe glibc_libs.source=/lib64 certs.source=/root/secure_etcd/
---> docker plugin set dockerciuser/hpedockerplugin:test glibc_libs.source=/lib64 certs.source=/root/secure_etcd/
---> docker plugin enable hpe
---> docker plugin enable dockerciuser/hpedockerplugin:test 
---> docker plugin ls
ID                  NAME                                DESCRIPTION                ENABLED
120af83bb85d        hpe:latest                          HPE Docker Volume Plugin   true
fac8827b0d96        dockerciuser/hpedockerplugin:test   HPE Docker Volume Plugin   true
---> docker volume create -d hpe --name imported_volume -o importVol=import_volume -o backend=backend2
---> docker volume ls
DRIVER                              VOLUME NAME
hpe:latest                          IMPORT-VOLUME
dockerciuser/hpedockerplugin:test   IMPORT-VOLUME

**Comment by wdurairaj** [comment]
Actually both the plugin exposes `/run/docker/plugin/hpe/hpe.sock` file in containerized form or `/var/lib/docker/plugins/<plugin_id>/rootfs/run/docker/plugin/hpe/hpe.sock` in managed plugin format.

When a volume is created docker engine does a REST call to this unix socket exposed by the plugin (hpe.sock) and invokes the twistd daemon running on the container (which listens to this sock file for REST calls).

what happens in the above case is that two plugins (2 twistd daemon runs as part of 2 containers of volume plugin), and most probably, one will proceed with the volume creation (depends on which one receives) and other will implicitly make a GET request on the same volume name, and sees it exist and does'nt do volume creation.

Is your expectation, that the other plugin should'nt be enabled ? when one is already active

**Comment by wdurairaj** [comment]
A single volume is listed twice (one under the first plugin and other against the 2nd plugin) since the `$ docker volume ls` is a etcd read operation, and both the plugins have read the identical information.

**Comment by virendra-sharma** [comment]
@wdurairaj as discussed with @imran-ansari came to know that one plugin can be enable at a time so I suppose if we have such restriction then in current issue plugin bypassing it. if one plugin can be enable at a time then other issue won't arise.

**Comment by prablr79** [comment]
recommendation is one instance of plugin should run.

**Comment by prablr79** [comment]
Not a defect, working as designed.
