### ISSUE TITLE
Volume creation on failed 'DEFAULT' backend fails with incorrect error message

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#418]
On Faulty replicated backend when we try to create a volume, incorrect message displays.

```
[root@CSSOSBE02-B10 ~]# docker plugin install hpestorage/hpedockervolumeplugin:3.0 --grant-all-permissions --disable --alias hpe
3.0: Pulling from hpestorage/hpedockervolumeplugin
31b7bb374a07: Download complete
Digest: sha256:e96f357a0e3b5ad111e8095c5ca85f87d7a2c5353fa9384530c7b844a10c6107
Status: Downloaded newer image for hpestorage/hpedockervolumeplugin:3.0
Installed plugin hpestorage/hpedockervolumeplugin:3.0
[root@CSSOSBE02-B10 ~]# docker plugin set hpe glibc_libs.source=/lib64 certs.source=/root/secure_etcd/
[root@CSSOSBE02-B10 ~]# docker plugin enable hpe
hpe
[root@CSSOSBE02-B10 ~]# docker volume create -d hpe -o help=backends
Error response from daemon: create 61f66fe1b27c6b0d09a26c661ce2bf544193a0bd3f00da43ae6fe174cb4f4219:
======================================================
NAME                                          STATUS
======================================================
3PAR                                           OK
3PAR1                                          OK
3par3                                          OK
ASYNC                                          OK
DEFAULT                                        FAILED
======================================================
[root@CSSOSBE02-B10 ~]#

[root@CSSOSBE02-B10 ~]# docker volume create -d hpe --name volume -o replicationGroup=SHASHI
Error response from daemon: create volume: EOF
[root@CSSOSBE02-B10 ~]#
```

Expected Results - 
Appropriate Message like, '' msg = 'Backend: "%s" having incorrect/missing some configuration. should be displayed

Actual  - EOF displays

**Comment by prablr79** [comment]
is this checked on Build 268 latest ?please confirm

**Comment by imran-ansari** [comment]
Looking at the backend validation, I believe this is a general error which will occur even in case of non-replicated volume. As a fix, we need to move the backend validation as the initial thing and independent of whether "-o" was used or not because in latter case, we default to "DEFAULT" backend which also needs to be validated as is the case with this issue.

**Comment by imran-ansari** [comment]
Moving the below code just after the request-validation part would fix this:

`        current_backend = DEFAULT_BACKEND_NAME
        if 'Opts' in contents and contents['Opts']:
            if ('backend' in contents['Opts'] and
                    contents['Opts']['backend'] != ""):
                current_backend = str(contents['Opts']['backend'])

        # check if current_backend present in config file
        if current_backend in self._backend_configs:
            # check if current_backend is initialised
            if current_backend not in self.orchestrator._manager:
                msg = 'Backend: %s having incorrect/missing some ' \
                      'configuration.' % current_backend
                LOG.error(msg)
                return json.dumps({u"Err": msg})
        else:
            msg = 'Backend: %s not present in config.' \
                  % current_backend
            LOG.error(msg)
            return json.dumps({u"Err": msg})
`

**Comment by prablr79** [comment]
guys, lets discuss this with william once..

**Comment by prablr79** [comment]
moving to low since its only error message correction

**Comment by sandesh-desai** [comment]
Verified and working as expected.
Attaching the output:

[root@CSSOSBE03-B03 ~]# docker volume create -d hpe --name volume -o replicationGroup=SHASHI
Error response from daemon: create volume: Invalid input received: Request to create replicated volume cannot be fulfilled without defining 'replication_device' entry defined in hpe.conf for the backend 'DEFAULT'. Please add it and execute the request again.
[root@CSSOSBE03-B03 ~]#
[root@CSSOSBE03-B03 ~]#
[root@CSSOSBE03-B03 ~]# docker volume create -d hpe -o help=backends
Error response from daemon: create ebba1c38791791309d6a3e1e79bad064d554cb3c43a016190e5648e31c8b946f:
======================================================
NAME                                          STATUS
======================================================
DEFAULT                                        OK

@sonawane-shashikant : Please closed the bug.

**Comment by sonawane-shashikant** [comment]
Closing this bug as per above comment.
