### ISSUE TITLE
Volume Prune feature does not work in Legacy and managed V2 plugin.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#42]
1. Create few volumes. Dont mount any volume.

_docker@csimbe13-b13:~$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          sum1
hpe:latest          sum2
hpe:latest          sum3_

2. Run volume prune command.

_docker@csimbe13-b13:~$ docker volume prune
WARNING! This will remove all volumes not used by at least one container.
Are you sure you want to continue? [y/N] y
Total reclaimed space: 0 B_

3. List all volumes.

_docker@csimbe13-b13:~$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          sum1
hpe:latest          sum2
hpe:latest          sum3_

**Expected result:** All the volumes must be removed.

**Observed result**: No volume was removed. 

**Note**: It was tested and failed on both legacy plugin as well as v2 plugin.

**Comment by hpe-storage** [comment]
After our investigation we found the prune command removes local volumes, and not the volumes created by plugins.

To clean the docker volumes created by plugin, please use

``docker volume rm $(docker volume ls -q -f "dangling=true")``
