### ISSUE TITLE
Documentation : Creation of non-replicated volume in the replicated backend 

### ISSUE THREAD

**Issue by prablr79** [hpe-storage/python-hpedockerplugin#420]
Scenario : if the user want to create a non-replicated volume with replicated backend in the hpe.conf will not allow to create.

Option : the same backend details need to added again without the replication params and with new backend name.  this will allow the user to create non-replicated volume for the same backend.

**Comment by imran-ansari** [comment]
@prablr79 
Please check out
https://github.com/imran-ansari/python-hpedockerplugin/blob/plugin_v2/docs/replication.md 
The note section mentions about this point.

**Comment by sonawane-shashikant** [comment]
Second point in the  Notes mentions, " In order to do so, she would need to ...."

Can this be changed to 
"In order to do so, he/she would need to. ..... "
or
"In order to do so, user would need to......."

**Comment by prablr79** [comment]
reviewed Imran documentation for this defect. once merged in Master will close this defect.

**Comment by prablr79** [comment]
Verified in master, hence closing this bug
