### ISSUE TITLE
Docker3.0: Volume operations fails with timeout with 3PAR Array version 3.3.1.389 (MU4)

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#435]
Summary - With Array version 3.3.1.389 (MU4), volumes operations fail.

Test Bed - 

CSIM-8K02_MXN6072AC7 cli% showversion -b
Release version 3.3.1.489 (MU4)
Patches:  None

Component Name                   Version
SELECTED AVAILABILITY RELEASE    3.3.1.489 (T05)
CLI Server                       3.3.1.489 (MU4)
CLI Client                       3.3.1.489
System Manager                   3.3.1.489 (MU4)
Kernel                           3.3.1.489 (MU4)
TPD Kernel Code                  3.3.1.489 (MU4)

[root@cld6b10 ~]# cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
[root@cld6b10 ~]# docker volume create -d hpe -o help=backends
Error response from daemon: create b3de7b3fff14d34b1f202975171de731e9e338d3c22d83474f33c3ce6acdc03c: Post http://%2Frun%2Fdocker%2Fplugins%2F75233283ef8a89c11ce81ab57f9e54ca629e08273a3777071f78deda6e09af6a%2Fhpe.sock/VolumeDriver.Create: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
[root@cld6b10 ~]# docker plugin ls
ID                  NAME                                         DESCRIPTION                    ENABLED
4a80a1ee515b        docker/telemetry:1.0.0.linux-x86_64-stable   Docker Inc. metrics exporter   false
75233283ef8a        hpe:latest                                   HPE Docker Volume Plugin       true
[root@cld6b10 ~]# docker version
Client: Docker Enterprise Edition (EE) 2.0
 Version:      17.06.2-ee-17
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   66834de
 Built:        Thu Oct 25 12:18:20 2018
 OS/Arch:      linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-17
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   66834de
  Built:        Thu Oct 25 12:19:45 2018
  OS/Arch:      linux/amd64
  Experimental: false
[root@cld6b10 ~]# docker volume ls
DRIVER              VOLUME NAME
[root@cld6b10 ~]# docker plugin inspect hpe | grep PluginRef                                                                                              "PluginReference": "docker.io/hpestorage/hpedockervolumeplugin:3.0",

STEPS TO REPRODUCE - 
1. IUpgrade 3PAR array with 3.3.1.489 (MU4)
2. Configure docker volume plugin with this array.
3. Perform basic volume operations
4. Observer the delayed response.

[root@cld6b10 ~]# docker volume ls
DRIVER              VOLUME NAME
[root@cld6b10 ~]# docker volume create -d hpe --name TEST-SHASHI -o size=20
Error response from daemon: create TEST-SHASHI: Post http://%2Frun%2Fdocker%2Fplugins%2F75233283ef8a89c11ce81ab57f9e54ca629e08273a3777071f78deda6e09af6a%2Fhpe.sock/VolumeDriver.Create: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
[root@cld6b10 ~]#

Below is the log captured while performing basic volume operations.

[VolumeOperations.log](https://github.com/hpe-storage/python-hpedockerplugin/files/2670461/VolumeOperations.log)

**Comment by prablr79** [comment]
@sonawane-shashikant is this real issue, are still seeing with latest firmware image ? please confirm.

**Comment by prablr79** [comment]
due to old mount entries this was failing, this is not a valid defect.
