### ISSUE TITLE
Hardcoded proxy in 3par docker volume plugin installation

### ISSUE THREAD

**Issue by farhan7500** [hpe-storage/python-hpedockerplugin#437]
The proxy in the 3par docker volume plugin installation is currently hardcoded to India HPE Proxy.

This is breaking customer installation.

**Comment by farhan7500** [comment]
Fixed at: https://github.com/hpe-storage/python-hpedockerplugin/pull/438/files

The proxy can be provided in the inventory file which will be read by the playbooks

**Comment by prablr79** [comment]
@farhan7500 please ask Leena or Sandesh verify and close

**Comment by sandesh-desai** [comment]
Verified and Working as expected.
@farhan7500 : please close the defect.

**Comment by farhan7500** [comment]
Closing as fixed
