### ISSUE TITLE
How to get the iscsi IPs in the automated ansible plugin installation?

### ISSUE THREAD

**Issue by farhan7500** [hpe-storage/python-hpedockerplugin#443]
One of the customer uses `showport -iscsivlans` to and populates the result in the iscsi IPs in hpe.conf.

In the current logic, we use `showport -iscsi` and get all the ready ports. However, on that particular setup, this command resturned all IPs as 0.0.0.0. However, the `-iscsivlans` returned all the valid IPs.

We need to figure out which is the generic command that can be used to populate the iscsi IPs

**Comment by farhan7500** [comment]
@wdurairaj 
During our previous discussion, here is what we planned:
The configuration properties yml file will have a vlan tagging parameter which when enabled (set to true - this parameter will be defaulted to false), will get the iscsi ips using `showport -iscsivlans` otherwise get the ips using `showport -iscsi`

Could there be a case where in a replicated backend, the two arrays can have the source vlan tagged and target not vlan tagged (or vice versa)?

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/456

**Comment by shaik-gousa-khaja-asif** [comment]
There is a vlan_tag property added in the properties file which is default set to False and populates the showport -iscsi IP's and when set to True populates showport -iscsivlans IP's . Also working with replicated backend .
