### ISSUE TITLE
Users should be able to set less than or more than 3 etcd during automated plugin installation

### ISSUE THREAD

**Issue by farhan7500** [hpe-storage/python-hpedockerplugin#444]
Currently, the number of etcd is hardcoded to 3. The users must be able to set less than or more than 3 etcd. Change required in the installer.

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/457

**Comment by sandesh-desai** [comment]
Verified and working as expected.
Attaching the logs.

[Less than 3 etcd.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2839619/Less.than.3.etcd.txt)
[log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2839620/log.txt)
[More than 3 etcd.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2839621/More.than.3.etcd.txt)
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2839622/hpe.conf.txt)

@farhan7500  please close the bug.
