### ISSUE TITLE
3par encryptor is unable to generate the encypted password if etcd is not installed on that node in a cluster

### ISSUE THREAD

**Issue by farhan7500** [hpe-storage/python-hpedockerplugin#447]
In a 5 node cluster, 3 nodes are etcd clustered.

The 4th and 5th node are not able to encrypt password using hpe3parencryptor because etcd container is not present on those nodes. The encryption utility should be able to create the password using the existing etcd cluster

`[root@localhost ~]# hpe3parencryptor --backend 3PAR1 -a second_key 3pardata
Traceback (most recent call last):
  File "/usr/bin/hpe3parencryptor", line 7, in <module>
    from hpe3parencryptor import encryption_utility
  File "/usr/lib/python2.7/site-packages/hpe3parencryptor/encryption_utility.py", line 212, in <module>
    ,host_etcd_client_key)
  File "/usr/lib/python2.7/site-packages/hpe3parencryptor/encryption_utility.py", line 168, in __init__
    self.client.read(BACKENDROOT)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 597, in read
    timeout=timeout)
  File "/usr/lib/python2.7/site-packages/etcd/client.py", line 893, in wrapper
    cause=e
etcd.EtcdConnectionFailed: Connection to etcd failed due to MaxRetryError(u"HTTPConnectionPool(host=u'192.168.120.133', port=23790): Max retries exceeded with url: /v2/keys/backend (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0932c571d0>: Failed to establish a new connection: [Errno 111] Connection refused',))",)`

**Comment by farhan7500** [comment]
Fixed at https://github.com/hpe-storage/python-hpedockerplugin/pull/454

**Comment by sandesh-desai** [comment]
Verified and working as expected.
Attaching the logs.

[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2839884/hpe.conf.txt)
[log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2839885/log.txt)


@farhan7500 please close the bug.
