### ISSUE TITLE
ansible: Document needs correction

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#449]
Go to https://github.com/hpe-storage/python-hpedockerplugin/blob/master/ansible_3par_docker_plugin/README.md

Please add below prerequisites under Prerequisites: header
In case of Kubertnetes and Openshift cluster password less communication should be set among master and worker nodes.

To simplify the installation steps, please add the below after ansible installation steps.
1. git clone https://github.com/hpe-storage/python-hpedockerplugin.
2. Navigate to hosts file and update master, worker, proxy and etcd details.
3. Navigate to https://github.com/hpe-storage/python-hpedockerplugin/tree/master/ansible_3par_docker_plugin/properties/   plugin_configuration_properties_sample.yml   and update the backend details as desired and save that file in properties folder only.
4. run  ansible-playbook -i <hosts file path> install_hpe_3par_volume_driver.yml from /root/python-hpedockerplugin/ansible_3par_docker_plugin folder only.

**Comment by farhan7500** [comment]
Modified the documentation based on test review
https://github.com/hpe-storage/python-hpedockerplugin/pull/453/files

**Comment by sonawane-shashikant** [comment]
This issue is resolved as FIXED.
