### ISSUE TITLE
Volume mount fails for old/new volumes after performing upgrade of managed v2 plugin.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#46]
Few volumes were mounted to containers and wrote data on them. 
Performed upgrade of plugin from Store 1.1 plugin to Store 2.0 plugin. 
Unmounted volumes and containers were in DEAD state which can't be removed.
Created new volumes and observed none of the volumes (old as well as new volumes) were able to mount.
Please refer the comment for detailed error and logs.

Root cause of this issue: https://github.com/moby/moby/issues/27381

The workaround is to restart the docker service or reboot the system and start etcd daemon again.

The current working steps to upgrade the plugin is mentioned in this following document:
https://github.com/hpe-storage/python-hpedockerplugin/blob/master/docs/migrate-volume-from-legacy-to-managed-plugin.md

**Comment by sumitshatwara** [comment]
Performed on CentOS 7.3
Upgrade from plugin 1.1 to plugin 2.0

All the volume mount requests are getting failed if one or two old volumes are kept mounted before performing upgrade.

1.	Installed 1.1 plugin.
2.	Created 4 volumes with different properties using iSCSI plugin .
3.	Mounted and wrote data on them.
4.	Unmounted two volumes and kept two volumes mounted with containers in detached state.

[docker@csimbe13-b03 ~]$ dvols
DRIVER              VOLUME NAME
hpe:latest          test1
hpe:latest          test2
hpe:latest          test3
hpe:latest          test4

[docker@csimbe13-b03 ~]$ dps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
30d87162c5b9        busybox                      "/bin/sh"                10 minutes ago      Up 10 minutes                                                                            mounter2
ae385cdc3326        busybox                      "/bin/sh"                10 minutes ago      Up 10 minutes                                                                            mounter1

5.	Disabled the plugin forcefully.
6.	Upgraded to 2.0 plugin.
7.	Enable the iSCSI plugin.
8.	Performed “docker attach” and umounted both the volumes. Both the container were in DEAD state. These dead containers can’t be removed.

[docker@csimbe13-b03 ~]$ docker attach mounter1
/ # exit

[docker@csimbe13-b03 ~]$ docker attach mounter2
/ # exit

[docker@csimbe13-b03 ~]$ dps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
30d87162c5b9        busybox                      "/bin/sh"                14 minutes ago      Dead                                                                                     mounter2
ae385cdc3326        busybox                      "/bin/sh"                14 minutes ago      Dead                                                                                     mounter1


9.	Mounted rest of two volumes. It failed with below error:

[docker@csimbe13-b03 ~]$ docker run -it -v test3:/data1 --volume-driver hpe --rm --name mounter3 busybox /bin/sh
docker: Error response from daemon: devmapper: Error activating devmapper device for '17436b31c7ce175f933d61ff0985159f670efb3a36aed33d9dcb54b2fcad2cea-init': devicemapper: Can't set cookie dm_task_set_cookie failed.
See 'docker run --help'.

[docker@csimbe13-b03 ~]$ docker run -it -v test4:/data1 --volume-driver hpe --rm --name mounter4 busybox /bin/sh
docker: Error response from daemon: devmapper: Error activating devmapper device for '95f60a78c50ce56bc0a3365de017e53ba1c2d6757fb2e26d14d25609ed4f3e71-init': devicemapper: Can't set cookie dm_task_set_cookie failed.
See 'docker run --help'.

10.	Created a new volume and tried mounting it. It failed with same error:

[docker@csimbe13-b03 ~]$ docker run -it -v test5:/data1 --volume-driver hpe --rm --name mounter5 busybox /bin/sh
docker: Error response from daemon: devmapper: Error activating devmapper device for 'ee23c36aba1f488e4c7c0954cfe7a8923eebcbd9059fff6b8f2681b5ae4b35b8-init': devicemapper: Can't set cookie dm_task_set_cookie failed.
See 'docker run --help'.

Please find the logs in the attachment.

One similar issue in moby project: https://github.com/moby/moby/issues/27381

The only workaround is to reboot the docker host and start etcd daemon again. We need to document this.

[upgrade_logs1.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1230922/upgrade_logs1.txt)

**Comment by hpe-storage** [comment]
Sumit has documented the steps for Upgradation as part of this wiki link:

https://github.com/hpe-storage/python-hpedockerplugin/blob/master/docs/migrate-volume-from-legacy-to-managed-plugin.md

Please refer this.

**Comment by sonivi** [comment]
Performed upgrade from "hpestorage/hpedockervolumeplugin:2.0.2" to "hpestorage/hpedockervolumeplugin:2.1"

Volume mounted in older version failed, while unmounting, after upgrade to later version

error log snippet:
_python-hpedockerplugin/hpedockerplugin/volume_manager.py:866 in unmount_volume
865        volid = vol['id']
866        is_snap = vol['is_snap']
867
exceptions.KeyError: 'is_snap'_

[host_machine.log](https://github.com/hpe-storage/python-hpedockerplugin/files/1945669/host_machine.log)
[3par.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1945670/3par.txt)

**Comment by sonivi** [comment]
After making the code changes for avoiding the error mentioned in previous comment, the execution failed at os-brick code here,
https://github.com/openstack/os-brick/blob/1.13.1/os_brick/initiator/linuxscsi.py#L280

with error,

/usr/lib/python2.7/site-packages/os_brick/initiator/linuxscsi.py:294 in\n find_multipath_device\n
293            raise exception.CommandExecutionFailed(
294                cmd='multipath -l %s' % device)

**Comment by wdurairaj** [comment]
Documentation done for this issue is : https://github.com/hpe-storage/python-hpedockerplugin/blob/master/docs/advanced/migrate-volume-from-legacy-to-managed-plugin.md

**Comment by prablr79** [comment]
Verified hence closing this bug
