### ISSUE TITLE
Docker 3.1: Unable to create Replicated Volume

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#460]
ISCSI Test-Bed - 

docker@10.50.128.110's password:
Last login: Wed Jan 23 11:08:37 2019 from cijump.set.rdlabs.hpecorp.net
[docker@cld6b10 ~]$ docker version
Client: Docker Enterprise Edition (EE) 2.0
 Version:      17.06.2-ee-17
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   66834de
 Built:        Thu Oct 25 12:18:20 2018
 OS/Arch:      linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-17
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   66834de
  Built:        Thu Oct 25 12:19:45 2018
  OS/Arch:      linux/amd64
  Experimental: false

[docker@cld6b10 ~]$ docker plugin inspect hpe | grep PluginRef
        "PluginReference": "docker.io/dockerciuser/hpedockerplugin:test",
[docker@cld6b10 ~]$

[docker@cld6b10 ~]$ cat /etc/redhat-release
CentOS Linux release 7.5.1804 (Core)
[docker@cld6b10 ~]$

[DEFAULT]
host_etcd_ip_address = 10.50.128.110
host_etcd_port_number = 2379
logging = DEBUG
hpe3par_debug = True
hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
hpe3par_api_url = https://10.50.3.7:8080/api/v1
hpe3par_username = 3paradm
hpe3par_password = 3pardata
san_ip = 10.50.3.7
san_login = 3paradm
san_password = 3pardata
hpe3par_cpg = md_cpg1
hpe3par_snapcpg = md_demo
hpe3par_iscsi_ips = 10.50.17.222,10.50.17.223
use_multipath = True
replication_device = backend_id:CSIMEOS12_1611702,
                     replication_mode:synchronous,
                     cpg_map:SHASHI_SRC_CPG:SHASHI_DEST_CPG,
                     snap_cpg_map:SHASHI_SNAP_SRC_CPG:SHASHI_SNAP_DEST_CPG,
                     hpe3par_username:3paradm,
                     hpe3par_password:3pardata,
                     hpe3par_api_url: https://10.50.3.22:8080/api/v1,
                     san_ip: 10.50.3.22,
                     san_login: 3paradm,
                     san_password:3pardata,
                     hpe3par_iscsi_ips: 10.50.1.25,10.50.1.26,10.50.1.27,10.50.1.28,10.50.1.29,10.50.1.30,10.50.1.31,10.50.1.32
[3PAR]
hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
hpe3par_api_url = https://10.50.3.9:8080/api/v1
hpe3par_username = 3paradm
hpe3par_password = 3pardata
san_ip = 10.50.3.9
san_login = 3paradm
san_password = 3pardata
hpe3par_cpg = SSD_r1
hpe3par_snapcpg = SSD_r1
hpe3par_iscsi_ips = 10.50.3.59,10.50.3.60
use_multipath = True

Steps to reproduce - 
	1. Configure docker volume plugin with Replication as Default and one additional backend
	2. Try to create replicated volume using -o replicationGroup parameter.
	3. Verify
	
Expected Result - 
Replicated volume should be created successfully

Actual Result - 
HTML Error is seen as below.

[docker@cld6b10 ~]$ docker volume create -d hpe --name xyz -o replicationGroup=Shashi
Error response from daemon: create xyz: VolumeDriver.Create: <html><head><title>web.Server Traceback (most recent call last)</title></head><body><b>web.Server Traceback (most recent call last):</b>

<div>
  <style type="text/css">
    div.error {
      color: red;
      font-family: Verdana, Arial, helvetica, sans-serif;
      font-weight: bold;
    }

    div {
      font-family: Verdana, Arial, helvetica, sans-serif;
    }

    div.stackTrace {
    }

    div.frame {
      padding: 1em;
      background: white;
      border-bottom: thin black dashed;
    }

    div.frame:first-child {
      padding: 1em;
      background: white;
      border-top: thin black dashed;
      border-bottom: thin black dashed;
    }

    div.location {
    }

    span.function {
      font-weight: bold;
      font-family: "Courier New", courier, monospace;
    }

    div.snippet {
      margin-bottom: 0.5em;
      margin-left: 1em;
      background: #FFFFDD;
    }

    div.snippetHighlightLine {
      color: red;
    }

    span.code {
      font-family: "Courier New", courier, monospace;
    }
  </style>

  <div class="error">
    <span>oslo_config.cfg.ConfigFileValueError</span>: <span>Value for option replication_device is not valid: Value should be NAME:VALUE pairs separated by ","</span>
  </div>
  <div class="stackTrace">
    <div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/Twisted-18.7.0rc1-py3.6-linux-x86_64.egg/twisted/internet/defer.py</span>:<span>151</span> in
        <span class="function">maybeDeferred</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">150</span>
          <code class="code"> &#160; &#160;try:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">151</span>
          <code class="code"> &#160; &#160; &#160; &#160;result = f(*args, **kw)</code>
        </div><div class="snippetLine">
          <span class="lineno">152</span>
          <code class="code"> &#160; &#160;except:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/klein-17.10.0-py3.6.egg/klein/app.py</span>:<span>128</span> in
        <span class="function">execute_endpoint</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">127</span>
          <code class="code"> &#160; &#160; &#160; &#160;endpoint_f = self._endpoints[endpoint]</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">128</span>
          <code class="code"> &#160; &#160; &#160; &#160;return endpoint_f(self._instance, *args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">129</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/klein-17.10.0-py3.6.egg/klein/app.py</span>:<span>227</span> in
        <span class="function">_f</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">226</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;def _f(instance, request, *a, **kw):</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">227</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;return _call(instance, f, request, *a, **kw)</code>
        </div><div class="snippetLine">
          <span class="lineno">228</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/klein-17.10.0-py3.6.egg/klein/app.py</span>:<span>50</span> in
        <span class="function">_call</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">49</span>
          <code class="code"> &#160; &#160; &#160; &#160;args = (instance,) + args</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">50</span>
          <code class="code"> &#160; &#160;result = f(*args, **kwargs)</code>
        </div><div class="snippetLine">
          <span class="lineno">51</span>
          <code class="code"> &#160; &#160;if iscoroutine(result):</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py</span>:<span>366</span> in
        <span class="function">volumedriver_create</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">365</span>
          <code class="code"> &#160; &#160; &#160; &#160;try:</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">366</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;self._validate_rcg_params(rcg_name, current_backend)</code>
        </div><div class="snippetLine">
          <span class="lineno">367</span>
          <code class="code"> &#160; &#160; &#160; &#160;except exception.InvalidInput as ex:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/python-hpedockerplugin/hpedockerplugin/hpe_storage_api.py</span>:<span>413</span> in
        <span class="function">_validate_rcg_params</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">412</span>
          <code class="code"> &#160; &#160; &#160; &#160;hpepluginconfig = self._backend_configs[backend_name]</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">413</span>
          <code class="code"> &#160; &#160; &#160; &#160;replication_device = hpepluginconfig.replication_device</code>
        </div><div class="snippetLine">
          <span class="lineno">414</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/python-hpedockerplugin/hpedockerplugin/configuration.py</span>:<span>163</span> in
        <span class="function">__getattr__</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">162</span>
          <code class="code"> &#160; &#160; &#160; &#160;conf = object.__getattribute__(self, 'conf')</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">163</span>
          <code class="code"> &#160; &#160; &#160; &#160;return getattr(conf, value)</code>
        </div><div class="snippetLine">
          <span class="lineno">164</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/python-hpedockerplugin/hpedockerplugin/configuration.py</span>:<span>131</span> in
        <span class="function">__getattr__</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">130</span>
          <code class="code"> &#160; &#160; &#160; &#160;backend_conf = object.__getattribute__(self, 'backend_conf')</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">131</span>
          <code class="code"> &#160; &#160; &#160; &#160;opt_value = getattr(backend_conf, opt_name)</code>
        </div><div class="snippetLine">
          <span class="lineno">132</span>
          <code class="code"> &#160; &#160; &#160; &#160;if opt_value is None:</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/oslo.config-6.3.0-py3.6.egg/oslo_config/cfg.py</span>:<span>3439</span> in
        <span class="function">__getattr__</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">3438</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;"""Look up an option value and perform template substitution."""</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">3439</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160;return self._conf._get(name, self._group)</code>
        </div><div class="snippetLine">
          <span class="lineno">3440</span>
          <code class="code"></code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/oslo.config-6.3.0-py3.6.egg/oslo_config/cfg.py</span>:<span>2976</span> in
        <span class="function">_get</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">2975</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;pass</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">2976</span>
          <code class="code"> &#160; &#160; &#160; &#160;value, loc = self._do_get(name, group, namespace)</code>
        </div><div class="snippetLine">
          <span class="lineno">2977</span>
          <code class="code"> &#160; &#160; &#160; &#160;self.__cache[key] = value</code>
        </div>
      </div>
    </div><div class="frame">
      <div class="location">
        <span>/usr/lib/python3.6/site-packages/oslo.config-6.3.0-py3.6.egg/oslo_config/cfg.py</span>:<span>3025</span> in
        <span class="function">_do_get</span>
      </div>
      <div class="snippet">
        <div class="snippetLine">
          <span class="lineno">3024</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;"Value for option %s is not valid: %s"</code>
        </div><div class="snippetHighlightLine">
          <span class="lineno">3025</span>
          <code class="code"> &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160; &#160;% (opt.name, str(ve)))</code>
        </div><div class="snippetLine">
          <span class="lineno">3026</span>
          <code class="code"></code>
        </div>
      </div>
    </div>
  </div>
  <div class="error">
    <span>oslo_config.cfg.ConfigFileValueError</span>: <span>Value for option replication_device is not valid: Value should be NAME:VALUE pairs separated by ","</span>
  </div>
</div>

</body></html>

[journalctl.log](https://github.com/hpe-storage/python-hpedockerplugin/files/2786357/journalctl.log)
[log_replication.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2786358/log_replication.txt)

**Comment by wdurairaj** [comment]
```
hpe3par_iscsi_ips: 10.50.1.25;10.50.1.26;10.50.1.27;10.50.1.28;10.50.1.29;10.50.1.30;10.50.1.31;10.50.1.32
```

Use semicolon for separating iscsi ip's in `replication_device` parameter
This is invalid bug.

**Comment by wdurairaj** [comment]
Read this doc for sample config -- https://github.com/hpe-storage/python-hpedockerplugin/blob/master/docs/active-passive-based-replication.md

**Comment by sonawane-shashikant** [comment]
Closing as Invalid.
After correcting replication_device iscsi_ips, I could create replicated volume.

[docker@cld6b10 ~]$ docker volume create -d hpe --name TESTTEST-VOL -o replicationGroup=RCG
TESTTEST-VOL
[docker@cld6b10 ~]$
