### ISSUE TITLE
Docker 3.1: Ansible: Error while uninstall playbook run

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#463]
[root@kuber-master 3.1]# docker version
Client: Docker Enterprise Edition (EE) 2.0
 Version:      17.06.2-ee-17
 API version:  1.30
 Go version:   go1.8.7
 Git commit:   66834de
 Built:        Thu Oct 25 12:18:20 2018
 OS/Arch:      linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-17
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.8.7
  Git commit:   66834de
  Built:        Thu Oct 25 12:19:45 2018
  OS/Arch:      linux/amd64
  Experimental: false

[root@kuber-master 3.1]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:36:44Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
[root@kuber-master 3.1]#

CSIM-8K02_MXN6072AC7 cli% showversion -b
Release version 3.3.1.489 (MU4)
Patches:  None

Component Name                   Version
SELECTED AVAILABILITY RELEASE    3.3.1.489 (T05)
CLI Server                       3.3.1.489 (MU4)
CLI Client                       3.3.1.489
System Manager                   3.3.1.489 (MU4)
Kernel                           3.3.1.489 (MU4)
TPD Kernel Code                  3.3.1.489 (MU4)
CSIM-8K02_MXN6072AC7 cli%

Steps To reproduce - 
1, Install docker volume plugin on k8s cluster.
2. Verify the installtion
3. Uninstall the plugin to see the below errors.

TASK [stop multipath services, also issue daemon-reload to pick up config changes] ***************************************************************
ok: [10.50.9.23] => (item=iscsid)
ok: [10.50.9.10] => (item=iscsid)
failed: [10.50.9.22] (item=iscsid) => {"changed": false, "item": "iscsid", "msg": "Unable to stop service iscsid: Job for iscsid.service canceled.\n"}
ok: [10.50.9.22] => (item=multipathd)
ok: [10.50.9.23] => (item=multipathd)
ok: [10.50.9.10] => (item=multipathd)

TASK [stop doryd service, also issue daemon-reload to pick up config changes] ********************************************************************
fatal: [10.50.9.10]: FAILED! => {"changed": false, "msg": "Could not find the requested service doryd.service: host"}
        to retry, use: --limit @/root/python-hpedockerplugin/ansible_3par_docker_plugin/uninstall/uninstall_hpe_3par_volume_driver.retry

PLAY RECAP ***************************************************************************************************************************************
10.50.9.10                 : ok=11   changed=4    unreachable=0    failed=1
10.50.9.22                 : ok=7    changed=4    unreachable=0    failed=1
10.50.9.23                 : ok=12   changed=4    unreachable=0    failed=0

[root@kuber-master ansible_3par_docker_plugin]#

[hosts.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2794662/hosts.txt)
[plugin_configuration_properties.yml.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2794663/plugin_configuration_properties.yml.txt)

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/456

**Comment by sonawane-shashikant** [comment]
This issue is verified by following below steps - 

1. Installed 3.0 legacy plugin manually on k8s cluster.
2. Validated the installation by creating sc,pvc and pod successfully
3. Uninstalled the plugin using Automated Installer.
4. Plugin gets successfully uninstalled.

Detailed Output is as below - 

[root@master-node ansible_3par_docker_plugin]# ansible-playbook -i /root/hosts  uninstall/uninstall_hpe_3par_volume_driver_etcd.yml
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use 'import_tasks' for static inclusions or 'include_tasks' for
dynamic inclusions. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False
in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is discouraged. The module documentation details page may explain
more about this rationale.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

PLAY [Uninstall HPE 3PAR Volume Driver for Kubernetes/OpenShift] *********************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [10.50.9.23]
ok: [10.50.9.10]
ok: [10.50.9.22]

TASK [load plugin settings] **********************************************************************************************************************
ok: [10.50.9.10]
ok: [10.50.9.23]
ok: [10.50.9.22]

TASK [load etcd settings] ************************************************************************************************************************
ok: [10.50.9.10]
ok: [10.50.9.23]
ok: [10.50.9.22]

TASK [Stop & remove etcd container] **************************************************************************************************************
changed: [10.50.9.22]
changed: [10.50.9.23]
changed: [10.50.9.10]

TASK [pause] *************************************************************************************************************************************
Pausing for 15 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [10.50.9.10]

TASK [Remove etcd container] *********************************************************************************************************************
changed: [10.50.9.23]
changed: [10.50.9.10]
changed: [10.50.9.22]

TASK [load etcd settings] ************************************************************************************************************************
ok: [10.50.9.10]
ok: [10.50.9.23]
ok: [10.50.9.22]

TASK [Stop & remove hpedockerplugin container] ***************************************************************************************************
changed: [10.50.9.23]
changed: [10.50.9.10]
changed: [10.50.9.22]

TASK [pause] *************************************************************************************************************************************
Pausing for 15 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [10.50.9.10]

TASK [Remove hpedockerplugin container] **********************************************************************************************************
changed: [10.50.9.23]
changed: [10.50.9.10]
changed: [10.50.9.22]

TASK [stop multipath services, also issue daemon-reload to pick up config changes] ***************************************************************
ok: [10.50.9.22] => (item=iscsid)
ok: [10.50.9.23] => (item=iscsid)
changed: [10.50.9.10] => (item=iscsid)
ok: [10.50.9.23] => (item=multipathd)
ok: [10.50.9.22] => (item=multipathd)
changed: [10.50.9.10] => (item=multipathd)

TASK [pause] *************************************************************************************************************************************
Pausing for 10 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [10.50.9.10]

TASK [remove multipath.conf file] ****************************************************************************************************************
changed: [10.50.9.10]
ok: [10.50.9.23]
ok: [10.50.9.22]

TASK [remove hpe.conf file] **********************************************************************************************************************
changed: [10.50.9.10]
changed: [10.50.9.23]
changed: [10.50.9.22]

PLAY [Remove HPE 3PAR Volume Driver for Kubernetes/OpenShift] ************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [10.50.9.10]

TASK [Check that the doryd.service file exists] **************************************************************************************************
ok: [10.50.9.10]

TASK [stop doryd service, also issue daemon-reload to pick up config changes] ********************************************************************
skipping: [10.50.9.10]

TASK [pause] *************************************************************************************************************************************
Pausing for 5 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [10.50.9.10]

TASK [remove doryd files] ************************************************************************************************************************
ok: [10.50.9.10]

PLAY [Uninstall HPE 3PAR Volume Driver for Kubernetes/OpenShift] *********************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************
ok: [10.50.9.10]
ok: [10.50.9.23]
ok: [10.50.9.22]

TASK [Get all doryd files] ***********************************************************************************************************************
ok: [10.50.9.10]
ok: [10.50.9.22]
ok: [10.50.9.23]

TASK [remove doryd files] ************************************************************************************************************************
changed: [10.50.9.10] => (item=0)
changed: [10.50.9.23] => (item=0)
changed: [10.50.9.22] => (item=0)
changed: [10.50.9.10] => (item=1)
changed: [10.50.9.23] => (item=1)
changed: [10.50.9.22] => (item=1)
changed: [10.50.9.23] => (item=2)
changed: [10.50.9.10] => (item=2)
changed: [10.50.9.22] => (item=2)
ok: [10.50.9.23] => (item=3)
ok: [10.50.9.10] => (item=3)
ok: [10.50.9.22] => (item=3)

TASK [Get all sock files] ************************************************************************************************************************
ok: [10.50.9.10]
ok: [10.50.9.23]
ok: [10.50.9.22]

TASK [Delete any existing sock files] ************************************************************************************************************
skipping: [10.50.9.10] => (item=0)
skipping: [10.50.9.23] => (item=0)
skipping: [10.50.9.22] => (item=0)

PLAY RECAP ***************************************************************************************************************************************
10.50.9.10                 : ok=22   changed=8    unreachable=0    failed=0
10.50.9.22                 : ok=15   changed=6    unreachable=0    failed=0
10.50.9.23                 : ok=15   changed=6    unreachable=0    failed=0

[root@master-node ansible_3par_docker_plugin]# docker ps | grep plugin
[root@master-node ansible_3par_docker_plugin]#
