### ISSUE TITLE
Unable to clone this directory 

### ISSUE THREAD

**Issue by Acidguy** [hpe-storage/python-hpedockerplugin#464]
Hi Team 
Unable to clone this directory
![image](https://user-images.githubusercontent.com/19946397/51908438-df2dfe00-23ef-11e9-91cf-19724cb8633a.png)

**Comment by wdurairaj** [comment]
this behaviour is same with other github.com projects as well. So I don't think so we can do much about that .. Clone the top level repository as a workaround to overcome this problem

Another repository which had the similar partial clone issue is
```
docker@csosbe03b10:/tmp$ git clone https://github.com/cinder/Cinder/tree/master/tools
Cloning into 'tools'...
fatal: repository 'https://github.com/cinder/Cinder/tree/master/tools/' not found
docker@csosbe03b10:/tmp$ git clone https://github.com/cinder/Cinder/
Cloning into 'Cinder'...
remote: Enumerating objects: 108449, done.
^Cceiving objects:  13% (14099/108449), 66.38 MiB | 2.43 MiB/s
```
