### ISSUE TITLE
Port conflict using automated installer 

### ISSUE THREAD

**Issue by Acidguy** [hpe-storage/python-hpedockerplugin#467]
automated installer port is conflicting ports and the portupdate is not happening even after updating the porperties files

**Comment by prablr79** [comment]
is this reproducible ? are you talking about ETCD ports here ? can you provide some details about the defect ?

**Comment by Acidguy** [comment]
yes it is reproducible 
we talking the ports for the etcd 
The workaround is to manually edit the etcd properties

**Comment by prablr79** [comment]
@Acidguy will address in  upcoming release

**Comment by farhan7500** [comment]
@Acidguy  I am looking into this.

**Comment by farhan7500** [comment]
@Acidguy This issue is fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/526 

Please await the merge and verify the fix

**Comment by prablr79** [comment]
@Acidguy , if you are finding this issue again please feel free to re-open this issue.
