### ISSUE TITLE
Sometimes "PVC" is not deleted

### ISSUE THREAD

**Issue by jeonghakw** [hpe-storage/python-hpedockerplugin#469]
When multiple PVs are simultaneously deleted, some PVs cannot be deleted as shown below.
We have created and deleted dozens of PVs using Yaml below.
There was a symptom that couldn't be deleted normally. 
Was it Bug? Can I avoid it?
---------------------------------------
thin_sc.yml : Storage Class yaml
---------------------------------------
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: thin
provisioner: hpe.com/hpe
parameters:
provisioning: "thin"
==============================================================
  make-pvc.sh : create 20 pvc
---------------------------------------
#!/bin/bash

for i in {001..020}
do
cat > ./pvc-$i.yaml << EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
     name: pvc-$i
spec:
     accessModes:
       - ReadWriteOnce
     resources:
       requests:
         storage: 1Gi
     storageClassName: thin
EOF
done
==============================================================
   # ls
make-pvc.sh   pvc-002.yaml  pvc-004.yaml  pvc-006.yaml  pvc-008.yaml  pvc-010.yaml  pvc-012.yaml  pvc-014.yaml  pvc-016.yaml  pvc-018.yaml  pvc-020.yaml
pvc-001.yaml  pvc-003.yaml  pvc-005.yaml  pvc-007.yaml  pvc-009.yaml  pvc-011.yaml  pvc-013.yaml  pvc-015.yaml  pvc-017.yaml  pvc-019.yaml

# kubectl apply -f ./   ==>  successfully created

==============================================================
# kubectl delete -f ./   ==>  Not successfully deleted (only partially deleted)
# kubectl delete pvc --all    ==>  Not successfully deleted

 *. Restarting "doryd" removes several more PVCs

**Comment by prablr79** [comment]
@nilangekarss is this tested in house, i remember testing multiple delete in our environment, can we quickly cross verify this ?

**Comment by prablr79** [comment]
@testteam can you quickly confirm this scenario ?

**Comment by sandesh-desai** [comment]
Verified and its working as expected.
Attaching the logs.
[pvc logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2905301/pvc.logs.txt)

@prablr79 :  Please close the bug.

**Comment by wdurairaj** [comment]
@sandesh-desai , will keep this bug, until we rollout a new flexvolume driver.

**Comment by wdurairaj** [comment]
Steps to install new flexvolume binary installer
```
1.	wget https://github.com/hpe-storage/python-hpedockerplugin/raw/master/dory_installer_v31 
2.	chmod u+x ./dory_installer_v31
3.	./dory_installer_v31 (type “yes” for the end user agreement, and the installation is done).
```

**Comment by wdurairaj** [comment]
Above steps needs to be done on all nodes.

**Comment by sandesh-desai** [comment]
Install new flexvolume driver dory_installer_v31
Verified and working as expected.
Attaching the logs.
[PVC delete logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3063675/PVC.delete.logs.txt)

**Comment by sandesh-desai** [comment]
@prablr79 : Please close the bug.

**Comment by wdurairaj** [comment]
Closing based on latest test results with new dory binary dory_installer_v31.
