### ISSUE TITLE
Kubernetes: Automated Plugin Install Issue while copying config file

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#478]
I tried installing plugin on my Kubernetes setup using automated scripts.
I end up with the below error.

TASK [Verify /etc/kubernetes/admin.conf exists] **************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/tmp/config'
fatal: [10.50.9.10]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/config'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/tmp/config'
fatal: [10.50.9.23]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/config'"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/tmp/config'
fatal: [10.50.9.22]: FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/config'"}
        to retry, use: --limit @/root/python-hpedockerplugin/ansible_3par_docker_plugin/install_hpe_3par_volume_driver.retry

PLAY RECAP ***************************************************************************************************************************************
10.50.9.10                 : ok=52   changed=22   unreachable=0    failed=1
10.50.9.22                 : ok=51   changed=22   unreachable=0    failed=1
10.50.9.23                 : ok=51   changed=22   unreachable=0    failed=1
localhost                  : ok=2    changed=0    unreachable=0    failed=0

My Setup details 
10.50.9.10 – Master
10.50.9.23 – Worker1
10.50.9.22 – Worker2

Cluster is up and all nodes are in ready state.

[root@kuber-master ~]# kubectl get nodes
NAME             STATUS   ROLES    AGE     VERSION
kuber-master     Ready    master   5h18m   v1.13.3
kuber-worker-1   Ready    <none>   5h17m   v1.13.3
kuber-worker-2   Ready    <none>   5h17m   v1.13.3
[root@kuber-master ~]#

Please look into it. I am keeping the setup as is for you to look into it.

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/477

**Comment by sonawane-shashikant** [comment]
This bug is verified as a part of Bug#541 verification.
Closing as FIXED.
