### ISSUE TITLE
Docker restart fails on nodes 

### ISSUE THREAD

**Issue by Acidguy** [hpe-storage/python-hpedockerplugin#479]
TASK [restart docker service, also issue daemon-reload to pick up config changes] *****************************************************************************

fatal: [10.0.8.135]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service docker.service: Job for docker.service invalid.\n"}
As per my understanding Job for docker.service invalid.\n"} happens when the service is present or has been called inapproriately  

This is Greenfield setup    

when the script(Playbook)  is running the service restart on the node fails to respond to 
systemctl restart docker.service 

before the running the plugin script 
systemctl restart docker.service  works fine 

seems like know issue 
https://github.com/moby/moby/issues/31997 
https://github.com/moby/moby/blob/v17.03.2-ce/container/stream/streams.go#L119

**Comment by prablr79** [comment]
@Team, is this observed in our internal testing ?

**Comment by prablr79** [comment]
This is not a Plugin bug, please open Docker bug

**Comment by prablr79** [comment]
Please work with Docker on this issue, this is not related to 3PAR Plugin hence closing this bug.
