### ISSUE TITLE
Plugin container going in restarting state

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#493]
Tried to install plugin "hpestorage/legacyvolumeplugin:2.1" but container corresponds to plugin going in restarting state.

Steps performed:
===========
1) Uninstall script executed to cleanup existing plugin.
2) Updated plugin tag "hpestorage/legacyvolumeplugin:2.1" in inventory file.
3) Executed install plugin script.

Output of plugin post install script:
=======================
[root@cssosbe03-b12-worker1 ~]# docker ps -a | grep etcd
fa17c0712c95        quay.io/coreos/etcd:v2.2.0          "/etcd"                  5 days ago           Up About a minute                       2379-2380/tcp, 4001/tcp, 0.0.0.0:23790->23790/tcp, 0.0.0.0:23800->23800/tcp, 7001/tcp, 0.0.0.0:40010->40010/tcp   etcd_hpe
[root@cssosbe03-b12-worker1 ~]# docker ps -a | grep legacyvolumeplugin:2.1
8857501eb65e        hpestorage/legacyvolumeplugin:2.1   "/bin/sh -c ./plug..."   48 seconds ago       Restarting (1) 13 seconds ago                                                                                                                     plugin_container

Note:- It is observed that plugin goes in restarting state in all of node in cluster.

**Comment by farhan7500** [comment]
The automated installer is designed to support plugin version 3.0 and above. It has not been tested on plugin 2.1

Please comment below in case you see the same behaviour on version 3.0 or the latest code base

**Comment by virendra-sharma** [comment]
Issues reproduced in plugin 2.1 and as per above @farhan7500 comment it is as per design.
Tried with plugin 3.0 and it worked well, hence closing this issue.
