### ISSUE TITLE
etcd going in restarting state

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#494]
manually deleted etcd from one of node in cluster and wanted to get it install as earlier through installer.
observation is etcd get installed but it is going it restarting state.

Steps performed:
===========
1) all node etcd and plugin working well.
2) deleted etcd from one of node.
3) executed uninstall script.
4) executed install script with earlier configuration of etcd cluster.
5) ectd get's installed on required node cluster but container of etcd went in restarting state.

**Comment by farhan7500** [comment]
@virendra-sharma Verified the defect, working on it

**Comment by farhan7500** [comment]
@prablr79 @wdurairaj This defect is being tracked as part of a new [user story ](https://pro.jira.g4ihos.itcs.hpecorp.net:8443/secure/RapidBoard.jspa?rapidView=768&projectKey=CIDG&view=detail&selectedIssue=CIDG-417) in this sprint. SHould this still be classified as High?

**Comment by prablr79** [comment]
WIP

**Comment by farhan7500** [comment]
Added this as a limitation in the installer documentation at https://github.com/hpe-storage/python-hpedockerplugin/pull/582

**Comment by prablr79** [comment]
CIDG 417 is opened as New story to track this bug as well.

**Comment by virendra-sharma** [comment]
As discussed, user story CIDG-417 created to implement this feature. hence closing this issue.
