### ISSUE TITLE
Ansible Installer : observed issue with importvol after plugin upgrade

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#495]
Unable to import volume from default backend after plugin upgrade.

Error:
====
MountVolume.SetUp failed for volume "pv-import-volume1" : mount command failed, status: Failure, reason: Volume:Test_vol1 does not exists Error: Not found (HTTP 404) 23 - volume does not exist

Steps performed:
===========
1) Installed plugin 3.0 tag with default backend through installer.
2) Imported volume (Test_vol) & performed multicpg feature, it suceeded.
3) Upgraded plugin by updating inventory file as "plugin_v2" tag with default backend configuration only.
4) Tried to import volume (Test_vol) but pod not coming in running state.

Status of pv,pvc,pod:
=============
[root@cssosbe03-b01-master ansible_3par_docker_plugin]# kubectl get pv,pvc,pod
NAME                                                           CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                    STORAGECLASS   REASON   AGE
persistentvolume/mysc10-d555806c-3ff9-11e9-8e82-9cdc71787200   10Gi       RWO            Delete           Bound    default/pvc-multicpg     mysc10                  18m
persistentvolume/pv-import-volume                              35Gi       RWO            Retain           Bound    default/pvc-importvol                            19m
persistentvolume/pv-import-volume1                             35Gi       RWO            Retain           Bound    default/pvc-importvol1                           11m

NAME                                   STATUS   VOLUME                                        CAPACITY   ACCESS MODES   STORAGECLASS   AGE
persistentvolumeclaim/pvc-importvol    Bound    pv-import-volume                              35Gi       RWO                           19m
persistentvolumeclaim/pvc-importvol1   Bound    pv-import-volume1                             35Gi       RWO                           11m
persistentvolumeclaim/pvc-multicpg     Bound    mysc10-d555806c-3ff9-11e9-8e82-9cdc71787200   10Gi       RWO            mysc10         18m

NAME                 READY   STATUS              RESTARTS   AGE
pod/pod-importvol    1/1     Running             1          19m
pod/pod-importvol1   0/1     ContainerCreating   0          10m
pod/pod-multicpg     1/1     Running             1          17m

Pod describe log:
===========
[pod describe.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2935732/pod.describe.txt)

YAML's used:
========
[YAML's for importvol issue.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2935741/YAML.s.for.importvol.issue.txt)

HPE.CONF used for both plugin (3.0 & plugin_v2)
================================
[DEFAULT]
host_etcd_ip_address=192.168.68.31:23790,192.168.68.42:23790,192.168.68.45:23790
host_etcd_port_number=23790
hpe3par_username=3paradm
hpe3par_password=wy4a8PYh4IY=
hpe3par_cpg=VIREN
hpedockerplugin_driver=hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
logging=DEBUG
hpe3par_snapcpg=VIREN-SNAP
san_ip=192.168.67.5
san_login=3paradm
san_password=wy4a8PYh4IY=
hpe3par_api_url=https://192.168.67.5:8080/api/v1
hpe3par_iscsi_ips=192.168.68.202

**Comment by prablr79** [comment]
Farhan can you quickly look into this bug ?

**Comment by prablr79** [comment]
@farhan7500 any update on this bug ?  are we seeing in multiple environments ?

**Comment by shaik-gousa-khaja-asif** [comment]
Tested with recent ansible installer code :  
1. Create volume Test_vol1 on 3par 
2. Successfully installed hpestorage/legacyvolumeplugin:3.0 from ansible installer
3. Created pv,pvc and pod [pod came to running state & volume was renamed to IMPORTED-VOLUME1]
4. Again created another volume Test_vol1 on 3par
5.  uccessfully installed hpestorage/legacyvolumeplugin:3.1 from ansible installer
6. Created pv,pvc and pod

Result : pod does come into running state . No failure as - "Test_vol1 does not exists Error: Not found (HTTP 404) 23 - volume does not exist" was observed

**Comment by virendra-sharma** [comment]
Closing as per above comment.
