### ISSUE TITLE
Sample configs should provide driver entry

### ISSUE THREAD

**Issue by ddefolo** [hpe-storage/python-hpedockerplugin#5]
With the move to delivering the plugin in a container the driver path should be directly specified for both the 3par and VSA config file samples.

For example, instead of this in the 3par sample config:

> # hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
> 
> hpedockerplugin_driver = <path to driver class definition> 

The actual standard path should be provided for 3par:

> hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver

And the standard path should be provided for VSA/lefthand:

> hpedockerplugin_driver = hpedockerplugin.hpe.hpe_lefthand_iscsi.HPELeftHandISCSIDriver

With the move to containers I would expect this setting will not need to be modified 99.9% of the time and should be kept in sync the plugin container.  Normal users won't be snooping inside the container to try to specify an alternate driver path.

**Comment by garthmbooth** [comment]
Resolved in v1.1.0 release.
