### ISSUE TITLE
Volume mount fails with single path when multipath parameters are not configured in hpe.conf

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#50]
1. Single Zone was created and enabled in FC switch.
2. use_multipath and enforce_multipath parameters were omitted from hpe.conf.
3. FC plugin was installed with tag: hpestorage/hpedockervolumeplugin:2.0 
4. Volume was created successfully with default properties (thin provisioning, 100 GB size).
5. Mounting volume failed with below error:

<span>hpedockerplugin.exception.HPEPluginFileSystemException</span>: <span>HPE Docker Volume Plugin File System error: (u'create file system failed exception is : %s', u'\n\n  RAN: /sbin/mkfs -F /dev/sdb\n\n  STDOUT:\n\n\n  STDERR:\nmke2fs 1.43.4 (31-Jan-2017)\n/dev/sdb is apparently in use by the system; will not make a filesystem here!\n')</span>

6. LUN was present in docker host:

docker@csimbe06-b07:~$ ls -lrt /dev/disk/by-path
total 0
lrwxrwxrwx 1 root root  9 Aug  2 03:48 pci-0000:03:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Aug  2 03:48 pci-0000:03:00.0-scsi-0:1:0:0-part3 -> ../../sda3
lrwxrwxrwx 1 root root 10 Aug  2 03:48 pci-0000:03:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Aug  2 03:48 pci-0000:03:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root  9 Aug  2 04:03 pci-0000:21:00.2-fc-0x20020002ac019d52-lun-0 -> ../../sdb

7. VLUN was present in 3par array:

CSIM-8K02_MXN6072AC7 cli% showvlun -host csimbe06-b07
Active VLUNs
Lun VVName                     HostName     -Host_WWN/iSCSI_Name-  Port        Type Status ID
  0 dcv-mO4WBGTvTievrurT6n3kXw csimbe06-b07 100038EAA730D4E9      0:0:2 matched set active  1
---------------------------------------------------------------------------------------------
  1 total

VLUN Templates
Lun VVName                     HostName     -Host_WWN/iSCSI_Name-  Port        Type
  0 dcv-mO4WBGTvTievrurT6n3kXw csimbe06-b07 ----------------      0:0:2 matched set
-----------------------------------------------------------------------------------
  1 total

8. Deleting volume failed as vlun was present in 3par array.
9. Removed VLUN manually from 3par array.
10. Deletion of volume was successful after that.
11. Disabled the plugin.
12. use_multipath and enforce_multipath parameters were set to true in hpe.conf
13. Enabled the plugin and new volume was created successfully after that.
14. Mounting new volume failed with below error:

<span>hpedockerplugin.exception.HPEPluginMakeDirException</span>: <span>HPE Docker Volume Plugin Makedir Failed: (u'Make directory failed exception is : %s', u'list index out of range')</span>
 
15. Further observations were similar to steps 6-10.

**Comment by sumitshatwara** [comment]
Observed the same issue with 3par iSCSI plugin as well.

**Comment by hpe-storage** [comment]
Address as part of 2.0.1 
Use
`docker plugin install store/hpestorage/hpedockervolumeplugin:2.0.1`
