### ISSUE TITLE
Volume mount suceeded without it's corresponding backend in hpe.conf

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#502]
Steps performed
===========
1) Added backend through installer.
2) Create pv,pvc,pod.
3) Removed backend through installer.
4) Tried to mount volume of additional backend, it succeeded.

Observation
========
1) Additional backend volume able to mount, even after removing backend from hpe.conf and plugin restart.
2) container created during pod creation is able to come up after removing it's corresponding backend and restarting container. (Usually after removing backend and plugin restart, existing container won't come up, because it's backend removed).
3) After remove backend from installer, existing pod remains in running state.
4) Unable to delete volume, even after using docker volume rm -f command too. 

Expected
======
1) Volume should not be mount after removing it's corresponding backend.
2) Mounted container should be running until it's stopped manually, but after removing it's backend and restarting plugin, this container should not be running after restarting it.

Please find below logs for pv,pvc,pod when additional backend presents.
[creation of pv,pvc,pod.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960703/creation.of.pv.pvc.pod.txt)
[pv,pvc,mount with backend exist (doryd log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960704/pv.pvc.mount.with.backend.exist.doryd.log.txt)
[pv,pvc,mount with backend exist (message log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960706/pv.pvc.mount.with.backend.exist.message.log.txt)
[pv,pvc,mount with backend exist (container log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960709/pv.pvc.mount.with.backend.exist.container.log.txt)

Logs for volume mount after removing backend:
[Steps logs of mount vol after backend remove.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960711/Steps.logs.of.mount.vol.after.backend.remove.txt)
[mount volume after backend remove (container logs).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960713/mount.volume.after.backend.remove.container.logs.txt)
[Mount vol after backend remove(messages log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960715/Mount.vol.after.backend.remove.messages.log.txt)
[mount vol after backend remove (doryd_log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960717/mount.vol.after.backend.remove.doryd_log.txt)

Logs for container pod container stop start after removing backend:
[steps for stop and start pod container after bakend remove.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960718/steps.for.stop.and.start.pod.container.after.bakend.remove.txt)
[stop and start of conatiner of pod after backend remove(dory log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960719/stop.and.start.of.conatiner.of.pod.after.backend.remove.dory.log.txt)
[stop and start of conatiner of pod after backend remove(message log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960721/stop.and.start.of.conatiner.of.pod.after.backend.remove.message.log.txt)
[stop and start of conatiner of pod after backend remove(container log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960724/stop.and.start.of.conatiner.of.pod.after.backend.remove.container.log.txt)

Logs for volume create with -o backend after removing additional backend:
[create volume without having additional backend (docker log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960728/create.volume.without.having.additional.backend.docker.log.txt)
[create volume without having additional backend (message log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960729/create.volume.without.having.additional.backend.message.log.txt)
[create volume without having additional backend (container log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960730/create.volume.without.having.additional.backend.container.log.txt)

Logs for snapshot & clone create from existing volume of additional backend:
[snapshot & clone of volume after backend remove (message log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960731/snapshot.clone.of.volume.after.backend.remove.message.log.txt)
[snapshot & clone of volume after backend remove (docker log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960735/snapshot.clone.of.volume.after.backend.remove.docker.log.txt)
[snapshot & clone of volume after backend remove (container log).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2960736/snapshot.clone.of.volume.after.backend.remove.container.log.txt)

**Comment by nilangekarss** [comment]
@virendra-sharma are you able to create volume or snapshots on the removed backend.

**Comment by nilangekarss** [comment]
@virendra-sharma can you also attach dory and container logs

**Comment by virendra-sharma** [comment]
@nilangekarss As discussed over skype chat, i have uploaded all the requested logs to issue.

**Comment by imran-ansari** [comment]
@virendra-sharma - after step 3, can you restart the plugin manually and then try to mount the volume?

**Comment by virendra-sharma** [comment]
@imran-ansari 
Please find below observation.
1) After removing and restarting plugin, mounted existing volume without specifying driver and volume mounted. I was under impression that existing volume mounted but it was overridden existing volume to local volume. 
2) When tried to mount volume after specifying driver, getting exception as "error while mounting volume '/': 'NoneType' object is not subscriptable"", message is not clear.
3) In all this steps volume created during additional backend is still visible in "docker volume ls" command after that backend but while inspecting that volume getting error as "Error: No such volume: VOLUME1".

Please find docker log for the same.
[error.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3033348/error.txt)

**Comment by prablr79** [comment]
@imran-ansari please take a look

**Comment by virendra-sharma** [comment]
@imran-ansari @prablr79 
I can see issue resolved from docker, like I am getting appropriate error message while doing mount of non exisiting backend volume.

But still i can see problem from kubernetes front.
1) Container created by pod is still running after removing backend and restarting plugin. Even i tried to stop running container but it come up again after few seconds.
2) I observed that mount entry in "multipath -ll" remains same after stopping running container of pod.
3) Seems as container stop not unmounting corresponding volume.
4) Tried to gather log for this activity but couldn't see any log getting generated, logs not generating neither in docker nor in plugin logs.

Still I will give one more try by cleaning up my setup completely, will re-produce same and share observation, if anything changed.

**Comment by virendra-sharma** [comment]
@imran-ansari  please find log after stopping running container of pod, which comes up automatically. (without having specific backend in hpe.conf)

```
Apr 11 02:43:26 cld6b16 dbus[8017]: [system] Activating service name='org.freedesktop.problems' (using servicehelper)
Apr 11 02:43:26 cld6b16 dbus[8017]: [system] Successfully activated service 'org.freedesktop.problems'
Apr 11 02:43:46 cld6b16 kubelet: E0411 02:43:46.955562   45233 pod_workers.go:186] Error syncing pod 10fcd531-5c24-11e9-8723-10604b98ece8 ("pod-import_default(10fcd531-5c24-11e9-8723-10604b98ece8)"), skipping: failed to "StartContainer" for "nginx" with CrashLoopBackOff: "Back-off 10s restarting failed container=nginx pod=pod-import_default(10fcd531-5c24-11e9-8723-10604b98ece8)"
Apr 11 02:43:47 cld6b16 kubelet: E0411 02:43:47.012694   45233 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: du command failed on /var/lib/docker/overlay2/f1f397ef0c77df710aea9c07ed1829718f81a1e33ab785ac7a996aa028af6873/diff with output stdout: , stderr: du: cannot access ‘/var/lib/docker/overlay2/f1f397ef0c77df710aea9c07ed1829718f81a1e33ab785ac7a996aa028af6873/diff’: No such file or directory
Apr 11 02:43:47 cld6b16 kubelet: - exit status 1, rootInodeErr: cmd [ionice -c3 nice -n 19 find /var/lib/docker/overlay2/f1f397ef0c77df710aea9c07ed1829718f81a1e33ab785ac7a996aa028af6873/diff -xdev -printf .] failed. stderr: find: ‘/var/lib/docker/overlay2/f1f397ef0c77df710aea9c07ed1829718f81a1e33ab785ac7a996aa028af6873/diff’: No such file or directory
Apr 11 02:43:47 cld6b16 kubelet: ; err: exit status 1, extraDiskErr: du command failed on /var/lib/docker/containers/1038583c88cec670fa18e4a55843701d3074be708a62c835a2dff02020806106 with output stdout: , stderr: du: cannot access ‘/var/lib/docker/containers/1038583c88cec670fa18e4a55843701d3074be708a62c835a2dff02020806106’: No such file or directory
Apr 11 02:43:47 cld6b16 kubelet: - exit status 1
Apr 11 02:44:01 cld6b16 dockerd: time="2019-04-11T02:44:01.604243510-04:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container 836e35599843356633ec9d6ee20b183e504f2eed5a67b578018ed66060bf2b48"
Apr 11 02:44:43 cld6b16 kubelet: E0411 02:44:43.216850   45233 pod_workers.go:186] Error syncing pod 10fcd531-5c24-11e9-8723-10604b98ece8 ("pod-import_default(10fcd531-5c24-11e9-8723-10604b98ece8)"), skipping: failed to "StartContainer" for "nginx" with CrashLoopBackOff: "Back-off 20s restarting failed container=nginx pod=pod-import_default(10fcd531-5c24-11e9-8723-10604b98ece8)"
Apr 11 02:44:57 cld6b16 kubelet: E0411 02:44:57.924986   45233 pod_workers.go:186] Error syncing pod 10fcd531-5c24-11e9-8723-10604b98ece8 ("pod-import_default(10fcd531-5c24-11e9-8723-10604b98ece8)"), skipping: failed to "StartContainer" for "nginx" with CrashLoopBackOff: "Back-off 20s restarting failed container=nginx pod=pod-import_default(10fcd531-5c24-11e9-8723-10604b98ece8)"
Apr 11 02:45:10 cld6b16 dockerd: time="2019-04-11T02:45:10.548095340-04:00" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container 2694f8367a057d134398cae58ca38349d0ea0f5dd477f5197d676e185726f823"
Apr 11 02:45:26 cld6b16 kubelet: I0411 02:45:26.167691   45233 reconciler.go:181] operationExecutor.UnmountVolume started for volume "export" (UniqueName: "flexvolume-hpe.com/hpe/300ec9cd-5b5d-11e9-8723-10604b98ece8-pv-import-volume") pod "300ec9cd-5b5d-11e9-8723-10604b98ece8" (UID: "300ec9cd-5b5d-11e9-8723-10604b98ece8")
Apr 11 02:45:26 cld6b16 kubelet: E0411 02:45:26.177334   45233 driver-call.go:258] unmount command failed, status: Failure, reason: rc=32
Apr 11 02:45:26 cld6b16 kubelet: E0411 02:45:26.177413   45233 nestedpendingoperations.go:267] Operation for "\"flexvolume-hpe.com/hpe/300ec9cd-5b5d-11e9-8723-10604b98ece8-pv-import-volume\" (\"300ec9cd-5b5d-11e9-8723-10604b98ece8\")" failed. No retries permitted until 2019-04-11 02:47:28.177380727 -0400 EDT m=+1109975.455394767 (durationBeforeRetry 2m2s). Error: "UnmountVolume.TearDown failed for volume \"export\" (UniqueName: \"flexvolume-hpe.com/hpe/300ec9cd-5b5d-11e9-8723-10604b98ece8-pv-import-volume\") pod \"300ec9cd-5b5d-11e9-8723-10604b98ece8\" (UID: \"300ec9cd-5b5d-11e9-8723-10604b98ece8\") : unmount command failed, status: Failure, reason: rc=32"
Apr 11 02:47:28 cld6b16 kubelet: I0411 02:47:28.267696   45233 reconciler.go:181] operationExecutor.UnmountVolume started for volume "export" (UniqueName: "flexvolume-hpe.com/hpe/300ec9cd-5b5d-11e9-8723-10604b98ece8-pv-import-volume") pod "300ec9cd-5b5d-11e9-8723-10604b98ece8" (UID: "300ec9cd-5b5d-11e9-8723-10604b98ece8")
```

**Comment by virendra-sharma** [comment]
As per below log, it is evident that Docker is returning appropriate error. However, Dory doesn't seem to handle it properly by marking the POD as failed. hence raised dory issue, which can be referred at https://github.com/hpe-storage/dory/issues/51.

Please find below log for the same.
```
2019-04-12 06:04:02.858 21 INFO hpedockerplugin.backend_orchestrator [-] Getting details for volume : IMPORTED-VOLUME
2019-04-12 06:04:02.858 21 DEBUG etcd.client [-] Issuing read for key /volumes/ with args {'recursive': True} read /usr/lib/python3.6/site-packages/python_etcd-0.4.5-py3.6.egg/etcd/client.py:582
2019-04-12 06:04:02.860 21 INFO hpedockerplugin.etcdutil [-] Get volbyname: volname is IMPORTED-VOLUME
2019-04-12 06:04:02.862 21 DEBUG hpedockerplugin.backend_orchestrator [-]  Populating cache IMPORTED-VOLUME, 3PAR1  add_cache_entry /python-hpedockerplugin/hpedockerplugin/backend_orchestrator.py:131
2019-04-12 06:04:02.862 21 INFO hpedockerplugin.backend_orchestrator [-]  Operating on backend : 3PAR1 on volume IMPORTED-VOLUME
2019-04-12 06:04:02.862 21 INFO hpedockerplugin.backend_orchestrator [-]  Request get_volume_snap_details
2019-04-12 06:04:02.862 21 INFO hpedockerplugin.backend_orchestrator [-]  with  args (None, 'IMPORTED-VOLUME')
2019-04-12 06:04:02.863 21 INFO hpedockerplugin.backend_orchestrator [-]  with  kwargs is {}
2019-04-12 06:04:02.863 21 ERROR hpedockerplugin.backend_orchestrator [-] ERROR: Backend '3PAR1' was NOT initialized successfully. Please check hpe.conf for incorrect entries and rectify it.
2019-04-12T06:04:02+0000 [twisted.python.log#info] "-" - - [12/Apr/2019:06:04:01 +0000] "POST /VolumeDriver.Get HTTP/1.1" 200 127 "-" "Go-http-client/1.1"
2019-04-12T06:05:02+0000 [twisted.web.http.HTTPChannel#info] Timing out client: UNIXAddress(None)
2019-04-12T06:05:25+0000 [twisted.python.log#info] "-" - - [12/Apr/2019:06:05:25 +0000] "POST /VolumeDriver.Capabilities HTTP/1.1" 200 37 "-" "Go-http-client/1.1"
2019-04-12 06:05:48.044 21 INFO hpedockerplugin.backend_orchestrator [-] Getting details for volume : IMPORTED-VOLUME
2019-04-12 06:05:48.045 21 DEBUG hpedockerplugin.backend_orchestrator [-]  Returning the backend details from cache IMPORTED-VOLUME , 3PAR1 get_volume_backend_details /python-hpedockerplugin/hpedockerplugin/backend_orchestrator.py:116
2019-04-12 06:05:48.045 21 INFO hpedockerplugin.backend_orchestrator [-]  Operating on backend : 3PAR1 on volume IMPORTED-VOLUME
2019-04-12 06:05:48.045 21 INFO hpedockerplugin.backend_orchestrator [-]  Request get_volume_snap_details
2019-04-12 06:05:48.046 21 INFO hpedockerplugin.backend_orchestrator [-]  with  args (None, 'IMPORTED-VOLUME')
2019-04-12 06:05:48.046 21 INFO hpedockerplugin.backend_orchestrator [-]  with  kwargs is {}
2019-04-12 06:05:48.046 21 ERROR hpedockerplugin.backend_orchestrator [-] ERROR: Backend '3PAR1' was NOT initialized successfully. Please check hpe.conf for incorrect entries and rectify it.
2019-04-12T06:05:48+0000 [twisted.python.log#info] "-" - - [12/Apr/2019:06:05:47 +0000] "POST /VolumeDriver.Get HTTP/1.1" 200 127 "-" "Go-http-client/1.1"
2019-04-12T06:06:48+0000 [twisted.web.http.HTTPChannel#info] Timing out client: UNIXAddress(None)
```

**Comment by virendra-sharma** [comment]
Issue is from dory side, hence we will tracking it from dory issue https://github.com/hpe-storage/dory/issues/51.

Hence closing this issue.
