### ISSUE TITLE
ssh_hosts_key_file must be a mandatory param in the installer properties file

### ISSUE THREAD

**Issue by farhan7500** [hpe-storage/python-hpedockerplugin#512]

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/514

**Comment by virendra-sharma** [comment]
Tested installer and it is taking default ssh key value in hpe.conf as documented. also path can be change as by providing it in inventory file before running installer.

**Comment by virendra-sharma** [comment]
can close this bug.
