### ISSUE TITLE
encrypted password decrytion fails when the passphrase length is of 16,24,32 characters

### ISSUE THREAD

**Issue by wdurairaj** [hpe-storage/python-hpedockerplugin#518]
key_check definition in https://github.com/hpe-storage/python-hpedockerplugin/blob/5e1fed9d1e568a4cd5903930d541b4834a2fa696/hpedockerplugin/volume_manager.py  has problem when passphrase length is 16,24,32

```
import string

def key_check( key):
   KEY_LEN = len(key)
   padding_string = string.ascii_letters

   if KEY_LEN < 16:
      KEY = key + padding_string[:16 - KEY_LEN]

   elif KEY_LEN > 16 and KEY_LEN < 24:
      KEY = key + padding_string[:24 - KEY_LEN]

   elif KEY_LEN > 24 and KEY_LEN < 32:
      KEY = key + padding_string[:32 - KEY_LEN]

   elif KEY_LEN > 32:
      KEY = key[:32]

   return KEY


return_val = key_check('thisisapassphras')
print return_val

```

```
Output of execution:

python test.py 
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    return_val = key_check('thisisapassphras')
  File "test.py", line 19, in key_check
    return KEY
UnboundLocalError: local variable 'KEY' referenced before assignment 
```

**Comment by sneharai4** [comment]
Fix given https://github.com/hpe-storage/python-hpedockerplugin/pull/551

**Comment by sonawane-shashikant** [comment]
Fix is not available in 3.1 tag
Will verify again,  once the fix is available in 3.1

**Comment by wdurairaj** [comment]
@sonawane-shashikant , can you do a 
`docker rmi -f <plugin_container_image>`
and then do
`docker pull <tag>`

I confirmed the fix is available as part of 3.1

**Comment by sonawane-shashikant** [comment]
@wdurairaj Automated installer does not remove the images when we run Uninstall script.
I am going to log new issues for the same.

Verification of this bug is in progress and I'll update the same soon.

**Comment by sonawane-shashikant** [comment]
3PAR1:
#Mandatory Parameters-----------------------------------------------------------------------------------

    # Specify the port to be used by HPE 3PAR plugin etcd cluster
    host_etcd_port_number: 23790
    # Plugin Driver - Fibre Channel
    hpedockerplugin_driver: hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
    hpe3par_ip: 10.50.3.9
    hpe3par_username: 3paradm
    hpe3par_password: 3pardata
    hpe3par_cpg: SHASHI-SSD
    # Plugin version - Required only in DEFAULT backend
    #volume_plugin: hpestorage/legacyvolumeplugin:3.0

#Optional Parameters------------------------------------------------------------------------------------

    # Uncomment to encrypt passwords in hpe.conf using defined passphrase
    encryptor_key: SHASHIENCRYPTOR1
    ssh_hosts_key_file: '/root/.ssh/known_hosts'
    logging: DEBUG
    #hpe3par_debug: True
    #suppress_requests_ssl_warning: True
    hpe3par_snapcpg: SHASHI-CPG
    #use_multipath: False
    #enforce_multipath: False


[root@master-node ansible_3par_docker_plugin]# docker ps | grep plugin
2e575d8b6a7f        hpestorage/legacyvolumeplugin:3.1   "/bin/sh -c ./plug..."   2 minutes ago       Up 2 minutes                                                                                                                          plugin_container
[root@master-node ansible_3par_docker_plugin]# docker volume create -d hpe -o help=backends | grep 3PAR1
Error response from daemon: create 7dd7668c2c04540c06ee0b49ad827b3c1d594e5277d7711654a9f119950fee18:
======================================================
NAME                                          STATUS
======================================================
3PAR1                                          OK

**Comment by sneharai4** [comment]
@sonawane-shashikant Verified the fix and is working.
