### ISSUE TITLE
HPE plugin is not getting enabled with multiple etcd host addresses (unsecured connection) in hpe.conf file.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#52]
1.	Created six node setups: 3 manager and 3 worker nodes where worker1 points to manager1, worker2->manager2 and worker3->manager3

stack@manager1:~$ sudo docker-machine ls
NAME       ACTIVE   DRIVER    STATE     URL                      SWARM   DOCKER              ERRORS
manager1   -        generic   Running   tcp://10.50.0.158:2376           v17.06.1-ee-1-rc2
manager2   -        generic   Running   tcp://10.50.0.160:2376           v17.06.1-ee-1-rc2
manager3   -        generic   Running   tcp://10.50.0.161:2376           v17.06.1-ee-1-rc2
worker1    -        generic   Running   tcp://10.50.0.152:2376           v17.06.1-ee-1-rc2
worker2    -        generic   Running   tcp://10.50.0.153:2376           v17.06.1-ee-1-rc2
worker3    -        generic   Running   tcp://10.50.0.151:2376           v17.06.1-ee-1-rc2

stack@manager1:~$ docker node ls
ID                            HOSTNAME            STATUS              AVAILABILITY        MANAGER STATUS
0m1nfl0hrvdqopacrpqwy1o6x     manager3            Ready               Active              Reachable
8r3u0q14ewukyi5hn36373aec     worker3             Ready               Active
9up7fkn5a7ttadmuo9pjbz3hf     worker2             Ready               Active
mu0oahv39fstr095cv3e2fvsr     worker1             Ready               Active
pqm3kmytshyigjeyajsckf3qt     manager2            Ready               Active              Leader
uzs1ojqfnv9oessstff2zpxa9 *   manager1            Ready               Active              Reachable

2.	Created etcd cluster of manager nodes. Etcd containers are running in all manager nodes. Ref link: https://coreos.com/etcd/docs/latest/v2/docker_guide.html

3.	All the worker nodes (etcd clients) are configured with a list of etcd members:

docker@worker3:~$ sudo etcdctl -C http://10.50.0.158:2379,http://10.50.0.160:2379,http://10.50.0.161:2379 member list
47a90b0067012ba2: name=etcd0 peerURLs=http://10.50.0.158:2380 clientURLs=http://10.50.0.158:2379,http://10.50.0.158:4001
818db80633603eff: name=etcd1 peerURLs=http://10.50.0.160:2380 clientURLs=http://10.50.0.160:2379,http://10.50.0.160:4001
d7de76820fdffe95: name=etcd2 peerURLs=http://10.50.0.161:2380 clientURLs=http://10.50.0.161:2379,http://10.50.0.161:4001

4.	HPE volume plugin is installed in all worker nodes with disable state.

stack@worker1:~$ docker plugin ls
ID                  NAME                                         DESCRIPTION                    ENABLED
cd5d714d44cb        hpe:latest                                   HPE Docker Volume Plugin       false

5.	Configured multiple etcd host IP addresses in hpe.conf of all theworker nodes.

host_etcd_ip_address = 10.50.0.158:2379,10.50.0.160:2379,10.50.0.161:2379
host_etcd_port_number = 2379

6.	Enabling plugin fails with below error.

stack@worker1:~$ docker plugin enable hpe
Error response from daemon: dial unix /run/docker/plugins/cd5d714d44cb87f39926b1ff20d0f96e9c5ac53e846c93f12f83ab179bb34b4f/hpe.sock: connect: no such file or directory

Aug  8 05:22:13 worker1 dockerd[11151]: time="2017-08-08T05:22:13-07:00" level=info msg="2017-08-08 12:22:13.497 22 ERROR etcd.client [-] List of hosts incompatible with allow_reconnect." plugin=cd5d714d44cb87f39926b1ff20d0f96e9c5ac53e846c93f12f83ab179bb34b4f
Aug  8 05:22:13 worker1 dockerd[11151]: time="2017-08-08T05:22:13-07:00" level=info msg="2017-08-08 12:22:13.498 22 ERROR hpe_storage_api   File \"/usr/lib/python2.7/site-packages/etcd/client.py\", line 139, in __init__" plugin=cd5d714d44cb87f39926b1ff20d0f96e9c5ac53e846c93f12f83ab179bb34b4f
Aug  8 05:22:13 worker1 dockerd[11151]: time="2017-08-08T05:22:13-07:00" level=info msg="2017-08-08 12:22:13.498 22 ERROR hpe_storage_api     raise etcd.EtcdException(\"A list of hosts to connect to was given, but reconnection not allowed?\")" plugin=cd5d714d44cb87f39926b1ff20d0f96e9c5ac53e846c93f12f83ab179bb34b4f
Aug  8 05:22:13 worker1 dockerd[11151]: time="2017-08-08T05:22:13-07:00" level=info msg="2017-08-08 12:22:13.498 22 ERROR hpe_storage_api EtcdException: A list of hosts to connect to was given, but reconnection not allowed?" plugin=cd5d714d44cb87f39926b1ff20d0f96e9c5ac53e846c93f12f83ab179bb34b4f
Aug  8 05:22:13 worker1 dockerd[11151]: time="2017-08-08T05:22:13-07:00" level=info msg="2017-08-08 12:22:13.498 22 ERROR hpe_storage_api " plugin=cd5d714d44cb87f39926b1ff20d0f96e9c5ac53e846c93f12f83ab179bb34b4f

**Comment by hpe-storage** [comment]
Created a pull request -- https://github.com/hpe-storage/python-hpedockerplugin/pull/51/ to address this issue.

**Comment by wdurairaj** [comment]
This is fixed as part of 2.0 tag of hpestorage/hpedockervolumeplugin

**Comment by hpe-storage** [comment]
store/hpestorage/hpedockervolumeplugin:2.0 address this defect, and hence closing.
