### ISSUE TITLE
Docker 3.1: Error while inspecting Snapshot

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#529]
Test Bed -
[stack@cld6b9 ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo)

[stack@cld6b9 ~]$ docker plugin inspect hpe | grep PluginRef
        "PluginReference": "docker.io/hpestorage/hpedockervolumeplugin:3.1",
[stack@cld6b9 ~]$

CSIM-EOS07_1611168 cli% showversion
Release version 3.3.1 (MU2)
Patches:  P63

Component Name                   Version
CLI Server                       3.3.1 (MU2)
CLI Client                       3.3.1
System Manager                   3.3.1 (P63)
Kernel                           3.3.1 (MU2)
TPD Kernel Code                  3.3.1 (P63)
TPD Kernel Patch                 3.3.1 (P63)
CSIM-EOS07_1611168 cli%

Steps to reproduce -

Create a docker volume with backend option.
Create  a snapshot scheduling  to the volume.
Inspect the snapshot.it gives the below error
[stack@cld6b9 ~]$ docker volume inspect Snapshot
                                    []
                                    Error: No such volume: Snapshot
List the volumes.
Expected Results - Inspect command should give all details of snapshot and list should show the snapshot.
Actual Result - "Docker volume ls" command is not showing the volume 'snapshot'. 
                  
Detailed OutPut -

[stack@cld6b9 ~]$ docker volume create -d hpe --name Volume2 -o backend=REPLI
Volume2
[stack@cld6b9 ~]$ docker volume inspect Volume2
[
    {
        "CreatedAt": "0001-01-01T00:00:00Z",
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "",
        "Name": "Volume2",
        "Options": {
            "backend": "REPLI"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-2Vpub4B3TD.NkUG2tzw4Jw",
                "backend": "REPLI",
                "compression": null,
                "cpg": "SHASHI_SRC_CPG",
                "domain": "SHASHI_DOMAIN",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "thin",
                "size": 100,
                "snap_cpg": "SHASHI_SNAP_SRC_CPG"
            }
        }
    }
]

ON 3PAR:

CSIM-EOS07_1611168 cli% showvv -cpg SHASHI_SRC_CPG -showcols Name,Comment
Name                       Comment                                                                                                                                      
dcv-2Vpub4B3TD.NkUG2tzw4Jw {"volume_id": "d95a6e6f-8077-4c3f-8d91-41b6b73c3827", "name": "d95a6e6f-8077-4c3f-8d91-41b6b73c3827", "type": "Docker", "display_name": "Volume2"}
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
total                                                                                                                                                                   
CSIM-EOS07_1611168 cli% showvv -cpg SHASHI_SNAP_SRC_CPG -showcols Name,Comment
Name                       Comment                                                                                                                                      
dcv-2Vpub4B3TD.NkUG2tzw4Jw {"volume_id": "d95a6e6f-8077-4c3f-8d91-41b6b73c3827", "name": "d95a6e6f-8077-4c3f-8d91-41b6b73c3827", "type": "Docker", "display_name": "Volume2"}
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
total  

                               

On Docker:

[stack@cld6b9 ~]$ docker volume create -d hpe --name Snapshot -o virtualCopyOf=Volume2 -o scheduleFrequency="20 * * * *" -o scheduleName=Schedule-Name -o snapshotPrefix=shashi
Snapshot
[stack@cld6b9 ~]$ docker volume inspect Snapshot
[]
Error: No such volume: Snapshot
[stack@cld6b9 ~]$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          Volume2
[stack@cld6b9 ~]$ docker volume inspect Snapshot
[]
Error: No such volume: Snapshot

On 3PAR:

CSIM-EOS07_1611168 cli% showvv -cpg SHASHI_SNAP_SRC_CPG -showcols Name,Comment
Name                        Comment                                                                                                                                     
dcv-2Vpub4B3TD.NkUG2tzw4Jw  {"volume_id": "d95a6e6f-8077-4c3f-8d91-41b6b73c3827", "name": "d95a6e6f-8077-4c3f-8d91-41b6b73c3827", "type": "Docker", "display_name": "Volume2"}
 dcs-L-4hx3viRMmPPMSoh.kN9g {"volume_name": "Volume2", "volume_id": "d95a6e6f-8077-4c3f-8d91-41b6b73c3827", "display_name": "Snapshot", "description": "snapshot of volume Volume2"}
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
total                                                                                                                                                                   
CSIM-EOS07_1611168 cli% showvv -cpg SHASHI_SRC_CPG -showcols Name,Comment
Name                       Comment                                                                                                                                      
dcv-2Vpub4B3TD.NkUG2tzw4Jw {"volume_id": "d95a6e6f-8077-4c3f-8d91-41b6b73c3827", "name": "d95a6e6f-8077-4c3f-8d91-41b6b73c3827", "type": "Docker", "display_name": "Volume2"}
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
total                                                                                                                                                                   
CSIM-EOS07_1611168 cli% showsched
                                                                               ------ Schedule ------
SchedName     File/Command                                                     Min Hour DOM Month DOW CreatedBy Status Alert NextRunTime
Schedule-Name createsv -f shashi.@y@@m@@d@@H@@M@@S@ dcv-2Vpub4B3TD.NkUG2tzw4Jw  20    *   *     *   * 3paradm   active     Y 2019-03-25 03:20:00 PDT
----------------------------------------------------------------------------------------------------------------------------------------------------
1             total

[docker.service_logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3007915/docker.service_logs.txt)
[var_log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3007916/var_log.txt)

**Comment by wdurairaj** [comment]
if this is functionality of snapshot of replicated volume is not tested on 3.0, why this is tested now and marked as "high". Can you confirm this functionality on 3.0 and see if this issues recreatable. ?

Right now, I'm marking this as "medium" based on the above comments.

**Comment by sonawane-shashikant** [comment]
This was tested in 3.0 regression and was working fine. 
Attaching word file where output was saved during 3.0 regression.
Please refer to page number 5-6 of the attached doc.

[RHEL regression on 17.06 managed 3.2.2 & 3.3.1 for snapshot schedilung.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/3057126/RHEL.regression.on.17.06.managed.3.2.2.3.3.1.for.snapshot.schedilung.docx)

**Comment by wdurairaj** [comment]
Thanks Shashi for your confirmation.
@nilangekarss , can you confirm if this is a regression on this build. ? We have to block the build release based on this analysis.

**Comment by prablr79** [comment]
Not reproduced in 3.0 only in 3.1..

**Comment by nilangekarss** [comment]
@sonawane-shashikant i am not clear with the use case here. Can you please share your hpe.conf and commands to execute to reproduce this issue.

**Comment by nilangekarss** [comment]
@sonawane-shashikant 
docker engine doesn't respond some times and we get buffer error. Solution to this problem is keep hpe3par_debug = False. I have tried creating snapshots on other 3 arrays i could see snapshot is getting created and i can inspect it.
Where as only in 192.168.68.5 i do see this problem and can be overcome by putting hpe3par_debug = False in hpe.conf

please verify the same.

**Comment by sonawane-shashikant** [comment]
With the latest plugin, even without "hpe3par_debug", this issue could not be reproduced on 3.0 and 3.1

**Comment by sonawane-shashikant** [comment]
Attaching the relevant output captured while testing...

[bug 529 on 3.1.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3078701/bug.529.on.3.1.txt)
[BUG 529 on 3.0.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3078702/BUG.529.on.3.0.txt)
