### ISSUE TITLE
Ansible Plugin installer : No support for mount prefix

### ISSUE THREAD

**Issue by shaik-gousa-khaja-asif** [hpe-storage/python-hpedockerplugin#538]
Mount prefix option when provided in properties file is not populated in hpe.conf file of the cluster

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/537

**Comment by shaik-gousa-khaja-asif** [comment]
Support added for mount prefix in latest ansible installer code
