### ISSUE TITLE
FC plugin: Volume mount fails when host entry is already present in 3PAR array.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#54]
Install FC plugin with hpestorage/hpedockervolumeplugin:2.0 tag and perform volume mount after volume creation.

[docker@csimbe13-b03 ~]$ docker volume create -d hpe --name vol1
vol1

[docker@csimbe13-b03 ~]$ docker volume ls
DRIVER              VOLUME NAME
hpe:latest          vol1

[docker@csimbe13-b03 ~]$ docker run -it -v vol1:/data1 --volume-driver hpe --rm --name mounter1 busybox sh
   <span>hpedockerplugin.exception.HPEPluginMountException</span>: <span>HPE Docker Volume Plugin Mount Failed: (u'connection info retrieval failed, error is: %s', u"'HPE3PARFCDriver' object has no attribute '_modify_3par_fibrechan_host'")</span>
[mount_failed_logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1217059/mount_failed_logs.txt)

Please find the logs attached here.

**Comment by hpe-storage** [comment]
Bug  is fixed in store/hpestorage/hpedockervolumeplugin:2.0
