### ISSUE TITLE
Ansible PLugin Installer : vlan_tag: True set for a particular backend is applied to the replication_device section 

### ISSUE THREAD

**Issue by shaik-gousa-khaja-asif** [hpe-storage/python-hpedockerplugin#540]
Steps to reproduce:
1.  Consider a backend with vlan_tag set to True in the plugin_configuration_properties.yml
2.  Add a replication device section to the backend with an array not vlan tagged.
3. Run the ansible installer

Expected Condition:
1. The replication section in hpe.conf file must have the iscsi ports of the non vlan tagged array populated in hpe3par_iscsi_ips:

Actual Condition:
1. The replication section in hpe.conf file has the iscsi vlan port populated in hpe3par_iscsi_ips:

Eg : 
host_etcd_ip_address=192.168.69.31:23790,192.168.69.32:23790,192.168.69.33:23790
hpe3par_username=3paradm
hpe3par_password=wy4a8PYh4IY=
hpe3par_cpg=SHASHI-PRIM
hpedockerplugin_driver=hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver
host_etcd_port_number=23790
ssh_hosts_key_file=/root/.ssh/known_hosts
logging=DEBUG
san_ip=192.168.67.7
san_login=3paradm
san_password=wy4a8PYh4IY=
hpe3par_api_url=https://192.168.67.7:8080/api/v1
hpe3par_iscsi_ips=192.168.68.203,192.168.68.201
replication_device=backend_id:CSSOS-SSA05,replication_mode:synchronous,cpg_map:SHASHI-PRIM:SHASHI-SEC,snap_cpg_map:SHASHI-PRIM-SNAP:SHASHI-SEC-SNAP,hpe3par_username:3paradm,hpe3par_password:wy4a8PYh4IY=,hpe3par_api_url: https://192.168.67.5:8080/api/v1,san_ip: 192.168.67.5,san_login: 3paradm,san_password: wy4a8PYh4IY=, hpe3par_iscsi_ips:

**Comment by farhan7500** [comment]
I'm looking into this

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/550

Testing in progress

**Comment by shaik-gousa-khaja-asif** [comment]
Working fine in latest build
