### ISSUE TITLE
Docker 3.1: Automated Installer: Plugin installation Fails on k8s

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#541]
Test bed - 

[root@master-node ansible_3par_docker_plugin]# kubectl get nodes
NAME            STATUS   ROLES    AGE     VERSION
master-node     Ready    master   6d19h   v1.13.3
worker-node-1   Ready    <none>   6d19h   v1.13.3
worker-node-2   Ready    <none>   6d19h   v1.13.3
[root@master-node ansible_3par_docker_plugin]#

[root@master-node ansible_3par_docker_plugin]# cat /root/hosts
[all]
10.50.9.10 ansible_user=root ansible_ssh_pass=hpinvent
10.50.9.23 ansible_user=root ansible_ssh_pass=hpinvent
10.50.9.22 ansible_user=root ansible_ssh_pass=hpinvent

[all:vars]
http_proxy=http://16.85.88.10:8080
https_proxy=http://16.85.88.10:8080

[masters]
10.50.9.10 ansible_user=root ansible_ssh_pass=hpinvent

[workers]
10.50.9.23 ansible_user=root ansible_ssh_pass=hpinvent
10.50.9.22 ansible_user=root ansible_ssh_pass=hpinvent

[etcd]
10.50.9.10 ansible_user=root ansible_ssh_pass=hpinvent
10.50.9.23 ansible_user=root ansible_ssh_pass=hpinvent
10.50.9.22 ansible_user=root ansible_ssh_pass=hpinvent
[root@master-node ansible_3par_docker_plugin]#

[root@master-node ~]# ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

[root@master-node ~]#

TASK [Create the etcd cluster var] ***************************************************************************************************************
fatal: [10.50.9.23]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ansible_default_ipv4'\n\nThe error appears to have been in '/root/python-hpedockerplugin/ansible_3par_docker_plugin/tasks/create_etcd_container.yml': line 9, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Create the etcd cluster var\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'ansible_default_ipv4'"}
fatal: [10.50.9.22]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ansible_default_ipv4'\n\nThe error appears to have been in '/root/python-hpedockerplugin/ansible_3par_docker_plugin/tasks/create_etcd_container.yml': line 9, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Create the etcd cluster var\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'ansible_default_ipv4'"}

PLAY [Install HPE 3PAR Volume Driver for Kubernetes/OpenShift] ***********************************************************************************

PLAY [Copy config file into admin.conf] **********************************************************************************************************

PLAY [Deploy FlexVolume drivers] *****************************************************************************************************************

PLAY [Install HPE 3PAR Volume Driver for Kubernetes/OpenShift] ***********************************************************************************
        to retry, use: --limit @/root/python-hpedockerplugin/ansible_3par_docker_plugin/install_hpe_3par_volume_driver.retry

PLAY RECAP ***************************************************************************************************************************************
10.50.9.10                 : ok=0    changed=0    unreachable=0    failed=1
10.50.9.22                 : ok=18   changed=6    unreachable=0    failed=1
10.50.9.23                 : ok=18   changed=6    unreachable=0    failed=1
localhost                  : ok=2    changed=0    unreachable=0    failed=0

Plugin properties yml - 

[plugin_configuration_properties.yml.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3021114/plugin_configuration_properties.yml.txt)

**Comment by sonawane-shashikant** [comment]
After cleaning up the k8s setup. Ran installer script again to see below error.

TASK [get the iscsi ports] ***********************************************************************************************************************
ok: [10.50.9.23] => (item=None)
fatal: [10.50.9.23]: FAILED! => {"msg": "The conditional check 'INVENTORY[item]['hpe3par_iscsi_ips'] is not defined and INVENTORY[item]['hpedockerplugin_driver'] == 'hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver' and not (INVENTORY[item]['vlan_tag'] is defined and INVENTORY[item]['vlan_tag'])' failed. The error was: error while evaluating conditional (INVENTORY[item]['hpe3par_iscsi_ips'] is not defined and INVENTORY[item]['hpedockerplugin_driver'] == 'hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver' and not (INVENTORY[item]['vlan_tag'] is defined and INVENTORY[item]['vlan_tag'])): 'dict object' has no attribute 'hpedockerplugin_driver'\n\nThe error appears to have been in '/root/python-hpedockerplugin/ansible_3par_docker_plugin/tasks/create_conf_file.yml': line 49, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: get the iscsi ports\n    ^ here\n"}
ok: [10.50.9.22] => (item=None)
fatal: [10.50.9.22]: FAILED! => {"msg": "The conditional check 'INVENTORY[item]['hpe3par_iscsi_ips'] is not defined and INVENTORY[item]['hpedockerplugin_driver'] == 'hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver' and not (INVENTORY[item]['vlan_tag'] is defined and INVENTORY[item]['vlan_tag'])' failed. The error was: error while evaluating conditional (INVENTORY[item]['hpe3par_iscsi_ips'] is not defined and INVENTORY[item]['hpedockerplugin_driver'] == 'hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver' and not (INVENTORY[item]['vlan_tag'] is defined and INVENTORY[item]['vlan_tag'])): 'dict object' has no attribute 'hpedockerplugin_driver'\n\nThe error appears to have been in '/root/python-hpedockerplugin/ansible_3par_docker_plugin/tasks/create_conf_file.yml': line 49, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: get the iscsi ports\n    ^ here\n"}

PLAY [Copy config file into admin.conf] **********************************************************************************************************

PLAY [Deploy FlexVolume drivers] *****************************************************************************************************************

PLAY [Install HPE 3PAR Volume Driver for Kubernetes/OpenShift] ***********************************************************************************
        to retry, use: --limit @/root/python-hpedockerplugin/ansible_3par_docker_plugin/install_hpe_3par_volume_driver.retry

PLAY RECAP ***************************************************************************************************************************************
10.50.9.10                 : ok=19   changed=6    unreachable=0    failed=1
10.50.9.22                 : ok=29   changed=11   unreachable=0    failed=1
10.50.9.23                 : ok=29   changed=11   unreachable=0    failed=1
localhost                  : ok=2    changed=0    unreachable=0    failed=0

**Comment by farhan7500** [comment]
Hi @sonawane-shashikant Please could you paste the properties file you used.

**Comment by prablr79** [comment]
@sonawane-shashikant is this reproduced in the latest setup ? can you confirm ?

**Comment by sonawane-shashikant** [comment]
Issue is the still reproducible.

Followed the below steps - 
1. Created K8S cluster with one master and 2 workers
2. Installed 3.0 legacy plugin manually. 
3. Validated the cluster and plugin installation by creating sc, pvc and pod
4. POD was in running state.
5. Uninstalled the plugin using Automated installer.
6. Plugin uninstalled successfully.
7. Installed the plugin using Automated installer to see the below error.

TASK [Populate WSAPI URL in hpe.conf] ************************************************************************************************************
changed: [10.50.9.22] => (item=[u'DEFAULT', {u'option': u'hpe3par_api_url', u'value': u'hpe3par_ip'}])
fatal: [10.50.9.22]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute u'hpe3par_ip'\n\nThe error appears to have been in '/root/python-hpedockerplugin/ansible_3par_docker_plugin/tasks/create_conf_file.yml': line 118, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Populate WSAPI URL in hpe.conf\n    ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute u'hpe3par_ip'"}

PLAY [Copy config file into admin.conf] **********************************************************************************************************

PLAY [Deploy FlexVolume drivers] *****************************************************************************************************************

PLAY [Install HPE 3PAR Volume Driver for Kubernetes/OpenShift] ***********************************************************************************
        to retry, use: --limit @/root/python-hpedockerplugin/ansible_3par_docker_plugin/install_hpe_3par_volume_driver.retry

PLAY RECAP ***************************************************************************************************************************************
10.50.9.10                 : ok=19   changed=6    unreachable=0    failed=1
10.50.9.22                 : ok=34   changed=16   unreachable=0    failed=1
10.50.9.23                 : ok=19   changed=6    unreachable=0    failed=1
localhost                  : ok=2    changed=0    unreachable=0    failed=0

[root@master-node ansible_3par_docker_plugin]#

Attaching plugin properties file for your reference.

[plugin_configuration_properties.yml (2).txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3041715/plugin_configuration_properties.yml.2.txt)

**Comment by farhan7500** [comment]
@sonawane-shashikant Please let me know when the setup is free.

**Comment by farhan7500** [comment]
The array IP of the the second backend is commented. Hence, the error.

![image](https://user-images.githubusercontent.com/22393330/55544366-8ed16600-56e8-11e9-8815-cb5192dea618.png)

The installation works well when uncommenting the array IP


```
PLAY RECAP **********************************************************************************************************************************************
10.50.9.10                 : ok=43   changed=21   unreachable=0    failed=0
10.50.9.22                 : ok=43   changed=17   unreachable=0    failed=0
10.50.9.23                 : ok=32   changed=14   unreachable=0    failed=0
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

```
[root@master-node ansible_3par_docker_plugin]# docker volume create -d hpe -o help=backends
Error response from daemon: create b4027bf63bc4d07bc0d4fe335a426a0d969de918174fc55f7c893e926ad52a2c:
======================================================
NAME                                          STATUS
======================================================
3PAR1                                          OK
DEFAULT                                        OK
```

**Comment by farhan7500** [comment]
In your test, the uninstallation worked because it does not use the array to do any of its operations. The array IP **is** required for installation though.

**Comment by virendra-sharma** [comment]
@sonawane-shashikant @farhan7500 
Tested above issue with Kubernetes 1.12 setup and able to install plugin through installer. Steps followed as below.

1) Manually installed etcd, plugin, dory & doryd setup on setup.
2) Created sc, pvc, pod for volume create.
3) Deleted all sc,pvc,pod and no volume left on setup.
4) Executed uninstall script of installer and it worked well, cleaned up plugin setup except etcd (which is 
expected).
5) Executed install script of installer and it installed plugin setup on all nodes.
6) Created sc,pvc,pod and it worked well.

Please find below configuration file.
[plugin configuration file.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3054069/plugin.configuration.file.txt)
[populated hpe conf file.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3054082/populated.hpe.conf.file.txt)

**Comment by sonawane-shashikant** [comment]
Closing as per above comment.
