### ISSUE TITLE
Docker 3.1: Automted Installer: Unwanted ymls in properties folder

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#544]
Properties folder in the 
python-hpedockerplugin/ansible_3par_docker_plugin/ 
has 4 YAMLs.
Out of these 4 YAMLs, 2 YAMLs are not updated by the user and should be removed to avoid confusion.

Below 2 YAMLs should be removed - 

1.  	etcd_properties.yml
2.  	sample_etcd_properties.yml

**Comment by farhan7500** [comment]
Agreed. These yml files are not used not. They are legacy files from initial commit

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/547

**Comment by sonawane-shashikant** [comment]
Closing as FIXED
