### ISSUE TITLE
Docker 3.1 Error while creating POD on Openshift 3.11 with array version 3.2.2

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#549]
While creating pv,pvc,pod on Openshift 3.11 POD are showing containerCreating state but on backend 3PAR vluns are created successfully.

Test Bed Details:
3PAR : 192.168.67.7
CSSOS-SSA04 cli% showversion -b
Release version 3.2.2.709 (MU6)
Patches:  None

Component Name                   Version
CLI Server                       3.2.2.709 (MU6)
CLI Client                       3.2.2.709
System Manager                   3.2.2.709 (MU6)
Kernel                           3.2.2.709 (MU6)
TPD Kernel Code                  3.2.2.709 (MU6)

192.168.69.46 - master,
192.168.69.35,192.168.69.41 - workers
login:root/12iso*help

Steps to reproduce:
1.Create  PV,PVC.
2.Create POD.
   POD is in Container Creating state but Vluns are created on backend 3PAR array and on the node where the pod is mounted.

Describe pod status error as below:

Events:
  Type     Reason       Age               From                    Message
  ----     ------       ----              ----                    -------
  Normal   Scheduled    1m                default-scheduler       Successfully assigned default/pod-multi to cssosbe04-b16
  Warning  FailedMount  7s (x2 over 30s)  kubelet, cssosbe04-b16  MountVolume.SetUp failed for volume "pv-multi" : mount command failed, status: Failure, reason: HPE Docker Volume Plugin Mount Failed: ('exception is : %!!(MISSING)!(MISSING)s(MISSING)', '\n\n  RAN: /bin/mount -t ext4 /dev/dm-6 /opt/hpe/data/hpedocker-dm-uuid-mpath-360002ac00000000000012a950001db31\n\n  STDOUT:\n\n\n  STDERR:\nmount: /opt/hpe/data/hpedocker-dm-uuid-mpath-360002ac00000000000012a950001db31: /dev/mapper/mpathba already mounted on /opt/hpe/data/hpedocker-dm-uuid-mpath-360002ac00000000000012a950001db31.\n')

please find the attached logs on node 192.168.69.46
1) dorylog_b16,
2) log_b16
3) plugin_logs_b16 
[3.2.2 on Openshift 3.11.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3038537/3.2.2.on.Openshift.3.11.txt)

**Comment by wdurairaj** [comment]
Mount failure lead to a dangling VLUN on 3par array is captured in this bug -- https://github.com/hpe-storage/python-hpedockerplugin/issues/513 . So, it's a duplicate.

**Comment by sandesh-desai** [comment]
Already verified in Bug#513 hence closing the bug.
