### ISSUE TITLE
Ansible Plugin Installer : The specified mount prefix is not set as default rshared in create_3par_docker_volume_plugin.yml file

### ISSUE THREAD

**Issue by shaik-gousa-khaja-asif** [hpe-storage/python-hpedockerplugin#558]
Steps to reproduce:
1. Specify the mount prefix as  /var/lib/kubelet/ in properties file. 
2. Run the ansible installer
3. Create SC ,PVC and POD
4. Check for the state of POD

Expected Result :
The POD must be in running state

Actual Result  : 
POD is in container creating state

Kubectl describe pod gives the following logs : 

Warning  FailedMount  4m (x9 over 22m)   kubelet, cssosbe04-b03  Unable to mount volumes for pod "pod1_default(0650a046-59fa-11e9-abd1-f40343a90200)": timeout expired waiting for volumes to attach or mount for pod "default"/"pod1". list of unmounted volumes=[export]. list of unattached volumes=[export default-token-zhpc9]
  Warning  FailedMount  3m (x18 over 23m)  kubelet, cssosbe04-b03  MountVolume.SetUp failed for volume "sc1-fb63626b-59f9-11e9-abd1-f40343a90200" : mount command failed, status: Failure, reason: Unable to get device for flexvolPath=/var/lib/origin/openshift.local.volumes/pods/0650a046-59fa-11e9-abd1-f40343a90200/volumes/hpe.com~hpe/sc1-fb63626b-59f9-11e9-abd1-f40343a90200 from docker volume=/var/lib/kubelet/dm-uuid-mpath-360002ac000000000000131960001db31

Reason : /var/lib/kubelet must be mapped as :rshared
Shown in the link https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/docs/configuring_docker_ee_2_with_volume_plugin.md

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/565

**Comment by shaik-gousa-khaja-asif** [comment]
Tested on latest build . Working fine
