### ISSUE TITLE
FC plugin: Volume mount operation fails intermittently with single path when multipath flags (use_multipath & enforce_multipath) are configured to TRUE in hpe.conf.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#56]
OS platform:  CentOS 7.3
Plugin tag: nilangekarswapnil/hpe3parplugin:2.0

All the performed steps are mentioned below on how the issue was observed:

1.	Created 4 volumes with different properties using FC plugin .
2.	Mounted and wrote data on them.
3.	Kept all the containers in detached state.
4.	Created a binary file in all the volumes.
5.	Got a md5 checksum for all the binary files of respective volumes.
6.	Unmount all volumes and disable the plugin.
7.	Configure iSCSI plugin in hpe.conf
8.	Enable the i
[mount_failure.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1217824/mount_failure.txt)
SCSI plugin.
9.	Mounted all the volumes.
10.	Verified the checksum persistence.
11.	Created one new volume and mounted it.
12.	Unmounted all 5 volumes.
13.	Disable iSCSI plugin and enable FC plugin.
14.	Mounted all the 5 volumes.
15.	Two mount requests failed with below error:

_<span>HPE Docker Volume Plugin Makedir Failed: (u'Make directory failed exception is : %s', u'list index out of range')</span>_

Please find the detailed logs for one volume mount failure in the attachments here.
[mount_failure.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1217827/mount_failure.txt)

**Comment by sumitshatwara** [comment]
Also observed 1 out of 6 times in swarm setup.
3 manager nodes and 3 worker nodes

Volume mount request failed with below error:
<span>hpedockerplugin.exception.HPEPluginFileSystemException</span>: <span>HPE Docker Volume Plugin File System error: (u'create file system failed exception is : %s', u'\n\n  RAN: /sbin/mkfs -F /dev/disk/by-id/dm-uuid-mpath-360002ac0000000000000db1800019d52\n\n  STDOUT:\n\n\n  STDERR:\nmke2fs 1.43.4 (31-Jan-2017)\nThe file /dev/disk/by-id/dm-uuid-mpath-360002ac0000000000000db1800019d52 does not exist and no size was specified.\n')</span>

**Comment by sumitshatwara** [comment]
Only one FC port of container host and 3par array must be in same zone in FC switch.

Couple of volume mount operations works successfully for the single volume and it fails intermittently for that particular volume on 3rd or 4th attempt with below error: 

_HPE Docker Volume Plugin Makedir Failed: (u'Make directory failed exception is : %s', u'list index out of range')_


After the first failure of volume mount operation, mount request continuously fails for that particular volume. I was able to mount that volume again after re-enabling the plugin but again it ended up with the same intermittent failure.

**Comment by hpe-storage** [comment]
Address as part of 2.0.1 
Use
`docker plugin install store/hpestorage/hpedockervolumeplugin:2.0.1`
