### ISSUE TITLE
Automated Installer: Need documentation on ETCD un-install and clean up script

### ISSUE THREAD

**Issue by prablr79** [hpe-storage/python-hpedockerplugin#560]
We need to document the ETCD un-install procedure and also explain the details what the information is being cleaned up during un-install procedure.

**Comment by farhan7500** [comment]
Added documentation in a fix at https://github.com/hpe-storage/python-hpedockerplugin/pull/568

**Comment by farhan7500** [comment]
Merged. @prablr79 Please could you close this. Thanks!

**Comment by prablr79** [comment]
Verified the documentation ansible Readme.md hence closing this defect..
