### ISSUE TITLE
Rancher: Pod mount on a snapshot with schedule fails.

### ISSUE THREAD

**Issue by leenaj0hn** [hpe-storage/python-hpedockerplugin#566]
Steps: 
Using Rancher UI create a storage class with the following parameters
1. expHrs =5
2. retHrs = 3
3. scheduleFrequency = 10 2 * * *
4. scheudleName = Daily
5. snapshotPrefix = pqr
6 virtualCopyOf = <volume name>

Create a pvc, selecting the above storage class and size of the pv to be created
When the pvc is in "Bound" state, deploy and pod, adding the existing persistent volume. Provide volume name, pvc details and mount point. 

The above steps fails with the below error.

ERROR hpedockerplugin.fileutil [-] ('exception is : %s', '\n\n  RAN: /bin/mount -t ext4 /dev/dm-5 /var/lib/rancher/dm-uuid-mpath-360002ac000000000000140f30001db31\n\n  STDOUT:\n\n\n  STDERR:\nmount: /var/lib/rancher/dm-uuid-mpath-360002ac000000000000140f30001db31: /dev/mapper/360002ac000000000000140f30001db31 already mounted on /var/lib/rancher/dm-uuid-mpath-360002ac000000000000140f30001db31.\n'): sh.ErrorReturnCode_32: ^[[00m

**Comment by sneharai4** [comment]
@leenaj0hn This was verified on the test setup. Please confirm and close.

**Comment by sneharai4** [comment]
1. Create SC with below parameters:
scheduleFrequency = 10 2 * * *
scheduleName        = schedule1
snapshotPrefix        = pqr
virtualCopyOf         = april11_vol1

2. Create a PVC. It creates a PV and marks it to Bound state

3. Create a POD with above created PVC. POD goes to running state.

4. Check the schedule in 3PAR using **showsched** command

**Comment by leenaj0hn** [comment]
closing this issue
