### ISSUE TITLE
Rancher: On a node shutdown, pods mounted on the node fail to be moved to the active node.

### ISSUE THREAD

**Issue by leenaj0hn** [hpe-storage/python-hpedockerplugin#567]
1. Shutdown an active node, pods mounted on the node fail to be moved to the active node.
2. The pods remained in the Updating/Unknow state.

**Comment by prablr79** [comment]
@leenaj0hn try to reproduce in clean environment before claim this is a bug.

**Comment by prablr79** [comment]
suspecting same K8's bug https://github.com/kubernetes/kubernetes/issues/60987

**Comment by sneharai4** [comment]
@leenaj0hn  We can mark this as low.

**Comment by prablr79** [comment]
https://github.com/hpe-storage/python-hpedockerplugin/issues/641#issuecomment-499832907, verified in another customer setup and it is working fine.
