### ISSUE TITLE
3par plugin failure on the worker node 

### ISSUE THREAD

**Issue by Acidguy** [hpe-storage/python-hpedockerplugin#570]
<10.0.8.6> SSH: EXEC sshpass -d21 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/b293cb41a1 10.0.8.6 '/bin/sh -c '"'"'rm -f -r /root/.ansible/tmp/ansible-tmp-1554961320.6-127718123438907/ > /dev/null 2>&1 && sleep 0'"'"''
<10.0.8.6> (0, '', '')
fatal: [10.0.8.6]: FAILED! => {
   "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/usr/libexec/kubernetes/kubelet-plugins/volume/exec/hpe.com~hpe/",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": 493,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "https://github.com/hpe-storage/python-hpedockerplugin/raw/master/dory_installer_v31",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Destination /usr/libexec/kubernetes/kubelet-plugins/volume/exec/hpe.com~hpe does not exist"

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/571

@Acidguy Please wait for the merge or take the bits from this commit to continue with your testing

**Comment by sneharai4** [comment]
Working now.
