### ISSUE TITLE
Ansible Plugin installer: Plugin installer fails if etcd is running

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#572]
Summary - Automated installer fails if etcd is running on any of the or all the nodes and if we give the same port in plugin reference yml

We see the below error in above scenario and plugin does not install on that node.

fatal: [10.50.9.23]: FAILED! => {"changed": false, "msg": "Error starting container 9f064bb4b3ab7e5978cc4bfaea75564e36bccea0b81ae05298ebe4fe41d4b25a: 500 Server Error: Internal Server Error (\"{\"message\":\"driver failed programming external connectivity on endpoint etcd_hpe (2a256c8904768c9cd6d70d34dd55bf2b999e7f1e15883175879287198bfd21fd): Bind for 0.0.0.0:40010 failed: port is already allocated\"}\")"}
changed: [10.50.9.22]

**Comment by prablr79** [comment]
@shaik-gousa-khaja-asif  did you also observ this issue ? port is already allocated message ?

**Comment by farhan7500** [comment]
This is only a documentation only change. Why has this been marked as a high defect?

**Comment by prablr79** [comment]
Since its a doc change moving this Medium defect.

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/573

**Comment by sonawane-shashikant** [comment]
Closing this issue as FIXED - 


![image](https://user-images.githubusercontent.com/21362687/56262599-00ec7680-60fd-11e9-8aed-82b5757a2737.png)
