### ISSUE TITLE
Automated Plugin Installer: Uninstall script does not remove plugin image

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#575]
Summary - Uninstall script does not remove plugin image. So if image is already present, while installing the plugin, installer uses the same image instead of pulling new images and install.

Test Bed - 
[root@master-node ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
[root@master-node ~]# kubectl get nodes
NAME            STATUS   ROLES    AGE   VERSION
master-node     Ready    master   23h   v1.13.3
worker-node-1   Ready    <none>   23h   v1.13.3
worker-node-2   Ready    <none>   23h   v1.13.3
[root@master-node ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:05:53Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
[root@master-node ~]#

Steps to reproduce - 
1. Install docker volume plugin using Automated Installer
2. Verify the running plugin and images.
3. Uninstall the plugin using Automated Installer

Expected - Uninstall script should remove plugin images as well as plugin.

Actual Results - 
Verify the running plugin and images. Plugin gets removed successfully but images remain in the system

Detailed output - 

Plugin and images before uninstall - 

[root@master-node ansible_3par_docker_plugin]# docker ps | grep plugin
a4a7dbcb3c30        hpestorage/legacyvolumeplugin:3.1   "/bin/sh -c ./plug..."   14 minutes ago      Up 14 minutes                                                                                                                         plugin_container

[root@master-node ansible_3par_docker_plugin]#  docker images | grep plugin
hpestorage/legacyvolumeplugin        3.1                 4b8c9c3f2426        38 hours ago        318MB
hpestorage/legacyvolumeplugin        <none>              1e4d1c4fdc79        4 weeks ago         307MB
hpestorage/legacyvolumeplugin        3.0                 22d7ab72c68f        4 months ago        550MB
[root@master-node ansible_3par_docker_plugin]#

Plugin and images after uninstall - 

[root@master-node ansible_3par_docker_plugin]# docker ps | grep plugin
[root@master-node ansible_3par_docker_plugin]#  docker images | grep plugin
hpestorage/legacyvolumeplugin        3.1                 4b8c9c3f2426        38 hours ago        318MB
hpestorage/legacyvolumeplugin        <none>              1e4d1c4fdc79        4 weeks ago         307MB
hpestorage/legacyvolumeplugin        3.0                 22d7ab72c68f        4 months ago        550MB
[root@master-node ansible_3par_docker_plugin]#

Above output shows plugin is removed but images are still there.

**Comment by prablr79** [comment]
@farhan7500 will look into it..

**Comment by farhan7500** [comment]
Fixed in https://github.com/hpe-storage/python-hpedockerplugin/pull/577

Kindly wait for review and merge

**Comment by sonawane-shashikant** [comment]
Closing this issue as FIXED

Before Uninstall - 

[root@master-node ~]# docker images | grep plugin
hpestorage/legacyvolumeplugin        3.1                 7ba8908ba5ae        45 hours ago        318MB
hpestorage/legacyvolumeplugin        <none>              4b8c9c3f2426        6 days ago          318MB
hpestorage/legacyvolumeplugin        3.0                 22d7ab72c68f        4 months ago        550MB
[root@master-node ~]#

After Uninstall, with 3.1 mentioned in properties file

[root@master-node ansible_3par_docker_plugin]# docker images | grep plugin
hpestorage/legacyvolumeplugin        <none>              4b8c9c3f2426        6 days ago          318MB
hpestorage/legacyvolumeplugin        3.0                 22d7ab72c68f        4 months ago        550MB

After Uninstall, with 3.0 mentioned in properties file

[root@master-node ansible_3par_docker_plugin]# docker images | grep plugin
hpestorage/legacyvolumeplugin        <none>              4b8c9c3f2426        6 days ago          318MB
[root@master-node ansible_3par_docker_plugin]#
