### ISSUE TITLE
Rancher: ImportVol not working

### ISSUE THREAD

**Issue by sneharai4** [hpe-storage/python-hpedockerplugin#580]
On Rancher importVol feature was not working correctly due to plugin not running correctly.

Steps to import legacy volumes into 3PAR.

1. Create a PV
2. Create a POD with Volume type as "Existing Volume" and mention the PV name.
3. POD created successfully with PV available on 3PAR

**Comment by prablr79** [comment]
correction in the documentation only

**Comment by leenaj0hn** [comment]
Working as expected. Sneha please close
