### ISSUE TITLE
FilePersona: File share creation hangs at "Creating" state with -o fpg

### ISSUE THREAD

**Issue by leenaj0hn** [hpe-storage/python-hpedockerplugin#592]
Test1:
Create an fpg passing -o fpg option.
CPG of the legacy FPG should be different from the default CPG passed in hpe.conf. 
This executions hangs at "Creating" state

Test2: 
Create an fpg passing -o fpg and -o cpg option with the cpg same as the cpg of the legacy FPG.
The execution fails with the below error

May  7 06:12:56 cssosbe04-b04 dockerd[2592]: time="2019-05-07T06:12:56-04:00" level=info msg="2019-05-07T10:12:56+0000 [stderr#error] hpedockerplugin.exception.ShareCreationFailed: Share creation failed [share_name: leenaShare_1, error: Key not found ETCD: [key=/file-persona/DEFAULT/swap_fs_cpg/swap_fpg2]" plugin=65f9ac225a7659d96de2a9fe17c9be8efe1d31c1e01cb4572c4a887428dd8256

**Comment by imran-ansari** [comment]
Hi @leenaj0hn - Could you please verify this with the latest build?

**Comment by leenaj0hn** [comment]
closing this issue:
CPG of the legacy FPG should be different from the default CPG passed in hpe.conf.
This executions hangs at "Creating" state
