### ISSUE TITLE
File Persona: -o filePersona option not available in "help"

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#593]
File Persona: -o filePersona option not available in "help"

Testbed Details:
Host:192.168.68.42
Host OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
Docker version:17.06.2-ee-21
3PAR array: 192.168.67.6 [DEFAULT]

Steps as follows:
1) docker volume create -d hpe -o help

Attaching the help output.
[Help Output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3155512/Help.Output.txt)

**Comment by imran-ansari** [comment]
Please try 
docker volume create -d hpe -o filePersona -o help
to see the help content.
Please mark this as invalid issue if you are good with the help content.

**Comment by sandesh-desai** [comment]
In "docker volume create -d hpe -o help" page need to mention -o filePersona related entries, by looking at that entry will execute the below command:
docker volume create -d hpe -o filePersona -o help

**Comment by sandesh-desai** [comment]
Verified and closed. 
Attaching the help info.
[Help output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3160492/Help.output.txt)
