### ISSUE TITLE
File Persona: Share gets deleted from docker but remains in backend 3PAR

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#595]
File Persona: Share gets deleted from docker but remains in backend 3PAR

Testbed Details:
Host:192.168.68.42
Host OS: Red Hat Enterprise Linux Server release 7.6 (Maipo)
Docker version:17.06.2-ee-21
3PAR array: 192.168.67.6 [DEFAULT]

Steps as follows:
1) create share 
    docker volume create -d hpe --name sandesh-share1 -o filePersona
2) Inspect share
    docker volume inspect sandesh-share1
3) On 3PAR check fpg status its created successfully.
    showfpg  
4) Remove share
   docker volume rm sandesh-share1
Share remove successfully  
[root@cssosbe03-b12 ~]# docker volume ls
DRIVER              VOLUME NAME

fpg not removed from 3PAR.

Attaching the logs.

[delete-share1.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3157060/delete-share1.txt)
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3157061/Docker.output.txt)
[3PAR output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3157062/3PAR.output.txt)

**Comment by virendra-sharma** [comment]
It is also observed that if we create series of share on host and remove all then after last share delete, fpg get's deleted from backend. but if we create single share(Default_Share) with default fpg then fpg not delete after removal of corresponding share(Default_Share).

**Comment by nilangekarss** [comment]
@virendra-sharma PR #617 addresses this issue. If there are no stores on the FPG, FPG will be deleted. Here if the FPG is legacy FPG then also this FPG gets deleted. But, it should not delete the legacy FPG. This new behavior will be addressed in next PR. Please make a note of it.

Currently it should successfully remove FPG for above scenario.

**Comment by sandesh-desai** [comment]
Closing this issue as FIXED.
Attaching the logs.
[Docker and 3PAR output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3225945/Docker.and.3PAR.output.txt)
