### ISSUE TITLE
Sample configs should show example of urls for 3par and VSA

### ISSUE THREAD

**Issue by ddefolo** [hpe-storage/python-hpedockerplugin#6]
The current sample config files provide no guidance on the format of the expected URLs:

> [root@localhost config]# grep url hpe*
> hpe.conf.sample.3par:hpe3par_api_url = <3par WSAPI URL>
> hpe.conf.sample.lefthand:hpelefthand_api_url = <lefthand cluster URL>

It would be clearer if actual URL examples were provided 

3par sample:
`hpe3par_api_url = https://<3par IP address>:8080/api/v1`

VSA sample:
`hpelefthand_api_url = https://<VSA cluster VIP address>:8081/lhos`

**Comment by garthmbooth** [comment]
Resolved in v1.1.0 release.
