### ISSUE TITLE
Docker volume creation is intermediately failing with volume options size & dedup are specified together.

### ISSUE THREAD

**Issue by dgavand** [hpe-storage/python-hpedockerplugin#60]
Docker volume creation is intermediately failing with volume options size & dedup are specified together

```
root@cld6b3:~# docker volume create -d hpe --name vol-01 -o size=15 -o provisioning=dedup
Error response from daemon: create vol-01: a more specific error could not be determined
root@cld6b3:~#
root@cld6b3:~# docker volume create -d hpe --name vol-01 -o size=15 -o provisioning=dedup
vol-01
root@cld6b3:~#
root@cld6b3:~# docker volume inspect vol-01
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/1123d27954d33d26190a18e8007ba4871225a41d9a5a6821779cd7a8978fab71/rootfs",
        "Name": "vol-01",
        "Options": {
            "provisioning": "dedup",
            "size": "15"
        },
        "Scope": "local"
    }
]
root@cld6b3:~#
```

[create_dcv.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1286779/create_dcv.txt)

**Comment by hpe-storage** [comment]
System IP : 10.50.199.1 (stack/hpinvent)
array : 10.50.3.9 (having SSD's with Flash Cache enabled)

**Comment by dgavand** [comment]
Adding system's details:

root@cld6b3:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
root@cld6b3:~#
root@cld6b3:~#
root@cld6b3:~# docker version
Client:
 Version:      17.06.1-ee-2
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   8e43158
 Built:        Wed Aug 23 21:15:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.1-ee-2
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   8e43158
 Built:        Wed Aug 23 21:14:20 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@cld6b3:~#

**Comment by hpe-storage** [comment]
showalert on the array 10.50.3.9 shows 96% of space is full, and hence there is a possibility that the volume creation calls are failing intermittently. Can you confirm this by cleaning some space on the CPG involved for docker volume plugin ?
```
Id          : 100
State       : New
Message Code: 0x0270018
Time        : 2017-09-06 23:36:02 MDT
Severity    : Degraded
Type        : CPG was grown with degraded parameters
Message     : CPG 1 (SSD_r5) could not grow using its default grow size of 32GB due to unavailability of free space.

Id          : 104
State       : New
Message Code: 0x0270018
Time        : 2017-09-07 03:49:14 MDT
Severity    : Degraded
Type        : CPG was grown with degraded parameters
Message     : CPG 11 (SHASHI-CPG) could not grow using its default grow size of 32GB due to unavailability of free space.

Id          : 98
State       : New
Message Code: 0x027001c
Time        : 2017-09-08 05:00:14 MDT
Severity    : Critical
Type        : SSD raw space allocation 95% alert
Message     : Total SSD raw space usage at 6877G (above 96% of total 7136G).

57 alerts
```

**Comment by dgavand** [comment]
I did check the array 10.50.3.9 for available space before testing and was observed enough space for the testing.

Used another array (10.50.3.7) and it is working normally; able to create docker volume(s) with volume options size & dedup are specified together.

Thanks for your quick analysis. I think, we can close this issue.
