### ISSUE TITLE
File Persona: Default FPG name conflict when hosts in multi-host setup have their own ETCDs

### ISSUE THREAD

**Issue by imran-ansari** [hpe-storage/python-hpedockerplugin#600]
ISSUE
====
Default FPG name generation is dependent on a counter present in ETCD. If each host has its own ETCD, then the counter value is duplicated resulting in same FPG name on different hosts.

SOLUTION
=======
Catch duplicate FPG exceptions from 3PAR and keep incrementing the counter till a unique FPG name is generated

**Comment by imran-ansari** [comment]
@sandesh-desai - I would like you to verify this before I can close it.

**Comment by sandesh-desai** [comment]
Not able to re-produce the issue.
Now Fpg creation is as per expected, while creating a share from different host,different FPG name is creating successfully.
Attaching the output:
[3PAR output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3271941/3PAR.output.txt)
[Share creation host1.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3271942/Share.creation.host1.txt)
[Share creation host2.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3271943/Share.creation.host2.txt)

**Comment by imran-ansari** [comment]
Based on the above observation closing this issue.
