### ISSUE TITLE
default share creation fails if default FPG capacity is full.

### ISSUE THREAD

**Issue by nilangekarss** [hpe-storage/python-hpedockerplugin#607]
Whenever user creates share on 3PAR with size=3.5TiB with below command execution 5 times
docker volume create -d hpe --name share_name -o filePersona -o size=3.5TiB

4 shares get created but 5th share creation fails.
The reason for this is, FPG doesn't have space to create this share.

Expected outcome: plugin should bring intelligence to create this share by creating new FPG, new VFS a, new Store and new share.

**Comment by sandesh-desai** [comment]
Verified and working as expected.
Attaching the logs:
[3PAR output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3259964/3PAR.output.txt)
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3259965/Docker.output.txt)
[Mesasges file.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3259966/Mesasges.file.txt)


@nilangekarss : Please close the bug.

**Comment by nilangekarss** [comment]
@sandesh-desai As per Sandesh comment closing this bug.
