### ISSUE TITLE
Wrong size is getting set while creating share on 3PAR via k8s

### ISSUE THREAD

**Issue by nilangekarss** [hpe-storage/python-hpedockerplugin#613]
When we create PVC with size 1024 GiB to create share of size 1TiB, the share getting created is of size 1GiB.

This is because currently plugin accepts size in MiB instead of GiB from docker user for creating share, where as volume size is expected to be passed in unit of GiB.

**Comment by sonawane-shashikant** [comment]
Verified this issue as FIXED and can be closed.

Below steps are followed to verify this issue.
1. Created PV with size, name and filePersona parameters
2. Created PVC and storage size is give as 2048 Gib
3. Created POD
4. POD is seen in Running state.
5. Inspected docker for the size. 
6. Size is verified as 2048 Gib

YAMLs - 
[root@master-node YAML]# cat PV-SHARE.yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv3-share
spec:
    capacity:
      storage: 2048Gi
    accessModes:
    - ReadWriteOnce
    flexVolume:
      driver: hpe.com/hpe
      options:
        name: SHASHI-SHARE
        filePersona: ""
        size: "2048"
[root@master-node YAML]# cat PVC-SHARE.yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc3-share
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2048Gi
[root@master-node YAML]# cat POD-SHARE.yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: pod3-share
spec:
  containers:
  - name: minio
    image: minio/minio:latest
    args:
    - server
    - /export
    env:
    - name: MINIO_ACCESS_KEY
      value: minio
    - name: MINIO_SECRET_KEY
      value: doryspeakswhale
    ports:
    - containerPort: 9000
    volumeMounts:
    - name: export
      mountPath: /export
  volumes:
    - name: export
      persistentVolumeClaim:
        claimName: pvc3-share
[root@master-node YAML]#


Volume inpsect - 

[root@master-node YAML]# docker volume inspect SHASHI-SHARE
[
    {
        "Driver": "hpe",
        "Labels": {},
        "Mountpoint": "[",
        "Name": "SHASHI-SHARE",
        "Options": {
            "filePersona": ""
        },
        "Scope": "global",
        "Status": {
            "backend": "DEFAULT_FILE",
            "clientIPs": [
                "10.50.9.22"
            ],
            "cpg": "SHASHI_CPG",
            "fpg": "DockerFpg_3",
            "fsMode": null,
            "fsOwner": null,
            "name": "SHASHI-SHARE",
            "protocol": "nfs",
            "sharePath": "10.50.9.198:/DockerFpg_3/DockerVfs_3/SHASHI-SHARE",
            "size": "2048 GiB",
            "status": "AVAILABLE",
            "vfs": "DockerVfs_3",
            "vfsIPs": [
                [
                    "10.50.9.198",
                    "255.255.255.0"
                ]
            ]
        }
    }
]
[root@master-node YAML]#

**Comment by sonawane-shashikant** [comment]
@wdurairaj @prablr79 Please close this issue.
