### ISSUE TITLE
Currently mount directory is hard coded to /opt/hpe/data/  this needs to be changed to accept directory location from conf file if provided

### ISSUE THREAD

**Issue by nilangekarss** [hpe-storage/python-hpedockerplugin#614]
Currently, mount directory is set to /opt/hpe/data/ this needs to be changed to accept any other directory provided in hpe.conf file for file persona backends.

**Comment by wdurairaj** [comment]
@nilangekarss, `mount_prefix` is supposed to do the above functionality of changing the default mount directory prefix.. Do you expect something else ?

**Comment by wdurairaj** [comment]
Removing bug label for now.

**Comment by sandesh-desai** [comment]
Verified and working as expected.
Attaching the logs:
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3271488/Docker.output.txt)
[hpe.conf.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3271489/hpe.conf.txt)

**Comment by wdurairaj** [comment]
Closing this issue based on @sandesh-desai update.
