### ISSUE TITLE
File Persona: legacyvolumeplugin:Unable to mount a share.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#618]
File Persona: legacyvolumeplugin:Unable to mount a share.

Testbed Details:
Host:192.168.68.33
Host OS: NAME="CentOS Linux" VERSION="7 (Core)"
Docker version:17.06.2-ee-21
3PAR array: 192.168.67.6 [DEFAULT]

Steps as follows:
1)Create a share on DEFAULT array
docker volume create -d hpe --name=Default_Share1 -o filePersona
2) Inspect the share
docker volume inspect Default_Share1
3) Mount a share
docker run -it --rm  --mount src=Default_Share1,dst=/DATA,volume-driver=hpe --name  mount alpine  /bin/sh

It gives below error:

[root@CSSOSBE03-B03 ~]# docker run -it --rm  --mount src=Default_Share1,dst=/DATA,volume-driver=hpe --name  mount alpine  /bin/sh
docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "process_linux.go:356: container init caused \"rootfs_linux.go:57: mounting \\\"/opt/hpe/data/hpedocker-ac1d8f63cd8e4c02f5aad1cc1eec4e3e478cb793d59e9c050d3889023a73ff5c\\\" to rootfs \\\"/var/lib/docker/overlay2/42e2bc56f3dc7fa927bb0822c908a1956f76fb20e8191f3eee20dcdcd12a718e/merged\\\" at \\\"/DATA\\\" caused \\\"stat /opt/hpe/data/hpedocker-ac1d8f63cd8e4c02f5aad1cc1eec4e3e478cb793d59e9c050d3889023a73ff5c: no such file or directory\\\"\"".

Attaching the logs.
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3205764/Docker.output.txt)
[Log file MOUNT.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3205765/Log.file.MOUNT.txt)
[3PAR output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3205766/3PAR.output.txt)

**Comment by nilangekarss** [comment]
@sandesh-desai Can you please retest this and check the output. 
Is mount working on RHEL and Ubuntu?

**Comment by prablr79** [comment]
This working fine in Ubuntu and RHEL, waiting for SLES update from Sandesh

**Comment by sandesh-desai** [comment]
On SLES also facing same mounting issue.
Attaching the docker output:
[docker output of mount.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3236116/docker.output.of.mount.txt)

**Comment by sandesh-desai** [comment]
Install managed plugin on same CentOS (192.168.68.33) and mount the share successfully.
Attaching the logs:
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3236521/Docker.output.txt)
[messages_file.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3236522/messages_file.txt)

**Comment by prablr79** [comment]
OpenShift  3.10 environment verified by Dev its working. @sandesh-desai ask to verify RHEL legacy plugin to verify and come back with results.

**Comment by sandesh-desai** [comment]
Invalid Bug as "/opt/hpe/data:/opt/hpe/data:rshared" parameter was missing on docker-compose.yml .
Updated docker-compose.yml and mount share successfully.

Attaching the logs:
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3246212/Docker.output.txt)
