### ISSUE TITLE
File Persona: legacyvolumeplugin:Validation of Default FPG size limit.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#635]
File Persona: legacyvolumeplugin:Validation of Default FPG size limit.

Testbed Details:
CSSOSBE03-B01:~ # cat /etc/os-release
NAME="SLES"
VERSION="12-SP3"
VERSION_ID="12.3"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP3"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp3"

Docker details:

CSSOSBE03-B01:~ # docker version
Client: Docker Enterprise Edition (EE) 2.0
 Version:      17.06.2-ee-20
 API version:  1.30
 Go version:   go1.10.8
 Git commit:   cd8d740
 Built:        Thu Feb 28 06:05:24 2019
 OS/Arch:      linux/amd64

Server: Docker Enterprise Edition (EE) 2.0
 Engine:
  Version:      17.06.2-ee-20
  API version:  1.30 (minimum version 1.12)
  Go version:   go1.10.8
  Git commit:   cd8d740
  Built:        Thu Feb 28 06:06:16 2019
  OS/Arch:      linux/amd64
  Experimental: false

Plugin details:
CSSOSBE03-B01:~ # docker ps | grep plugin
0b18efec6c9b        hpestorage/legacyvolumeplugin:3.2-prerelease   "/bin/sh -c ./plug..."   2 days ago          Up 5 hours                                                                               plugin_container

Steps as follows:
1.Create a share1 of size 15TiB with default FPG. 
    docker volume create -d hpe --name SHARE01 -o filePersona -o size=15360
2.Create a share2 of size 2TiB with -o fpg option.
    docker volume create -d hpe --name SHARE02 -o filePersona -o size=2048 -o fpg=<Default_Fpg>
3.Create a share3 of size 2TiB with -o fpg option.
    docker volume create -d hpe --name SHARE03 -o filePersona -o size=2048 -o fpg=<Default_Fpg>
Expected Result:
 Share2 and Share3 will be in Failed State.
Actual Result:
 Share2 and Share3 is created on that Fpg.

3PAR:
CSSOS-SSA06 cli% showfshare nfs -fpg DockerFpg_9
ShareName VFS         FileStore ------------SharePath------------ State  -Clients-
SHARE01   DockerVfs_9 SHARE01   /DockerFpg_9/DockerVfs_9/SHARE01/ normal 127.0.0.1
SHARE02   DockerVfs_9 SHARE02   /DockerFpg_9/DockerVfs_9/SHARE02/ normal 127.0.0.1
SHARE03   DockerVfs_9 SHARE03   /DockerFpg_9/DockerVfs_9/SHARE03/ normal 127.0.0.1
----------------------------------------------------------------------------------
        3 total
CSSOS-SSA06 cli% showfsquota
                                                                                         -------Files-------- -------Capacity(MiB)--------
Name                                               ID Type   VFS             FPG         Curr Soft Hard Grace Curr     Soft     Hard Grace
SHARE01                                             3 fstore DockerVfs_9     DockerFpg_9    2    0    0  none    0 15728640 15728640  none
SHARE02                                             4 fstore DockerVfs_9     DockerFpg_9    2    0    0  none    0  2097152  2097152  none
SHARE03                                             5 fstore DockerVfs_9     DockerFpg_9    2    0    0  none    0  2097152  2097152  none
FailedShare                                         3 fstore ImranNewFpg_vfs ImranNewFpg    2    0    0  none    0  1048576  1048576  none
scpersona1-0be7bbe6-7877-11e9-846a-f40343a90200     3 fstore swap_fpg2_vfs   swap_fpg2      2    0    0  none    0       16       16  none
MyDefShare_01                                       3 fstore DockerVfs_4     DockerFpg_4    2    0    0  none    0  1048576  1048576  none
------------------------------------------------------------------------------------------------------------------------------------------
                                              

Attaching the logs:
1) [docker and 3par output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3236711/docker.and.3par.output.txt)

2) [LOGS_PLUGIN.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3236726/LOGS_PLUGIN.txt)

3) [VAR_LOGS.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3236727/VAR_LOGS.txt)

4) [3pardcv.log](https://github.com/hpe-storage/python-hpedockerplugin/files/3236734/3pardcv.log)

**Comment by imran-ansari** [comment]
This has been fixed as part of pull request https://github.com/hpe-storage/python-hpedockerplugin/pull/629 which is being reviewed.

**Comment by sandesh-desai** [comment]
Closing this issue as FIXED.
Attaching the logs.
Docker output.txt
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3247061/Docker.output.txt)
