### ISSUE TITLE
File Persona: Inconsistent error message for volume create

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#636]
While creating volume with -o backend as file backend getting inconsistent error message.

**Config file have backend as :**
DEFAULT
DEFAULT_FILE

**Command:**
docker volume create -d hpe --name volume1 -o backend=DEFAULT_FILE

**Error:**
Error response from daemon: create volume1: Backend: DEFAULT_FILE not present in config.

**Expectation:-** 
1) It should be same error which is displaying in case of share creation with [DEFAULT_BLOCK] backend.
2) Error message should be like **"ERROR: Backend DEFAULT_FILE is not configured for block storage"**

**Comment by imran-ansari** [comment]
This has been fixed. To be available in next build.

**Comment by imran-ansari** [comment]
Fixed as part of PR https://github.com/hpe-storage/python-hpedockerplugin/pull/639 which has been submitted for review

**Comment by virendra-sharma** [comment]
Getting appropriate error message now "Error response from daemon: create volume1: Backend DEFAULT_FILE is reserved for File Persona. Cannot specify it for Block operations."

@imran-ansari just for clarification, we getting appropriate error message but i thing message is not consistent with block operation for same use case.
```
For block error :- ERROR: Backend DEFAULT_FILE is not configured for block storage.
For file error :- Error response from daemon: create volume1: Backend DEFAULT_FILE is reserved for File Persona. Cannot specify it for Block operations
```

Can we get both operation error message consistent or else let me know, if both follow different operations here so error message display is according to it?

**Comment by sandesh-desai** [comment]
Closing this issue as FIXED as Getting appropriate error message now:

[root@CSSOSBE03-B03 ~]# docker volume create -d hpe --name volume1 -o backend=DEFAULT_FILE
Error response from daemon: create volume1: Backend DEFAULT_FILE is reserved for File Persona. Cannot specify it for Block operations
[root@CSSOSBE03-B03 ~]#

**Comment by imran-ansari** [comment]
> Getting appropriate error message now "Error response from daemon: create volume1: Backend DEFAULT_FILE is reserved for File Persona. Cannot specify it for Block operations."
> 
> @imran-ansari just for clarification, we getting appropriate error message but i thing message is not consistent with block operation for same use case.
> 
> ```
> For block error :- ERROR: Backend DEFAULT_FILE is not configured for block storage.
> For file error :- Error response from daemon: create volume1: Backend DEFAULT_FILE is reserved for File Persona. Cannot specify it for Block operations
> ```
> 
> Can we get both operation error message consistent or else let me know, if both follow different operations here so error message display is according to it?

@virendra-sharma - Following are the messages that are seen for the reserved backend names "DEFAULT_BLOCK" and "DEFAULT_FILE" if they are used incorrectly which is consistent:
```sh
$ docker volume create -d hpe --name VOL01 -o backend=DEFAULT_FILE
Error response from daemon: create VOL01: Backend DEFAULT_FILE is reserved for File Persona. Cannot specify it for Block operations
$ docker volume create -d hpe --name SH01 -o backend=DEFAULT_BLOCK -o filePersona
Error response from daemon: create SH01: Backend DEFAULT_BLOCK is reserved for Block operations. Cannot specify it for File operations
```
As far as specifying any other regular backend which is not defined for Block or File will result in the following error which I think appropriately and adequately conveys the problem:
```sh
$ docker volume create -d hpe --name VOL01 -o filePersona -o backend=3PAR_BLOCK
Error response from daemon: create VOL01: ERROR: Backend 3PAR_BLOCK is not configured for File Persona
```

**Comment by virendra-sharma** [comment]
Thank You @imran-ansari, Agreed with above clarification.
Closing this issue as resolved now.
