### ISSUE TITLE
File Persona: IPs in use to be obtained from 3PAR

### ISSUE THREAD

**Issue by imran-ansari** [hpe-storage/python-hpedockerplugin#638]
Since the plugin supports multiple hosts each having its own ETCD, the truth about IPs in use can only be obtained from 3PAR rather than depending on ETCD

**Comment by imran-ansari** [comment]
This has been fixed in PR https://github.com/hpe-storage/python-hpedockerplugin/pull/639 which has been submitted for review

**Comment by sandesh-desai** [comment]
Verified and working as expected.
Attaching the logs:
[Docker output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3279637/Docker.output.txt)
[Messages file.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3279638/Messages.file.txt)
[3PAR output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3279639/3PAR.output.txt)

[root@CSSOSBE03-B03 ~]# docker volume create -d hpe --name share4 -o filePersona -o fpg=DockerFpg_1
share4
[root@CSSOSBE03-B03 ~]# docker volume inspect share4
[
    {
        "Driver": "hpe",
        "Labels": {},
        "Mountpoint": "/opt/hpe/data/hpedocker-share4",
        "Name": "share4",
        "Options": {
            "filePersona": "",
            "fpg": "DockerFpg_1"
        },
        "Scope": "global",
        "Status": {
            "backend": "DEFAULT_FILE",
            "clientIPs": [],
            "cpg": "Sandesh",
            "fpg": "DockerFpg_1",
            "fsMode": null,
            "fsOwner": null,
            "name": "share4",
            "protocol": "nfs",
            "sharePath": null,
            "size": "1024 GiB",
            "status": "CREATING",
            "vfs": null
        }
    }
]
[root@CSSOSBE03-B03 ~]# docker volume inspect share4
[
    {
        "Driver": "hpe",
        "Labels": {},
        "Mountpoint": "/opt/hpe/data/hpedocker-share4",
        "Name": "share4",
        "Options": {
            "filePersona": "",
            "fpg": "DockerFpg_1"
        },
        "Scope": "global",
        "Status": {
            "backend": "DEFAULT_FILE",
            "clientIPs": [],
            "cpg": "Sandesh",
            "detailedStatus": "Share creation failed: Share creation on new FPG failed. Reason: VFS creation failed: Claim available IP failed. Reason: IP address pool exhausted",
            "fpg": "DockerFpg_1",
            "fsMode": null,
            "fsOwner": null,
            "name": "share4",
            "protocol": "nfs",
            "sharePath": null,
            "size": "1024 GiB",
            "status": "FAILED",
            "vfs": "DockerFpg_1_vfs"
        }
    }
]

**Comment by sandesh-desai** [comment]
@imran-ansari   please verify and close the bug.

**Comment by imran-ansari** [comment]
Based on the above verification steps, closing this issue.
