### ISSUE TITLE
Volume mount operation fails intermittently when iSCSI plugin is enabled.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#64]
OS platform: Ubuntu 16.04 / CentOS 7.3
Plugin tag: hpestorage/hpedockervolumeplugin:2.0.1

All the performed steps are mentioned below on how the issue was observed:

1. Perform mount operations (writing data) on 30 different volumes on Ubuntu/CentOS using below command:

$ for i in `seq 1 30`; do  echo  "Writing data to volume: $i"; docker run -it -v ubuntu$i:/data1 --volume-driver hpe --rm busybox /bin/sh -c "echo 'data' > /data1/hi$i.txt" ; done

Observed couple of failures with below error:

<span>hpedockerplugin.exception.HPEPluginMountException</span>: <span>HPE Docker Volume Plugin Mount Failed: (u'exception is : %s', u'\n\n  RAN: /bin/mount -t ext4 /dev/sdc /opt/hpe/data/hpedocker-scsi-360002ac000000000040124ba00002ba0\n\n  STDOUT:\n\n\n  STDERR:\nmount: /opt/hpe/data/hpedocker-scsi-360002ac000000000040124ba00002ba0: wrong fs type, bad option, bad superblock on /dev/sdc, missing codepage or helper program, or other error.\n')</span>

2. Perform mount operations (reading data) on 30 different volumes on Ubuntu/CentOS using below command:

$ for i in `seq 1 30`; do  echo "Reading data from volume: $i"; docker run -it -v ubuntu$i:/data1 --volume-driver hpe --rm busybox cat /data1/hi$i.txt ; done

Observed 5-6 failures with the same error.

Orphaned LUN entry available after unmounting the volume which was NOT expected:

[docker@csimbe13-b03 ~]$ lsscsi
[0:0:0:0]    storage HP       P244br           3.00  -
[0:0:0:4194240] storage HP       P244br           3.00  -
[0:0:0:4194496] storage HP       P244br           3.00  -
[0:1:0:0]    disk    HP       LOGICAL VOLUME   3.00  /dev/sda
[0:1:0:1]    disk    HP       LOGICAL VOLUME   3.00  /dev/sdb
[1:0:0:254]  enclosu 3PARdata SES              3310  -
[2:0:0:254]  enclosu 3PARdata SES              3310  -
[11:0:0:254] enclosu 3PARdata SES              3224  -
[193:0:0:254] enclosu 3PARdata SES              3310  -
[198:0:0:0]  disk    3PARdata VV               3310  /dev/sdc
[198:0:0:254] enclosu 3PARdata SES              3310  -

[docker@csimbe13-b03 ~]$ ls -lrt /dev/disk/by-path
total 0
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 pci-0000:07:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 pci-0000:07:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx. 1 root root  9 Sep 22 00:53 pci-0000:07:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx. 1 root root  9 Sep 22 00:53 pci-0000:07:00.0-scsi-0:1:0:1 -> ../../sdb
lrwxrwxrwx. 1 root root  9 Sep 22 03:26 ip-10.50.17.220:3260-iscsi-iqn.2000-05.com.3pardata:20210002ac002ba0-lun-0 -> ../../sdc

[docker@csimbe13-b03 ~]$ ls -lrt /dev/disk/by-id
total 0
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 wwn-0x600508b1001c00753453523c856f650b-part2 -> ../../sda2
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 scsi-3600508b1001c00753453523c856f650b-part2 -> ../../sda2
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 lvm-pv-uuid-RMJGcT-80Fa-x9HD-Q4jk-UFmr-NcZQ-mXjZM6 -> ../../sda2
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 wwn-0x600508b1001c00753453523c856f650b-part1 -> ../../sda1
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 scsi-3600508b1001c00753453523c856f650b-part1 -> ../../sda1
lrwxrwxrwx. 1 root root  9 Sep 22 00:53 wwn-0x600508b1001c00753453523c856f650b -> ../../sda
lrwxrwxrwx. 1 root root  9 Sep 22 00:53 scsi-3600508b1001c00753453523c856f650b -> ../../sda
lrwxrwxrwx. 1 root root  9 Sep 22 00:53 wwn-0x600508b1001c84476eafd7bf7b837471 -> ../../sdb
lrwxrwxrwx. 1 root root  9 Sep 22 00:53 scsi-3600508b1001c84476eafd7bf7b837471 -> ../../sdb
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 dm-name-docker-253:0-16786440-eb861cc588796b5c1859904d8afeccf48aaa4c39198f296e6631938d3b5d2e06 -> ../../dm-5
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 dm-uuid-LVM-0K3PtinMg6bLZFeBAsM5ryNXPvrkQa3RxMZENZTxoADmykRX150JJ0r921SEdw5m -> ../../dm-3
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 dm-name-cl-home -> ../../dm-3
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 dm-name-cl-root -> ../../dm-0
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 dm-uuid-LVM-0K3PtinMg6bLZFeBAsM5ryNXPvrkQa3RNuYqnphtbtE3G6TGZa4KeZCeruUrEfo7 -> ../../dm-1
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 dm-uuid-LVM-0K3PtinMg6bLZFeBAsM5ryNXPvrkQa3Rkkk0J0Bb7iiwiJ8dVU1XXC1gqJyuArYQ -> ../../dm-0
lrwxrwxrwx. 1 root root 10 Sep 22 00:53 dm-name-cl-swap -> ../../dm-1
lrwxrwxrwx. 1 root root  9 Sep 22 03:26 wwn-0x60002ac000000000040124bf00002ba0 -> ../../sdc
lrwxrwxrwx. 1 root root  9 Sep 22 03:26 scsi-360002ac000000000040124bf00002ba0 -> ../../sdc

If above LUN entries will be available after unmounting the volume, the next mount operation for same volume will work as expected but the next mount operation for different volume will cause to FAIL.

**Comment by sumitshatwara** [comment]
Workaround for this issue:

If you observe any dangling LUN entries available in container host after unmount operation, then unexport that particular volume from 3par array and run below command after installing `sg3_utils` tool (required in CentOS/RHEL):
`sudo rescan-scsi-bus.sh -r -f –m`

Verify there is no dangling LUN entry  available in following paths:
`/dev/disk/by-path`
`/dev/disk/by-id`

**Comment by sumitshatwara** [comment]
**After enabling the plugin, first volume mount operation often fails with below error:**

_hpedockerplugin.exception.HPEPluginFileSystemException: HPE Docker Volume Plugin File System error: (u'create file system failed exception is : %s', u'\\n\\n  RAN: /sbin/mkfs -F /dev/dm-7\\n\\n  STDOUT:\\nCreating filesystem with 2883584 4k blocks and 720896 inodes\\nFilesystem UUID: 9ae6d934-968e-4bd0-9bdd-af1cfa56a4a8\\nSuperblock backups stored on blocks: \\n\\t32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208\\n\\nAllocating group tables:  0/88\\x08\\x08\\x08\\x08\\x08     \\x08\\x08\\x08\\x08\\x08done                            \\nWriting inode tables:  0/88\\x08\\x08\\x08\\x08\\x08     \\x08\\x08\\x08\\x08\\x08done                            \\nWriting superblocks and filesystem accounting information:  0/88\\x08\\x08\\x08\\x08\\x08\\n\\n  STDERR:\\nmke2fs 1.43.6 (29-Aug-2017)\\nWarning: could not erase sector 2: I/O error\\nWarning: could not read block 0: I/O error\\nWarning: could not erase sector 0: I/O error\\n\\nWarning, had trouble writing out superblocks.\\n')" plugin=cd6d7fdb5fd49a6de366aa94c2d6881000bf430124d4bf44e8c5cf7a62ee32cf_

**Attaching the detailed logs for above error.**
[failed_mount_block.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1335862/failed_mount_block.txt)

**Also, following error was observed couple of times while mounting the volume in Ubuntu 16.04:**

_<span>hpedockerplugin.exception.HPEPluginFileSystemException</span>: <span>HPE Docker Volume Plugin File System error: (u'create file system failed exception is : %s', u'\n\n  RAN: /sbin/mkfs -F /dev/sdd\n\n  STDOUT:\n\n\n  STDERR:\nmke2fs 1.43.6 (29-Aug-2017)\n/dev/sdd is apparently in use by the system; will not make a filesystem here!\n')</span>_

**Comment by wdurairaj** [comment]
Mount issues addressed with the pull request #72 

create file system failed exception will be addressed by issue #83
