### ISSUE TITLE
File persona: inconsistent mountpath of share and unexpected behaviour after updating wrong IP in "host_ip_address"

### ISSUE THREAD

**Issue by virendra-sharma** [hpe-storage/python-hpedockerplugin#647]
**Observation: -** 
1) Mount path in containerized platform is invalid after un-mounting particular share. it shows only "[".
2) If wrong "host_ip_address" passed in config file, it allow to create and mount volumes of different host sharing same etcd. but after un-mounting share from host(have wrong entry of host), share mount for other host get hanged and in 3PAR share, FPG, VFS get's deleted. whereas in inspect we could still see all entry's.

```
Note: - Second point is being tested with correct host IP and also with no such parameter so that it takes default, in both cases it worked well.
```

**"Expectation: -"**
1) Same as managed plugin, containerized plugin should show mount path consistent, like before mouth "/var/--" and after mount "/opt/--" directory or some appropriate directory.
2) If "host_ip_address" is not appropriate then it should not allow to mount share or should fail particular backend. so that further unexpected behavior could be avoided.

**"Outputs: -"**
```
Mount path outputs

Before mount
============
[root@CSSOSBE03-B03 ~]# docker volume inspect share03
[
    {
        "Driver": "hpe",
        "Labels": null,
        "Mountpoint": "/opt/hpe/data/hpedocker-share03",
        "Name": "share03",
        "Options": {},
        "Scope": "global",
        "Status": {
            "backend": "DEFAULT",
            "clientIPs": [],
            "cpg": "swap_fs_cpg",
            "fpg": "DockerFpg_1",
            "fsMode": null,
            "fsOwner": null,
            "name": "share03",
            "protocol": "nfs",
            "sharePath": "192.168.98.43:/DockerFpg_1/DockerVfs_1/share03",
            "size": "1024 GiB",
            "status": "AVAILABLE",
            "vfs": "DockerVfs_1",
            "vfsIPs": [
                [
                    "192.168.98.43",
                    "255.255.192.0"
                ]
            ]
        }
    }
]

After mount
===========
[root@CSSOSBE03-B03 ~]# docker volume inspect share03
[
    {
        "Driver": "hpe",
        "Labels": null,
        "Mountpoint": "[/opt/hpe/data/hpedocker-acd1eaf63d035110b1a68cf4e5e72a73584eac014341601c3fc5afaf9380c37c, ]",
        "Name": "share03",
        "Options": {},
        "Scope": "global",
        "Status": {
            "backend": "DEFAULT",
            "clientIPs": [
                "192.168.68.33"
            ],
            "cpg": "swap_fs_cpg",
            "fpg": "DockerFpg_1",
            "fsMode": null,
            "fsOwner": null,
            "name": "share03",
            "protocol": "nfs",
            "sharePath": "192.168.98.43:/DockerFpg_1/DockerVfs_1/share03",
            "size": "1024 GiB",
            "status": "AVAILABLE",
            "vfs": "DockerVfs_1",
            "vfsIPs": [
                [
                    "192.168.98.43",
                    "255.255.192.0"
                ]
            ]
        }
    }
]

After unmount
=============
[root@CSSOSBE03-B03 ~]# docker volume inspect share03
[
    {
        "Driver": "hpe",
        "Labels": null,
        "Mountpoint": "[",
        "Name": "share03",
        "Options": {},
        "Scope": "global",
        "Status": {
            "backend": "DEFAULT",
            "clientIPs": [
                "192.168.68.42"
            ],
            "cpg": "swap_fs_cpg",
            "fpg": "DockerFpg_1",
            "fsMode": null,
            "fsOwner": null,
            "name": "share03",
            "protocol": "nfs",
            "sharePath": "192.168.98.43:/DockerFpg_1/DockerVfs_1/share03",
            "size": "1024 GiB",
            "status": "AVAILABLE",
            "vfs": "DockerVfs_1",
            "vfsIPs": [
                [
                    "192.168.98.43",
                    "255.255.192.0"
                ]
            ]
        }
    }
]
```

**Comment by nilangekarss** [comment]
@virendra-sharma I understood the first point. Can you elaborate what is "host_ip_address" field in hpe.conf refers to?

**Comment by nilangekarss** [comment]
@virendra-sharma fixing #646 will fix the mount point issue of inspecting a share.

**Comment by virendra-sharma** [comment]
@nilangekarss I had used it for file testing, I think it shores host IP.
If it is not required then wrong value should not impact plugin behavior. I case it causes issue then it need to be validated while enabling plugin.

**Comment by imran-ansari** [comment]
host_ip_address is not a supported configuration parameter. It was included so that we could add it to the NFS client list for that host to be able to access the share. But after the first demo, on Eric's suggestion, we decided the plugin needs to fetch the Docker host IP address programmatically and use it to add to NFS client list. As a result, this parameter was removed.
If you specify it, it should not have any negative impact on the plugin behavior.

**Comment by virendra-sharma** [comment]
@imran-ansari I have observed negative impact due to wrong entry of host_ip_address parameter. we can discuss on it.

**Comment by prablr79** [comment]
@virendra-sharma can you please discuss with Imran and close this ?

**Comment by wdurairaj** [comment]
Please use the 3.2 tag of
`hpestorage/hpedockervolumeplugin:3.2`
`hpestorage/legacyvolumeplugin:3.2`

**Comment by virendra-sharma** [comment]
Verified on managed & containerized plugin and able to see valid mountpoint entry after unmount of share. but for containerized platform, inspect showing "/" before mount and after unmount. whereas for managed plugin we could see complete mountpoint without share mount.

Please find below output for both plugins.

[mount issue for managed.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3344751/mount.issue.for.managed.txt)
[mount issue for containerized.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3344752/mount.issue.for.containerized.txt)

@wdurairaj @imran-ansari Please suggest, whether it is consistent or we are good to go ahead with it.

**Comment by virendra-sharma** [comment]
Unable to re-produce second observation so will be closing this bug once above query get addressed.

**Comment by virendra-sharma** [comment]
Discussed with @wdurairaj @nilangekarss regarding bug. Came to conclusion that mountpoint entry for containerized before mount is visible as design and after mount it usually take /opt/ directory, unless we specify "mount_prefix".

In my case I had specified "mount_prefix" which was reason for different mountentry after share mount.

Query addressed, hence closing this issue as resolved.
