### ISSUE TITLE
Workflow which mounts the volume, writes/reads data, unmounts, removes it fails

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#65]
**Docker Plugin Details -** 
[root@csimbe13-b03 shashi]# docker plugin inspect hpe | grep 2.0
        "sha256:afc35e8f4cd31fa1613afe49fc46957defcc553ed9d40219bd1b2f2c2b0dc966"
        "Id": "c2e280f215cf7aa3b60963d6b52982963b9eba7008e3a103aa067ec202613b77",
        "PluginReference": "docker.io/hpestorage/hpedockervolumeplugin:2.0.1",
[root@csimbe13-b03 shashi]#

Array Details - 
Component Name                   Version
CLI Server                       3.3.1.215
CLI Client                       3.3.1.215
System Manager                   3.3.1.215
Kernel                           3.3.1.215
TPD Kernel Code                  3.3.1.215
CSIM-EOS07_1611168 cli%

**Steps to reproduce**

1. "Create a shell script ""test_script.sh"" with below commands:

volume=<volume_name>
docker volume create -d hpe $volume
docker run -it -v $volume:/data1 --rm --volume-driver hpe ubuntu bash -c 'echo ""data"" > /data1/test.txt '
docker run -it -v $volume:/data1 --rm --volume-driver hpe ubuntu bash -c 'cat /data1/test.txt'
docker volume remove $volume

2. On Docker 17.06 or later, run below command:

volume=<volume_name>
docker volume create -d hpe $volume
docker run -it --mount src=$volume,dst=/data1,volume-driver=hpe --rm ubuntu bash -c 'echo ""data"" > /data1/test.txt '
docker run -it --mount src=$volume,dst=/data1,volume-driver=hpe --rm ubuntu bash -c 'cat /data1/test.txt'
docker volume remove $volume"
		
3. "Run test_script.sh:

$ sh -x ./test_script.sh"	Script run must be successful.	
4. "Run test_script.sh script for more than 10 times.

Expected Results - Script run must be successful.
Actual Result - Script failed once out of 10 RUNs.

**Error Details -** 
<span>hpedockerplugin.exception.HPEPluginMountException</span>: <span>HPE Docker Volume Plugin Mount Failed: (u'OS Brick connect volume failed, error is: %s', u"Unexpected error while running command.\nCommand: /lib/udev/scsi_id --page 0x83 --whitelisted /dev/disk/by-path/pci-0000:08:00.2-fc-0x20110002ac002ba0-lun-1\nExit code: 1\nStdout: u''\nStderr: u''")</span>

**Note:-**
With 3.2.2.MU4 array version, below error is seen.
<span>hpedockerplugin.exception.HPEPluginMountException</span>: <span>HPE Docker Volume Plugin Mount Failed: (u'connection info retrieval failed, error is: %s', u'Not found (HTTP 404) 17 - host does not exist')</span>
  </div>

[TC_Docker_3PAR_FC_017.log](https://github.com/hpe-storage/python-hpedockerplugin/files/1355365/TC_Docker_3PAR_FC_017.log)

**Comment by sonivi** [comment]
With Docker ee version 17.06.2-ee-6, and plugin nightly build, issue could not be reproduced.
Attaching the output captured while running the script.
This issue can be closed.

[OutPut.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/1525739/OutPut.docx)

**Comment by wdurairaj** [comment]
Based on previous comments closing this as not reproducible.
