### ISSUE TITLE
Upgrade Testing:Plugin upgrade 3.0 to 3.2 failed.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#652]
Upgrade Testing:Plugin upgrade 3.0 to 3.2 failed.

Testbed Details:
Host:192.168.68.33
Host OS: CentOS
Docker Version: 17.06.2-ee-21
3PAR array: 192.168.67.7 [DEFAULT].

Steps perform:

1) Install old plugin 3.0.
2) Enable plugin successfully.
3) Upgrade plugin 3.2 by using below command:
docker plugin upgrade hpe hpestorage/hpedockervolumeplugin:3.2-prerelease

It gives below error messages:
[root@CSSOSBE03-B03 ~]# docker plugin upgrade hpe hpestorage/hpedockervolumeplugin:3.2-prerelease
error parsing current image reference: invalid reference format.

Attaching the logs:
[Messages file.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3289236/Messages.file.txt)
[Upgrade 3.0 to 3.2 docker.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3289237/Upgrade.3.0.to.3.2.docker.txt)

**Comment by imran-ansari** [comment]
Tried this out on my Ubuntu setup and the upgrade just went fine. Possibly OS specific issue.
```sh
root@COSSOSBE03-B06:~/imran/docker-src/python-hpedockerplugin# docker plugin upgrade hpe imranansari/hpedockerplugin:hpe
Upgrading plugin hpe:latest from hpestorage/hpedockervolumeplugin:3.0 to imranansari/hpedockerplugin:hpe
Plugin images do not match, are you sure? [y/N] y
Plugin "imranansari/hpedockerplugin:hpe" is requesting the following privileges:
 - network: [host]
 - mount: [/dev]
 - mount: [/run/lock]
 - mount: [/var/lib]
 - mount: [/etc]
 - mount: [/var/run/docker.sock]
 - mount: [/root/.ssh]
 - mount: [/sys]
 - mount: [/root/plugin/certs]
 - mount: [/sbin/iscsiadm]
 - mount: [/lib/modules]
 - mount: [/lib/x86_64-linux-gnu]
 - allow-all-devices: [true]
 - capabilities: [CAP_SYS_ADMIN CAP_SYS_RESOURCE CAP_MKNOD CAP_SYS_MODULE]
Do you grant the above permissions? [y/N] y
hpe: Pulling from imranansari/hpedockerplugin
b866ce1e2caa: Download complete
Digest: sha256:e42c1ebeed110801faddf81ef224819661607b68b519cd5f206a659f495a6711
Status: Downloaded newer image for imranansari/hpedockerplugin:hpe
Upgraded plugin hpe:latest to imranansari/hpedockerplugin:hpe
```

**Comment by prablr79** [comment]
@imran-ansari Thanks, Great relief looks like very specific.. Test Team please confirm again with Dev on is this issue specific to OS or generic upgrade issue ?

**Comment by prablr79** [comment]
Reducing to Medium since it is working in Ubuntu OS

**Comment by sandesh-desai** [comment]
Setup new CentOS with docker version 18.03.1-ee-8, build 2da2ee5 and Install 3.0 and upgrade to 3.2 successfully.
Attaching the logs:
[Upgrade plugin output 3.0-3.2.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3332971/Upgrade.plugin.output.3.0-3.2.txt)

**Comment by sandesh-desai** [comment]
Verified the upgrade from 3.0-3.2 and 3.1-3.2 successfully with docker 17.06 RHEL.
Attaching the logs:
[Upgrade from 3.0-3.2 on docker 17.06 successfully RHEL.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3333143/Upgrade.from.3.0-3.2.on.docker.17.06.successfully.RHEL.txt)
[Upgrade from 3.1-3.2 on docker 17.06 successfully RHEL.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3333144/Upgrade.from.3.1-3.2.on.docker.17.06.successfully.RHEL.txt)

**Comment by sandesh-desai** [comment]
Verified and working as expected.
