### ISSUE TITLE
File Persona: Help contents need correction

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#661]
Attached is the corrected help content.
Corrected section is highlighted in the attached document.
[Corrected help contents.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/3314502/Corrected.help.contents.docx)

**Comment by prablr79** [comment]
@sandesh-desai last release we have changed a file which will directly taken up as help content file, please feel free to modify the same. and raise PR for review.  work with Imran on this request.

**Comment by prablr79** [comment]
please review the help content and close this bug https://github.com/hpe-storage/python-hpedockerplugin/blob/plugin_v2/config/create_share_help.txt

**Comment by sandesh-desai** [comment]
Verified the help content.
