### ISSUE TITLE
Unable to initialize storage via - docker plugin enable

### ISSUE THREAD

**Issue by puppetpies** [hpe-storage/python-hpedockerplugin#68]
We are trying to connect to a 3PAR Storage device via ISCSI i can see the disk via fdisk but when trying to enable i encounter a dial unix error.

The correct IQN's are assigned on the 3PAR side of things.

[root@sldv-grp-swarm5 bhood]# docker plugin enable 2c
Error response from daemon: dial unix /run/docker/plugins/2cbefc8846cc2a51a1e496fed43a03be5a730b8ca18f77664a9c7edb6058c6d1/hpe.sock: connect: no such file or directory
[root@sldv-grp-swarm5 bhood]# docker plugin list
ID                  NAME                DESCRIPTION                ENABLED
2cbefc8846cc        hpe:latest          HPE Docker Volume Plugin   false

The config file is as follows.

[root@sldv-grp-swarm5 bhood]# cat /etc/hpedockerplugin/hpe.conf 
[DEFAULT]

logging = DEBUG
suppress_requests_ssl_warnings = False

hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver

hpe3par_api_url = https://10.226.8.10:8080/api/v1
iscsi_ip_address = 10.226.8.10
hpe3par_iscsi_ips = 10.226.8.10,10.226.8.11,10.226.8.12,10.226.8.13

use_multipath = False
enforce_multipath = False

Please advise.

Brian Hood

**Comment by wdurairaj** [comment]
Hi Brian,

Can you add couple of more details here ?

1) what operating system you are using the plugin with ? (CentOS/RHEL/Ubuntu) 
2) Can you attach the /var/log/syslog (if it is debian based) or /var/log/messages (if RPM based distribution)?

3) Is you etcd daemon running as per step https://github.com/hpe-storage/python-hpedockerplugin/tree/master/quick-start#single-node-etcd-setup---install-etcd 

Is it listed as "Up" in `docker ps -a`

4) Have you done 
`docker plugin set hpe certs.source=/tmp` in Ubuntu 
`docker plugin set hpe glibc_libs.source=/lib64 certs.source=/tmp` in case on RHEL/CentOS before enabling the hpe plugin

**Comment by puppetpies** [comment]
Hi wdurairaj,

I am currently running RHEL 7.3 i have my etc running as the step above.

[root@sldv-grp-swarm1 bhood]# docker plugin enable cbb
Error response from daemon: dial unix /run/docker/plugins/cbb0ba3235d2660d6564bc7da57574b3ee09fe8a33f5b4ea38e003d694f69304/hpe.sock: connect: no such file or directory
[root@sldv-grp-swarm1 bhood]# tail -f /var/log/messages
Oct 11 15:35:31 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:35:31.658240228+01:00" level=info msg="Node join event for sldv-grp-swarm3-8e679ef5da01/10.226.33.136"
Oct 11 15:35:34 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:35:34.037487160+01:00" level=info msg="Node join event for sldv-grp-swarm3-8e679ef5da01/10.226.33.136"
Oct 11 15:35:34 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:35:34.407330705+01:00" level=info msg="Node join event for sldv-grp-swarm2-a2bc1a296da1/10.226.33.135"
Oct 11 15:36:04 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:36:04.041648257+01:00" level=info msg="Node join event for sldv-grp-swarm3-8e679ef5da01/10.226.33.136"
Oct 11 15:36:34 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:36:34.044850448+01:00" level=info msg="Node join event for sldv-grp-swarm3-8e679ef5da01/10.226.33.136"
Oct 11 15:36:34 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:36:34.416182424+01:00" level=info msg="Node join event for sldv-grp-swarm2-a2bc1a296da1/10.226.33.135"
Oct 11 15:36:55 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:36:55+01:00" level=info msg="Multipath NOT configured: DO NO turn on multipath services" plugin=cbb0ba3235d2660d6564bc7da57574b3ee09fe8a33f5b4ea38e003d694f69304
Oct 11 15:36:57 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:36:57+01:00" level=info msg="/home/vagrant/python-hpedockerplugin/config/hpe.conf" plugin=cbb0ba3235d2660d6564bc7da57574b3ee09fe8a33f5b4ea38e003d694f69304
Oct 11 15:36:57 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:36:57+01:00" level=info msg="2017-10-11 14:36:57.237 16 INFO hpedockerplugin.hpe_storage_api [-] Initialize Volume Plugin" plugin=cbb0ba3235d2660d6564bc7da57574b3ee09fe8a33f5b4ea38e003d694f69304
Oct 11 15:37:04 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:37:04.049314759+01:00" level=info msg="Node join event for sldv-grp-swarm2-a2bc1a296da1/10.226.33.135"
Oct 11 15:37:34 sldv-grp-swarm1 dockerd[945]: time="2017-10-11T15:37:34.053304019+01:00" level=info msg="Node join event for sldv-grp-swarm3-8e679ef5da01/10.226.33.136"
^C
[root@sldv-grp-swarm1 bhood]# docker plugin list
ID                  NAME                                         DESCRIPTION                ENABLED
cbb0ba3235d2        store/hpestorage/hpedockervolumeplugin:2.0   HPE Docker Volume Plugin   false

[root@sldv-grp-swarm1 bhood]# cat /etc/hpedockerplugin/hpe.conf 
[DEFAULT]

logging = DEBUG
suppress_requests_ssl_warnings = False

hpedockerplugin_driver = hpedockerplugin.hpe.hpe_3par_iscsi.HPE3PARISCSIDriver

host_etcd_ip_address = 172.17.0.13
host_etcd_port_number = 2379

hpe3par_api_url = https://10.226.8.10:8080/api/v1
iscsi_ip_address = 10.226.8.10
hpe3par_iscsi_ips = 10.226.8.10,10.226.8.11,10.226.8.12,10.226.8.13

use_multipath = False
enforce_multipath = False

**Comment by puppetpies** [comment]
I have also done docker plugin set hpe glibc_libs.source=/lib64 certs.source=/tmp

**Comment by hpe-storage** [comment]
your hpe.conf should have settings for

ssh_hosts_key_file = /root/.ssh/known_hosts
hpe3par_api_url = https://<3PAR IP address>:8080/api/v1
hpe3par_username = <3par WSAPI username>
hpe3par_password = <3par WSAPI password>
san_ip = <SAN IP>
san_login = <SAN username>
san_password = <SAN password>
hpe3par_cpg = <CPG name used for volume creation>
iscsi_ip_address = <iSCSI IP address>

# iscsi_ip_address should be substituted with the target portal IP of the array.


Refer : https://github.com/hpe-storage/python-hpedockerplugin/blob/master/config/hpe.conf.sample.3parISCSI

**Comment by hpe-storage** [comment]
Also one more thing i noticed is that you are using

`hpe3par_iscsi_ips = 10.226.8.10,10.226.8.11,10.226.8.12,10.226.8.13` which is not required if the multipath flags are False. Delete this from your configuration.

**Comment by hpe-storage** [comment]
Closing this issue due to no response. Re-open if you are running into issues still.
