### ISSUE TITLE
Docker 3.2: DockerFpg_0 creation fails with if 2 docker servers point to the same CPG

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#680]
Summary - When we have 2 docker severs having independent etcd, which are pointing to the same CPG of the same 3PAR array, and if the share is created from first docker followed by the another, share creation on second docker fails with the below error.

 "detailedStatus": "Share creation failed: Share creation on new FPG failed. Reason: FPG creation failed: Create new FPG DockerFpg_0 failed. Msg: FPG already exists: Error: FPG DockerFpg_0 already exists.",

Attaching detailed output with relevant Logs - 
[Default_FPG01_Create_Error.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/3373649/Default_FPG01_Create_Error.docx)
[Default_fpg0_Create_Issue.log](https://github.com/hpe-storage/python-hpedockerplugin/files/3373650/Default_fpg0_Create_Issue.log)

**Comment by amitk1977** [comment]
To be verified by Shashi in final RC build of 7/10

**Comment by sonawane-shashikant** [comment]
This issue is verified as FIXED.
Please see attached output captured for plain docker and k8s for verification details.

[680_verification_k8s.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/3381484/680_verification_k8s.docx)
[FileServiceStaticWithoutCPGInHPEConf_Log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3381485/FileServiceStaticWithoutCPGInHPEConf_Log.txt)
