### ISSUE TITLE
Docker 3.2: File persona shared volume mount fails

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#689]
Summary - When we have 2 different docker hosts sharing common etcd, and volume is created from docker host1 followed by mounting the same. 
And if we try to mount same share  from other docker host2, it fails with below error.

[root@cld6b14 ~]# docker run -it -d -v SHASHI_18_1:/Data1 --volume-driver hpe --rm --name MOUNT_18_2 busybox /bin/sh
docker: Error response from daemon: create SHASHI_18_1: found reference to volume 'SHASHI_18_1' in driver 'hpe:latest', but got an error while checking the driver: error while checking if volume "SHASHI_18_1" exists in driver "hpe:latest": Post http://%2Frun%2Fdocker%2Fplugins%2Fccd18d88b64a9d001c65fef5dba43e1fbdbd31a672c99772d0726b9bd29ca2d8%2Fhpe.sock/VolumeDriver.Get: net/http: request canceled (Client.Timeout exceeded while awaiting headers): volume name must be unique.
See 'docker run --help'.

**Comment by imran-ansari** [comment]
VFS IP is not reachable from the host where mount is failing.
Please ensure that you choose the VFS IP that is reachable from both the hosts.

**Comment by sandesh-desai** [comment]
Verified and working as expected.
Attaching the logs:
[Steps to Reproduce.docx](https://github.com/hpe-storage/python-hpedockerplugin/files/3385198/Steps.to.Reproduce.docx)

@sonawane-shashikant : Please close the bug.

**Comment by sonawane-shashikant** [comment]
Closing as per comment by @sandesh-desai
