### ISSUE TITLE
DECO: Need proper alignment for error message.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#696]
Steps to re-produce:
1) docker volume create -d hpe --name Default_Volume10 -o provisioning=dedup -o compression=false -o backend=merlin

Expected result:Error response from daemon: create Default_Volume10: Invalid input received: For enabling the compression for primera tdvv and compression both are true.

Actual Result :Error response from daemon: create Default_Volume10: Invalid input received: For enabling the                         compression for primera tdvv and compression                         both are true.

**Comment by bhagyashree-sarawate** [comment]
Fixed #PR72

**Comment by sandesh-desai** [comment]
Verified and working as expected. Closing the bug. 

[root@cssosbe01-b13-196117 ~]# docker volume create -d hpe --name Default_Volume10 -o provisioning=dedup -o compression=false -o backend=Merlin_140
Error response from daemon: create Default_Volume10: Invalid input received: For deduplicated and compressed volume, provisioning must be specified as 'dedup' and 'compression' must be specified as true.
