### ISSUE TITLE
DECO:Error message need correction

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#698]
[root@cssosecostor-b10 ~]# docker volume create -d hpe --name Default_Volume9 -o compression=yes  -o provisioning=no -o backend=merlin

Actual Error : Error response from daemon: create Default_Volume9: create volume failed, error is:passed compression parameter do not have a valid value. Valid **vaues** are: ['true', 'false']

Expected Error: Error response from daemon: create Default_Volume9: create volume failed, error is:passed compression parameter do not have a valid value. Valid **values** are: ['true', 'false']

**Comment by bhagyashree-sarawate** [comment]
Fixed PR#699

**Comment by sandesh-desai** [comment]
Verified and working as expected.Closing the bug.

docker volume create -d hpe --name Default_Volume9 -o compression=yes -o provisioning=no -o backend=Merlin_140
Error response from daemon: create Default_Volume9: create volume failed, error is:passed compression parameter do not have a valid value. Valid values are: ['true', 'false']
