### ISSUE TITLE
[Merlin][Automated Installer]: Hardcoded wsapi url port [8080]

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#707]
Summary - When we install docker volume plugin using automated installer, its observed that port of api url set in hpe.conf is hardcoded as "8080" in "/root/python-hpedockerplugin/ansible_3par_docker_plugin/tasks/create_conf_file.yml"

Test Bed - 
Kubernetes Setup on CentOS
Merlin Array 15.213.68.203

Steps to reproduce - 
1. Create K8s cluster
2. Prepare plugin properties file for Merlin
3. Run Automated installer
4. Verify hpe.conf

Expected Result - 
hpe3par_api_url in hpe.conf should be generated as below
hpe3par_api_url=https://15.213.68.203:443/api/v1

Actual Result - 
hpe3par_api_url in hpe.conf is generated as below
hpe3par_api_url=https://15.213.68.203:8080/api/v1

**Comment by bhagyashree-sarawate** [comment]
Assign to me

**Comment by sneharai4** [comment]
@sonawane-shashikant Please verify. Fix is merged https://github.com/hpe-storage/python-hpedockerplugin/pull/728.
