### ISSUE TITLE
provisioning "thin' and compression false should result in creation of thin volume  

### ISSUE THREAD

**Issue by c-raghav** [hpe-storage/python-hpedockerplugin#709]
provisioning "thin' and compression false should result in creation of thin volume  , but it is but it is erroring out, this needs to be addressed

Provisioning       Compression     Result
======================================
thin                        FALSE                    ERROR

**Comment by bhagyashree-sarawate** [comment]
Fixed

**Comment by sandesh-desai** [comment]
Verified and working fine.

[root@cssosbe01-b13-196117 ~]# docker volume create -d hpe --name Default_Volume2  -o provisioning=thin  -o compression=false
Default_Volume2

[root@cssosbe01-b13-196117 ~]# docker volume inspect Default_Volume2
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/89cfa19582ea79c6c4da521cf6c5733c65c067c89d1b219d777b21d5b6387fad/rootfs",
        "Name": "Default_Volume2",
        "Options": {
            "compression": "false",
            "provisioning": "thin"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-J6EtgB-LQ-qhYy9yIDdcug",
                "backend": "DEFAULT",
                "compression": "false",
                "cpg": "bh_cpg",
                "domain": null,
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "thin",
                "size": 100,
                "snap_cpg": "bh_cpg"
            }
        }
    }
]

on 3PAR
2887 dcv-J6EtgB-LQ-qhYy9yIDdcug  tpvv No    No    base  2019-08-19 17:06:05 IST --                 --               --              --                     --                    {"volume_id": "27a12d80-1fcb-43fa-a163-2f7220375cba", "name": "27a12d80-1fcb-43fa-a163-2f7220375cba", "type": "Docker", "display_name": "Default_Volume2"}

@c-raghav :  Please close the bug.

**Comment by amitk1977** [comment]
Raghavendra C to verify and close

**Comment by c-raghav** [comment]
Verified and closing the issue

[root@cssosbe01-196113 hpedockerplugin]# docker volume create -d hpe --name test-defect -o size=10 -o provisioning="thin" -o compression="false"
test-defect
[root@cssosbe01-196113 hpedockerplugin]# docker volume ls
DRIVER              VOLUME NAME
hpe                 3par-1-e9dca4a9-c4c0-4b78-9cd9-85ede19b0f66
hpe                 sc-snapshot-54f42f3d-268a-4df0-acac-9cc814c038ef
hpe                 sched_vol
hpe                 test-defect
[root@cssosbe01-196113 hpedockerplugin]# docker volume inspect test-defect
[
    {
        "Driver": "hpe",
        "Labels": {},
        "Mountpoint": "/",
        "Name": "test-defect",
        "Options": {
            "compression": "false",
            "provisioning": "thin",
            "size": "10"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-nfPbTlHHQiedZdECysQ20A",
                "backend": "DEFAULT",
                "compression": "false",
                "cpg": "demo",
                "domain": null,
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "id": "9df3db4e-51c7-4227-9d65-d102cac436d0",
                "mountConflictDelay": 30,
                "provisioning": "thin",
                "size": 10,
                "snap_cpg": "demo11"
            }
        }
    }
