### ISSUE TITLE
provisioning "thin' and compression "",should result in ERROR instead of creating thin volume

### ISSUE THREAD

**Issue by c-raghav** [hpe-storage/python-hpedockerplugin#710]
provisioning "thin' and compression "",should result in ERROR instead of creating thin volume

Provisioning       Compression     Result
======================================
thin                        “”                            ERROR

**Comment by c-raghav** [comment]
proisioning ="" and compression "", is resulting in creating thin volume instead of erroring out , this  needs to address

**Comment by c-raghav** [comment]
creating volume with size = "0" or size = o

it still creates volume of size 1024 MB in the backed.
But inspect show size = 0

Since we are restricting the case of provisioning ="" and compression "",

This also we need to address, by restricting creation with proper message

**Comment by bhagyashree-sarawate** [comment]
Assign to me, need discussion with imran

**Comment by bhagyashree-sarawate** [comment]
Fixed and merged

**Comment by amitk1977** [comment]
Raghavendra C to verify and close

**Comment by c-raghav** [comment]
Verified and find the output below

[root@cssosbe01-196113 hpedockerplugin]# docker volume create -d hpe --name test-defect -o size=10 -o provisioning=thin -o compression=""
Error response from daemon: create test-defect: create volume failed, error is: passed compression parameter does not have a valid value. Valid values are: ['true', 'false']

[root@cssosbe01-196113 hpedockerplugin]# docker volume create -d hpe --name test-defect -o size=10 -o provisioning="thin" -o compression=""
Error response from daemon: create test-defect: create volume failed, error is: passed compression parameter does not have a valid value. Valid values are: ['true', 'false']

[root@cssosbe01-196113 hpedockerplugin]# docker volume create -d hpe --name test-defect -o size=10 -o provisioning="" -o compression=""
Error response from daemon: create test-defect: create volume failed, error is: passed compression parameter does not have a valid value. Valid values are: ['true', 'false']

[root@cssosbe01-196113 hpedockerplugin]# docker volume create -d hpe --name test-defect -o size=0 -o provisioning="thin"
Error response from daemon: create test-defect: Please enter the valid integer value for size                        parameter
