### ISSUE TITLE
Incorrect/Inconsistent provisioning type displayed on 3PAR for FULL provisioned volume

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#712]
Summary: Incorrect/inconsistent provisioning type displayed on 3par for volume created through docker cli with provisioning type as full.
 
OS: Centos 7.6
 
3PAR IP: 10.50.3.9
3par OS: 3.3.1 (MU4)
 
pre-requisite:
Docker should be installed and etcd should be up and running
 
Steps to reproduce:
1. Installed and enable HPE 3par plugin.
2. create full provisioning volume on 3PAR using 3PAR CLI
3. create full provisioning volume on docker using docker cli.
3. verify provisioning type for both the volume on 3par using shovv command.
 
 
Expected: Provisioning type should be displayed as "full" for both the volumes.
 
Actual result: provisioning type has been shown as "cpvv" instead of "full" for volume created using docker CLI.
 
 
Note:
As per HPE 3PAR OS Command Line Interface <HPE 3PAR OS 3.3.1 MU1> The "-type cpvv" option is deprecated and will be removed in a subsequent release.
 
output:
 
Full provision volume created on 3PAR
 
CSIM-8K02_MXN6072AC7 cli% createvv jupyter vol_3par 20g
 
 
Full provision volume created on docker:
 
[root@cld6b10 ~]# docker volume create -d hpe --name vol_docker -o provisioning="full"
vol_docker
 
 
CSIM-8K02_MXN6072AC7 cli% showvv -cpg jupyter
                                                                                                                -Rsvd(MiB)- -(MiB)--
    Id Name                        Prov Compr Dedup Type  CopyOf                       BsId Rd -Detailed_State-  Snp    Usr    VSize
107894 .shared.jupyter_0           dds  NA    No    base  ---                        107894 RW normal              0   1024 67108864
107895  dcv-DEjY-YgURfOqNHuhJLHAgw tdvv Yes   Yes   base  ---                        107895 RW normal           1024   1024   102400
108032   jup.190804212000          snp  Yes   NA    vcopy dcv-DEjY-YgURfOqNHuhJLHAgw 107895 RW normal             --     --   102400
108034   jup.190804222000          snp  Yes   NA    vcopy dcv-DEjY-YgURfOqNHuhJLHAgw 107895 RW normal             --     --   102400
108038   jup.190804232000          snp  Yes   NA    vcopy dcv-DEjY-YgURfOqNHuhJLHAgw 107895 RW normal             --     --   102400
108040 dcv-acx6FcH0QU.gAOo5hQ1sNg  cpvv NA    NA    base  ---                        108040 RW normal           1024 102400   102400
108039 vol_3par                    full NA    NA    base  ---                        108039 RW normal              0  20480    20480
------------------------------------------------------------------------------------------------------------------------------------
     7 total       

![cli_guide](https://user-images.githubusercontent.com/21362687/62619439-6d051b80-b934-11e9-8e87-5de1f8cbf5d7.jpg)

**Comment by bhagyashree-sarawate** [comment]
Needs investigation from wsapi

**Comment by bhagyashree-sarawate** [comment]
When we create the volume using docker plugin commands we have the provisioning type as FULL  as per the wsapi document.
As per WSAPI document ,
FULL -   1 FPVV,       either with no snapshot space or with statically allocated snapshot space.
                                Also, a commonly-provisioned VV where the user space is fully provisioned 
                                and the snapshot space is associated with the snapCPG property.

Provision type is shown as 1 for both full and cpvv provision type volume as per wsapi document, so this seems to be invalid issue for Docker plugin.

**Comment by bhagyashree-sarawate** [comment]
Created volume using full provisioning and verified wsapi output which always give provisioningType=1. 
Output
---------
[root@cld6b10 ~]# docker volume create -d hpe --name jvol23 -o provisioning=full
jvol23

[root@cld6b10 ~]# docker volume inspect jvol23
[
    {
        "CreatedAt": "0001-01-01T00:00:00Z",
        "Driver": "hpe",
        "Labels": {},
        "Mountpoint": "",
        "Name": "jvol23",
        "Options": {
            "provisioning": "full"
        },
        "Scope": "global",
        "Status": {
            "volume_detail": {
                "3par_vol_name": "dcv-98X4thu-QviUaNx9.CSShQ",
                "backend": "DEFAULT",
                "compression": null,
                "cpg": "FC_r1",
                "domain": "CAPGEMINI",
                "flash_cache": null,
                "fsMode": null,
                "fsOwner": null,
                "mountConflictDelay": 30,
                "provisioning": "full",
                "size": 100,
                "snap_cpg": "FC_r1"
            }
        }
    }
]

CSIM_EOS14_1674003 cli% showvv -cpg FC_r1
                                                                                        -Rsvd(MiB)- -(MiB)-
   Id Name                       Prov Compr Dedup Type CopyOf  BsId Rd -Detailed_State-  Snp    Usr   VSize
60530 dcv-98X4thu-QviUaNx9.CSShQ cpvv NA    NA    base ---    60530 RW normal           1024 102400  102400


WSAPI:
'
{
"id": 60530,
"name": "dcv-98X4thu-QviUaNx9.CSShQ",
"domain": "CAPGEMINI",
"deduplicationState": 3,
"compressionState": 4,
"provisioningType": 1,
"copyType": 1,
"baseId": 60530,
"readOnly": false,
"state": 1,
"failedStates":[],
"degradedStates":[],
"additionalStates":[],
"adminSpace":{
"reservedMiB": 512,
"rawReservedMiB": 1536,
"usedMiB": 2,
"freeMiB": 510
},
"snapshotSpace":{
"reservedMiB": 1024,
"rawReservedMiB": 2048,
"usedMiB": 0,
"freeMiB": 1024
},
"userSpace":{
"reservedMiB": 102400,
"rawReservedMiB": 204800,
"usedMiB": 102400,
"freeMiB": 0
},
"totalReservedMiB": 103424,
"totalUsedMiB": 102400,
"sizeMiB": 102400,
"wwn": "60002AC0000000000000EC7200012113",
"creationTimeSec": 1566450067,
"creationTime8601": "2019-08-21T23:01:07-06:00",
"ssSpcAllocWarningPct": 0,
"ssSpcAllocLimitPct": 0,
"usrSpcAllocWarningPct": 0,
"usrSpcAllocLimitPct": 0,
"policies":{
"staleSS": true,
"oneHost": false,
"zeroDetect": false,
"system": false,
"caching": true,
"fsvc": false,
"hostDIF": 3
},
"userCPG": "FC_r1",
"snapCPG": "FC_r1",
"uuid": "4a4289a8-1037-4ea0-86c7-c2c46116f2d0",
"udid": 60530,
"comment": "{\"volume_id\": \"f7c5f8b6-1bbf-42f8-9468-dc7df8249285\", \"name\": \"f7c5f8b6-1bbf-42f8-9468-dc7df8249285\", \"type\": \"Docker\", \"display_name\": \"jvol23\"}",
"capacityEfficiency":{
"compaction": 1
},
"rcopyStatus": 1,
"links":[
{
"href": "https://10.50.3.24:8080/api/v1/volumes/dcv-98X4thu-QviUaNx9.CSShQ",
"rel": "self"
},
{
"href": "https://10.50.3.24:8080/api/v1/volumespacedistribution/dcv-98X4thu-QviUaNx9.CSShQ",
"rel": "volumeSpaceDistribution"
}
]
}

**Comment by sonawane-shashikant** [comment]
Closing as per above comment.
