### ISSUE TITLE
Snapshot Schedule: Need correction in Error Message

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#714]
[root@cssosbe01-196113 ~]# docker volume create -d hpe  -o virtualCopyOf=SHASHI-VOL -o scheduleFrequency="0 0,12 * * *" -o expHrs=1 -o retHrs=3 -o scheduleName=SHASHI-SCHED1 -o snapshotPrefix=ABC
Error response from daemon: create 23a86e6a7f0f581cc7ce33b9ca20194e78f2318699a3171a32f7aab2ad9ab937: create schedule failed, error is: expiration hours cannot be greater than retention hours
[root@cssosbe01-196113 ~]#

Expected Results - 
Error Message should be seen as below (any one)
retention hours cannot be greater than expiration hours.
OR
expiration hours must be greater than retention hours.

Actual result - 
Error Message is seen as below
expiration hours cannot be greater than retention hours

**Comment by bhagyashree-sarawate** [comment]
Fixed and merged

**Comment by amitk1977** [comment]
Shashi to verify and close

**Comment by sonawane-shashikant** [comment]
This issue is verified as FIXED.

Attached is the relevant output for reference.

[714_fixed.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3689147/714_fixed.txt)
