### ISSUE TITLE
Merlin:Error message need correction

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#718]
[root@cssosbe01-b13-196117 ~]# docker volume create -d hpe --name Default_Volume5  -o provisioning=full  -o compression=false

Actual Error message: Error response from daemon: create Default_Volume5: Invalid input received: For thin volume, 'provisioning' must be specified as 'thin'. And for deduplicated and compressed volume, 'provisioning' must be specified as 'dedup' and 'compression' must be specified to true. If any of these conditions for a given type of **volumeis** not met volume creation will fail

Expected Error message: Error response from daemon: create Default_Volume5: Invalid input received: For thin volume, 'provisioning' must be specified as 'thin'. And for deduplicated and compressed volume, 'provisioning' must be specified as 'dedup' and 'compression' must be specified to true. If any of these conditions for a given type of **volume is** not met volume creation will fail.

**Comment by virendra-sharma** [comment]
[root@ecostor-b13 virendra]# docker volume create -d hpe --name volume1 -o compression=true -o provisioning=full

Actual Error message: Error response from daemon: create volume1: Invalid input received: To create compression enabled volume, size of the volume should be **atleast** 16GB. Fully provisioned volume **can not** be compressed. Please **re enter** requested volume size or provisioning type.

Expected error message: [root@ecostor-b13 virendra]# docker volume create -d hpe --name volume1 -o compression=true -o provisioning=full
Error response from daemon: create volume1: Invalid input received: To create compression enabled volume, size of the volume should be **at least** 16GB. Fully provisioned volume **cannot** be compressed. Please **re-enter** requested volume size or provisioning type.

**Comment by bhagyashree-sarawate** [comment]
Fixed and merged

**Comment by amitk1977** [comment]
Sandesh to verify and close

**Comment by sonawane-shashikant** [comment]
This bug is verified as FIXED.
Attached is the output for reference.

[718_fixed.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3689169/718_fixed.txt)

**Comment by sandesh-desai** [comment]
closing as per above message.
