### ISSUE TITLE
Merlin: Merlin related option not available in "help"

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#719]
Steps as follows:

docker volume create -d hpe -o help

Expected result:Merlin related option not available in "help"

**Comment by bhagyashree-sarawate** [comment]
This will be taken with the re-branding task

**Comment by bhagyashree-sarawate** [comment]
Fixed and merged

**Comment by amitk1977** [comment]
Sandesh to verify and close

**Comment by sandesh-desai** [comment]
Verified and closed.
[719_fixed.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3688889/719_fixed.txt)
