### ISSUE TITLE
Merlin: VLUNs are not get deleted after pod mount to other node.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#724]
TestBed Details:
15.212.196.113 - Master node

[root@cssosbe01-196113 DECO]# docker version
Client: Docker Enterprise Edition (EE) 2.0
 Version:      17.06.2-ee-23

[root@cssosbe01-196113 DECO]# docker ps  | grep plugin
b731871b46c2        hpestorage/legacyvolumeplugin:3.2.1-prerelease   "/bin/sh -c ./plug..."   2 days ago          Up 2 days                                                                                                                             plugin_container
[root@cssosbe01-196113 DECO]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"

Steps Performed:

1.Create SC,PVC with mountConflictDelay as 60.
2.Create POD1 on PVC on workernode-1 and check the vluns on docker and 3par array.
3.Create POD2 on same PVC (used by workernode-1) on Workernode-2 and check the vluns on docker and 3par array

Expected Result: Vluns on workernode-1 should be deleted once pod2 mounted to other node.

Actual Result: Vluns on workernode-1 are not deleted.
Also after removing the both pods volume is still showing the mount path in docker volume inspect command.

Attaching the  Bug Details,log file and Yamls:

[BUG detail.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3519699/BUG.detail.txt)
[LOG_FILE.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3519700/LOG_FILE.txt)
[Yamls for the BUG.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3519736/Yamls.for.the.BUG.txt)

**Comment by amitk1977** [comment]
Sandesh will investigate if this is seen on 3PAR.
Bhagyashree for investigation.

**Comment by sandesh-desai** [comment]
Able to re-produce on 3PAR attaching the logs.

[BUG 724 on 3PAR.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3534810/BUG.724.on.3PAR.txt)
[LOGs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3534811/LOGs.txt)

**Comment by sandesh-desai** [comment]
Verified and working as expected.Closing the bug
Attaching the logs:

[Pod creation logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3717042/Pod.creation.logs.txt)
