### ISSUE TITLE
Automated Installer: Installer with etcd cluster leaves k8s cluster in NotReady state

### ISSUE THREAD

**Issue by sonawane-shashikant** [hpe-storage/python-hpedockerplugin#741]
Run Automated installer on kubernetes multi-master setup with multiple IPs in etcd section of hosts file.
Plugin installs successfully without any errors.
But kubertnetes cluster goes into NotReady state.

Expected Results - 
Installer should not corrupt the existing kubernetes cluster

Actual Results - 
Installer leaves k8s cluster in NotReady state

Attached are the logs captured - 

[installer-output-on-3-workers.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3658661/installer-output-on-3-workers.txt)
[message_log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3658662/message_log.txt)
[hosts.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3658664/hosts.txt)

**Comment by sandesh-desai** [comment]
Ran Automated installer on Openshift 3.11 Observed the same issue.
Installer leaves openshift cluster in NotReady state.
Plugin is in restarting mode.

Attaching the logs:

[docker_logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3858558/docker_logs.txt)
[messages_log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3858559/messages_log.txt)
[output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3858560/output.txt)
[3pardcv_logs.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3858561/3pardcv_logs.txt)

**Comment by sandesh-desai** [comment]
Ran Automated installer on Openshift 3.11 and now cluster is in ready state.
Attaching the output.
[Automated installer output for doryd as a Service.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3872916/Automated.installer.output.for.doryd.as.a.Service.txt)

**Comment by sonawane-shashikant** [comment]
This issue is verified as FIXED.
Attached are the scenarios executed to verify this bug.
Closing this bug as FIXED.

[Bug_741_Verification.zip](https://github.com/hpe-storage/python-hpedockerplugin/files/3939086/Bug_741_Verification.zip)
