### ISSUE TITLE
3.3 MountConflictDelay :After deleting pod multipath -ll entries not cleaned.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#743]
3.3 MountConflictDelay :After deleting pod multipath -ll entries not cleaned.

Testbed Details:
Host: -- openshift single master setup.
Host OS: "Red Hat Enterprise Linux Server"VERSION="7.6
OC version: oc v3.11.117

Steps followed on OpenShift 3.11 single-master

1)	Create a pv,pvc,pod with the yml
2)	pod/pod-provisionedvol are in Running state on worker-2
3)	verify multipath -ll  on worker-2 (entries are present)
4)	verify multipath -ll on worker-1 (No entries)
5)	Create additional POD by using same PVC pod / pod-provisionedvol2 are in Running state on worker-1.
6)	Verify multipath -ll on worker-1 (entries are present)
7)	Delete pod on worker-2  
oc delete pod pod-provisionedvol
8)	Verify multipath -ll on worker-2 **entries are still present**
9)	Delete pod/ pod-provisionedvol2 on worker-1
oc delete pod pod-provisionedvol2
10)	Verify multipath -ll  on worker -1 ( No entries)

Attaching the log files
[MCD_W1.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3674812/MCD_W1.txt)
[MCD_W2.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3674813/MCD_W2.txt)

**Comment by sonawane-shashikant** [comment]
This bug is verifed as FIXED.
Attaching output.

[743_fixed.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3711887/743_fixed.txt)

**Comment by sonawane-shashikant** [comment]
@sandesh-desai please close this bug

**Comment by sandesh-desai** [comment]
Closing the bug as per above comment.

**Comment by sandesh-desai** [comment]
With Ansible installer on etcd cluster multipath -ll entries not cleaned.

Attaching the logs:

[Uploading dory.log…]()
[Uploading TC_mount.txt…]()
[Uploading 3pardcv.log…]()

**Comment by sandesh-desai** [comment]
Attaching the updated logs:

[mount_conflict_Delay.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3793661/mount_conflict_Delay.txt)

[dcvlog_115.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3793666/dcvlog_115.txt)
[dory_114.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3793667/dory_114.txt)
[dory_115.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3793668/dory_115.txt)

**Comment by sandesh-desai** [comment]
Attaching dcvlog_114.

[dcvlogs_114.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3802752/dcvlogs_114.txt)

**Comment by amitk1977** [comment]
This usecase of pods P1 on node 1 and pod P2 on node 2 using the same volume V1 is not a generally deployed scenario. This may be a usage error and does not qualify for a  high bug. Will have to discuss further as a medium bug while we check the validity of this scenario.

**Comment by amitk1977** [comment]
Documented and closed: https://github.com/hpe-storage/python-hpedockerplugin/blob/master/docs/recover_post_reboot.md

**Comment by amitk1977** [comment]
Closing as document fix
