### ISSUE TITLE
3.3 Statefulset: After node reboot 1 pod is still remain in ContainerCreating state.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#746]
Testbed Details:
Host: -- Openshift single master setup.
Host OS: "Red Hat Enterprise Linux Server"VERSION="7.6
OC version: oc v3.11.117

Steps to reproduce:

1) Cordon master and worker-1
 [root@cssosbe04-b01 StatefulSet1]# oc get nodes
NAME            STATUS                     ROLES           AGE       VERSION
cssosbe04-b01   Ready,SchedulingDisabled   master          79d       v1.11.0+d4cacc0
cssosbe04-b02   Ready,SchedulingDisabled   compute         79d       v1.11.0+d4cacc0
cssosbe04-b03   Ready                      compute,infra   79d       v1.11.0+d4cacc0

2)  oc create -f sc.yml
3) oc create -f pvc.yml
4) oc create -f configmap.yaml
5) oc create -f statefulset.yaml
10 replicas created successfully on worker-2
6) reboot worker-2
7) After reboot 9 pods are in Running state and one pod remain in ContainerCreating state.

Attaching the logs and yml.

[3parlog.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3685418/3parlog.txt)
[10 POD creation result.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3685419/10.POD.creation.result.txt)
[dory log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3685420/dory.log.txt)

 

[sc.yml.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3685496/sc.yml.txt)

[pvc.yml.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3685497/pvc.yml.txt)

[configmap.yaml.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3685502/configmap.yaml.txt)
[statefulset.yaml.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3685503/statefulset.yaml.txt)

=============================================================
In Kubernetes Multimaster 
1) Scaleup to 15 :  2 out of 15 PODs is in ContainerCreating State.
2) Scaledown to 10 : 3 out of 15 PODs is in Terminating State.

Steps Followed:

1.Create SC,PVC,Configmap,POD with replicas=5 on one worker.
2.Scale up to 15 PODs
  Expected Result: All 15 PODs should be in running state.
  Actual Result:2 out of 15 PODs is in ContainerCreating State.
3.Scale down to 10 PODs 
  Expected Result: 15 PODs should reduce to 10 and come into running state.
  Actual Result:3 out of 15 PODs is in Terminating State.

Attaching the logs:

[BUG_DETAILS.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3685524/BUG_DETAILS.txt)

[LOG_3pardcv.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3685528/LOG_3pardcv.txt)

[log_dory11.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3685568/log_dory11.txt)

**Comment by sandesh-desai** [comment]
In Kubernetes singlemaster

1.Create SC,PVC,Configmap,POD with replicas=10 on one worker.
2.Scale down to 5 PODs.
3.Scale up to 12 PODs.
4.Reboot worker-1

Expected Result: All 15 PODs should be in running state.
Actual Result:All 12 PODs is in ContainerCreating State.

Attaching the logs:
[dcv log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3697064/dcv.log.txt)
[statefulset.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3697066/statefulset.txt)
[worker1 dory log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3697067/worker1.dory.log.txt)

**Comment by wdurairaj** [comment]
@sandesh-desai , please follow the steps in https://github.com/hpe-storage/python-hpedockerplugin/blob/master/docs/troubleshooting.md#debugging-issue-with-statefulset-pod-stuck-in-containercreating-state-after-a-node-reboot and let me know, if this is a viable workaround for the issue.

Root cause of this issue, is the absense of `/dev/mapper` entries after the `atomic-openshift-node.service` starts (after dockerd starts). The dev mapper entries are not formed even after the host is rescanned for new devices with mounts issued. 

The situation can only be recovered by restarting multipathd using `systemctl restart multipathd`

**Comment by sandesh-desai** [comment]
Follow below steps:
kubectl cordon <node> before the node is shutdown (which has statefulset pods mounted) and kubectl uncordon <node> after the node reboots and the kubelet (or) atomic-openshift-node.service starts properly

Verified and working fine.

Attaching the logs:
[3PAR dcv.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3733382/3PAR.dcv.txt)
[BUG 746.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3733383/BUG.746.txt)
[DORY_746.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3733384/DORY_746.txt)

Also run below Steps: 
1) Cordon master and worker-1
2) oc create -f sc.yml
3) oc create -f pvc.yml
4) oc create -f configmap.yaml
5) oc create -f statefulset.yaml
6) 10 replicas created successfully on worker-2
7) Reboot worker-2

After reboot All pods are in Running state.

Verified and working fine.

Attaching the logs:
[dcvlog_746.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3733649/dcvlog_746.txt)
[DORY_746.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3733650/DORY_746.txt)
[bug_746.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3733652/bug_746.txt)

Closing the Bug.
