### ISSUE TITLE
Automation-FilePersona testcase: file persona test cases failing with volume not found error

### ISSUE THREAD

**Issue by leenaj0hn** [hpe-storage/python-hpedockerplugin#751]
Automation-FilePersona testcase: file persona test cases failing with volume not found error

1. Ran file persona (5 testcases ) automation suite on ubuntu CI slave on 3.3 docker plugin build.
Test case with -o fpg (non-existent) and -o size options failed
Test case with -o fpg (non-existent) and -o cpg options failed
Test case with -o fpg (non-existent) and -o backend options failed
Test case with -o filePersona failed
Test case with only -o fpg (non-existent) option passed.
Note: The issue is due to delay in execution of "docker volume ls" command which in turn results in the test failing with error "volume not found"

2. Ran the above failed tests on the same box manually and all tests passed.
3. In the automation tests included and 30 sec sleep between creation of the share and inspect of the share. Executed the failed test again with this change. All tests passed

Will push the change to include the delay to test automation branch

**Comment by amitk1977** [comment]
Fixed and verified by Leena and closing. 
The File Persona CI is also running successfully.
