### ISSUE TITLE
Automated Installer: iptables failed issue found Intermittently 

### ISSUE THREAD

**Issue by bhagyashree-sarawate** [hpe-storage/python-hpedockerplugin#756]
During  ansible installation while creating etcd container observed iptables failed issue
 
task path: /root/ansible_new/python-hpedockerplugin/ansible_3par_docker_plugin/tasks/create_etcd_container.yml:14
fatal: [15.212.196.113]: FAILED! => {"changed": false, "msg": "Error starting container 7c2591837fae4d017660e57bf1d4e8399667ff77f1b57140b2a735ba10375231: 500 Server Error: Internal Server Error (\"driver failed programming external connectivity on endpoint etcd_hpe (36e7bd7df61eed2043e74d7044d8b4da7e9b49d3322e0b10ea8ee4915008b0d0):  (iptables failed: iptables --wait -t nat -A DOCKER -p tcp -d 0/0 --dport 40010 -j DNAT --to-destination 172.17.0.2:40010 ! -i docker0: iptables: No chain/target/match by that name.\n (exit status 1))\")"}

Workaround for the above issue: 
Iptables should be clean from all the three nodes and restart the docker service before starting the installation.

sudo iptables -t filter -F
sudo iptables -t filter -X
systemctl restart docker

**Comment by amitk1977** [comment]
@sneharai4 suggestion awaited on clearing the iptables for specific ports

**Comment by amitk1977** [comment]
Not an issue anymore in the new approach for etcd deployment. closing the issue.
