### ISSUE TITLE
Multimaster 1.15 Statefulset : After reboot 2 PODs are in Completed State and 3 PODs are in Running state.

### ISSUE THREAD

**Issue by sandesh-desai** [hpe-storage/python-hpedockerplugin#758]
Testbed Details:
Host: -- K8s multimaster 
Host OS: CentOS 
K8s version: GitVersion:"v1.15.3

Steps performed:
1.Created SC,PVC,ConfigMap.
2.Created Statefulset with replicas=5 and all are in Running state on worker-1(cssosbe01-196150).
3.Scaled up to 12 PODs successfully and all PODs are in Running state.
4.Scaled down to 5 PODs successfully and all PODs are in Running state.
5.Rebooted worker-1.
  Expected Result: All PODs should be in Running State after the node came up.

Observation:
  Actual Result: 2 PODs are in Completed State and 3 PODs are in Running state.

Attaching the logs and output.

[dcvlog_statefulset.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3840587/dcvlog_statefulset.txt)
[dorylog_statefulset.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3840588/dorylog_statefulset.txt)
[output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3840589/output.txt)

**Comment by imran-ansari** [comment]
PR https://github.com/hpe-storage/python-hpedockerplugin/pull/761 raised that describes the steps to recover PODs after rebooting a node

**Comment by sandesh-desai** [comment]
Verified and working fine.closing the bug.
Attaching the logs:

[Statefulset testing.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/3925697/Statefulset.testing.txt)
