### ISSUE TITLE
tox failure in jenkins build

### ISSUE THREAD

**Issue by dockerciuser** [hpe-storage/python-hpedockerplugin#76]
The tox command in jenkins build is failing.
The detailed errors are given below - 

10:07:00 pep8 runtests: PYTHONHASHSEED='1625958770'
10:07:00 pep8 runtests: commands[0] | flake8 hpedockerplugin test
10:07:01 hpedockerplugin/hpe_storage_api.py:41:1: F401 'time' imported but unused
10:07:01 import time
10:07:01 ^
10:07:01 hpedockerplugin/hpe_plugin_service.py:122:17: E999 SyntaxError: invalid syntax
10:07:01         print cfg
10:07:01                 ^
10:07:01 hpedockerplugin/hpe/san_driver.py:82:50: E999 SyntaxError: invalid syntax
10:07:01         print "Error from iscsiadm -m discovery: ", targetip
10:07:01                                                  ^
10:07:01 test/test_hpe_plugin.py:73:37: E999 SyntaxError: invalid syntax
10:07:01             print 'self.twistd_pid: ', self.twistd_pid
10:07:01                                     ^
10:07:01 test/test_hpe_plugin.py:146:9: E722 do not use bare except'
10:07:01         except:
10:07:01         ^
10:07:01 ERROR: InvocationError: '/home/jenkins/jenkins_slave/workspace/docker-3par-iscsi-plugin-build/.tox/pep8/bin/flake8 hpedockerplugin test'
10:07:01 ___________________________________ summary ____________________________________
10:07:01 ERROR:   pep8: commands failed

Regards,
Tushar

**Comment by hpe-storage** [comment]
Probably the CI is running on the master branch is what I believe. These tox errors are resolved already in plugin_v2 branch. Please check.

**Comment by dockerciuser** [comment]
Thank you. I have modified the jenkins job to run unit tests on plugin_v2 branch instead of master.
