### ISSUE TITLE
Discrepancy in the output of inspect between source and cloned docker volume

### ISSUE THREAD

**Issue by dgavand** [hpe-storage/python-hpedockerplugin#78]
Cloned volume does not fetches source volume's options or volume properties.

# docker volume create -d hpe --name vol -o size=10 -o flash-cache=True
vol
#
# docker volume inspect vol
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/ac0298e054e4769ad622557dac226ba246079c187a05f26317d12a52ffa72150/rootfs",
        "Name": "vol",
        "Options": {
            "flash-cache": "True",
            "size": "10"
        },
        "Scope": "local"
    }
]
#

After cloned operation, it shows only "cloneOf" options instead of all options / properties of source volume in docker inspect :

# docker volume create -d hpe --name vol-clone -o cloneOf=vol
vol-clone
#
#
# docker volume inspect vol-clone
[
    {
        "Driver": "hpe:latest",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/plugins/ac0298e054e4769ad622557dac226ba246079c187a05f26317d12a52ffa72150/rootfs",
        "Name": "vol-clone",
        "Options": {
            "cloneOf": "vol"
        },
        "Scope": "local"
    }
]

**Comment by wdurairaj** [comment]
Fixed in the recent tag

**Comment by wdurairaj** [comment]
dockerciuser/hpedockerplugin:test
