### ISSUE TITLE
Usage guide has no information about driver option 'mount-volume'

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#79]
Driver option 'mount-volume' is displayed as supported option from HPE 3PAR plugin.

docker@worker3:~$ dvol create -d hpe -o help
Error response from daemon: create 1ac12c608434ab026c3136d5adb27b2f4419575131ae994e0a9da84e680ae40d: create volume failed, error is: help is not a valid option. Valid options are: ['mount-volume', 'size', 'provisioning', 'flash-cache', 'cloneOf', 'snapshotOf', 'snapCloneOf', 'expirationHours', 'retentionHours'] 

But, there is no instruction provided about 'mount-volume' in usage guide and the use case is still not known.

**Comment by imran-ansari** [comment]
Option 'mount-volume' is an unused option and must be removed from the valid-options list in the plugin.

**Comment by sandesh-desai** [comment]
Verified and closed.
Attaching the help output.
[Docker help output.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/2483076/Docker.help.output.txt)

**Comment by prablr79** [comment]
Based on the Sandesh inputs this bug is closed.
