### ISSUE TITLE
Docker copy operation fails when files are copied from container to Docker host and vice-versa

### ISSUE THREAD

**Issue by leeantho** [hpe-storage/python-hpedockerplugin#8]
Attempts to mount a volume multiple times will result in an error from the plugin.

One example of where this occurs is when a 'docker cp ...' is used to copy a file to a volume that is already attached to a container.

The plugin will throw an error stating that the volume is already in use and then be unmounted by the cleanup stage (caused by the exception being thrown).

**Comment by rpong79** [comment]
We are also facing this issue now. We want multiple containers with same software to use same data on volume. At this point it's not possible.

**Comment by hpe-storage** [comment]
This is a shared volume usecase, and hence it needs to be addressed as an enhancement.

**Comment by wdurairaj** [comment]
recent release of hpestorage/legacyvolumeplugin:2.1 tag shared volume use case is supported .. please follow this instructions to bringup a plugin container -- https://github.com/hpe-storage/python-hpedockerplugin/tree/plugin_v2/quick-start
