### ISSUE TITLE
Volume mount operation fails intermittently with iSCSI with Creating filesystem error.

### ISSUE THREAD

**Issue by dgavand** [hpe-storage/python-hpedockerplugin#83]
OS platform: Ubuntu 16.04 with iSCSI Backend
Plugin tag: sandanar/hpedockerplugin:2.0.2
Docker Version : 17.06.1-ee-2 / API version:  1.30

All the performed steps are mentioned below on how the issue was observed:

1. Performed CHO Script on Ubuntu system with iSCSI multipath backend for 12 hours.

Observed multiple failures with below error:

<div class="error">
    <span>hpedockerplugin.exception.HPEPluginFileSystemException</span>: <span>HPE Docker Volume Plugin File System error: (u'create file system failed exception is : %s', u'\n\n  RAN: /sbin/mkfs -F /dev/sdb\n\n  STDOUT:\nDiscarding device blocks:    4096/2359296\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08               \x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08\x08failed - Remote I/O error\nCreating filesystem with 2359296 4k blocks and 589824 inodes\nFilesystem UUID: 2ea67058-366d-4f09-a25d-2bdab089c222\nSuperblock backups stored on blocks: \n\t32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632\n\nAllocating group tables:  0/72\x08\x08\x08\x08\x08     \x08\x08\x08\x08\x08done                            \nWriting inode tables:  0/72\x08\x08\x08\x08\x08     \x08\x08\x08\x08\x08done                            \nWriting superblocks and filesystem accounting information:  0/72\x08\x08\x08\x08\x08\n\n  STDERR:\nmke2fs 1.43.6 (29-Aug-2017)\n\nWarning, had trouble writing out superblocks.\n')</span>
  </div>

  Observed stale entries in Docker host and same numbers of vlun entries in 3PAR as well.

# ls -lrt /dev/disk/by-path/
total 0
lrwxrwxrwx 1 root root  9 Nov 10 04:02 pci-0000:03:00.0-scsi-0:1:0:0 -> ../../sda
lrwxrwxrwx 1 root root 10 Nov 10 04:02 pci-0000:03:00.0-scsi-0:1:0:0-part5 -> ../../sda5
lrwxrwxrwx 1 root root 10 Nov 10 04:02 pci-0000:03:00.0-scsi-0:1:0:0-part2 -> ../../sda2
lrwxrwxrwx 1 root root 10 Nov 10 04:02 pci-0000:03:00.0-scsi-0:1:0:0-part1 -> ../../sda1
lrwxrwxrwx 1 root root  9 Nov 13 23:57 ip-10.50.1.20:3260-iscsi-iqn.2000-05.com.3pardata:20220002ac002b9f-lun-0 -> ../../sdc
lrwxrwxrwx 1 root root  9 Nov 13 23:57 ip-10.50.1.19:3260-iscsi-iqn.2000-05.com.3pardata:20210002ac002b9f-lun-0 -> ../../sdb
lrwxrwxrwx 1 root root  9 Nov 13 23:59 ip-10.50.1.20:3260-iscsi-iqn.2000-05.com.3pardata:20220002ac002b9f-lun-1 -> ../../sde
lrwxrwxrwx 1 root root  9 Nov 14 00:00 ip-10.50.1.19:3260-iscsi-iqn.2000-05.com.3pardata:20210002ac002b9f-lun-1 -> ../../sdd
lrwxrwxrwx 1 root root  9 Nov 14 11:50 ip-10.50.1.19:3260-iscsi-iqn.2000-05.com.3pardata:20210002ac002b9f-lun-3 -> ../../sdh
lrwxrwxrwx 1 root root  9 Nov 14 11:51 ip-10.50.1.20:3260-iscsi-iqn.2000-05.com.3pardata:20220002ac002b9f-lun-3 -> ../../sdi
lrwxrwxrwx 1 root root  9 Nov 14 11:51 ip-10.50.1.20:3260-iscsi-iqn.2000-05.com.3pardata:20220002ac002b9f-lun-2 -> ../../sdg
lrwxrwxrwx 1 root root  9 Nov 14 11:51 ip-10.50.1.19:3260-iscsi-iqn.2000-05.com.3pardata:20210002ac002b9f-lun-2 -> ../../sdf
# 

# lsscsi
[0:0:0:0]    storage HP       P220i            7.02  -
[0:0:0:4194240]storage HP       P220i            7.02  -
[0:1:0:0]    disk    HP       LOGICAL VOLUME   7.02  /dev/sda
[1:0:0:254]  enclosu 3PARdata SES              3310  -
[1:0:1:254]  enclosu 3PARdata SES              3310  -
[1:0:2:254]  enclosu 3PARdata SES              3310  -
[1:0:3:254]  enclosu 3PARdata SES              3310  -
[2:0:0:254]  enclosu 3PARdata SES              3310  -
[2:0:1:254]  enclosu 3PARdata SES              3310  -
[2:0:2:254]  enclosu 3PARdata SES              3310  -
[2:0:3:254]  enclosu 3PARdata SES              3310  -
[156:0:0:0]  disk    3PARdata VV               3310  /dev/sdb
[156:0:0:1]  disk    3PARdata VV               3310  /dev/sdd
[156:0:0:2]  disk    3PARdata VV               3310  /dev/sdf
[156:0:0:3]  disk    3PARdata VV               3310  /dev/sdh
[156:0:0:254]enclosu 3PARdata SES              3310  -
[157:0:0:0]  disk    3PARdata VV               3310  /dev/sdc
[157:0:0:1]  disk    3PARdata VV               3310  /dev/sde
[157:0:0:2]  disk    3PARdata VV               3310  /dev/sdg
[157:0:0:3]  disk    3PARdata VV               3310  /dev/sdi
[157:0:0:254]enclosu 3PARdata SES              3310  -

3PAR cli% showvlun -host cld6b3

Active VLUNs

Lun VVName                     HostName ---------Host_WWN/iSCSI_Name----------  Port        Type Status ID

  0 dcv-BTnuRp-TTrSjfeGgbfoT1w cld6b3   iqn.1993-08.org.debian:01:417efac88ed9 0:2:1 matched set active  1
  1 dcv-Z3swchnVQq6gQbeiTgFZjg cld6b3   iqn.1993-08.org.debian:01:417efac88ed9 0:2:1 matched set active  1
  2 dcv-xUvntlgpQ8ajGgsI6H3HyA cld6b3   iqn.1993-08.org.debian:01:417efac88ed9 0:2:1 matched set active  1
  3 dcv-YN7g6oCCSi.38.8hVN-V7A cld6b3   iqn.1993-08.org.debian:01:417efac88ed9 0:2:1 matched set active  1
  0 dcv-BTnuRp-TTrSjfeGgbfoT1w cld6b3   iqn.1993-08.org.debian:01:417efac88ed9 0:2:2 matched set active  1
  1 dcv-Z3swchnVQq6gQbeiTgFZjg cld6b3   iqn.1993-08.org.debian:01:417efac88ed9 0:2:2 matched set active  1
  2 dcv-xUvntlgpQ8ajGgsI6H3HyA cld6b3   iqn.1993-08.org.debian:01:417efac88ed9 0:2:2 matched set active  1
  3 dcv-YN7g6oCCSi.38.8hVN-V7A cld6b3   iqn.1993-08.org.debian:01:417efac88ed9 0:2:2 matched set active  1
----------------------------------------------------------------------------------------------------------
  8 total

Even after above LUN entries available after unmounting or delete operation fails, the next mount operation for new volume(s) work as expected.

2. Performed CHO Script on Ubuntu system with iSCSI snigle path backend for 12 hours.

Observed same error as above but there were 100+ dangling LUN entries in docker host & Same numbers of entries (as vlun) observed in 3PAR. Also observed Docker services in unresponsive state in Docker host after few hours.

**Comment by dgavand** [comment]
CHO run logs.

[cho_run_ubuntu_4_iSCSI_MP.log](https://github.com/hpe-storage/python-hpedockerplugin/files/1477374/cho_run_ubuntu_4_iSCSI_MP.log)

**Comment by wdurairaj** [comment]
Fix available in store/hpestorage/hpedockervolumeplugin:2.0.2
