### ISSUE TITLE
No error is displayed when volume (with child snapshot) is tried for deletion more than once.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#88]
Plugin: dockerciuser/hpedockerplugin:test

Steps to Reproduce:

1. Create a volume.
$ docker volume create -d dockerciuser/hpedockerplugin:test --name test_volume -o size=5
test_volume

2. Create a snapshot of the above created volume.
$  docker volume create -d dockerciuser/hpedockerplugin:test -o snapshotOf=test_volume test_snapshot
test_snapshot

3. Delete the volume and observe the proper error.
$  docker volume rm test_volume
Error response from daemon: unable to remove volume: remove test_volume: Err: Volume test_volume has one or more child snapshots - volume cannot be deleted!

4. Delete the volume again. No error was displayed.
$ docker volume rm test_volume
test_volume

5. Delete the volume again (third time). No error was displayed.
$ docker volume rm test_volume
test_volume

**Comment by wdurairaj** [comment]
you can test the fix for this issue using tag : dockerciuser/hpedockerplugin:test

**Comment by sumitshatwara** [comment]
Verified as fixed in the latest CI plugin: dockerciuser/hpedockerplugin:test
