### ISSUE TITLE
iscsiadm logout errors when attempting to unmount volume

### ISSUE THREAD

**Issue by ddefolo** [hpe-storage/python-hpedockerplugin#9]
When stopping a container with a mounted volume errors are seen trying to log out of the iscsi session such as the one below.  It does appear the volume was unpresented from the 3par perspective (no longer shows as exported), but it is unclear if something was left behind on the host system itself.

> exceptions.TypeError: <twisted.python.failure.Failure oslo_concurrency.processutils.ProcessExecutionError: Unexpected error while running command.
> Command: iscsiadm -m node -T iqn.2000-05.com.3pardata:20210002ac019cc1 -p 172.28.30.1:3260 --logout
> Exit code: 2
> Stdout: u'Logging out of session [sid: 5, target: iqn.2000-05.com.3pardata:20210002ac019cc1, portal: 172.28.30.1,3260]\n'
> Stderr: u'iscsiadm: Could not logout of [sid: 5, target: iqn.2000-05.com.3pardata:20210002ac019cc1, portal: 172.28.30.1,3260].\niscsiadm: initiator reported error (2 - session not found)\niscsiadm: Could not logout of all requested sessions\n'> is not JSON serializable

This was observed with a RHEL 7.2 host running the following compose file:

> [root@rheldocker1 quick-start]# cat docker-compose.yml
> hpedockerplugin:
>   image: hub.docker.hpecorp.net/hpe-storage/hpedockerplugin:0.5.4.4-1
>   container_name: hpeplugin
>   net: host
>   privileged: true
>   volumes:
>      - /dev:/dev
>      - /run/docker/plugins:/run/docker/plugins
>      - /etc/iscsi/initiatorname.iscsi:/etc/iscsi/initiatorname.iscsi
>      - /lib/modules:/lib/modules
>      - /var/lib/docker/:/var/lib/docker
>      - /etc/hpedockerplugin/data:/etc/hpedockerplugin/data:shared
>      - /etc/hpedockerplugin:/etc/hpedockerplugin
>      - /var/run/docker.sock:/var/run/docker.sock

See attached log:
[hpeplugin.log.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/465009/hpeplugin.log.txt)

**Comment by sumitshatwara** [comment]
This issue was not observed in our latest managed plugin 2.0. No error was seen in logs. Please find the logs in the attachments.
[issue9.txt](https://github.com/hpe-storage/python-hpedockerplugin/files/1333342/issue9.txt)

**Comment by sumitshatwara** [comment]
This issue was not observed in legacy docker volume plugin 2.1 (hpestorage/legacyvolumeplugin:2.1). No error was seen in logs.
