### ISSUE TITLE
QoS : Cloned volume is not added as a member into VVSet of source volume.

### ISSUE THREAD

**Issue by dgavand** [hpe-storage/python-hpedockerplugin#95]
OS platform: Ubuntu 16.04 with FC Backend
Plugin tag: dockerciuser/hpedockerplugin:test (Date : 12/12/2017)
Docker Version : 17.06.1-ee-2 / API version: 1.30

All the performed steps are mentioned below on how the issue was observed:

1. Created a docker volume with QoS option:
   docker volume create -d hpe --name qos_vol1 -o qos-name=vvk_vvset

2. Verified docker volume as member of respective VVset in 3PAR.

3. Created clone of the same volume:
   docker volume create -d hpe --name clone_qos_vol1 -o cloneOf=qos_vol1

4. Verified volume as created but it was not added as member into the respective VVset (in 3PAR).

**Comment by wdurairaj** [comment]
you can test the fix for this issue using tag : dockerciuser/hpedockerplugin:test
