### ISSUE TITLE
Error message is not displayed when snapshot is tried for deletion within its retention period.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#97]
**Plugin: dockerciuser/hpedockerplugin:test**

**Steps to Reproduce:**

1. Create a volume.
$ docker volume create -d hpe sumit -o size=15
sumit

2. Create a snapshot of the above created volume with expiration and retention hours.
$ docker volume create -d hpe snap -o snapshotOf=sumit -o retentionHours=1 -o expirationHours=2
snap

3. Delete the snapshot within retention period (within 1 hour). No error was displayed. User is under impression that snapshot got deleted.
$ docker volume rm sumit/snap
sumit/snap

**Expected result:** Proper error message must be displayed when snapshot is tried for deletion within retention period.

4. Snapshot is still present which is expected.
$ docker volume inspect sumit/snap
[
    {
        "Driver": "hpe:latest",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/plugins/2e10a3e5d057a44690fccad4e9d4675a22d6e3e909aa221533ddb80e8c392cd1/rootfs",
        "Name": "sumit/snap",
        "Options": {},
        "Scope": "local",
        "Status": {
            "Settings": {
                "expirationHours": 2,
                "retentionHours": 1
            }
        }
    }
]

**Comment by wdurairaj** [comment]
you can test the fix for this issue using tag : dockerciuser/hpedockerplugin:test

**Comment by sumitshatwara** [comment]
Verified as fixed in the latest CI plugin: dockerciuser/hpedockerplugin:test
