### ISSUE TITLE
CentOS/RHEL Kernal Issue: CPU Soft lockup error is observed after performing continuous hours of operations or upgrade process.

### ISSUE THREAD

**Issue by sumitshatwara** [hpe-storage/python-hpedockerplugin#99]
**Plugin**: hpestorage/hpedockervolumeplugin:2.0.2 or earlier
**Docker version**: 17.06.2-ee-6
**OS**: CentOS 7.x and RHEL 7.x

We are often observing one severe and critical Kernal issue called CPU Soft lockup error in CentOS 7.x platform. This issue is rare in RHEL 7.x.

After performing randomn operations for some time OR continuous hours of operations through scripts, it resulted in CPU Soft lock up error intermittently.
Detailed steps will be mentioned as comments of this issue.

The workaround is to restart the docker engine service. If it doesn't work, follow below steps:
1. Reboot the system completely.
2. Start docker engine service and etcd daemon.
3. Enable 3par volume plugin.
4. Spin up all containers again.

**Comment by sumitshatwara** [comment]
One way to reproduce this issue is to run CHO script on CentOS platform.

Run this python script for period between 12 hours and 96 hours: https://github.com/sumitshatwara/docker-3par-cho/blob/master/hpe_3par_cho_test.py

This script randomly performs:  volume creation, deletion, mount and unmount operations for a given duration.

**Comment by sumitshatwara** [comment]
Other way to reproduce this issue:

1. Installed and enabled 3par plugin 2.0.1 
2. Created 4 volumes with different properties using 3par plugin .
3. Mounted and wrote data on them.
4. Disabled the plugin forcefully.
5. Upgraded to 2.0.2 plugin.
6. Enable the plugin.
7. Stopped all the containers and observed all containers were dead which was expected as per Issue #46

$ docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
16c2e5e613f4        busybox                      "/bin/sh"                About an hour ago   Dead                                                                                     container14
ff0d204fd656        busybox                      "/bin/sh"                About an hour ago   Dead                                                                                     container13
ccc3b5088186        busybox                      "/bin/sh"                About an hour ago   Dead                                                                                     container12
db2b94c9d424        busybox                      "/bin/sh"                About an hour ago   Dead      container11

8. Created two new volumes and mounted all 6 volumes again.

$ docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS                                                                NAMES
569844629d41        busybox                      "/bin/sh"                13 minutes ago      Up 12 minutes                                                                            mounter16
01a0624ee314        busybox                      "/bin/sh"                14 minutes ago      Up 13 minutes                                                                            mounter15
e9b09b5c57b8        busybox                      "/bin/sh"                14 minutes ago      Up 14 minutes                                                                            mounter14
7fcbea3b1aa2        busybox                      "/bin/sh"                15 minutes ago      Up 14 minutes                                                                            mounter13
96672230f4f7        busybox                      "/bin/sh"                16 minutes ago      Up 15 minutes                                                                            mounter12
fce457d3708a        busybox                      "/bin/sh"                17 minutes ago      Up 16 minutes                                                                            mounter11
16c2e5e613f4        busybox                      "/bin/sh"                About an hour ago   Dead                                                                                     container14
ff0d204fd656        busybox                      "/bin/sh"                About an hour ago   Dead                                                                                     container13
ccc3b5088186        busybox                      "/bin/sh"                About an hour ago   Dead                                                                                     container12
db2b94c9d424        busybox                      "/bin/sh"                About an hour ago   Dead container11

9. Stopped all containers(where old volumes are mounted)and observed CPU Soft lockup issue .

$ for i in `seq 11 14`; do  echo $i; docker stop mounter$i ; done
11

Message from syslogd@csimbe13-b02 at Dec  7 00:57:53 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#6 stuck for 22s! [gmain:1240]

Message from syslogd@csimbe13-b02 at Dec  7 00:57:53 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#14 stuck for 22s! [dockerd:30195]

Message from syslogd@csimbe13-b02 at Dec  7 00:57:57 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#5 stuck for 22s! [udevd:10847]

Message from syslogd@csimbe13-b02 at Dec  7 00:57:57 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#11 stuck for 22s! [etcd:31637]

Message from syslogd@csimbe13-b02 at Dec  7 00:57:57 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#12 stuck for 22s! [systemd-udevd:2141]

Message from syslogd@csimbe13-b02 at Dec  7 00:57:57 ...
 kernel:NMI watchdog: BUG: soft lockup - CPU#30 stuck for 22s! [irqbalance:1122]
 
10. Observed the same error for containers named mounter13 and mounter14

**Comment by wdurairaj** [comment]
Might be similar to https://github.com/moby/moby/issues/19758

**Comment by sumitshatwara** [comment]
This issue is documented for HPE 3PAR docker volume plugin 2.1. Hence, I am closing it.
